import { createFileRoute } from "@tanstack/react-router";
import { requireAuthenticatedUser, getSupabaseServer } from "@/platform/supabase";
import { getWorkflow } from "@/domain/workflows";
import { validateAppealDraft } from "@/domain/draft-validator";
import { COURT_RULING_AUTHORITY_RULES } from "@/domain/court-ruling-gold";
import { callAIText, resolveAI } from "@/platform/control-plane-ai";

export const Route = createFileRoute("/api/workflows/court-ruling/draft")({ server: { handlers: { POST: async ({ request }) => { try {
  const user = await requireAuthenticatedUser(request); const input = await request.json() as any; if (!input.appealId) return Response.json({ error: "Appeal id is required." }, { status: 400 }); const s = await getSupabaseServer(); const { data: a, error } = await s.from("appeals").select("*").eq("id", input.appealId).single(); if (error || !a) return Response.json({ error: "Appeal case not found." }, { status: 404 }); if (a.user_id !== user.id) return Response.json({ error: "You do not own this appeal case." }, { status: 403 }); if (a.workflow_id !== "court-ruling") return Response.json({ error: "Appeal workflow mismatch." }, { status: 409 });
  const wf = getWorkflow("court-ruling"); const d = await resolveAI("court-ruling", "draft"); const v = await resolveAI("court-ruling", "validation"); const analysis = input.analysis || a.decision; const draft = input.draftOverride?.trim() || await callAIText(d, "Write a review-ready response for human approval. Use only supported facts and controlling-source references.", d.promptOverride || [`Create a response for ${wf.title}.`, wf.workflowPrompt, `Authority rules: ${COURT_RULING_AUTHORITY_RULES.join(" | ")}.`, "Do not invent legal authority, filing requirements, deadlines, procedural posture, forms, service requirements, or court findings. If the response posture is unresolved, say so explicitly.", `CASE ANALYSIS:\n${JSON.stringify(analysis)}`].join("\n\n"));
  const validation = await callAIText(v, "Return strict JSON. Flag invented law, unsupported facts, wrong post-ruling mechanism, unverified deadlines, missing evidence, contradictions, and outcome overstatement.", v.promptOverride || [`Audit this ${wf.title} draft.`, "Return JSON with valid, issues, unsupportedClaims, missingEvidence, deadlineIssues, filingInstructionIssues, sourceConflicts, suggestions.", `CASE ANALYSIS:\n${JSON.stringify(analysis)}`, `DRAFT:\n${draft}`].join("\n\n"), true); const persisted = `${draft}\n\nSincerely,\n[Your Name]`; const draftValidation = validateAppealDraft(draft, a.decision || {}, Array.isArray(a.grounds) ? a.grounds : [], Array.isArray(a.evidence) ? a.evidence : []); const blockingFindings = draftValidation.findings.filter((f: any) => (f.severity === "block" || f.severity === "error") && !f.passed); if (blockingFindings.length) return Response.json({ error: "Draft failed validation.", draftValidation, blockingFindings }, { status: 422 }); const ver = a.version ?? 1; const { error: updateError } = await s.from("appeals").update({ draft: persisted, status: "in_progress", version: ver + 1, updated_at: new Date().toISOString() }).eq("id", a.id).eq("user_id", user.id).eq("version", ver); if (updateError) throw new Error(`Unable to persist draft: ${updateError.message}`);
  return Response.json({ ok: true, appealId: a.id, draft: persisted, validation, draftValidation, provider: d.provider, draftModel: d.model, validationModel: v.model });
} catch (error) { const message = error instanceof Error ? error.message : "Unable to create court response."; return Response.json({ error: message }, { status: /authentication|required|token/i.test(message) ? 401 : 502 }); } } } } });
