// @generated by the supervised workflow factory build executor.
// This file is machine-owned. Do not hand-edit generated profiles.

import type { NoticeResponseWorkflowProfile } from "./profiles.js";

export const GENERATED_NOTICE_RESPONSE_WORKFLOW_PROFILES = Object.freeze(
  [] as const satisfies readonly NoticeResponseWorkflowProfile[],
);
