/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppealADecisionRouteImport } from './routes/appeal-a-decision'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as MailAPdfRouteImport } from './routes/mail-a-pdf'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as StartRouteImport } from './routes/start'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as WorkflowsRouteImport } from './routes/workflows'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe-webhook'
import { Route as AppealSlugRouteImport } from './routes/appeal/$slug'
import { Route as AppealAdministrativeRouteImport } from './routes/appeal/administrative'
import { Route as AppealDisabilityRouteImport } from './routes/appeal/disability'
import { Route as AppealMedicaidRouteImport } from './routes/appeal/medicaid'
import { Route as AppealPublicAssistanceRouteImport } from './routes/appeal/public-assistance'
import { Route as AppealUnemploymentRouteImport } from './routes/appeal/unemployment'
import { Route as AppealVeteransRouteImport } from './routes/appeal/veterans'
import { Route as ResourcesIndexRouteImport } from './routes/resources/index'
import { Route as ResourcesSlugRouteImport } from './routes/resources/$slug'
import { Route as WorkflowsIndexRouteImport } from './routes/workflows/index'
import { Route as WorkflowsWorkflowIdRouteImport } from './routes/workflows/$workflowId'
import { Route as WorkflowsBenefitsReconsiderationRouteImport } from './routes/workflows/benefits-reconsideration'
import { Route as WorkflowsDisabilityBenefitsDenialRouteImport } from './routes/workflows/disability-benefits-denial'
import { Route as WorkflowsEddDenialRouteImport } from './routes/workflows/edd-denial'
import { Route as WorkflowsHearingPreparationRouteImport } from './routes/workflows/hearing-preparation'
import { Route as WorkflowsHousingBenefitsDenialRouteImport } from './routes/workflows/housing-benefits-denial'
import { Route as WorkflowsMedicaidDenialRouteImport } from './routes/workflows/medicaid-denial'
import { Route as WorkflowsOverpaymentRouteImport } from './routes/workflows/overpayment'
import { Route as WorkflowsSnapDenialRouteImport } from './routes/workflows/snap-denial'
import { Route as WorkflowsSocialSecurityDenialRouteImport } from './routes/workflows/social-security-denial'
import { Route as WorkflowsSsdiDenialRouteImport } from './routes/workflows/ssdi-denial'
import { Route as WorkflowsSsdiReconsiderationRouteImport } from './routes/workflows/ssdi-reconsideration'
import { Route as WorkflowsSsiDenialRouteImport } from './routes/workflows/ssi-denial'
import { Route as WorkflowsSsiReconsiderationRouteImport } from './routes/workflows/ssi-reconsideration'
import { Route as WorkflowsUnemploymentDenialRouteImport } from './routes/workflows/unemployment-denial'
import { Route as WorkflowsVaBenefitsDenialRouteImport } from './routes/workflows/va-benefits-denial'
import { Route as ApiAdminAppealsRouteImport } from './routes/api/admin/appeals'
import { Route as ApiAdminHealthRouteImport } from './routes/api/admin/health'
import { Route as ApiAuthStatusRouteImport } from './routes/api/auth/status'
import { Route as ApiControlPlaneAiRouteImport } from './routes/api/control-plane/ai'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppealADecisionRoute = AppealADecisionRouteImport.update({
  id: '/appeal-a-decision',
  path: '/appeal-a-decision',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const MailAPdfRoute = MailAPdfRouteImport.update({
  id: '/mail-a-pdf',
  path: '/mail-a-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsRoute = WorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe-webhook',
  path: '/api/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AppealSlugRoute = AppealSlugRouteImport.update({
  id: '/appeal/$slug',
  path: '/appeal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppealAdministrativeRoute = AppealAdministrativeRouteImport.update({
  id: '/appeal/administrative',
  path: '/appeal/administrative',
  getParentRoute: () => rootRouteImport,
} as any)
const AppealDisabilityRoute = AppealDisabilityRouteImport.update({
  id: '/appeal/disability',
  path: '/appeal/disability',
  getParentRoute: () => rootRouteImport,
} as any)
const AppealMedicaidRoute = AppealMedicaidRouteImport.update({
  id: '/appeal/medicaid',
  path: '/appeal/medicaid',
  getParentRoute: () => rootRouteImport,
} as any)
const AppealPublicAssistanceRoute = AppealPublicAssistanceRouteImport.update({
  id: '/appeal/public-assistance',
  path: '/appeal/public-assistance',
  getParentRoute: () => rootRouteImport,
} as any)
const AppealUnemploymentRoute = AppealUnemploymentRouteImport.update({
  id: '/appeal/unemployment',
  path: '/appeal/unemployment',
  getParentRoute: () => rootRouteImport,
} as any)
const AppealVeteransRoute = AppealVeteransRouteImport.update({
  id: '/appeal/veterans',
  path: '/appeal/veterans',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesSlugRoute = ResourcesSlugRouteImport.update({
  id: '/resources/$slug',
  path: '/resources/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsIndexRoute = WorkflowsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkflowsRoute,
} as any)
const WorkflowsWorkflowIdRoute = WorkflowsWorkflowIdRouteImport.update({
  id: '/$workflowId',
  path: '/$workflowId',
  getParentRoute: () => WorkflowsRoute,
} as any)
const WorkflowsBenefitsReconsiderationRoute =
  WorkflowsBenefitsReconsiderationRouteImport.update({
    id: '/benefits-reconsideration',
    path: '/benefits-reconsideration',
    getParentRoute: () => WorkflowsRoute,
  } as any)
const WorkflowsDisabilityBenefitsDenialRoute =
  WorkflowsDisabilityBenefitsDenialRouteImport.update({
    id: '/disability-benefits-denial',
    path: '/disability-benefits-denial',
    getParentRoute: () => WorkflowsRoute,
  } as any)
const WorkflowsEddDenialRoute = WorkflowsEddDenialRouteImport.update({
  id: '/edd-denial',
  path: '/edd-denial',
  getParentRoute: () => WorkflowsRoute,
} as any)
const WorkflowsHearingPreparationRoute =
  WorkflowsHearingPreparationRouteImport.update({
    id: '/hearing-preparation',
    path: '/hearing-preparation',
    getParentRoute: () => WorkflowsRoute,
  } as any)
const WorkflowsHousingBenefitsDenialRoute =
  WorkflowsHousingBenefitsDenialRouteImport.update({
    id: '/housing-benefits-denial',
    path: '/housing-benefits-denial',
    getParentRoute: () => WorkflowsRoute,
  } as any)
const WorkflowsMedicaidDenialRoute = WorkflowsMedicaidDenialRouteImport.update({
  id: '/medicaid-denial',
  path: '/medicaid-denial',
  getParentRoute: () => WorkflowsRoute,
} as any)
const WorkflowsOverpaymentRoute = WorkflowsOverpaymentRouteImport.update({
  id: '/overpayment',
  path: '/overpayment',
  getParentRoute: () => WorkflowsRoute,
} as any)
const WorkflowsSnapDenialRoute = WorkflowsSnapDenialRouteImport.update({
  id: '/snap-denial',
  path: '/snap-denial',
  getParentRoute: () => WorkflowsRoute,
} as any)
const WorkflowsSocialSecurityDenialRoute =
  WorkflowsSocialSecurityDenialRouteImport.update({
    id: '/social-security-denial',
    path: '/social-security-denial',
    getParentRoute: () => WorkflowsRoute,
  } as any)
const WorkflowsSsdiDenialRoute = WorkflowsSsdiDenialRouteImport.update({
  id: '/ssdi-denial',
  path: '/ssdi-denial',
  getParentRoute: () => WorkflowsRoute,
} as any)
const WorkflowsSsdiReconsiderationRoute =
  WorkflowsSsdiReconsiderationRouteImport.update({
    id: '/ssdi-reconsideration',
    path: '/ssdi-reconsideration',
    getParentRoute: () => WorkflowsRoute,
  } as any)
const WorkflowsSsiDenialRoute = WorkflowsSsiDenialRouteImport.update({
  id: '/ssi-denial',
  path: '/ssi-denial',
  getParentRoute: () => WorkflowsRoute,
} as any)
const WorkflowsSsiReconsiderationRoute =
  WorkflowsSsiReconsiderationRouteImport.update({
    id: '/ssi-reconsideration',
    path: '/ssi-reconsideration',
    getParentRoute: () => WorkflowsRoute,
  } as any)
const WorkflowsUnemploymentDenialRoute =
  WorkflowsUnemploymentDenialRouteImport.update({
    id: '/unemployment-denial',
    path: '/unemployment-denial',
    getParentRoute: () => WorkflowsRoute,
  } as any)
const WorkflowsVaBenefitsDenialRoute =
  WorkflowsVaBenefitsDenialRouteImport.update({
    id: '/va-benefits-denial',
    path: '/va-benefits-denial',
    getParentRoute: () => WorkflowsRoute,
  } as any)
const ApiAdminAppealsRoute = ApiAdminAppealsRouteImport.update({
  id: '/api/admin/appeals',
  path: '/api/admin/appeals',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminHealthRoute = ApiAdminHealthRouteImport.update({
  id: '/api/admin/health',
  path: '/api/admin/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthStatusRoute = ApiAuthStatusRouteImport.update({
  id: '/api/auth/status',
  path: '/api/auth/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiControlPlaneAiRoute = ApiControlPlaneAiRouteImport.update({
  id: '/api/control-plane/ai',
  path: '/api/control-plane/ai',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/appeal-a-decision': typeof AppealADecisionRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/mail-a-pdf': typeof MailAPdfRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRoute
  '/start': typeof StartRoute
  '/terms': typeof TermsRoute
  '/workflows': typeof WorkflowsRouteWithChildren
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/appeal/$slug': typeof AppealSlugRoute
  '/appeal/administrative': typeof AppealAdministrativeRoute
  '/appeal/disability': typeof AppealDisabilityRoute
  '/appeal/medicaid': typeof AppealMedicaidRoute
  '/appeal/public-assistance': typeof AppealPublicAssistanceRoute
  '/appeal/unemployment': typeof AppealUnemploymentRoute
  '/appeal/veterans': typeof AppealVeteransRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/workflows/$workflowId': typeof WorkflowsWorkflowIdRoute
  '/workflows/benefits-reconsideration': typeof WorkflowsBenefitsReconsiderationRoute
  '/workflows/disability-benefits-denial': typeof WorkflowsDisabilityBenefitsDenialRoute
  '/workflows/edd-denial': typeof WorkflowsEddDenialRoute
  '/workflows/hearing-preparation': typeof WorkflowsHearingPreparationRoute
  '/workflows/housing-benefits-denial': typeof WorkflowsHousingBenefitsDenialRoute
  '/workflows/medicaid-denial': typeof WorkflowsMedicaidDenialRoute
  '/workflows/overpayment': typeof WorkflowsOverpaymentRoute
  '/workflows/snap-denial': typeof WorkflowsSnapDenialRoute
  '/workflows/social-security-denial': typeof WorkflowsSocialSecurityDenialRoute
  '/workflows/ssdi-denial': typeof WorkflowsSsdiDenialRoute
  '/workflows/ssdi-reconsideration': typeof WorkflowsSsdiReconsiderationRoute
  '/workflows/ssi-denial': typeof WorkflowsSsiDenialRoute
  '/workflows/ssi-reconsideration': typeof WorkflowsSsiReconsiderationRoute
  '/workflows/unemployment-denial': typeof WorkflowsUnemploymentDenialRoute
  '/workflows/va-benefits-denial': typeof WorkflowsVaBenefitsDenialRoute
  '/resources/': typeof ResourcesIndexRoute
  '/workflows/': typeof WorkflowsIndexRoute
  '/api/admin/appeals': typeof ApiAdminAppealsRoute
  '/api/admin/health': typeof ApiAdminHealthRoute
  '/api/auth/status': typeof ApiAuthStatusRoute
  '/api/control-plane/ai': typeof ApiControlPlaneAiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/appeal-a-decision': typeof AppealADecisionRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/mail-a-pdf': typeof MailAPdfRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRoute
  '/start': typeof StartRoute
  '/terms': typeof TermsRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/appeal/$slug': typeof AppealSlugRoute
  '/appeal/administrative': typeof AppealAdministrativeRoute
  '/appeal/disability': typeof AppealDisabilityRoute
  '/appeal/medicaid': typeof AppealMedicaidRoute
  '/appeal/public-assistance': typeof AppealPublicAssistanceRoute
  '/appeal/unemployment': typeof AppealUnemploymentRoute
  '/appeal/veterans': typeof AppealVeteransRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/workflows/$workflowId': typeof WorkflowsWorkflowIdRoute
  '/workflows/benefits-reconsideration': typeof WorkflowsBenefitsReconsiderationRoute
  '/workflows/disability-benefits-denial': typeof WorkflowsDisabilityBenefitsDenialRoute
  '/workflows/edd-denial': typeof WorkflowsEddDenialRoute
  '/workflows/hearing-preparation': typeof WorkflowsHearingPreparationRoute
  '/workflows/housing-benefits-denial': typeof WorkflowsHousingBenefitsDenialRoute
  '/workflows/medicaid-denial': typeof WorkflowsMedicaidDenialRoute
  '/workflows/overpayment': typeof WorkflowsOverpaymentRoute
  '/workflows/snap-denial': typeof WorkflowsSnapDenialRoute
  '/workflows/social-security-denial': typeof WorkflowsSocialSecurityDenialRoute
  '/workflows/ssdi-denial': typeof WorkflowsSsdiDenialRoute
  '/workflows/ssdi-reconsideration': typeof WorkflowsSsdiReconsiderationRoute
  '/workflows/ssi-denial': typeof WorkflowsSsiDenialRoute
  '/workflows/ssi-reconsideration': typeof WorkflowsSsiReconsiderationRoute
  '/workflows/unemployment-denial': typeof WorkflowsUnemploymentDenialRoute
  '/workflows/va-benefits-denial': typeof WorkflowsVaBenefitsDenialRoute
  '/resources': typeof ResourcesIndexRoute
  '/workflows': typeof WorkflowsIndexRoute
  '/api/admin/appeals': typeof ApiAdminAppealsRoute
  '/api/admin/health': typeof ApiAdminHealthRoute
  '/api/auth/status': typeof ApiAuthStatusRoute
  '/api/control-plane/ai': typeof ApiControlPlaneAiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/appeal-a-decision': typeof AppealADecisionRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/mail-a-pdf': typeof MailAPdfRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRoute
  '/start': typeof StartRoute
  '/terms': typeof TermsRoute
  '/workflows': typeof WorkflowsRouteWithChildren
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/appeal/$slug': typeof AppealSlugRoute
  '/appeal/administrative': typeof AppealAdministrativeRoute
  '/appeal/disability': typeof AppealDisabilityRoute
  '/appeal/medicaid': typeof AppealMedicaidRoute
  '/appeal/public-assistance': typeof AppealPublicAssistanceRoute
  '/appeal/unemployment': typeof AppealUnemploymentRoute
  '/appeal/veterans': typeof AppealVeteransRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/workflows/$workflowId': typeof WorkflowsWorkflowIdRoute
  '/workflows/benefits-reconsideration': typeof WorkflowsBenefitsReconsiderationRoute
  '/workflows/disability-benefits-denial': typeof WorkflowsDisabilityBenefitsDenialRoute
  '/workflows/edd-denial': typeof WorkflowsEddDenialRoute
  '/workflows/hearing-preparation': typeof WorkflowsHearingPreparationRoute
  '/workflows/housing-benefits-denial': typeof WorkflowsHousingBenefitsDenialRoute
  '/workflows/medicaid-denial': typeof WorkflowsMedicaidDenialRoute
  '/workflows/overpayment': typeof WorkflowsOverpaymentRoute
  '/workflows/snap-denial': typeof WorkflowsSnapDenialRoute
  '/workflows/social-security-denial': typeof WorkflowsSocialSecurityDenialRoute
  '/workflows/ssdi-denial': typeof WorkflowsSsdiDenialRoute
  '/workflows/ssdi-reconsideration': typeof WorkflowsSsdiReconsiderationRoute
  '/workflows/ssi-denial': typeof WorkflowsSsiDenialRoute
  '/workflows/ssi-reconsideration': typeof WorkflowsSsiReconsiderationRoute
  '/workflows/unemployment-denial': typeof WorkflowsUnemploymentDenialRoute
  '/workflows/va-benefits-denial': typeof WorkflowsVaBenefitsDenialRoute
  '/resources/': typeof ResourcesIndexRoute
  '/workflows/': typeof WorkflowsIndexRoute
  '/api/admin/appeals': typeof ApiAdminAppealsRoute
  '/api/admin/health': typeof ApiAdminHealthRoute
  '/api/auth/status': typeof ApiAuthStatusRoute
  '/api/control-plane/ai': typeof ApiControlPlaneAiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/appeal-a-decision'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/how-it-works'
    | '/mail-a-pdf'
    | '/pricing'
    | '/privacy'
    | '/products'
    | '/start'
    | '/terms'
    | '/workflows'
    | '/api/stripe-webhook'
    | '/appeal/$slug'
    | '/appeal/administrative'
    | '/appeal/disability'
    | '/appeal/medicaid'
    | '/appeal/public-assistance'
    | '/appeal/unemployment'
    | '/appeal/veterans'
    | '/resources/$slug'
    | '/workflows/$workflowId'
    | '/workflows/benefits-reconsideration'
    | '/workflows/disability-benefits-denial'
    | '/workflows/edd-denial'
    | '/workflows/hearing-preparation'
    | '/workflows/housing-benefits-denial'
    | '/workflows/medicaid-denial'
    | '/workflows/overpayment'
    | '/workflows/snap-denial'
    | '/workflows/social-security-denial'
    | '/workflows/ssdi-denial'
    | '/workflows/ssdi-reconsideration'
    | '/workflows/ssi-denial'
    | '/workflows/ssi-reconsideration'
    | '/workflows/unemployment-denial'
    | '/workflows/va-benefits-denial'
    | '/resources/'
    | '/workflows/'
    | '/api/admin/appeals'
    | '/api/admin/health'
    | '/api/auth/status'
    | '/api/control-plane/ai'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/appeal-a-decision'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/how-it-works'
    | '/mail-a-pdf'
    | '/pricing'
    | '/privacy'
    | '/products'
    | '/start'
    | '/terms'
    | '/api/stripe-webhook'
    | '/appeal/$slug'
    | '/appeal/administrative'
    | '/appeal/disability'
    | '/appeal/medicaid'
    | '/appeal/public-assistance'
    | '/appeal/unemployment'
    | '/appeal/veterans'
    | '/resources/$slug'
    | '/workflows/$workflowId'
    | '/workflows/benefits-reconsideration'
    | '/workflows/disability-benefits-denial'
    | '/workflows/edd-denial'
    | '/workflows/hearing-preparation'
    | '/workflows/housing-benefits-denial'
    | '/workflows/medicaid-denial'
    | '/workflows/overpayment'
    | '/workflows/snap-denial'
    | '/workflows/social-security-denial'
    | '/workflows/ssdi-denial'
    | '/workflows/ssdi-reconsideration'
    | '/workflows/ssi-denial'
    | '/workflows/ssi-reconsideration'
    | '/workflows/unemployment-denial'
    | '/workflows/va-benefits-denial'
    | '/resources'
    | '/workflows'
    | '/api/admin/appeals'
    | '/api/admin/health'
    | '/api/auth/status'
    | '/api/control-plane/ai'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/appeal-a-decision'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/how-it-works'
    | '/mail-a-pdf'
    | '/pricing'
    | '/privacy'
    | '/products'
    | '/start'
    | '/terms'
    | '/workflows'
    | '/api/stripe-webhook'
    | '/appeal/$slug'
    | '/appeal/administrative'
    | '/appeal/disability'
    | '/appeal/medicaid'
    | '/appeal/public-assistance'
    | '/appeal/unemployment'
    | '/appeal/veterans'
    | '/resources/$slug'
    | '/workflows/$workflowId'
    | '/workflows/benefits-reconsideration'
    | '/workflows/disability-benefits-denial'
    | '/workflows/edd-denial'
    | '/workflows/hearing-preparation'
    | '/workflows/housing-benefits-denial'
    | '/workflows/medicaid-denial'
    | '/workflows/overpayment'
    | '/workflows/snap-denial'
    | '/workflows/social-security-denial'
    | '/workflows/ssdi-denial'
    | '/workflows/ssdi-reconsideration'
    | '/workflows/ssi-denial'
    | '/workflows/ssi-reconsideration'
    | '/workflows/unemployment-denial'
    | '/workflows/va-benefits-denial'
    | '/resources/'
    | '/workflows/'
    | '/api/admin/appeals'
    | '/api/admin/health'
    | '/api/auth/status'
    | '/api/control-plane/ai'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  AppealADecisionRoute: typeof AppealADecisionRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  FaqRoute: typeof FaqRoute
  HowItWorksRoute: typeof HowItWorksRoute
  MailAPdfRoute: typeof MailAPdfRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProductsRoute: typeof ProductsRoute
  StartRoute: typeof StartRoute
  TermsRoute: typeof TermsRoute
  WorkflowsRoute: typeof WorkflowsRouteWithChildren
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  AppealSlugRoute: typeof AppealSlugRoute
  AppealAdministrativeRoute: typeof AppealAdministrativeRoute
  AppealDisabilityRoute: typeof AppealDisabilityRoute
  AppealMedicaidRoute: typeof AppealMedicaidRoute
  AppealPublicAssistanceRoute: typeof AppealPublicAssistanceRoute
  AppealUnemploymentRoute: typeof AppealUnemploymentRoute
  AppealVeteransRoute: typeof AppealVeteransRoute
  ResourcesSlugRoute: typeof ResourcesSlugRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
  ApiAdminAppealsRoute: typeof ApiAdminAppealsRoute
  ApiAdminHealthRoute: typeof ApiAdminHealthRoute
  ApiAuthStatusRoute: typeof ApiAuthStatusRoute
  ApiControlPlaneAiRoute: typeof ApiControlPlaneAiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appeal-a-decision': {
      id: '/appeal-a-decision'
      path: '/appeal-a-decision'
      fullPath: '/appeal-a-decision'
      preLoaderRoute: typeof AppealADecisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mail-a-pdf': {
      id: '/mail-a-pdf'
      path: '/mail-a-pdf'
      fullPath: '/mail-a-pdf'
      preLoaderRoute: typeof MailAPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows': {
      id: '/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe-webhook': {
      id: '/api/stripe-webhook'
      path: '/api/stripe-webhook'
      fullPath: '/api/stripe-webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appeal/$slug': {
      id: '/appeal/$slug'
      path: '/appeal/$slug'
      fullPath: '/appeal/$slug'
      preLoaderRoute: typeof AppealSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appeal/administrative': {
      id: '/appeal/administrative'
      path: '/appeal/administrative'
      fullPath: '/appeal/administrative'
      preLoaderRoute: typeof AppealAdministrativeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appeal/disability': {
      id: '/appeal/disability'
      path: '/appeal/disability'
      fullPath: '/appeal/disability'
      preLoaderRoute: typeof AppealDisabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appeal/medicaid': {
      id: '/appeal/medicaid'
      path: '/appeal/medicaid'
      fullPath: '/appeal/medicaid'
      preLoaderRoute: typeof AppealMedicaidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appeal/public-assistance': {
      id: '/appeal/public-assistance'
      path: '/appeal/public-assistance'
      fullPath: '/appeal/public-assistance'
      preLoaderRoute: typeof AppealPublicAssistanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appeal/unemployment': {
      id: '/appeal/unemployment'
      path: '/appeal/unemployment'
      fullPath: '/appeal/unemployment'
      preLoaderRoute: typeof AppealUnemploymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appeal/veterans': {
      id: '/appeal/veterans'
      path: '/appeal/veterans'
      fullPath: '/appeal/veterans'
      preLoaderRoute: typeof AppealVeteransRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/': {
      id: '/resources/'
      path: '/resources'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/$slug': {
      id: '/resources/$slug'
      path: '/resources/$slug'
      fullPath: '/resources/$slug'
      preLoaderRoute: typeof ResourcesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/': {
      id: '/workflows/'
      path: '/'
      fullPath: '/workflows/'
      preLoaderRoute: typeof WorkflowsIndexRouteImport
      parentRoute: typeof WorkflowsRoute
    }
    '/workflows/$workflowId': {
      id: '/workflows/$workflowId'
      path: '/$workflowId'
      fullPath: '/workflows/$workflowId'
      preLoaderRoute: typeof WorkflowsWorkflowIdRouteImport
      parentRoute: typeof WorkflowsRoute
    }
    '/workflows/benefits-reconsideration': {
      id: '/workflows/benefits-reconsideration'
      path: '/benefits-reconsideration'
      fullPath: '/workflows/benefits-reconsideration'
      preLoaderRoute: typeof WorkflowsBenefitsReconsiderationRouteImport
      parentRoute: typeof WorkflowsRoute
    }
    '/workflows/disability-benefits-denial': {
      id: '/workflows/disability-benefits-denial'
      path: '/disability-benefits-denial'
      fullPath: '/workflows/disability-benefits-denial'
      preLoaderRoute: typeof WorkflowsDisabilityBenefitsDenialRouteImport
      parentRoute: typeof WorkflowsRoute
    }
    '/workflows/edd-denial': {
      id: '/workflows/edd-denial'
      path: '/edd-denial'
      fullPath: '/workflows/edd-denial'
      preLoaderRoute: typeof WorkflowsEddDenialRouteImport
      parentRoute: typeof WorkflowsRoute
    }
    '/workflows/hearing-preparation': {
      id: '/workflows/hearing-preparation'
      path: '/hearing-preparation'
      fullPath: '/workflows/hearing-preparation'
      preLoaderRoute: typeof WorkflowsHearingPreparationRouteImport
      parentRoute: typeof WorkflowsRoute
    }
    '/workflows/housing-benefits-denial': {
      id: '/workflows/housing-benefits-denial'
      path: '/housing-benefits-denial'
      fullPath: '/workflows/housing-benefits-denial'
      preLoaderRoute: typeof WorkflowsHousingBenefitsDenialRouteImport
      parentRoute: typeof WorkflowsRoute
    }
    '/workflows/medicaid-denial': {
      id: '/workflows/medicaid-denial'
      path: '/medicaid-denial'
      fullPath: '/workflows/medicaid-denial'
      preLoaderRoute: typeof WorkflowsMedicaidDenialRouteImport
      parentRoute: typeof WorkflowsRoute
    }
    '/workflows/overpayment': {
      id: '/workflows/overpayment'
      path: '/overpayment'
      fullPath: '/workflows/overpayment'
      preLoaderRoute: typeof WorkflowsOverpaymentRouteImport
      parentRoute: typeof WorkflowsRoute
    }
    '/workflows/snap-denial': {
      id: '/workflows/snap-denial'
      path: '/snap-denial'
      fullPath: '/workflows/snap-denial'
      preLoaderRoute: typeof WorkflowsSnapDenialRouteImport
      parentRoute: typeof WorkflowsRoute
    }
    '/workflows/social-security-denial': {
      id: '/workflows/social-security-denial'
      path: '/social-security-denial'
      fullPath: '/workflows/social-security-denial'
      preLoaderRoute: typeof WorkflowsSocialSecurityDenialRouteImport
      parentRoute: typeof WorkflowsRoute
    }
    '/workflows/ssdi-denial': {
      id: '/workflows/ssdi-denial'
      path: '/ssdi-denial'
      fullPath: '/workflows/ssdi-denial'
      preLoaderRoute: typeof WorkflowsSsdiDenialRouteImport
      parentRoute: typeof WorkflowsRoute
    }
    '/workflows/ssdi-reconsideration': {
      id: '/workflows/ssdi-reconsideration'
      path: '/ssdi-reconsideration'
      fullPath: '/workflows/ssdi-reconsideration'
      preLoaderRoute: typeof WorkflowsSsdiReconsiderationRouteImport
      parentRoute: typeof WorkflowsRoute
    }
    '/workflows/ssi-denial': {
      id: '/workflows/ssi-denial'
      path: '/ssi-denial'
      fullPath: '/workflows/ssi-denial'
      preLoaderRoute: typeof WorkflowsSsiDenialRouteImport
      parentRoute: typeof WorkflowsRoute
    }
    '/workflows/ssi-reconsideration': {
      id: '/workflows/ssi-reconsideration'
      path: '/ssi-reconsideration'
      fullPath: '/workflows/ssi-reconsideration'
      preLoaderRoute: typeof WorkflowsSsiReconsiderationRouteImport
      parentRoute: typeof WorkflowsRoute
    }
    '/workflows/unemployment-denial': {
      id: '/workflows/unemployment-denial'
      path: '/unemployment-denial'
      fullPath: '/workflows/unemployment-denial'
      preLoaderRoute: typeof WorkflowsUnemploymentDenialRouteImport
      parentRoute: typeof WorkflowsRoute
    }
    '/workflows/va-benefits-denial': {
      id: '/workflows/va-benefits-denial'
      path: '/va-benefits-denial'
      fullPath: '/workflows/va-benefits-denial'
      preLoaderRoute: typeof WorkflowsVaBenefitsDenialRouteImport
      parentRoute: typeof WorkflowsRoute
    }
    '/api/admin/appeals': {
      id: '/api/admin/appeals'
      path: '/api/admin/appeals'
      fullPath: '/api/admin/appeals'
      preLoaderRoute: typeof ApiAdminAppealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/health': {
      id: '/api/admin/health'
      path: '/api/admin/health'
      fullPath: '/api/admin/health'
      preLoaderRoute: typeof ApiAdminHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/status': {
      id: '/api/auth/status'
      path: '/api/auth/status'
      fullPath: '/api/auth/status'
      preLoaderRoute: typeof ApiAuthStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/control-plane/ai': {
      id: '/api/control-plane/ai'
      path: '/api/control-plane/ai'
      fullPath: '/api/control-plane/ai'
      preLoaderRoute: typeof ApiControlPlaneAiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface WorkflowsRouteChildren {
  WorkflowsWorkflowIdRoute: typeof WorkflowsWorkflowIdRoute
  WorkflowsBenefitsReconsiderationRoute: typeof WorkflowsBenefitsReconsiderationRoute
  WorkflowsDisabilityBenefitsDenialRoute: typeof WorkflowsDisabilityBenefitsDenialRoute
  WorkflowsEddDenialRoute: typeof WorkflowsEddDenialRoute
  WorkflowsHearingPreparationRoute: typeof WorkflowsHearingPreparationRoute
  WorkflowsHousingBenefitsDenialRoute: typeof WorkflowsHousingBenefitsDenialRoute
  WorkflowsMedicaidDenialRoute: typeof WorkflowsMedicaidDenialRoute
  WorkflowsOverpaymentRoute: typeof WorkflowsOverpaymentRoute
  WorkflowsSnapDenialRoute: typeof WorkflowsSnapDenialRoute
  WorkflowsSocialSecurityDenialRoute: typeof WorkflowsSocialSecurityDenialRoute
  WorkflowsSsdiDenialRoute: typeof WorkflowsSsdiDenialRoute
  WorkflowsSsdiReconsiderationRoute: typeof WorkflowsSsdiReconsiderationRoute
  WorkflowsSsiDenialRoute: typeof WorkflowsSsiDenialRoute
  WorkflowsSsiReconsiderationRoute: typeof WorkflowsSsiReconsiderationRoute
  WorkflowsUnemploymentDenialRoute: typeof WorkflowsUnemploymentDenialRoute
  WorkflowsVaBenefitsDenialRoute: typeof WorkflowsVaBenefitsDenialRoute
  WorkflowsIndexRoute: typeof WorkflowsIndexRoute
}

const WorkflowsRouteChildren: WorkflowsRouteChildren = {
  WorkflowsWorkflowIdRoute: WorkflowsWorkflowIdRoute,
  WorkflowsBenefitsReconsiderationRoute: WorkflowsBenefitsReconsiderationRoute,
  WorkflowsDisabilityBenefitsDenialRoute:
    WorkflowsDisabilityBenefitsDenialRoute,
  WorkflowsEddDenialRoute: WorkflowsEddDenialRoute,
  WorkflowsHearingPreparationRoute: WorkflowsHearingPreparationRoute,
  WorkflowsHousingBenefitsDenialRoute: WorkflowsHousingBenefitsDenialRoute,
  WorkflowsMedicaidDenialRoute: WorkflowsMedicaidDenialRoute,
  WorkflowsOverpaymentRoute: WorkflowsOverpaymentRoute,
  WorkflowsSnapDenialRoute: WorkflowsSnapDenialRoute,
  WorkflowsSocialSecurityDenialRoute: WorkflowsSocialSecurityDenialRoute,
  WorkflowsSsdiDenialRoute: WorkflowsSsdiDenialRoute,
  WorkflowsSsdiReconsiderationRoute: WorkflowsSsdiReconsiderationRoute,
  WorkflowsSsiDenialRoute: WorkflowsSsiDenialRoute,
  WorkflowsSsiReconsiderationRoute: WorkflowsSsiReconsiderationRoute,
  WorkflowsUnemploymentDenialRoute: WorkflowsUnemploymentDenialRoute,
  WorkflowsVaBenefitsDenialRoute: WorkflowsVaBenefitsDenialRoute,
  WorkflowsIndexRoute: WorkflowsIndexRoute,
}

const WorkflowsRouteWithChildren = WorkflowsRoute._addFileChildren(
  WorkflowsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  AppealADecisionRoute: AppealADecisionRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  FaqRoute: FaqRoute,
  HowItWorksRoute: HowItWorksRoute,
  MailAPdfRoute: MailAPdfRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ProductsRoute: ProductsRoute,
  StartRoute: StartRoute,
  TermsRoute: TermsRoute,
  WorkflowsRoute: WorkflowsRouteWithChildren,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  AppealSlugRoute: AppealSlugRoute,
  AppealAdministrativeRoute: AppealAdministrativeRoute,
  AppealDisabilityRoute: AppealDisabilityRoute,
  AppealMedicaidRoute: AppealMedicaidRoute,
  AppealPublicAssistanceRoute: AppealPublicAssistanceRoute,
  AppealUnemploymentRoute: AppealUnemploymentRoute,
  AppealVeteransRoute: AppealVeteransRoute,
  ResourcesSlugRoute: ResourcesSlugRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
  ApiAdminAppealsRoute: ApiAdminAppealsRoute,
  ApiAdminHealthRoute: ApiAdminHealthRoute,
  ApiAuthStatusRoute: ApiAuthStatusRoute,
  ApiControlPlaneAiRoute: ApiControlPlaneAiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
