/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppealADecisionRouteImport } from './routes/appeal-a-decision'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as MailAPdfRouteImport } from './routes/mail-a-pdf'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as StartRouteImport } from './routes/start'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as WorkflowsRouteImport } from './routes/workflows'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe-webhook'
import { Route as AppealSlugRouteImport } from './routes/appeal/$slug'
import { Route as AppealAdministrativeRouteImport } from './routes/appeal/administrative'
import { Route as AppealDisabilityRouteImport } from './routes/appeal/disability'
import { Route as AppealMedicaidRouteImport } from './routes/appeal/medicaid'
import { Route as AppealPublicAssistanceRouteImport } from './routes/appeal/public-assistance'
import { Route as AppealUnemploymentRouteImport } from './routes/appeal/unemployment'
import { Route as AppealVeteransRouteImport } from './routes/appeal/veterans'
import { Route as ResourcesIndexRouteImport } from './routes/resources/index'
import { Route as ResourcesSlugRouteImport } from './routes/resources/$slug'
import { Route as WorkflowsIndexRouteImport } from './routes/workflows/index'
import { Route as WorkflowsWorkflowIdRouteImport } from './routes/workflows/$workflowId'
import { Route as WorkflowsBenefitsReconsiderationRouteImport } from './routes/workflows/benefits-reconsideration'
import { Route as WorkflowsDisabilityBenefitsDenialRouteImport } from './routes/workflows/disability-benefits-denial'
import { Route as WorkflowsEddDenialRouteImport } from './routes/workflows/edd-denial'
import { Route as WorkflowsHearingPreparationRouteImport } from './routes/workflows/hearing-preparation'
import { Route as WorkflowsHousingBenefitsDenialRouteImport } from './routes/workflows/housing-benefits-denial'
import { Route as WorkflowsMedicaidDenialRouteImport } from './routes/workflows/medicaid-denial'
import { Route as WorkflowsOverpaymentRouteImport } from './routes/workflows/overpayment'
import { Route as WorkflowsSnapDenialRouteImport } from './routes/workflows/snap-denial'
import { Route as WorkflowsSocialSecurityDenialRouteImport } from './routes/workflows/social-security-denial'
import { Route as WorkflowsSsdiDenialRouteImport } from './routes/workflows/ssdi-denial'
import { Route as WorkflowsSsdiReconsiderationRouteImport } from './routes/workflows/ssdi-reconsideration'
import { Route as WorkflowsSsiDenialRouteImport } from './routes/workflows/ssi-denial'
import { Route as WorkflowsSsiReconsiderationRouteImport } from './routes/workflows/ssi-reconsideration'
import { Route as WorkflowsUnemploymentDenialRouteImport } from './routes/workflows/unemployment-denial'
import { Route as WorkflowsVaBenefitsDenialRouteImport } from './routes/workflows/va-benefits-denial'
import { Route as ApiAdminAppealsRouteImport } from './routes/api/admin/appeals'
import { Route as ApiAdminHealthRouteImport } from './routes/api/admin/health'
import { Route as ApiAuthStatusRouteImport } from './routes/api/auth/status'
import { Route as ApiControlPlaneAiRouteImport } from './routes/api/control-plane/ai'
import { Route as ApiMailResponseRouteImport } from './routes/api/mail/response'
import { Route as WorkflowsWorkflowIdStartRouteImport } from './routes/workflows/$workflowId/start'
import { Route as ApiWorkflowsSlugAnalyzeRouteImport } from './routes/api/workflows/$slug/analyze'
import { Route as ApiWorkflowsSlugDraftRouteImport } from './routes/api/workflows/$slug/draft'
import { Route as ApiWorkflowsBenefitsReconsiderationApproveRouteImport } from './routes/api/workflows/benefits-reconsideration/approve'
import { Route as ApiWorkflowsBenefitsReconsiderationCheckoutRouteImport } from './routes/api/workflows/benefits-reconsideration/checkout'
import { Route as ApiWorkflowsDisabilityBenefitsDenialApproveRouteImport } from './routes/api/workflows/disability-benefits-denial/approve'
import { Route as ApiWorkflowsDisabilityBenefitsDenialCheckoutRouteImport } from './routes/api/workflows/disability-benefits-denial/checkout'
import { Route as ApiWorkflowsEddDenialApproveRouteImport } from './routes/api/workflows/edd-denial/approve'
import { Route as ApiWorkflowsEddDenialCheckoutRouteImport } from './routes/api/workflows/edd-denial/checkout'
import { Route as ApiWorkflowsHearingPreparationApproveRouteImport } from './routes/api/workflows/hearing-preparation/approve'
import { Route as ApiWorkflowsHearingPreparationCheckoutRouteImport } from './routes/api/workflows/hearing-preparation/checkout'
import { Route as ApiWorkflowsHousingBenefitsDenialApproveRouteImport } from './routes/api/workflows/housing-benefits-denial/approve'
import { Route as ApiWorkflowsHousingBenefitsDenialCheckoutRouteImport } from './routes/api/workflows/housing-benefits-denial/checkout'
import { Route as ApiWorkflowsMedicaidDenialApproveRouteImport } from './routes/api/workflows/medicaid-denial/approve'
import { Route as ApiWorkflowsMedicaidDenialCheckoutRouteImport } from './routes/api/workflows/medicaid-denial/checkout'
import { Route as ApiWorkflowsOverpaymentApproveRouteImport } from './routes/api/workflows/overpayment/approve'
import { Route as ApiWorkflowsOverpaymentCheckoutRouteImport } from './routes/api/workflows/overpayment/checkout'
import { Route as ApiWorkflowsSnapDenialApproveRouteImport } from './routes/api/workflows/snap-denial/approve'
import { Route as ApiWorkflowsSnapDenialCheckoutRouteImport } from './routes/api/workflows/snap-denial/checkout'
import { Route as ApiWorkflowsSocialSecurityDenialApproveRouteImport } from './routes/api/workflows/social-security-denial/approve'
import { Route as ApiWorkflowsSocialSecurityDenialCheckoutRouteImport } from './routes/api/workflows/social-security-denial/checkout'
import { Route as ApiWorkflowsSsdiDenialApproveRouteImport } from './routes/api/workflows/ssdi-denial/approve'
import { Route as ApiWorkflowsSsdiDenialCheckoutRouteImport } from './routes/api/workflows/ssdi-denial/checkout'
import { Route as ApiWorkflowsSsdiReconsiderationApproveRouteImport } from './routes/api/workflows/ssdi-reconsideration/approve'
import { Route as ApiWorkflowsSsdiReconsiderationCheckoutRouteImport } from './routes/api/workflows/ssdi-reconsideration/checkout'
import { Route as ApiWorkflowsSsiDenialApproveRouteImport } from './routes/api/workflows/ssi-denial/approve'
import { Route as ApiWorkflowsSsiDenialCheckoutRouteImport } from './routes/api/workflows/ssi-denial/checkout'
import { Route as ApiWorkflowsSsiReconsiderationApproveRouteImport } from './routes/api/workflows/ssi-reconsideration/approve'
import { Route as ApiWorkflowsSsiReconsiderationCheckoutRouteImport } from './routes/api/workflows/ssi-reconsideration/checkout'
import { Route as ApiWorkflowsUnemploymentDenialApproveRouteImport } from './routes/api/workflows/unemployment-denial/approve'
import { Route as ApiWorkflowsUnemploymentDenialCheckoutRouteImport } from './routes/api/workflows/unemployment-denial/checkout'
import { Route as ApiWorkflowsVaBenefitsDenialApproveRouteImport } from './routes/api/workflows/va-benefits-denial/approve'
import { Route as ApiWorkflowsVaBenefitsDenialCheckoutRouteImport } from './routes/api/workflows/va-benefits-denial/checkout'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppealADecisionRoute = AppealADecisionRouteImport.update({
  id: '/appeal-a-decision',
  path: '/appeal-a-decision',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const MailAPdfRoute = MailAPdfRouteImport.update({
  id: '/mail-a-pdf',
  path: '/mail-a-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsRoute = WorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe-webhook',
  path: '/api/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AppealSlugRoute = AppealSlugRouteImport.update({
  id: '/appeal/$slug',
  path: '/appeal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppealAdministrativeRoute = AppealAdministrativeRouteImport.update({
  id: '/appeal/administrative',
  path: '/appeal/administrative',
  getParentRoute: () => rootRouteImport,
} as any)
const AppealDisabilityRoute = AppealDisabilityRouteImport.update({
  id: '/appeal/disability',
  path: '/appeal/disability',
  getParentRoute: () => rootRouteImport,
} as any)
const AppealMedicaidRoute = AppealMedicaidRouteImport.update({
  id: '/appeal/medicaid',
  path: '/appeal/medicaid',
  getParentRoute: () => rootRouteImport,
} as any)
const AppealPublicAssistanceRoute = AppealPublicAssistanceRouteImport.update({
  id: '/appeal/public-assistance',
  path: '/appeal/public-assistance',
  getParentRoute: () => rootRouteImport,
} as any)
const AppealUnemploymentRoute = AppealUnemploymentRouteImport.update({
  id: '/appeal/unemployment',
  path: '/appeal/unemployment',
  getParentRoute: () => rootRouteImport,
} as any)
const AppealVeteransRoute = AppealVeteransRouteImport.update({
  id: '/appeal/veterans',
  path: '/appeal/veterans',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesSlugRoute = ResourcesSlugRouteImport.update({
  id: '/resources/$slug',
  path: '/resources/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsIndexRoute = WorkflowsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkflowsRoute,
} as any)
const WorkflowsWorkflowIdRoute = WorkflowsWorkflowIdRouteImport.update({
  id: '/$workflowId',
  path: '/$workflowId',
  getParentRoute: () => WorkflowsRoute,
} as any)
const WorkflowsBenefitsReconsiderationRoute =
  WorkflowsBenefitsReconsiderationRouteImport.update({
    id: '/benefits-reconsideration',
    path: '/benefits-reconsideration',
    getParentRoute: () => WorkflowsRoute,
  } as any)
const WorkflowsDisabilityBenefitsDenialRoute =
  WorkflowsDisabilityBenefitsDenialRouteImport.update({
    id: '/disability-benefits-denial',
    path: '/disability-benefits-denial',
    getParentRoute: () => WorkflowsRoute,
  } as any)
const WorkflowsEddDenialRoute = WorkflowsEddDenialRouteImport.update({
  id: '/edd-denial',
  path: '/edd-denial',
  getParentRoute: () => WorkflowsRoute,
} as any)
const WorkflowsHearingPreparationRoute =
  WorkflowsHearingPreparationRouteImport.update({
    id: '/hearing-preparation',
    path: '/hearing-preparation',
    getParentRoute: () => WorkflowsRoute,
  } as any)
const WorkflowsHousingBenefitsDenialRoute =
  WorkflowsHousingBenefitsDenialRouteImport.update({
    id: '/housing-benefits-denial',
    path: '/housing-benefits-denial',
    getParentRoute: () => WorkflowsRoute,
  } as any)
const WorkflowsMedicaidDenialRoute = WorkflowsMedicaidDenialRouteImport.update({
  id: '/medicaid-denial',
  path: '/medicaid-denial',
  getParentRoute: () => WorkflowsRoute,
} as any)
const WorkflowsOverpaymentRoute = WorkflowsOverpaymentRouteImport.update({
  id: '/overpayment',
  path: '/overpayment',
  getParentRoute: () => WorkflowsRoute,
} as any)
const WorkflowsSnapDenialRoute = WorkflowsSnapDenialRouteImport.update({
  id: '/snap-denial',
  path: '/snap-denial',
  getParentRoute: () => WorkflowsRoute,
} as any)
const WorkflowsSocialSecurityDenialRoute =
  WorkflowsSocialSecurityDenialRouteImport.update({
    id: '/social-security-denial',
    path: '/social-security-denial',
    getParentRoute: () => WorkflowsRoute,
  } as any)
const WorkflowsSsdiDenialRoute = WorkflowsSsdiDenialRouteImport.update({
  id: '/ssdi-denial',
  path: '/ssdi-denial',
  getParentRoute: () => WorkflowsRoute,
} as any)
const WorkflowsSsdiReconsiderationRoute =
  WorkflowsSsdiReconsiderationRouteImport.update({
    id: '/ssdi-reconsideration',
    path: '/ssdi-reconsideration',
    getParentRoute: () => WorkflowsRoute,
  } as any)
const WorkflowsSsiDenialRoute = WorkflowsSsiDenialRouteImport.update({
  id: '/ssi-denial',
  path: '/ssi-denial',
  getParentRoute: () => WorkflowsRoute,
} as any)
const WorkflowsSsiReconsiderationRoute =
  WorkflowsSsiReconsiderationRouteImport.update({
    id: '/ssi-reconsideration',
    path: '/ssi-reconsideration',
    getParentRoute: () => WorkflowsRoute,
  } as any)
const WorkflowsUnemploymentDenialRoute =
  WorkflowsUnemploymentDenialRouteImport.update({
    id: '/unemployment-denial',
    path: '/unemployment-denial',
    getParentRoute: () => WorkflowsRoute,
  } as any)
const WorkflowsVaBenefitsDenialRoute =
  WorkflowsVaBenefitsDenialRouteImport.update({
    id: '/va-benefits-denial',
    path: '/va-benefits-denial',
    getParentRoute: () => WorkflowsRoute,
  } as any)
const ApiAdminAppealsRoute = ApiAdminAppealsRouteImport.update({
  id: '/api/admin/appeals',
  path: '/api/admin/appeals',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminHealthRoute = ApiAdminHealthRouteImport.update({
  id: '/api/admin/health',
  path: '/api/admin/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthStatusRoute = ApiAuthStatusRouteImport.update({
  id: '/api/auth/status',
  path: '/api/auth/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiControlPlaneAiRoute = ApiControlPlaneAiRouteImport.update({
  id: '/api/control-plane/ai',
  path: '/api/control-plane/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMailResponseRoute = ApiMailResponseRouteImport.update({
  id: '/api/mail/response',
  path: '/api/mail/response',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsWorkflowIdStartRoute =
  WorkflowsWorkflowIdStartRouteImport.update({
    id: '/start',
    path: '/start',
    getParentRoute: () => WorkflowsWorkflowIdRoute,
  } as any)
const ApiWorkflowsSlugAnalyzeRoute = ApiWorkflowsSlugAnalyzeRouteImport.update({
  id: '/api/workflows/$slug/analyze',
  path: '/api/workflows/$slug/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkflowsSlugDraftRoute = ApiWorkflowsSlugDraftRouteImport.update({
  id: '/api/workflows/$slug/draft',
  path: '/api/workflows/$slug/draft',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkflowsBenefitsReconsiderationApproveRoute =
  ApiWorkflowsBenefitsReconsiderationApproveRouteImport.update({
    id: '/api/workflows/benefits-reconsideration/approve',
    path: '/api/workflows/benefits-reconsideration/approve',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWorkflowsBenefitsReconsiderationCheckoutRoute =
  ApiWorkflowsBenefitsReconsiderationCheckoutRouteImport.update({
    id: '/api/workflows/benefits-reconsideration/checkout',
    path: '/api/workflows/benefits-reconsideration/checkout',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWorkflowsDisabilityBenefitsDenialApproveRoute =
  ApiWorkflowsDisabilityBenefitsDenialApproveRouteImport.update({
    id: '/api/workflows/disability-benefits-denial/approve',
    path: '/api/workflows/disability-benefits-denial/approve',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWorkflowsDisabilityBenefitsDenialCheckoutRoute =
  ApiWorkflowsDisabilityBenefitsDenialCheckoutRouteImport.update({
    id: '/api/workflows/disability-benefits-denial/checkout',
    path: '/api/workflows/disability-benefits-denial/checkout',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWorkflowsEddDenialApproveRoute =
  ApiWorkflowsEddDenialApproveRouteImport.update({
    id: '/api/workflows/edd-denial/approve',
    path: '/api/workflows/edd-denial/approve',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWorkflowsEddDenialCheckoutRoute =
  ApiWorkflowsEddDenialCheckoutRouteImport.update({
    id: '/api/workflows/edd-denial/checkout',
    path: '/api/workflows/edd-denial/checkout',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWorkflowsHearingPreparationApproveRoute =
  ApiWorkflowsHearingPreparationApproveRouteImport.update({
    id: '/api/workflows/hearing-preparation/approve',
    path: '/api/workflows/hearing-preparation/approve',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWorkflowsHearingPreparationCheckoutRoute =
  ApiWorkflowsHearingPreparationCheckoutRouteImport.update({
    id: '/api/workflows/hearing-preparation/checkout',
    path: '/api/workflows/hearing-preparation/checkout',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWorkflowsHousingBenefitsDenialApproveRoute =
  ApiWorkflowsHousingBenefitsDenialApproveRouteImport.update({
    id: '/api/workflows/housing-benefits-denial/approve',
    path: '/api/workflows/housing-benefits-denial/approve',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWorkflowsHousingBenefitsDenialCheckoutRoute =
  ApiWorkflowsHousingBenefitsDenialCheckoutRouteImport.update({
    id: '/api/workflows/housing-benefits-denial/checkout',
    path: '/api/workflows/housing-benefits-denial/checkout',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWorkflowsMedicaidDenialApproveRoute =
  ApiWorkflowsMedicaidDenialApproveRouteImport.update({
    id: '/api/workflows/medicaid-denial/approve',
    path: '/api/workflows/medicaid-denial/approve',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWorkflowsMedicaidDenialCheckoutRoute =
  ApiWorkflowsMedicaidDenialCheckoutRouteImport.update({
    id: '/api/workflows/medicaid-denial/checkout',
    path: '/api/workflows/medicaid-denial/checkout',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWorkflowsOverpaymentApproveRoute =
  ApiWorkflowsOverpaymentApproveRouteImport.update({
    id: '/api/workflows/overpayment/approve',
    path: '/api/workflows/overpayment/approve',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWorkflowsOverpaymentCheckoutRoute =
  ApiWorkflowsOverpaymentCheckoutRouteImport.update({
    id: '/api/workflows/overpayment/checkout',
    path: '/api/workflows/overpayment/checkout',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWorkflowsSnapDenialApproveRoute =
  ApiWorkflowsSnapDenialApproveRouteImport.update({
    id: '/api/workflows/snap-denial/approve',
    path: '/api/workflows/snap-denial/approve',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWorkflowsSnapDenialCheckoutRoute =
  ApiWorkflowsSnapDenialCheckoutRouteImport.update({
    id: '/api/workflows/snap-denial/checkout',
    path: '/api/workflows/snap-denial/checkout',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWorkflowsSocialSecurityDenialApproveRoute =
  ApiWorkflowsSocialSecurityDenialApproveRouteImport.update({
    id: '/api/workflows/social-security-denial/approve',
    path: '/api/workflows/social-security-denial/approve',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWorkflowsSocialSecurityDenialCheckoutRoute =
  ApiWorkflowsSocialSecurityDenialCheckoutRouteImport.update({
    id: '/api/workflows/social-security-denial/checkout',
    path: '/api/workflows/social-security-denial/checkout',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWorkflowsSsdiDenialApproveRoute =
  ApiWorkflowsSsdiDenialApproveRouteImport.update({
    id: '/api/workflows/ssdi-denial/approve',
    path: '/api/workflows/ssdi-denial/approve',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWorkflowsSsdiDenialCheckoutRoute =
  ApiWorkflowsSsdiDenialCheckoutRouteImport.update({
    id: '/api/workflows/ssdi-denial/checkout',
    path: '/api/workflows/ssdi-denial/checkout',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWorkflowsSsdiReconsiderationApproveRoute =
  ApiWorkflowsSsdiReconsiderationApproveRouteImport.update({
    id: '/api/workflows/ssdi-reconsideration/approve',
    path: '/api/workflows/ssdi-reconsideration/approve',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWorkflowsSsdiReconsiderationCheckoutRoute =
  ApiWorkflowsSsdiReconsiderationCheckoutRouteImport.update({
    id: '/api/workflows/ssdi-reconsideration/checkout',
    path: '/api/workflows/ssdi-reconsideration/checkout',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWorkflowsSsiDenialApproveRoute =
  ApiWorkflowsSsiDenialApproveRouteImport.update({
    id: '/api/workflows/ssi-denial/approve',
    path: '/api/workflows/ssi-denial/approve',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWorkflowsSsiDenialCheckoutRoute =
  ApiWorkflowsSsiDenialCheckoutRouteImport.update({
    id: '/api/workflows/ssi-denial/checkout',
    path: '/api/workflows/ssi-denial/checkout',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWorkflowsSsiReconsiderationApproveRoute =
  ApiWorkflowsSsiReconsiderationApproveRouteImport.update({
    id: '/api/workflows/ssi-reconsideration/approve',
    path: '/api/workflows/ssi-reconsideration/approve',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWorkflowsSsiReconsiderationCheckoutRoute =
  ApiWorkflowsSsiReconsiderationCheckoutRouteImport.update({
    id: '/api/workflows/ssi-reconsideration/checkout',
    path: '/api/workflows/ssi-reconsideration/checkout',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWorkflowsUnemploymentDenialApproveRoute =
  ApiWorkflowsUnemploymentDenialApproveRouteImport.update({
    id: '/api/workflows/unemployment-denial/approve',
    path: '/api/workflows/unemployment-denial/approve',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWorkflowsUnemploymentDenialCheckoutRoute =
  ApiWorkflowsUnemploymentDenialCheckoutRouteImport.update({
    id: '/api/workflows/unemployment-denial/checkout',
    path: '/api/workflows/unemployment-denial/checkout',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWorkflowsVaBenefitsDenialApproveRoute =
  ApiWorkflowsVaBenefitsDenialApproveRouteImport.update({
    id: '/api/workflows/va-benefits-denial/approve',
    path: '/api/workflows/va-benefits-denial/approve',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWorkflowsVaBenefitsDenialCheckoutRoute =
  ApiWorkflowsVaBenefitsDenialCheckoutRouteImport.update({
    id: '/api/workflows/va-benefits-denial/checkout',
    path: '/api/workflows/va-benefits-denial/checkout',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/appeal-a-decision': typeof AppealADecisionRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/mail-a-pdf': typeof MailAPdfRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRoute
  '/start': typeof StartRoute
  '/terms': typeof TermsRoute
  '/workflows': typeof WorkflowsRouteWithChildren
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/appeal/$slug': typeof AppealSlugRoute
  '/appeal/administrative': typeof AppealAdministrativeRoute
  '/appeal/disability': typeof AppealDisabilityRoute
  '/appeal/medicaid': typeof AppealMedicaidRoute
  '/appeal/public-assistance': typeof AppealPublicAssistanceRoute
  '/appeal/unemployment': typeof AppealUnemploymentRoute
  '/appeal/veterans': typeof AppealVeteransRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/workflows/$workflowId': typeof WorkflowsWorkflowIdRouteWithChildren
  '/workflows/benefits-reconsideration': typeof WorkflowsBenefitsReconsiderationRoute
  '/workflows/disability-benefits-denial': typeof WorkflowsDisabilityBenefitsDenialRoute
  '/workflows/edd-denial': typeof WorkflowsEddDenialRoute
  '/workflows/hearing-preparation': typeof WorkflowsHearingPreparationRoute
  '/workflows/housing-benefits-denial': typeof WorkflowsHousingBenefitsDenialRoute
  '/workflows/medicaid-denial': typeof WorkflowsMedicaidDenialRoute
  '/workflows/overpayment': typeof WorkflowsOverpaymentRoute
  '/workflows/snap-denial': typeof WorkflowsSnapDenialRoute
  '/workflows/social-security-denial': typeof WorkflowsSocialSecurityDenialRoute
  '/workflows/ssdi-denial': typeof WorkflowsSsdiDenialRoute
  '/workflows/ssdi-reconsideration': typeof WorkflowsSsdiReconsiderationRoute
  '/workflows/ssi-denial': typeof WorkflowsSsiDenialRoute
  '/workflows/ssi-reconsideration': typeof WorkflowsSsiReconsiderationRoute
  '/workflows/unemployment-denial': typeof WorkflowsUnemploymentDenialRoute
  '/workflows/va-benefits-denial': typeof WorkflowsVaBenefitsDenialRoute
  '/resources/': typeof ResourcesIndexRoute
  '/workflows/': typeof WorkflowsIndexRoute
  '/api/admin/appeals': typeof ApiAdminAppealsRoute
  '/api/admin/health': typeof ApiAdminHealthRoute
  '/api/auth/status': typeof ApiAuthStatusRoute
  '/api/control-plane/ai': typeof ApiControlPlaneAiRoute
  '/api/mail/response': typeof ApiMailResponseRoute
  '/workflows/$workflowId/start': typeof WorkflowsWorkflowIdStartRoute
  '/api/workflows/$slug/analyze': typeof ApiWorkflowsSlugAnalyzeRoute
  '/api/workflows/$slug/draft': typeof ApiWorkflowsSlugDraftRoute
  '/api/workflows/benefits-reconsideration/approve': typeof ApiWorkflowsBenefitsReconsiderationApproveRoute
  '/api/workflows/benefits-reconsideration/checkout': typeof ApiWorkflowsBenefitsReconsiderationCheckoutRoute
  '/api/workflows/disability-benefits-denial/approve': typeof ApiWorkflowsDisabilityBenefitsDenialApproveRoute
  '/api/workflows/disability-benefits-denial/checkout': typeof ApiWorkflowsDisabilityBenefitsDenialCheckoutRoute
  '/api/workflows/edd-denial/approve': typeof ApiWorkflowsEddDenialApproveRoute
  '/api/workflows/edd-denial/checkout': typeof ApiWorkflowsEddDenialCheckoutRoute
  '/api/workflows/hearing-preparation/approve': typeof ApiWorkflowsHearingPreparationApproveRoute
  '/api/workflows/hearing-preparation/checkout': typeof ApiWorkflowsHearingPreparationCheckoutRoute
  '/api/workflows/housing-benefits-denial/approve': typeof ApiWorkflowsHousingBenefitsDenialApproveRoute
  '/api/workflows/housing-benefits-denial/checkout': typeof ApiWorkflowsHousingBenefitsDenialCheckoutRoute
  '/api/workflows/medicaid-denial/approve': typeof ApiWorkflowsMedicaidDenialApproveRoute
  '/api/workflows/medicaid-denial/checkout': typeof ApiWorkflowsMedicaidDenialCheckoutRoute
  '/api/workflows/overpayment/approve': typeof ApiWorkflowsOverpaymentApproveRoute
  '/api/workflows/overpayment/checkout': typeof ApiWorkflowsOverpaymentCheckoutRoute
  '/api/workflows/snap-denial/approve': typeof ApiWorkflowsSnapDenialApproveRoute
  '/api/workflows/snap-denial/checkout': typeof ApiWorkflowsSnapDenialCheckoutRoute
  '/api/workflows/social-security-denial/approve': typeof ApiWorkflowsSocialSecurityDenialApproveRoute
  '/api/workflows/social-security-denial/checkout': typeof ApiWorkflowsSocialSecurityDenialCheckoutRoute
  '/api/workflows/ssdi-denial/approve': typeof ApiWorkflowsSsdiDenialApproveRoute
  '/api/workflows/ssdi-denial/checkout': typeof ApiWorkflowsSsdiDenialCheckoutRoute
  '/api/workflows/ssdi-reconsideration/approve': typeof ApiWorkflowsSsdiReconsiderationApproveRoute
  '/api/workflows/ssdi-reconsideration/checkout': typeof ApiWorkflowsSsdiReconsiderationCheckoutRoute
  '/api/workflows/ssi-denial/approve': typeof ApiWorkflowsSsiDenialApproveRoute
  '/api/workflows/ssi-denial/checkout': typeof ApiWorkflowsSsiDenialCheckoutRoute
  '/api/workflows/ssi-reconsideration/approve': typeof ApiWorkflowsSsiReconsiderationApproveRoute
  '/api/workflows/ssi-reconsideration/checkout': typeof ApiWorkflowsSsiReconsiderationCheckoutRoute
  '/api/workflows/unemployment-denial/approve': typeof ApiWorkflowsUnemploymentDenialApproveRoute
  '/api/workflows/unemployment-denial/checkout': typeof ApiWorkflowsUnemploymentDenialCheckoutRoute
  '/api/workflows/va-benefits-denial/approve': typeof ApiWorkflowsVaBenefitsDenialApproveRoute
  '/api/workflows/va-benefits-denial/checkout': typeof ApiWorkflowsVaBenefitsDenialCheckoutRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/appeal-a-decision': typeof AppealADecisionRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/mail-a-pdf': typeof MailAPdfRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRoute
  '/start': typeof StartRoute
  '/terms': typeof TermsRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/appeal/$slug': typeof AppealSlugRoute
  '/appeal/administrative': typeof AppealAdministrativeRoute
  '/appeal/disability': typeof AppealDisabilityRoute
  '/appeal/medicaid': typeof AppealMedicaidRoute
  '/appeal/public-assistance': typeof AppealPublicAssistanceRoute
  '/appeal/unemployment': typeof AppealUnemploymentRoute
  '/appeal/veterans': typeof AppealVeteransRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/workflows/$workflowId': typeof WorkflowsWorkflowIdRouteWithChildren
  '/workflows/benefits-reconsideration': typeof WorkflowsBenefitsReconsiderationRoute
  '/workflows/disability-benefits-denial': typeof WorkflowsDisabilityBenefitsDenialRoute
  '/workflows/edd-denial': typeof WorkflowsEddDenialRoute
  '/workflows/hearing-preparation': typeof WorkflowsHearingPreparationRoute
  '/workflows/housing-benefits-denial': typeof WorkflowsHousingBenefitsDenialRoute
  '/workflows/medicaid-denial': typeof WorkflowsMedicaidDenialRoute
  '/workflows/overpayment': typeof WorkflowsOverpaymentRoute
  '/workflows/snap-denial': typeof WorkflowsSnapDenialRoute
  '/workflows/social-security-denial': typeof WorkflowsSocialSecurityDenialRoute
  '/workflows/ssdi-denial': typeof WorkflowsSsdiDenialRoute
  '/workflows/ssdi-reconsideration': typeof WorkflowsSsdiReconsiderationRoute
  '/workflows/ssi-denial': typeof WorkflowsSsiDenialRoute
  '/workflows/ssi-reconsideration': typeof WorkflowsSsiReconsiderationRoute
  '/workflows/unemployment-denial': typeof WorkflowsUnemploymentDenialRoute
  '/workflows/va-benefits-denial': typeof WorkflowsVaBenefitsDenialRoute
  '/resources': typeof ResourcesIndexRoute
  '/workflows': typeof WorkflowsIndexRoute
  '/api/admin/appeals': typeof ApiAdminAppealsRoute
  '/api/admin/health': typeof ApiAdminHealthRoute
  '/api/auth/status': typeof ApiAuthStatusRoute
  '/api/control-plane/ai': typeof ApiControlPlaneAiRoute
  '/api/mail/response': typeof ApiMailResponseRoute
  '/workflows/$workflowId/start': typeof WorkflowsWorkflowIdStartRoute
  '/api/workflows/$slug/analyze': typeof ApiWorkflowsSlugAnalyzeRoute
  '/api/workflows/$slug/draft': typeof ApiWorkflowsSlugDraftRoute
  '/api/workflows/benefits-reconsideration/approve': typeof ApiWorkflowsBenefitsReconsiderationApproveRoute
  '/api/workflows/benefits-reconsideration/checkout': typeof ApiWorkflowsBenefitsReconsiderationCheckoutRoute
  '/api/workflows/disability-benefits-denial/approve': typeof ApiWorkflowsDisabilityBenefitsDenialApproveRoute
  '/api/workflows/disability-benefits-denial/checkout': typeof ApiWorkflowsDisabilityBenefitsDenialCheckoutRoute
  '/api/workflows/edd-denial/approve': typeof ApiWorkflowsEddDenialApproveRoute
  '/api/workflows/edd-denial/checkout': typeof ApiWorkflowsEddDenialCheckoutRoute
  '/api/workflows/hearing-preparation/approve': typeof ApiWorkflowsHearingPreparationApproveRoute
  '/api/workflows/hearing-preparation/checkout': typeof ApiWorkflowsHearingPreparationCheckoutRoute
  '/api/workflows/housing-benefits-denial/approve': typeof ApiWorkflowsHousingBenefitsDenialApproveRoute
  '/api/workflows/housing-benefits-denial/checkout': typeof ApiWorkflowsHousingBenefitsDenialCheckoutRoute
  '/api/workflows/medicaid-denial/approve': typeof ApiWorkflowsMedicaidDenialApproveRoute
  '/api/workflows/medicaid-denial/checkout': typeof ApiWorkflowsMedicaidDenialCheckoutRoute
  '/api/workflows/overpayment/approve': typeof ApiWorkflowsOverpaymentApproveRoute
  '/api/workflows/overpayment/checkout': typeof ApiWorkflowsOverpaymentCheckoutRoute
  '/api/workflows/snap-denial/approve': typeof ApiWorkflowsSnapDenialApproveRoute
  '/api/workflows/snap-denial/checkout': typeof ApiWorkflowsSnapDenialCheckoutRoute
  '/api/workflows/social-security-denial/approve': typeof ApiWorkflowsSocialSecurityDenialApproveRoute
  '/api/workflows/social-security-denial/checkout': typeof ApiWorkflowsSocialSecurityDenialCheckoutRoute
  '/api/workflows/ssdi-denial/approve': typeof ApiWorkflowsSsdiDenialApproveRoute
  '/api/workflows/ssdi-denial/checkout': typeof ApiWorkflowsSsdiDenialCheckoutRoute
  '/api/workflows/ssdi-reconsideration/approve': typeof ApiWorkflowsSsdiReconsiderationApproveRoute
  '/api/workflows/ssdi-reconsideration/checkout': typeof ApiWorkflowsSsdiReconsiderationCheckoutRoute
  '/api/workflows/ssi-denial/approve': typeof ApiWorkflowsSsiDenialApproveRoute
  '/api/workflows/ssi-denial/checkout': typeof ApiWorkflowsSsiDenialCheckoutRoute
  '/api/workflows/ssi-reconsideration/approve': typeof ApiWorkflowsSsiReconsiderationApproveRoute
  '/api/workflows/ssi-reconsideration/checkout': typeof ApiWorkflowsSsiReconsiderationCheckoutRoute
  '/api/workflows/unemployment-denial/approve': typeof ApiWorkflowsUnemploymentDenialApproveRoute
  '/api/workflows/unemployment-denial/checkout': typeof ApiWorkflowsUnemploymentDenialCheckoutRoute
  '/api/workflows/va-benefits-denial/approve': typeof ApiWorkflowsVaBenefitsDenialApproveRoute
  '/api/workflows/va-benefits-denial/checkout': typeof ApiWorkflowsVaBenefitsDenialCheckoutRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/appeal-a-decision': typeof AppealADecisionRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/mail-a-pdf': typeof MailAPdfRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRoute
  '/start': typeof StartRoute
  '/terms': typeof TermsRoute
  '/workflows': typeof WorkflowsRouteWithChildren
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/appeal/$slug': typeof AppealSlugRoute
  '/appeal/administrative': typeof AppealAdministrativeRoute
  '/appeal/disability': typeof AppealDisabilityRoute
  '/appeal/medicaid': typeof AppealMedicaidRoute
  '/appeal/public-assistance': typeof AppealPublicAssistanceRoute
  '/appeal/unemployment': typeof AppealUnemploymentRoute
  '/appeal/veterans': typeof AppealVeteransRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/workflows/$workflowId': typeof WorkflowsWorkflowIdRouteWithChildren
  '/workflows/benefits-reconsideration': typeof WorkflowsBenefitsReconsiderationRoute
  '/workflows/disability-benefits-denial': typeof WorkflowsDisabilityBenefitsDenialRoute
  '/workflows/edd-denial': typeof WorkflowsEddDenialRoute
  '/workflows/hearing-preparation': typeof WorkflowsHearingPreparationRoute
  '/workflows/housing-benefits-denial': typeof WorkflowsHousingBenefitsDenialRoute
  '/workflows/medicaid-denial': typeof WorkflowsMedicaidDenialRoute
  '/workflows/overpayment': typeof WorkflowsOverpaymentRoute
  '/workflows/snap-denial': typeof WorkflowsSnapDenialRoute
  '/workflows/social-security-denial': typeof WorkflowsSocialSecurityDenialRoute
  '/workflows/ssdi-denial': typeof WorkflowsSsdiDenialRoute
  '/workflows/ssdi-reconsideration': typeof WorkflowsSsdiReconsiderationRoute
  '/workflows/ssi-denial': typeof WorkflowsSsiDenialRoute
  '/workflows/ssi-reconsideration': typeof WorkflowsSsiReconsiderationRoute
  '/workflows/unemployment-denial': typeof WorkflowsUnemploymentDenialRoute
  '/workflows/va-benefits-denial': typeof WorkflowsVaBenefitsDenialRoute
  '/resources/': typeof ResourcesIndexRoute
  '/workflows/': typeof WorkflowsIndexRoute
  '/api/admin/appeals': typeof ApiAdminAppealsRoute
  '/api/admin/health': typeof ApiAdminHealthRoute
  '/api/auth/status': typeof ApiAuthStatusRoute
  '/api/control-plane/ai': typeof ApiControlPlaneAiRoute
  '/api/mail/response': typeof ApiMailResponseRoute
  '/workflows/$workflowId/start': typeof WorkflowsWorkflowIdStartRoute
  '/api/workflows/$slug/analyze': typeof ApiWorkflowsSlugAnalyzeRoute
  '/api/workflows/$slug/draft': typeof ApiWorkflowsSlugDraftRoute
  '/api/workflows/benefits-reconsideration/approve': typeof ApiWorkflowsBenefitsReconsiderationApproveRoute
  '/api/workflows/benefits-reconsideration/checkout': typeof ApiWorkflowsBenefitsReconsiderationCheckoutRoute
  '/api/workflows/disability-benefits-denial/approve': typeof ApiWorkflowsDisabilityBenefitsDenialApproveRoute
  '/api/workflows/disability-benefits-denial/checkout': typeof ApiWorkflowsDisabilityBenefitsDenialCheckoutRoute
  '/api/workflows/edd-denial/approve': typeof ApiWorkflowsEddDenialApproveRoute
  '/api/workflows/edd-denial/checkout': typeof ApiWorkflowsEddDenialCheckoutRoute
  '/api/workflows/hearing-preparation/approve': typeof ApiWorkflowsHearingPreparationApproveRoute
  '/api/workflows/hearing-preparation/checkout': typeof ApiWorkflowsHearingPreparationCheckoutRoute
  '/api/workflows/housing-benefits-denial/approve': typeof ApiWorkflowsHousingBenefitsDenialApproveRoute
  '/api/workflows/housing-benefits-denial/checkout': typeof ApiWorkflowsHousingBenefitsDenialCheckoutRoute
  '/api/workflows/medicaid-denial/approve': typeof ApiWorkflowsMedicaidDenialApproveRoute
  '/api/workflows/medicaid-denial/checkout': typeof ApiWorkflowsMedicaidDenialCheckoutRoute
  '/api/workflows/overpayment/approve': typeof ApiWorkflowsOverpaymentApproveRoute
  '/api/workflows/overpayment/checkout': typeof ApiWorkflowsOverpaymentCheckoutRoute
  '/api/workflows/snap-denial/approve': typeof ApiWorkflowsSnapDenialApproveRoute
  '/api/workflows/snap-denial/checkout': typeof ApiWorkflowsSnapDenialCheckoutRoute
  '/api/workflows/social-security-denial/approve': typeof ApiWorkflowsSocialSecurityDenialApproveRoute
  '/api/workflows/social-security-denial/checkout': typeof ApiWorkflowsSocialSecurityDenialCheckoutRoute
  '/api/workflows/ssdi-denial/approve': typeof ApiWorkflowsSsdiDenialApproveRoute
  '/api/workflows/ssdi-denial/checkout': typeof ApiWorkflowsSsdiDenialCheckoutRoute
  '/api/workflows/ssdi-reconsideration/approve': typeof ApiWorkflowsSsdiReconsiderationApproveRoute
  '/api/workflows/ssdi-reconsideration/checkout': typeof ApiWorkflowsSsdiReconsiderationCheckoutRoute
  '/api/workflows/ssi-denial/approve': typeof ApiWorkflowsSsiDenialApproveRoute
  '/api/workflows/ssi-denial/checkout': typeof ApiWorkflowsSsiDenialCheckoutRoute
  '/api/workflows/ssi-reconsideration/approve': typeof ApiWorkflowsSsiReconsiderationApproveRoute
  '/api/workflows/ssi-reconsideration/checkout': typeof ApiWorkflowsSsiReconsiderationCheckoutRoute
  '/api/workflows/unemployment-denial/approve': typeof ApiWorkflowsUnemploymentDenialApproveRoute
  '/api/workflows/unemployment-denial/checkout': typeof ApiWorkflowsUnemploymentDenialCheckoutRoute
  '/api/workflows/va-benefits-denial/approve': typeof ApiWorkflowsVaBenefitsDenialApproveRoute
  '/api/workflows/va-benefits-denial/checkout': typeof ApiWorkflowsVaBenefitsDenialCheckoutRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/appeal-a-decision'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/how-it-works'
    | '/mail-a-pdf'
    | '/pricing'
    | '/privacy'
    | '/products'
    | '/start'
    | '/terms'
    | '/workflows'
    | '/api/stripe-webhook'
    | '/appeal/$slug'
    | '/appeal/administrative'
    | '/appeal/disability'
    | '/appeal/medicaid'
    | '/appeal/public-assistance'
    | '/appeal/unemployment'
    | '/appeal/veterans'
    | '/resources/$slug'
    | '/workflows/$workflowId'
    | '/workflows/benefits-reconsideration'
    | '/workflows/disability-benefits-denial'
    | '/workflows/edd-denial'
    | '/workflows/hearing-preparation'
    | '/workflows/housing-benefits-denial'
    | '/workflows/medicaid-denial'
    | '/workflows/overpayment'
    | '/workflows/snap-denial'
    | '/workflows/social-security-denial'
    | '/workflows/ssdi-denial'
    | '/workflows/ssdi-reconsideration'
    | '/workflows/ssi-denial'
    | '/workflows/ssi-reconsideration'
    | '/workflows/unemployment-denial'
    | '/workflows/va-benefits-denial'
    | '/resources/'
    | '/workflows/'
    | '/api/admin/appeals'
    | '/api/admin/health'
    | '/api/auth/status'
    | '/api/control-plane/ai'
    | '/api/mail/response'
    | '/workflows/$workflowId/start'
    | '/api/workflows/$slug/analyze'
    | '/api/workflows/$slug/draft'
    | '/api/workflows/benefits-reconsideration/approve'
    | '/api/workflows/benefits-reconsideration/checkout'
    | '/api/workflows/disability-benefits-denial/approve'
    | '/api/workflows/disability-benefits-denial/checkout'
    | '/api/workflows/edd-denial/approve'
    | '/api/workflows/edd-denial/checkout'
    | '/api/workflows/hearing-preparation/approve'
    | '/api/workflows/hearing-preparation/checkout'
    | '/api/workflows/housing-benefits-denial/approve'
    | '/api/workflows/housing-benefits-denial/checkout'
    | '/api/workflows/medicaid-denial/approve'
    | '/api/workflows/medicaid-denial/checkout'
    | '/api/workflows/overpayment/approve'
    | '/api/workflows/overpayment/checkout'
    | '/api/workflows/snap-denial/approve'
    | '/api/workflows/snap-denial/checkout'
    | '/api/workflows/social-security-denial/approve'
    | '/api/workflows/social-security-denial/checkout'
    | '/api/workflows/ssdi-denial/approve'
    | '/api/workflows/ssdi-denial/checkout'
    | '/api/workflows/ssdi-reconsideration/approve'
    | '/api/workflows/ssdi-reconsideration/checkout'
    | '/api/workflows/ssi-denial/approve'
    | '/api/workflows/ssi-denial/checkout'
    | '/api/workflows/ssi-reconsideration/approve'
    | '/api/workflows/ssi-reconsideration/checkout'
    | '/api/workflows/unemployment-denial/approve'
    | '/api/workflows/unemployment-denial/checkout'
    | '/api/workflows/va-benefits-denial/approve'
    | '/api/workflows/va-benefits-denial/checkout'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/appeal-a-decision'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/how-it-works'
    | '/mail-a-pdf'
    | '/pricing'
    | '/privacy'
    | '/products'
    | '/start'
    | '/terms'
    | '/api/stripe-webhook'
    | '/appeal/$slug'
    | '/appeal/administrative'
    | '/appeal/disability'
    | '/appeal/medicaid'
    | '/appeal/public-assistance'
    | '/appeal/unemployment'
    | '/appeal/veterans'
    | '/resources/$slug'
    | '/workflows/$workflowId'
    | '/workflows/benefits-reconsideration'
    | '/workflows/disability-benefits-denial'
    | '/workflows/edd-denial'
    | '/workflows/hearing-preparation'
    | '/workflows/housing-benefits-denial'
    | '/workflows/medicaid-denial'
    | '/workflows/overpayment'
    | '/workflows/snap-denial'
    | '/workflows/social-security-denial'
    | '/workflows/ssdi-denial'
    | '/workflows/ssdi-reconsideration'
    | '/workflows/ssi-denial'
    | '/workflows/ssi-reconsideration'
    | '/workflows/unemployment-denial'
    | '/workflows/va-benefits-denial'
    | '/resources'
    | '/workflows'
    | '/api/admin/appeals'
    | '/api/admin/health'
    | '/api/auth/status'
    | '/api/control-plane/ai'
    | '/api/mail/response'
    | '/workflows/$workflowId/start'
    | '/api/workflows/$slug/analyze'
    | '/api/workflows/$slug/draft'
    | '/api/workflows/benefits-reconsideration/approve'
    | '/api/workflows/benefits-reconsideration/checkout'
    | '/api/workflows/disability-benefits-denial/approve'
    | '/api/workflows/disability-benefits-denial/checkout'
    | '/api/workflows/edd-denial/approve'
    | '/api/workflows/edd-denial/checkout'
    | '/api/workflows/hearing-preparation/approve'
    | '/api/workflows/hearing-preparation/checkout'
    | '/api/workflows/housing-benefits-denial/approve'
    | '/api/workflows/housing-benefits-denial/checkout'
    | '/api/workflows/medicaid-denial/approve'
    | '/api/workflows/medicaid-denial/checkout'
    | '/api/workflows/overpayment/approve'
    | '/api/workflows/overpayment/checkout'
    | '/api/workflows/snap-denial/approve'
    | '/api/workflows/snap-denial/checkout'
    | '/api/workflows/social-security-denial/approve'
    | '/api/workflows/social-security-denial/checkout'
    | '/api/workflows/ssdi-denial/approve'
    | '/api/workflows/ssdi-denial/checkout'
    | '/api/workflows/ssdi-reconsideration/approve'
    | '/api/workflows/ssdi-reconsideration/checkout'
    | '/api/workflows/ssi-denial/approve'
    | '/api/workflows/ssi-denial/checkout'
    | '/api/workflows/ssi-reconsideration/approve'
    | '/api/workflows/ssi-reconsideration/checkout'
    | '/api/workflows/unemployment-denial/approve'
    | '/api/workflows/unemployment-denial/checkout'
    | '/api/workflows/va-benefits-denial/approve'
    | '/api/workflows/va-benefits-denial/checkout'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/appeal-a-decision'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/faq'
    | '/how-it-works'
    | '/mail-a-pdf'
    | '/pricing'
    | '/privacy'
    | '/products'
    | '/start'
    | '/terms'
    | '/workflows'
    | '/api/stripe-webhook'
    | '/appeal/$slug'
    | '/appeal/administrative'
    | '/appeal/disability'
    | '/appeal/medicaid'
    | '/appeal/public-assistance'
    | '/appeal/unemployment'
    | '/appeal/veterans'
    | '/resources/$slug'
    | '/workflows/$workflowId'
    | '/workflows/benefits-reconsideration'
    | '/workflows/disability-benefits-denial'
    | '/workflows/edd-denial'
    | '/workflows/hearing-preparation'
    | '/workflows/housing-benefits-denial'
    | '/workflows/medicaid-denial'
    | '/workflows/overpayment'
    | '/workflows/snap-denial'
    | '/workflows/social-security-denial'
    | '/workflows/ssdi-denial'
    | '/workflows/ssdi-reconsideration'
    | '/workflows/ssi-denial'
    | '/workflows/ssi-reconsideration'
    | '/workflows/unemployment-denial'
    | '/workflows/va-benefits-denial'
    | '/resources/'
    | '/workflows/'
    | '/api/admin/appeals'
    | '/api/admin/health'
    | '/api/auth/status'
    | '/api/control-plane/ai'
    | '/api/mail/response'
    | '/workflows/$workflowId/start'
    | '/api/workflows/$slug/analyze'
    | '/api/workflows/$slug/draft'
    | '/api/workflows/benefits-reconsideration/approve'
    | '/api/workflows/benefits-reconsideration/checkout'
    | '/api/workflows/disability-benefits-denial/approve'
    | '/api/workflows/disability-benefits-denial/checkout'
    | '/api/workflows/edd-denial/approve'
    | '/api/workflows/edd-denial/checkout'
    | '/api/workflows/hearing-preparation/approve'
    | '/api/workflows/hearing-preparation/checkout'
    | '/api/workflows/housing-benefits-denial/approve'
    | '/api/workflows/housing-benefits-denial/checkout'
    | '/api/workflows/medicaid-denial/approve'
    | '/api/workflows/medicaid-denial/checkout'
    | '/api/workflows/overpayment/approve'
    | '/api/workflows/overpayment/checkout'
    | '/api/workflows/snap-denial/approve'
    | '/api/workflows/snap-denial/checkout'
    | '/api/workflows/social-security-denial/approve'
    | '/api/workflows/social-security-denial/checkout'
    | '/api/workflows/ssdi-denial/approve'
    | '/api/workflows/ssdi-denial/checkout'
    | '/api/workflows/ssdi-reconsideration/approve'
    | '/api/workflows/ssdi-reconsideration/checkout'
    | '/api/workflows/ssi-denial/approve'
    | '/api/workflows/ssi-denial/checkout'
    | '/api/workflows/ssi-reconsideration/approve'
    | '/api/workflows/ssi-reconsideration/checkout'
    | '/api/workflows/unemployment-denial/approve'
    | '/api/workflows/unemployment-denial/checkout'
    | '/api/workflows/va-benefits-denial/approve'
    | '/api/workflows/va-benefits-denial/checkout'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  AppealADecisionRoute: typeof AppealADecisionRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  FaqRoute: typeof FaqRoute
  HowItWorksRoute: typeof HowItWorksRoute
  MailAPdfRoute: typeof MailAPdfRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProductsRoute: typeof ProductsRoute
  StartRoute: typeof StartRoute
  TermsRoute: typeof TermsRoute
  WorkflowsRoute: typeof WorkflowsRouteWithChildren
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  AppealSlugRoute: typeof AppealSlugRoute
  AppealAdministrativeRoute: typeof AppealAdministrativeRoute
  AppealDisabilityRoute: typeof AppealDisabilityRoute
  AppealMedicaidRoute: typeof AppealMedicaidRoute
  AppealPublicAssistanceRoute: typeof AppealPublicAssistanceRoute
  AppealUnemploymentRoute: typeof AppealUnemploymentRoute
  AppealVeteransRoute: typeof AppealVeteransRoute
  ResourcesSlugRoute: typeof ResourcesSlugRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
  ApiAdminAppealsRoute: typeof ApiAdminAppealsRoute
  ApiAdminHealthRoute: typeof ApiAdminHealthRoute
  ApiAuthStatusRoute: typeof ApiAuthStatusRoute
  ApiControlPlaneAiRoute: typeof ApiControlPlaneAiRoute
  ApiMailResponseRoute: typeof ApiMailResponseRoute
  ApiWorkflowsSlugAnalyzeRoute: typeof ApiWorkflowsSlugAnalyzeRoute
  ApiWorkflowsSlugDraftRoute: typeof ApiWorkflowsSlugDraftRoute
  ApiWorkflowsBenefitsReconsiderationApproveRoute: typeof ApiWorkflowsBenefitsReconsiderationApproveRoute
  ApiWorkflowsBenefitsReconsiderationCheckoutRoute: typeof ApiWorkflowsBenefitsReconsiderationCheckoutRoute
  ApiWorkflowsDisabilityBenefitsDenialApproveRoute: typeof ApiWorkflowsDisabilityBenefitsDenialApproveRoute
  ApiWorkflowsDisabilityBenefitsDenialCheckoutRoute: typeof ApiWorkflowsDisabilityBenefitsDenialCheckoutRoute
  ApiWorkflowsEddDenialApproveRoute: typeof ApiWorkflowsEddDenialApproveRoute
  ApiWorkflowsEddDenialCheckoutRoute: typeof ApiWorkflowsEddDenialCheckoutRoute
  ApiWorkflowsHearingPreparationApproveRoute: typeof ApiWorkflowsHearingPreparationApproveRoute
  ApiWorkflowsHearingPreparationCheckoutRoute: typeof ApiWorkflowsHearingPreparationCheckoutRoute
  ApiWorkflowsHousingBenefitsDenialApproveRoute: typeof ApiWorkflowsHousingBenefitsDenialApproveRoute
  ApiWorkflowsHousingBenefitsDenialCheckoutRoute: typeof ApiWorkflowsHousingBenefitsDenialCheckoutRoute
  ApiWorkflowsMedicaidDenialApproveRoute: typeof ApiWorkflowsMedicaidDenialApproveRoute
  ApiWorkflowsMedicaidDenialCheckoutRoute: typeof ApiWorkflowsMedicaidDenialCheckoutRoute
  ApiWorkflowsOverpaymentApproveRoute: typeof ApiWorkflowsOverpaymentApproveRoute
  ApiWorkflowsOverpaymentCheckoutRoute: typeof ApiWorkflowsOverpaymentCheckoutRoute
  ApiWorkflowsSnapDenialApproveRoute: typeof ApiWorkflowsSnapDenialApproveRoute
  ApiWorkflowsSnapDenialCheckoutRoute: typeof ApiWorkflowsSnapDenialCheckoutRoute
  ApiWorkflowsSocialSecurityDenialApproveRoute: typeof ApiWorkflowsSocialSecurityDenialApproveRoute
  ApiWorkflowsSocialSecurityDenialCheckoutRoute: typeof ApiWorkflowsSocialSecurityDenialCheckoutRoute
  ApiWorkflowsSsdiDenialApproveRoute: typeof ApiWorkflowsSsdiDenialApproveRoute
  ApiWorkflowsSsdiDenialCheckoutRoute: typeof ApiWorkflowsSsdiDenialCheckoutRoute
  ApiWorkflowsSsdiReconsiderationApproveRoute: typeof ApiWorkflowsSsdiReconsiderationApproveRoute
  ApiWorkflowsSsdiReconsiderationCheckoutRoute: typeof ApiWorkflowsSsdiReconsiderationCheckoutRoute
  ApiWorkflowsSsiDenialApproveRoute: typeof ApiWorkflowsSsiDenialApproveRoute
  ApiWorkflowsSsiDenialCheckoutRoute: typeof ApiWorkflowsSsiDenialCheckoutRoute
  ApiWorkflowsSsiReconsiderationApproveRoute: typeof ApiWorkflowsSsiReconsiderationApproveRoute
  ApiWorkflowsSsiReconsiderationCheckoutRoute: typeof ApiWorkflowsSsiReconsiderationCheckoutRoute
  ApiWorkflowsUnemploymentDenialApproveRoute: typeof ApiWorkflowsUnemploymentDenialApproveRoute
  ApiWorkflowsUnemploymentDenialCheckoutRoute: typeof ApiWorkflowsUnemploymentDenialCheckoutRoute
  ApiWorkflowsVaBenefitsDenialApproveRoute: typeof ApiWorkflowsVaBenefitsDenialApproveRoute
  ApiWorkflowsVaBenefitsDenialCheckoutRoute: typeof ApiWorkflowsVaBenefitsDenialCheckoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appeal-a-decision': {
      id: '/appeal-a-decision'
      path: '/appeal-a-decision'
      fullPath: '/appeal-a-decision'
      preLoaderRoute: typeof AppealADecisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mail-a-pdf': {
      id: '/mail-a-pdf'
      path: '/mail-a-pdf'
      fullPath: '/mail-a-pdf'
      preLoaderRoute: typeof MailAPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows': {
      id: '/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe-webhook': {
      id: '/api/stripe-webhook'
      path: '/api/stripe-webhook'
      fullPath: '/api/stripe-webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appeal/$slug': {
      id: '/appeal/$slug'
      path: '/appeal/$slug'
      fullPath: '/appeal/$slug'
      preLoaderRoute: typeof AppealSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appeal/administrative': {
      id: '/appeal/administrative'
      path: '/appeal/administrative'
      fullPath: '/appeal/administrative'
      preLoaderRoute: typeof AppealAdministrativeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appeal/disability': {
      id: '/appeal/disability'
      path: '/appeal/disability'
      fullPath: '/appeal/disability'
      preLoaderRoute: typeof AppealDisabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appeal/medicaid': {
      id: '/appeal/medicaid'
      path: '/appeal/medicaid'
      fullPath: '/appeal/medicaid'
      preLoaderRoute: typeof AppealMedicaidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appeal/public-assistance': {
      id: '/appeal/public-assistance'
      path: '/appeal/public-assistance'
      fullPath: '/appeal/public-assistance'
      preLoaderRoute: typeof AppealPublicAssistanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appeal/unemployment': {
      id: '/appeal/unemployment'
      path: '/appeal/unemployment'
      fullPath: '/appeal/unemployment'
      preLoaderRoute: typeof AppealUnemploymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appeal/veterans': {
      id: '/appeal/veterans'
      path: '/appeal/veterans'
      fullPath: '/appeal/veterans'
      preLoaderRoute: typeof AppealVeteransRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/': {
      id: '/resources/'
      path: '/resources'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/$slug': {
      id: '/resources/$slug'
      path: '/resources/$slug'
      fullPath: '/resources/$slug'
      preLoaderRoute: typeof ResourcesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/': {
      id: '/workflows/'
      path: '/'
      fullPath: '/workflows/'
      preLoaderRoute: typeof WorkflowsIndexRouteImport
      parentRoute: typeof WorkflowsRoute
    }
    '/workflows/$workflowId': {
      id: '/workflows/$workflowId'
      path: '/$workflowId'
      fullPath: '/workflows/$workflowId'
      preLoaderRoute: typeof WorkflowsWorkflowIdRouteImport
      parentRoute: typeof WorkflowsRoute
    }
    '/workflows/benefits-reconsideration': {
      id: '/workflows/benefits-reconsideration'
      path: '/benefits-reconsideration'
      fullPath: '/workflows/benefits-reconsideration'
      preLoaderRoute: typeof WorkflowsBenefitsReconsiderationRouteImport
      parentRoute: typeof WorkflowsRoute
    }
    '/workflows/disability-benefits-denial': {
      id: '/workflows/disability-benefits-denial'
      path: '/disability-benefits-denial'
      fullPath: '/workflows/disability-benefits-denial'
      preLoaderRoute: typeof WorkflowsDisabilityBenefitsDenialRouteImport
      parentRoute: typeof WorkflowsRoute
    }
    '/workflows/edd-denial': {
      id: '/workflows/edd-denial'
      path: '/edd-denial'
      fullPath: '/workflows/edd-denial'
      preLoaderRoute: typeof WorkflowsEddDenialRouteImport
      parentRoute: typeof WorkflowsRoute
    }
    '/workflows/hearing-preparation': {
      id: '/workflows/hearing-preparation'
      path: '/hearing-preparation'
      fullPath: '/workflows/hearing-preparation'
      preLoaderRoute: typeof WorkflowsHearingPreparationRouteImport
      parentRoute: typeof WorkflowsRoute
    }
    '/workflows/housing-benefits-denial': {
      id: '/workflows/housing-benefits-denial'
      path: '/housing-benefits-denial'
      fullPath: '/workflows/housing-benefits-denial'
      preLoaderRoute: typeof WorkflowsHousingBenefitsDenialRouteImport
      parentRoute: typeof WorkflowsRoute
    }
    '/workflows/medicaid-denial': {
      id: '/workflows/medicaid-denial'
      path: '/medicaid-denial'
      fullPath: '/workflows/medicaid-denial'
      preLoaderRoute: typeof WorkflowsMedicaidDenialRouteImport
      parentRoute: typeof WorkflowsRoute
    }
    '/workflows/overpayment': {
      id: '/workflows/overpayment'
      path: '/overpayment'
      fullPath: '/workflows/overpayment'
      preLoaderRoute: typeof WorkflowsOverpaymentRouteImport
      parentRoute: typeof WorkflowsRoute
    }
    '/workflows/snap-denial': {
      id: '/workflows/snap-denial'
      path: '/snap-denial'
      fullPath: '/workflows/snap-denial'
      preLoaderRoute: typeof WorkflowsSnapDenialRouteImport
      parentRoute: typeof WorkflowsRoute
    }
    '/workflows/social-security-denial': {
      id: '/workflows/social-security-denial'
      path: '/social-security-denial'
      fullPath: '/workflows/social-security-denial'
      preLoaderRoute: typeof WorkflowsSocialSecurityDenialRouteImport
      parentRoute: typeof WorkflowsRoute
    }
    '/workflows/ssdi-denial': {
      id: '/workflows/ssdi-denial'
      path: '/ssdi-denial'
      fullPath: '/workflows/ssdi-denial'
      preLoaderRoute: typeof WorkflowsSsdiDenialRouteImport
      parentRoute: typeof WorkflowsRoute
    }
    '/workflows/ssdi-reconsideration': {
      id: '/workflows/ssdi-reconsideration'
      path: '/ssdi-reconsideration'
      fullPath: '/workflows/ssdi-reconsideration'
      preLoaderRoute: typeof WorkflowsSsdiReconsiderationRouteImport
      parentRoute: typeof WorkflowsRoute
    }
    '/workflows/ssi-denial': {
      id: '/workflows/ssi-denial'
      path: '/ssi-denial'
      fullPath: '/workflows/ssi-denial'
      preLoaderRoute: typeof WorkflowsSsiDenialRouteImport
      parentRoute: typeof WorkflowsRoute
    }
    '/workflows/ssi-reconsideration': {
      id: '/workflows/ssi-reconsideration'
      path: '/ssi-reconsideration'
      fullPath: '/workflows/ssi-reconsideration'
      preLoaderRoute: typeof WorkflowsSsiReconsiderationRouteImport
      parentRoute: typeof WorkflowsRoute
    }
    '/workflows/unemployment-denial': {
      id: '/workflows/unemployment-denial'
      path: '/unemployment-denial'
      fullPath: '/workflows/unemployment-denial'
      preLoaderRoute: typeof WorkflowsUnemploymentDenialRouteImport
      parentRoute: typeof WorkflowsRoute
    }
    '/workflows/va-benefits-denial': {
      id: '/workflows/va-benefits-denial'
      path: '/va-benefits-denial'
      fullPath: '/workflows/va-benefits-denial'
      preLoaderRoute: typeof WorkflowsVaBenefitsDenialRouteImport
      parentRoute: typeof WorkflowsRoute
    }
    '/api/admin/appeals': {
      id: '/api/admin/appeals'
      path: '/api/admin/appeals'
      fullPath: '/api/admin/appeals'
      preLoaderRoute: typeof ApiAdminAppealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/health': {
      id: '/api/admin/health'
      path: '/api/admin/health'
      fullPath: '/api/admin/health'
      preLoaderRoute: typeof ApiAdminHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/status': {
      id: '/api/auth/status'
      path: '/api/auth/status'
      fullPath: '/api/auth/status'
      preLoaderRoute: typeof ApiAuthStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/control-plane/ai': {
      id: '/api/control-plane/ai'
      path: '/api/control-plane/ai'
      fullPath: '/api/control-plane/ai'
      preLoaderRoute: typeof ApiControlPlaneAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mail/response': {
      id: '/api/mail/response'
      path: '/api/mail/response'
      fullPath: '/api/mail/response'
      preLoaderRoute: typeof ApiMailResponseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/$workflowId/start': {
      id: '/workflows/$workflowId/start'
      path: '/start'
      fullPath: '/workflows/$workflowId/start'
      preLoaderRoute: typeof WorkflowsWorkflowIdStartRouteImport
      parentRoute: typeof WorkflowsWorkflowIdRoute
    }
    '/api/workflows/$slug/analyze': {
      id: '/api/workflows/$slug/analyze'
      path: '/api/workflows/$slug/analyze'
      fullPath: '/api/workflows/$slug/analyze'
      preLoaderRoute: typeof ApiWorkflowsSlugAnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workflows/$slug/draft': {
      id: '/api/workflows/$slug/draft'
      path: '/api/workflows/$slug/draft'
      fullPath: '/api/workflows/$slug/draft'
      preLoaderRoute: typeof ApiWorkflowsSlugDraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workflows/benefits-reconsideration/approve': {
      id: '/api/workflows/benefits-reconsideration/approve'
      path: '/api/workflows/benefits-reconsideration/approve'
      fullPath: '/api/workflows/benefits-reconsideration/approve'
      preLoaderRoute: typeof ApiWorkflowsBenefitsReconsiderationApproveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workflows/benefits-reconsideration/checkout': {
      id: '/api/workflows/benefits-reconsideration/checkout'
      path: '/api/workflows/benefits-reconsideration/checkout'
      fullPath: '/api/workflows/benefits-reconsideration/checkout'
      preLoaderRoute: typeof ApiWorkflowsBenefitsReconsiderationCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workflows/disability-benefits-denial/approve': {
      id: '/api/workflows/disability-benefits-denial/approve'
      path: '/api/workflows/disability-benefits-denial/approve'
      fullPath: '/api/workflows/disability-benefits-denial/approve'
      preLoaderRoute: typeof ApiWorkflowsDisabilityBenefitsDenialApproveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workflows/disability-benefits-denial/checkout': {
      id: '/api/workflows/disability-benefits-denial/checkout'
      path: '/api/workflows/disability-benefits-denial/checkout'
      fullPath: '/api/workflows/disability-benefits-denial/checkout'
      preLoaderRoute: typeof ApiWorkflowsDisabilityBenefitsDenialCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workflows/edd-denial/approve': {
      id: '/api/workflows/edd-denial/approve'
      path: '/api/workflows/edd-denial/approve'
      fullPath: '/api/workflows/edd-denial/approve'
      preLoaderRoute: typeof ApiWorkflowsEddDenialApproveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workflows/edd-denial/checkout': {
      id: '/api/workflows/edd-denial/checkout'
      path: '/api/workflows/edd-denial/checkout'
      fullPath: '/api/workflows/edd-denial/checkout'
      preLoaderRoute: typeof ApiWorkflowsEddDenialCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workflows/hearing-preparation/approve': {
      id: '/api/workflows/hearing-preparation/approve'
      path: '/api/workflows/hearing-preparation/approve'
      fullPath: '/api/workflows/hearing-preparation/approve'
      preLoaderRoute: typeof ApiWorkflowsHearingPreparationApproveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workflows/hearing-preparation/checkout': {
      id: '/api/workflows/hearing-preparation/checkout'
      path: '/api/workflows/hearing-preparation/checkout'
      fullPath: '/api/workflows/hearing-preparation/checkout'
      preLoaderRoute: typeof ApiWorkflowsHearingPreparationCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workflows/housing-benefits-denial/approve': {
      id: '/api/workflows/housing-benefits-denial/approve'
      path: '/api/workflows/housing-benefits-denial/approve'
      fullPath: '/api/workflows/housing-benefits-denial/approve'
      preLoaderRoute: typeof ApiWorkflowsHousingBenefitsDenialApproveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workflows/housing-benefits-denial/checkout': {
      id: '/api/workflows/housing-benefits-denial/checkout'
      path: '/api/workflows/housing-benefits-denial/checkout'
      fullPath: '/api/workflows/housing-benefits-denial/checkout'
      preLoaderRoute: typeof ApiWorkflowsHousingBenefitsDenialCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workflows/medicaid-denial/approve': {
      id: '/api/workflows/medicaid-denial/approve'
      path: '/api/workflows/medicaid-denial/approve'
      fullPath: '/api/workflows/medicaid-denial/approve'
      preLoaderRoute: typeof ApiWorkflowsMedicaidDenialApproveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workflows/medicaid-denial/checkout': {
      id: '/api/workflows/medicaid-denial/checkout'
      path: '/api/workflows/medicaid-denial/checkout'
      fullPath: '/api/workflows/medicaid-denial/checkout'
      preLoaderRoute: typeof ApiWorkflowsMedicaidDenialCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workflows/overpayment/approve': {
      id: '/api/workflows/overpayment/approve'
      path: '/api/workflows/overpayment/approve'
      fullPath: '/api/workflows/overpayment/approve'
      preLoaderRoute: typeof ApiWorkflowsOverpaymentApproveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workflows/overpayment/checkout': {
      id: '/api/workflows/overpayment/checkout'
      path: '/api/workflows/overpayment/checkout'
      fullPath: '/api/workflows/overpayment/checkout'
      preLoaderRoute: typeof ApiWorkflowsOverpaymentCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workflows/snap-denial/approve': {
      id: '/api/workflows/snap-denial/approve'
      path: '/api/workflows/snap-denial/approve'
      fullPath: '/api/workflows/snap-denial/approve'
      preLoaderRoute: typeof ApiWorkflowsSnapDenialApproveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workflows/snap-denial/checkout': {
      id: '/api/workflows/snap-denial/checkout'
      path: '/api/workflows/snap-denial/checkout'
      fullPath: '/api/workflows/snap-denial/checkout'
      preLoaderRoute: typeof ApiWorkflowsSnapDenialCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workflows/social-security-denial/approve': {
      id: '/api/workflows/social-security-denial/approve'
      path: '/api/workflows/social-security-denial/approve'
      fullPath: '/api/workflows/social-security-denial/approve'
      preLoaderRoute: typeof ApiWorkflowsSocialSecurityDenialApproveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workflows/social-security-denial/checkout': {
      id: '/api/workflows/social-security-denial/checkout'
      path: '/api/workflows/social-security-denial/checkout'
      fullPath: '/api/workflows/social-security-denial/checkout'
      preLoaderRoute: typeof ApiWorkflowsSocialSecurityDenialCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workflows/ssdi-denial/approve': {
      id: '/api/workflows/ssdi-denial/approve'
      path: '/api/workflows/ssdi-denial/approve'
      fullPath: '/api/workflows/ssdi-denial/approve'
      preLoaderRoute: typeof ApiWorkflowsSsdiDenialApproveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workflows/ssdi-denial/checkout': {
      id: '/api/workflows/ssdi-denial/checkout'
      path: '/api/workflows/ssdi-denial/checkout'
      fullPath: '/api/workflows/ssdi-denial/checkout'
      preLoaderRoute: typeof ApiWorkflowsSsdiDenialCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workflows/ssdi-reconsideration/approve': {
      id: '/api/workflows/ssdi-reconsideration/approve'
      path: '/api/workflows/ssdi-reconsideration/approve'
      fullPath: '/api/workflows/ssdi-reconsideration/approve'
      preLoaderRoute: typeof ApiWorkflowsSsdiReconsiderationApproveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workflows/ssdi-reconsideration/checkout': {
      id: '/api/workflows/ssdi-reconsideration/checkout'
      path: '/api/workflows/ssdi-reconsideration/checkout'
      fullPath: '/api/workflows/ssdi-reconsideration/checkout'
      preLoaderRoute: typeof ApiWorkflowsSsdiReconsiderationCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workflows/ssi-denial/approve': {
      id: '/api/workflows/ssi-denial/approve'
      path: '/api/workflows/ssi-denial/approve'
      fullPath: '/api/workflows/ssi-denial/approve'
      preLoaderRoute: typeof ApiWorkflowsSsiDenialApproveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workflows/ssi-denial/checkout': {
      id: '/api/workflows/ssi-denial/checkout'
      path: '/api/workflows/ssi-denial/checkout'
      fullPath: '/api/workflows/ssi-denial/checkout'
      preLoaderRoute: typeof ApiWorkflowsSsiDenialCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workflows/ssi-reconsideration/approve': {
      id: '/api/workflows/ssi-reconsideration/approve'
      path: '/api/workflows/ssi-reconsideration/approve'
      fullPath: '/api/workflows/ssi-reconsideration/approve'
      preLoaderRoute: typeof ApiWorkflowsSsiReconsiderationApproveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workflows/ssi-reconsideration/checkout': {
      id: '/api/workflows/ssi-reconsideration/checkout'
      path: '/api/workflows/ssi-reconsideration/checkout'
      fullPath: '/api/workflows/ssi-reconsideration/checkout'
      preLoaderRoute: typeof ApiWorkflowsSsiReconsiderationCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workflows/unemployment-denial/approve': {
      id: '/api/workflows/unemployment-denial/approve'
      path: '/api/workflows/unemployment-denial/approve'
      fullPath: '/api/workflows/unemployment-denial/approve'
      preLoaderRoute: typeof ApiWorkflowsUnemploymentDenialApproveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workflows/unemployment-denial/checkout': {
      id: '/api/workflows/unemployment-denial/checkout'
      path: '/api/workflows/unemployment-denial/checkout'
      fullPath: '/api/workflows/unemployment-denial/checkout'
      preLoaderRoute: typeof ApiWorkflowsUnemploymentDenialCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workflows/va-benefits-denial/approve': {
      id: '/api/workflows/va-benefits-denial/approve'
      path: '/api/workflows/va-benefits-denial/approve'
      fullPath: '/api/workflows/va-benefits-denial/approve'
      preLoaderRoute: typeof ApiWorkflowsVaBenefitsDenialApproveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workflows/va-benefits-denial/checkout': {
      id: '/api/workflows/va-benefits-denial/checkout'
      path: '/api/workflows/va-benefits-denial/checkout'
      fullPath: '/api/workflows/va-benefits-denial/checkout'
      preLoaderRoute: typeof ApiWorkflowsVaBenefitsDenialCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface WorkflowsWorkflowIdRouteChildren {
  WorkflowsWorkflowIdStartRoute: typeof WorkflowsWorkflowIdStartRoute
}

const WorkflowsWorkflowIdRouteChildren: WorkflowsWorkflowIdRouteChildren = {
  WorkflowsWorkflowIdStartRoute: WorkflowsWorkflowIdStartRoute,
}

const WorkflowsWorkflowIdRouteWithChildren =
  WorkflowsWorkflowIdRoute._addFileChildren(WorkflowsWorkflowIdRouteChildren)

interface WorkflowsRouteChildren {
  WorkflowsWorkflowIdRoute: typeof WorkflowsWorkflowIdRouteWithChildren
  WorkflowsBenefitsReconsiderationRoute: typeof WorkflowsBenefitsReconsiderationRoute
  WorkflowsDisabilityBenefitsDenialRoute: typeof WorkflowsDisabilityBenefitsDenialRoute
  WorkflowsEddDenialRoute: typeof WorkflowsEddDenialRoute
  WorkflowsHearingPreparationRoute: typeof WorkflowsHearingPreparationRoute
  WorkflowsHousingBenefitsDenialRoute: typeof WorkflowsHousingBenefitsDenialRoute
  WorkflowsMedicaidDenialRoute: typeof WorkflowsMedicaidDenialRoute
  WorkflowsOverpaymentRoute: typeof WorkflowsOverpaymentRoute
  WorkflowsSnapDenialRoute: typeof WorkflowsSnapDenialRoute
  WorkflowsSocialSecurityDenialRoute: typeof WorkflowsSocialSecurityDenialRoute
  WorkflowsSsdiDenialRoute: typeof WorkflowsSsdiDenialRoute
  WorkflowsSsdiReconsiderationRoute: typeof WorkflowsSsdiReconsiderationRoute
  WorkflowsSsiDenialRoute: typeof WorkflowsSsiDenialRoute
  WorkflowsSsiReconsiderationRoute: typeof WorkflowsSsiReconsiderationRoute
  WorkflowsUnemploymentDenialRoute: typeof WorkflowsUnemploymentDenialRoute
  WorkflowsVaBenefitsDenialRoute: typeof WorkflowsVaBenefitsDenialRoute
  WorkflowsIndexRoute: typeof WorkflowsIndexRoute
}

const WorkflowsRouteChildren: WorkflowsRouteChildren = {
  WorkflowsWorkflowIdRoute: WorkflowsWorkflowIdRouteWithChildren,
  WorkflowsBenefitsReconsiderationRoute: WorkflowsBenefitsReconsiderationRoute,
  WorkflowsDisabilityBenefitsDenialRoute:
    WorkflowsDisabilityBenefitsDenialRoute,
  WorkflowsEddDenialRoute: WorkflowsEddDenialRoute,
  WorkflowsHearingPreparationRoute: WorkflowsHearingPreparationRoute,
  WorkflowsHousingBenefitsDenialRoute: WorkflowsHousingBenefitsDenialRoute,
  WorkflowsMedicaidDenialRoute: WorkflowsMedicaidDenialRoute,
  WorkflowsOverpaymentRoute: WorkflowsOverpaymentRoute,
  WorkflowsSnapDenialRoute: WorkflowsSnapDenialRoute,
  WorkflowsSocialSecurityDenialRoute: WorkflowsSocialSecurityDenialRoute,
  WorkflowsSsdiDenialRoute: WorkflowsSsdiDenialRoute,
  WorkflowsSsdiReconsiderationRoute: WorkflowsSsdiReconsiderationRoute,
  WorkflowsSsiDenialRoute: WorkflowsSsiDenialRoute,
  WorkflowsSsiReconsiderationRoute: WorkflowsSsiReconsiderationRoute,
  WorkflowsUnemploymentDenialRoute: WorkflowsUnemploymentDenialRoute,
  WorkflowsVaBenefitsDenialRoute: WorkflowsVaBenefitsDenialRoute,
  WorkflowsIndexRoute: WorkflowsIndexRoute,
}

const WorkflowsRouteWithChildren = WorkflowsRoute._addFileChildren(
  WorkflowsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  AppealADecisionRoute: AppealADecisionRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  FaqRoute: FaqRoute,
  HowItWorksRoute: HowItWorksRoute,
  MailAPdfRoute: MailAPdfRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ProductsRoute: ProductsRoute,
  StartRoute: StartRoute,
  TermsRoute: TermsRoute,
  WorkflowsRoute: WorkflowsRouteWithChildren,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  AppealSlugRoute: AppealSlugRoute,
  AppealAdministrativeRoute: AppealAdministrativeRoute,
  AppealDisabilityRoute: AppealDisabilityRoute,
  AppealMedicaidRoute: AppealMedicaidRoute,
  AppealPublicAssistanceRoute: AppealPublicAssistanceRoute,
  AppealUnemploymentRoute: AppealUnemploymentRoute,
  AppealVeteransRoute: AppealVeteransRoute,
  ResourcesSlugRoute: ResourcesSlugRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
  ApiAdminAppealsRoute: ApiAdminAppealsRoute,
  ApiAdminHealthRoute: ApiAdminHealthRoute,
  ApiAuthStatusRoute: ApiAuthStatusRoute,
  ApiControlPlaneAiRoute: ApiControlPlaneAiRoute,
  ApiMailResponseRoute: ApiMailResponseRoute,
  ApiWorkflowsSlugAnalyzeRoute: ApiWorkflowsSlugAnalyzeRoute,
  ApiWorkflowsSlugDraftRoute: ApiWorkflowsSlugDraftRoute,
  ApiWorkflowsBenefitsReconsiderationApproveRoute:
    ApiWorkflowsBenefitsReconsiderationApproveRoute,
  ApiWorkflowsBenefitsReconsiderationCheckoutRoute:
    ApiWorkflowsBenefitsReconsiderationCheckoutRoute,
  ApiWorkflowsDisabilityBenefitsDenialApproveRoute:
    ApiWorkflowsDisabilityBenefitsDenialApproveRoute,
  ApiWorkflowsDisabilityBenefitsDenialCheckoutRoute:
    ApiWorkflowsDisabilityBenefitsDenialCheckoutRoute,
  ApiWorkflowsEddDenialApproveRoute: ApiWorkflowsEddDenialApproveRoute,
  ApiWorkflowsEddDenialCheckoutRoute: ApiWorkflowsEddDenialCheckoutRoute,
  ApiWorkflowsHearingPreparationApproveRoute:
    ApiWorkflowsHearingPreparationApproveRoute,
  ApiWorkflowsHearingPreparationCheckoutRoute:
    ApiWorkflowsHearingPreparationCheckoutRoute,
  ApiWorkflowsHousingBenefitsDenialApproveRoute:
    ApiWorkflowsHousingBenefitsDenialApproveRoute,
  ApiWorkflowsHousingBenefitsDenialCheckoutRoute:
    ApiWorkflowsHousingBenefitsDenialCheckoutRoute,
  ApiWorkflowsMedicaidDenialApproveRoute:
    ApiWorkflowsMedicaidDenialApproveRoute,
  ApiWorkflowsMedicaidDenialCheckoutRoute:
    ApiWorkflowsMedicaidDenialCheckoutRoute,
  ApiWorkflowsOverpaymentApproveRoute: ApiWorkflowsOverpaymentApproveRoute,
  ApiWorkflowsOverpaymentCheckoutRoute: ApiWorkflowsOverpaymentCheckoutRoute,
  ApiWorkflowsSnapDenialApproveRoute: ApiWorkflowsSnapDenialApproveRoute,
  ApiWorkflowsSnapDenialCheckoutRoute: ApiWorkflowsSnapDenialCheckoutRoute,
  ApiWorkflowsSocialSecurityDenialApproveRoute:
    ApiWorkflowsSocialSecurityDenialApproveRoute,
  ApiWorkflowsSocialSecurityDenialCheckoutRoute:
    ApiWorkflowsSocialSecurityDenialCheckoutRoute,
  ApiWorkflowsSsdiDenialApproveRoute: ApiWorkflowsSsdiDenialApproveRoute,
  ApiWorkflowsSsdiDenialCheckoutRoute: ApiWorkflowsSsdiDenialCheckoutRoute,
  ApiWorkflowsSsdiReconsiderationApproveRoute:
    ApiWorkflowsSsdiReconsiderationApproveRoute,
  ApiWorkflowsSsdiReconsiderationCheckoutRoute:
    ApiWorkflowsSsdiReconsiderationCheckoutRoute,
  ApiWorkflowsSsiDenialApproveRoute: ApiWorkflowsSsiDenialApproveRoute,
  ApiWorkflowsSsiDenialCheckoutRoute: ApiWorkflowsSsiDenialCheckoutRoute,
  ApiWorkflowsSsiReconsiderationApproveRoute:
    ApiWorkflowsSsiReconsiderationApproveRoute,
  ApiWorkflowsSsiReconsiderationCheckoutRoute:
    ApiWorkflowsSsiReconsiderationCheckoutRoute,
  ApiWorkflowsUnemploymentDenialApproveRoute:
    ApiWorkflowsUnemploymentDenialApproveRoute,
  ApiWorkflowsUnemploymentDenialCheckoutRoute:
    ApiWorkflowsUnemploymentDenialCheckoutRoute,
  ApiWorkflowsVaBenefitsDenialApproveRoute:
    ApiWorkflowsVaBenefitsDenialApproveRoute,
  ApiWorkflowsVaBenefitsDenialCheckoutRoute:
    ApiWorkflowsVaBenefitsDenialCheckoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
