import { defineWorkflowDomainSpec } from "@mailmypdf/workflows";

export const cp14DomainSpec = defineWorkflowDomainSpec({
  workflowId: "cp14-response",
  version: 1,
  authorityMaxAgeDays: 90,
  extractionSchemaIds: ["irs.cp14.v1"],
  authoritySources: [
    {
      id: "irs.cp14",
      title: "Understanding your CP14 notice",
      publisher: "Internal Revenue Service",
      url: "https://www.irs.gov/individuals/understanding-your-cp14-notice",
      sourceType: "official_agency",
      reviewedAt: "2026-09-16",
      jurisdiction: "United States",
    },
  ],
  rules: [
    {
      id: "treat-as-balance-due-notice",
      label: "Treat CP14 as a balance-due notice",
      kind: "requirement",
      description: "Preserve the notice's role as a balance-due notice and do not characterize it as an appeal determination or proposed adjustment.",
      severity: "blocking",
      authoritySourceIds: ["irs.cp14"],
    },
    {
      id: "use-printed-due-date",
      label: "Use the controlling printed due date",
      kind: "deadline",
      description: "Extract and confirm the due date printed on the controlling notice or cover sheet instead of calculating a replacement date.",
      severity: "blocking",
      authoritySourceIds: ["irs.cp14"],
    },
    {
      id: "follow-notice-specific-resolution-path",
      label: "Follow the notice-specific resolution path",
      kind: "requirement",
      description: "The workflow must distinguish paying, payment-plan needs, disagreement, already-paid situations, and other correspondence instead of forcing every CP14 into a mailed dispute.",
      severity: "blocking",
      authoritySourceIds: ["irs.cp14"],
    },
    {
      id: "confirm-mail-destination",
      label: "Confirm any mailing destination",
      kind: "submission",
      description: "Mailing is allowed only after the user confirms the destination against the controlling notice or current IRS instructions. Do not invent a response address.",
      severity: "blocking",
      authoritySourceIds: ["irs.cp14"],
    },
    {
      id: "no-payment-or-outcome-invention",
      label: "Do not invent payments, balances, or outcomes",
      kind: "drafting",
      description: "Draft only from confirmed notice facts, user-confirmed facts, and included records; do not claim a payment posted, a balance is wrong, or an IRS outcome is guaranteed without support.",
      severity: "blocking",
      authoritySourceIds: ["irs.cp14"],
    },
  ],
  evidenceRequirements: [
    {
      id: "controlling-cp14",
      label: "Controlling CP14 notice",
      description: "The complete CP14-series notice being addressed, including pages showing the amount due, tax period, due date, help information, and any mailing destination.",
      required: true,
      acceptedDocumentKinds: ["notice"],
      supportsRuleIds: [
        "treat-as-balance-due-notice",
        "use-printed-due-date",
        "follow-notice-specific-resolution-path",
        "confirm-mail-destination",
      ],
    },
    {
      id: "supporting-records",
      label: "Records supporting the user's response",
      description: "Payment confirmations, canceled checks, amended returns, account records, prior correspondence, or other records the user relies on.",
      required: false,
      acceptedDocumentKinds: ["evidence", "form", "receipt", "correspondence"],
      supportsRuleIds: ["follow-notice-specific-resolution-path", "no-payment-or-outcome-invention"],
    },
  ],
  aiTasks: [
    {
      id: "classify-cp14",
      kind: "classify",
      promptVersion: "cp14.classify.v1",
      purpose: "Confirm that the controlling document is a CP14-series balance-due notice.",
      instruction: "Classify from the document itself. If it is not a CP14-series notice, report the mismatch rather than forcing the workflow.",
      sourcePolicy: "document_only",
      requiresHumanConfirmation: true,
    },
    {
      id: "extract-cp14",
      kind: "extract",
      promptVersion: "cp14.extract.v1",
      purpose: "Extract the notice series, tax period, printed dates, balance, identifiers, help number, and any mailing destination.",
      instruction: "Extract only values actually supported by the notice and include page/excerpt provenance for every non-null value. Never calculate a due date or invent a response address.",
      sourcePolicy: "document_only",
      outputSchemaId: "irs.cp14.v1",
      requiresHumanConfirmation: true,
    },
    {
      id: "analyze-cp14",
      kind: "analyze",
      promptVersion: "cp14.analyze.v1",
      purpose: "Separate the notice facts from the user's selected response path and available supporting records.",
      instruction: "Distinguish extracted notice facts, confirmed user facts, disagreement, already-paid claims, inability-to-pay statements, missing information, and supporting records. Do not decide that the IRS balance is correct or incorrect.",
      sourcePolicy: "matter_record",
      requiresHumanConfirmation: true,
    },
    {
      id: "research-cp14",
      kind: "research",
      promptVersion: "cp14.research.v1",
      purpose: "Ground workflow guidance in the approved IRS CP14 source.",
      instruction: "Use the approved IRS source for general workflow guidance while preserving the user's actual notice as the source for case-specific amounts, dates, contact information, and destinations.",
      sourcePolicy: "authority_grounded",
    },
    {
      id: "draft-cp14-correspondence",
      kind: "draft",
      promptVersion: "cp14.draft.v1",
      purpose: "Prepare factual CP14 correspondence when the user's selected path calls for written correspondence.",
      instruction: "Draft only from confirmed notice facts, confirmed user facts, and records actually included. Do not invent tax figures, payment history, deadlines, addresses, authorities, or outcomes. Do not imply that mailing is required unless the controlling notice or current instructions support it.",
      sourcePolicy: "matter_record",
      requiresHumanConfirmation: true,
    },
    {
      id: "validate-cp14-correspondence",
      kind: "validate",
      promptVersion: "cp14.validate.v1",
      purpose: "Block unsupported claims, unconfirmed notice facts, unresolved required items, or an unverified mailing destination.",
      instruction: "Fail closed when a material draft claim lacks support, when the controlling due date is misrepresented, or when a mailing destination was not confirmed against the notice or current IRS instructions.",
      sourcePolicy: "matter_record",
    },
  ],
  drafting: {
    purpose: "Prepare reviewable factual CP14 correspondence from the verified matter record when written correspondence is appropriate.",
    templateId: "official-response-letter.v1",
    tone: "professional, factual, concise",
    requiresSourceBackedClaims: true,
    prohibitedClaims: [
      "Do not invent or calculate a due date.",
      "Do not claim the balance is incorrect unless the user explicitly states a disagreement supported by the matter record.",
      "Do not claim a payment was made or posted unless the user confirms it and the record supports the statement.",
      "Do not claim evidence is enclosed unless it is actually included in the approved packet.",
      "Do not guarantee abatement, account adjustment, payment posting, collection relief, or any other IRS outcome.",
      "Do not invent an IRS mailing address or imply that a mailed response is mandatory.",
    ],
    requiredSections: [
      "notice-reference",
      "response-position",
      "factual-explanation",
      "supporting-records",
      "requested-action",
    ],
  },
});

export default cp14DomainSpec;
