packages:
  - "packages/*"
  - "apps/*"
  - "mailmypdf"
  - "apps/verticals/*"
  - "services/*"
  - "appeal-mail"
  - "notice-respond"
  - "records-request"
  - "immigration-mail"
  - "secured-transactions"
