/**
 * Collection Due Process (CDP) Document Generation
 * Generates levy prevention response documents
 */

import type {
  GeneratedDocument,
  CDPIntakeConfirmation,
  PaymentPlanProposalPayload,
  NotCurrentlyCollectiblePayload,
  OfferInCompromisePayload,
  LiabilityDisputePayload,
  LienWithdrawalPayload,
  LevyHardshipReliefPayload,
} from "./types";

/**
 * Generate payment plan proposal letter
 */
export function generatePaymentPlanProposal(
  intake: CDPIntakeConfirmation,
  payload: PaymentPlanProposalPayload
): GeneratedDocument {
  const extraction = intake.extraction;
  const markdown = `# Proposed Installment Agreement

**Date:** ${new Date().toISOString().split("T")[0]}

**Taxpayer:** ${extraction.taxpayer_name}
${extraction.taxpayer_ssn_masked ? `**SSN:** ${extraction.taxpayer_ssn_masked}` : ""}

## Proposed Monthly Payment

**Total Tax Debt:** $${extraction.total_tax_debt.toLocaleString()}
**Proposed Monthly Payment:** $${payload.monthly_payment.toLocaleString()}
**Payment Duration:** ${payload.duration_months} months
**First Payment Date:** ${payload.first_payment_date}
**Payment Method:** ${payload.payment_method.toUpperCase()}

## Legal Basis

This proposal is submitted in response to the Notice of Intent to Levy (${extraction.notice_number}) issued on ${extraction.notice_date}.

Under IRC § 6330 Collection Due Process procedures, the taxpayer requests consideration of this installment agreement as an alternative to levy action. An approved installment agreement will suspend collection action and provide payment relief while the debt is satisfied.

## Financial Ability

The proposed monthly payment of $${payload.monthly_payment.toLocaleString()} reflects the taxpayer's reasonable financial capacity. This amount represents a balance between:
- Ability to continue current living expenses
- Reasonable ability to pay toward tax liability
- Prevention of undue financial hardship

## Effect of Approval

Upon approval, this installment agreement will:
- Suspend levy action under IRC § 6330(c)(4)
- Allow continued wage income and bank account access
- Provide structured path to resolve tax liability
- Preserve taxpayer's credit rating

## Important Notices

**This is not legal advice.** Taxpayer should consult with a qualified tax professional or attorney before submitting this agreement.

Interest and penalties continue to accrue during the payment period. The IRS may modify or terminate the agreement if circumstances change materially.

**Deadline:** This response must be submitted by **${extraction.response_deadline}** (${Math.floor((new Date(extraction.response_deadline).getTime() - new Date().getTime()) / (1000 * 60 * 60 * 24))} days remaining).

---

*Generated by Notice Respond | MailMyPDF*
*This is not a substitute for professional tax representation*`;

  const plaintext = markdown
    .replace(/[#*`]/g, "")
    .replace(/---/g, "════════════════════════════════════════");

  return {
    type: "payment-plan-proposal",
    title: "Proposed Installment Agreement",
    content: plaintext,
    markdown_content: markdown,
    requires_signature: true,
    is_official_form: false,
    generated_at: new Date().toISOString(),
    model_used: "claude",
    provider: "claude",
  };
}

/**
 * Generate Currently Not Collectible request
 */
export function generateCurrentlyNotCollectibleRequest(
  intake: CDPIntakeConfirmation,
  payload: NotCurrentlyCollectiblePayload
): GeneratedDocument {
  const extraction = intake.extraction;
  const markdown = `# Request for Currently Not Collectible Status

**Date:** ${new Date().toISOString().split("T")[0]}

**Taxpayer:** ${extraction.taxpayer_name}
${extraction.taxpayer_ssn_masked ? `**SSN:** ${extraction.taxpayer_ssn_masked}` : ""}

## Request Summary

The taxpayer hereby requests Currently Not Collectible (CNC) status for the tax liability detailed in the Notice of Intent to Levy (${extraction.notice_number}) issued on ${extraction.notice_date}.

**Total Tax Debt:** $${extraction.total_tax_debt.toLocaleString()}

## Financial Hardship Documentation

### Monthly Income
**Total Monthly Income:** $${payload.monthly_income.toLocaleString()}

### Monthly Expenses
**Total Monthly Expenses:** $${payload.monthly_expenses.toLocaleString()}

**Monthly Shortfall:** $${(payload.monthly_expenses - payload.monthly_income).toLocaleString()}

### Hardship Explanation

${payload.financial_hardship_reason}

### Expected Duration
**Anticipated Duration of Hardship:** ${payload.expected_hardship_duration}

## Supporting Documentation Provided

The following financial documentation is submitted in support of this request:

${payload.supporting_documentation.map((doc) => `- ${doc}`).join("\n")}

## Legal Framework

This request is made under IRC § 6330 Collection Due Process provisions. Currently Not Collectible status temporarily suspends collection action when the taxpayer demonstrates genuine financial hardship and inability to pay.

## Important Information

**CNC Status Details:**
- Suspends active collection efforts for 12-24 months
- Does not eliminate the tax liability
- Interest and penalties continue to accrue
- Status subject to periodic review
- IRS may resume collection if circumstances improve

**This is not legal advice.** Consult a tax professional before submitting.

**Deadline:** This response must be submitted by **${extraction.response_deadline}** (${Math.floor((new Date(extraction.response_deadline).getTime() - new Date().getTime()) / (1000 * 60 * 60 * 24))} days remaining).

---

*Generated by Notice Respond | MailMyPDF*
*This is not a substitute for professional tax representation*`;

  const plaintext = markdown
    .replace(/[#*`]/g, "")
    .replace(/---/g, "════════════════════════════════════════");

  return {
    type: "currently-not-collectible-request",
    title: "Request for Currently Not Collectible Status",
    content: plaintext,
    markdown_content: markdown,
    requires_signature: true,
    is_official_form: false,
    generated_at: new Date().toISOString(),
    model_used: "claude",
    provider: "claude",
  };
}

/**
 * Generate Offer in Compromise proposal
 */
export function generateOfferInCompromise(
  intake: CDPIntakeConfirmation,
  payload: OfferInCompromisePayload
): GeneratedDocument {
  const extraction = intake.extraction;
  const markdown = `# Offer in Compromise Proposal

**Date:** ${new Date().toISOString().split("T")[0]}

**Taxpayer:** ${extraction.taxpayer_name}
${extraction.taxpayer_ssn_masked ? `**SSN:** ${extraction.taxpayer_ssn_masked}` : ""}

## Offer Summary

The taxpayer hereby submits an Offer in Compromise (OIC) to settle the tax liability identified in the Notice of Intent to Levy (${extraction.notice_number}) issued on ${extraction.notice_date}.

**Original Assessment:** $${extraction.total_tax_debt.toLocaleString()}
**Proposed Offer Amount:** $${payload.offer_amount.toLocaleString()}
**Percentage of Debt:** ${((payload.offer_amount / extraction.total_tax_debt) * 100).toFixed(1)}%

## Basis for Offer

**Offer Basis:** ${payload.offer_basis}

${payload.offer_basis.includes("Doubt as to Collectibility") ? `
### Collectibility Analysis

The taxpayer's current financial situation demonstrates limited ability to satisfy the full tax assessment. The proposed offer amount reflects a reasonable estimate of collectible income over the remainder of the applicable collection statute period (10 years).
` : ""}

${payload.offer_basis.includes("Hazards of Litigation") ? `
### Litigation Hazards

Significant uncertainties exist regarding the taxpayer's liability or the government's ability to sustain its burden in litigation, including:

${payload.legal_arguments.map((arg) => `- ${arg}`).join("\n")}
` : ""}

## Supporting Evidence

The following evidence is submitted in support of this offer:

${payload.supporting_evidence.map((evidence) => `- ${evidence}`).join("\n")}

## Financial Summary

${payload.financial_summary}

## Processing and Timeline

**Filing Fee:** $225 (or applicable amount)
**Processing Time:** Typically 120-180 days for IRS review
**Suspension of Collection:** Collection action is suspended while OIC is under review

## Important Provisions

- This OIC suspends collection action pending IRS review
- If OIC is rejected, collection proceedings may resume
- Acceptance of OIC constitutes satisfaction of the full liability
- If declined, taxpayer may appeal the decision

**This is not legal advice.** Consult a tax professional or attorney before submitting an OIC.

**Deadline:** This response must be submitted by **${extraction.response_deadline}** (${Math.floor((new Date(extraction.response_deadline).getTime() - new Date().getTime()) / (1000 * 60 * 60 * 24))} days remaining).

---

*Generated by Notice Respond | MailMyPDF*
*This is not a substitute for professional tax representation*`;

  const plaintext = markdown
    .replace(/[#*`]/g, "")
    .replace(/---/g, "════════════════════════════════════════");

  return {
    type: "offer-in-compromise",
    title: "Offer in Compromise Proposal",
    content: plaintext,
    markdown_content: markdown,
    requires_signature: true,
    is_official_form: false,
    generated_at: new Date().toISOString(),
    model_used: "claude",
    provider: "claude",
  };
}

/**
 * Generate liability dispute letter
 */
export function generateLiabilityDispute(
  intake: CDPIntakeConfirmation,
  payload: LiabilityDisputePayload
): GeneratedDocument {
  const extraction = intake.extraction;
  const markdown = `# Notice of Dispute of Liability

**Date:** ${new Date().toISOString().split("T")[0]}

**Taxpayer:** ${extraction.taxpayer_name}
${extraction.taxpayer_ssn_masked ? `**SSN:** ${extraction.taxpayer_ssn_masked}` : ""}

## Dispute of Underlying Tax Liability

The taxpayer disputes the underlying tax assessment identified in the Notice of Intent to Levy (${extraction.notice_number}) issued on ${extraction.notice_date}.

**Total Tax Debt Disputed:** $${extraction.total_tax_debt.toLocaleString()}
**Tax Years Involved:** ${payload.disputed_tax_years.join(", ")}

## Basis for Dispute

${payload.dispute_reason}

## Disputed Tax Years

The following tax year(s) are subject to this dispute:

${payload.disputed_tax_years.map((year) => `- ${year}`).join("\n")}

## Legal Arguments and Authority

The taxpayer asserts the following legal positions:

${payload.legal_arguments.map((arg) => `- ${arg}`).join("\n")}

## Supporting Evidence

The following evidence is submitted in support of this dispute:

${payload.supporting_evidence.map((evidence) => `- ${evidence}`).join("\n")}

## Collection Due Process Claim

Under IRC § 6330, the taxpayer asserts this dispute of liability as a valid Collection Due Process (CDP) defense. The underlying assessment is disputed on the merits, and collection action should be suspended pending resolution of this dispute.

## Appeals Consideration

The taxpayer requests that this matter be referred to the IRS Appeals function for independent consideration of this liability dispute, separate from the collection action.

## Effect of Timely Assertion

A timely assertion of this liability dispute halts collection action under IRC § 6330(c)(3). The IRS must provide the taxpayer opportunity for an administrative hearing before the Appeals Officer prior to levy.

**This is not legal advice.** Consult a tax professional or attorney before submitting this dispute.

**Deadline:** This response must be submitted by **${extraction.response_deadline}** (${Math.floor((new Date(extraction.response_deadline).getTime() - new Date().getTime()) / (1000 * 60 * 60 * 24))} days remaining).

---

*Generated by Notice Respond | MailMyPDF*
*This is not a substitute for professional tax representation*`;

  const plaintext = markdown
    .replace(/[#*`]/g, "")
    .replace(/---/g, "════════════════════════════════════════");

  return {
    type: "liability-dispute",
    title: "Notice of Dispute of Liability",
    content: plaintext,
    markdown_content: markdown,
    requires_signature: true,
    is_official_form: false,
    generated_at: new Date().toISOString(),
    model_used: "claude",
    provider: "claude",
  };
}

/**
 * Generate lien withdrawal request
 */
export function generateLienWithdrawalRequest(
  intake: CDPIntakeConfirmation,
  payload: LienWithdrawalPayload
): GeneratedDocument {
  const extraction = intake.extraction;
  const markdown = `# Request for Federal Tax Lien Withdrawal

**Date:** ${new Date().toISOString().split("T")[0]}

**Taxpayer:** ${extraction.taxpayer_name}
${extraction.taxpayer_ssn_masked ? `**SSN:** ${extraction.taxpayer_ssn_masked}` : ""}

## Request for NFTL Withdrawal

The taxpayer requests withdrawal of the Notice of Federal Tax Lien (NFTL) filed in connection with the Notice of Intent to Levy (${extraction.notice_number}) issued on ${extraction.notice_date}.

**Total Tax Debt:** $${extraction.total_tax_debt.toLocaleString()}

## Basis for Withdrawal Request

${payload.withdrawal_basis}

Federal tax liens significantly damage the taxpayer's credit rating, impair access to financing, and create substantial collateral consequences. Withdrawal would:

- Restore creditworthiness
- Enable refinancing opportunities
- Reduce financial hardship
- Allow taxpayer to satisfy obligation through payment plan

## Taxpayer's Commitment

${payload.taxpayer_commitment}

The taxpayer commits to fulfilling the terms of any approved payment arrangement and maintaining current status with respect to all filing and payment obligations going forward.

## Supporting Documentation

The following documentation supports this request:

${payload.supporting_documentation.map((doc) => `- ${doc}`).join("\n")}

## Legal Framework

**IRC § 6325** provides for withdrawal of liens when:
- Collection can be assured by other means
- The taxpayer will comply with filing and payment obligations
- The taxpayer establishes reasonable ability to pay through alternative means

**IRC § 6330(c)(4)** permits consideration of alternative payment arrangements, including lien withdrawal as a component of a broader settlement.

## Effect of Withdrawal

Upon approval, withdrawal would:
- Remove the filed NFTL from public records
- Restore taxpayer's credit standing
- Enable taxpayer to conduct business without lien encumbrance
- Preserve filing and payment compliance as condition

**This is not legal advice.** Consult a tax professional or attorney before submitting this request.

**Deadline:** This response must be submitted by **${extraction.response_deadline}** (${Math.floor((new Date(extraction.response_deadline).getTime() - new Date().getTime()) / (1000 * 60 * 60 * 24))} days remaining).

---

*Generated by Notice Respond | MailMyPDF*
*This is not a substitute for professional tax representation*`;

  const plaintext = markdown
    .replace(/[#*`]/g, "")
    .replace(/---/g, "════════════════════════════════════════");

  return {
    type: "lien-withdrawal-request",
    title: "Request for Federal Tax Lien Withdrawal",
    content: plaintext,
    markdown_content: markdown,
    requires_signature: true,
    is_official_form: false,
    generated_at: new Date().toISOString(),
    model_used: "claude",
    provider: "claude",
  };
}

/**
 * Generate levy hardship relief request
 */
export function generateLevyHardshipRelief(
  intake: CDPIntakeConfirmation,
  payload: LevyHardshipReliefPayload
): GeneratedDocument {
  const extraction = intake.extraction;
  const markdown = `# Request for Levy Hardship Relief

**Date:** ${new Date().toISOString().split("T")[0]}

**Taxpayer:** ${extraction.taxpayer_name}
${extraction.taxpayer_ssn_masked ? `**SSN:** ${extraction.taxpayer_ssn_masked}` : ""}

## Hardship Relief Request

The taxpayer respectfully requests relief from levy action based on demonstrated financial hardship that would result from collection through levy.

**Total Tax Debt:** $${extraction.total_tax_debt.toLocaleString()}

## Hardship Circumstances

### Nature of Hardship

${payload.hardship_reason}

### Impact of Levy

${payload.levy_impact_explanation}

Levy action would result in:
- Loss of essential income required for basic living expenses
- Inability to meet mortgage/rent obligations
- Threat to health and safety of dependents
- Irreparable damage to employment prospects
- Loss of housing and financial stability

## Financial Documentation

The following financial documentation supports this hardship claim:

${payload.financial_documentation.map((doc) => `- ${doc}`).join("\n")}

## Alternative Payment Proposal

Rather than levy action, the taxpayer proposes the following alternative:

${payload.alternative_payment_proposal}

This alternative:
- Avoids the collateral consequences of levy
- Preserves the taxpayer's ability to earn income
- Provides reasonable payment satisfaction
- Prevents irreversible financial damage

## Legal Basis

**IRC § 6330(c)(4)** provides authority for the IRS to consider alternatives to levy, including:
- Installment agreements
- Currently Not Collectible status
- Offer in Compromise
- Other payment relief measures

**IRS Manual § 5.8.1** recognizes economic hardship as valid consideration in levy determinations, particularly when alternative collection methods are available.

## Conclusion

The proposed alternative to levy provides reasonable collection opportunity while avoiding unnecessary hardship. The taxpayer respectfully requests approval of the alternative collection method.

**This is not legal advice.** Consult a tax professional or attorney before submitting this request.

**Deadline:** This response must be submitted by **${extraction.response_deadline}** (${Math.floor((new Date(extraction.response_deadline).getTime() - new Date().getTime()) / (1000 * 60 * 60 * 24))} days remaining).

---

*Generated by Notice Respond | MailMyPDF*
*This is not a substitute for professional tax representation*`;

  const plaintext = markdown
    .replace(/[#*`]/g, "")
    .replace(/---/g, "════════════════════════════════════════");

  return {
    type: "levy-hardship-relief",
    title: "Request for Levy Hardship Relief",
    content: plaintext,
    markdown_content: markdown,
    requires_signature: true,
    is_official_form: false,
    generated_at: new Date().toISOString(),
    model_used: "claude",
    provider: "claude",
  };
}

/**
 * Generate bankruptcy notice document
 */
export function generateBankruptcyNotice(
  intake: CDPIntakeConfirmation
): GeneratedDocument {
  const extraction = intake.extraction;
  const markdown = `# Bankruptcy Filing Notice - Automatic Stay

**Date:** ${new Date().toISOString().split("T")[0]}

**Taxpayer:** ${extraction.taxpayer_name}
${extraction.taxpayer_ssn_masked ? `**SSN:** ${extraction.taxpayer_ssn_masked}` : ""}

## URGENT: COLLECTION ACTION HALTED BY BANKRUPTCY STAY

This notice is submitted in response to the Notice of Intent to Levy (${extraction.notice_number}) issued on ${extraction.notice_date}.

**CRITICAL:** The taxpayer has commenced bankruptcy proceedings. Upon filing of a bankruptcy petition, an automatic stay under 11 U.S.C. § 362 immediately halts ALL collection action, including levy proceedings.

## Automatic Stay Effect

The automatic stay in bankruptcy:
- **Immediately halts** all IRS collection activity
- **Prevents** wage levy, bank levy, and asset seizure
- **Protects** taxpayer assets during bankruptcy proceedings
- **Provides** court-supervised resolution of debts
- **May discharge** certain tax liabilities

## Bankruptcy Information

**Bankruptcy Type:** Typically Chapter 7 (liquidation) or Chapter 13 (reorganization)

**Key Effects:**
- Chapter 7: Debts liquidated/discharged (3-6 months)
- Chapter 13: Structured repayment plan (3-5 years)
- Chapter 11: Business reorganization (varies)

## Notice to IRS

The Internal Revenue Service is hereby notified that bankruptcy protection has been invoked and all collection activities must cease immediately per 11 U.S.C. § 362.

The taxpayer's bankruptcy counsel (if appointed) should be contacted regarding:
- Collection stay compliance
- Tax claim filing procedures
- Treatment of tax debt in bankruptcy plan
- Discharge eligibility

## Critical Notice

**THIS IS NOT A LEGAL DOCUMENT.** This is an informational notice of bankruptcy filing. The taxpayer MUST immediately:

1. Retain a bankruptcy attorney
2. Provide this notice to the IRS
3. Comply with bankruptcy court procedures
4. File required financial disclosures
5. Appear at scheduled hearings

## Legal Framework

- **11 U.S.C. § 362(a)** - Automatic stay upon filing
- **11 U.S.C. § 523** - Non-dischargeable tax liabilities
- **11 U.S.C. § 1322** - Chapter 13 treatment of tax claims
- **IRC § 6330** - Collection Due Process superseded by bankruptcy court jurisdiction

## Important Disclaimers

**This is not legal advice.** The taxpayer MUST work with a qualified bankruptcy attorney to ensure:
- Proper protection under bankruptcy law
- Compliance with filing deadlines
- Understanding of tax debt treatment
- Proper handling of all IRS matters

Bankruptcy is a serious legal proceeding with long-term consequences. Professional representation is essential.

---

*Generated by Notice Respond | MailMyPDF*
*This is not a substitute for professional tax representation or bankruptcy legal counsel*`;

  const plaintext = markdown
    .replace(/[#*`]/g, "")
    .replace(/---/g, "════════════════════════════════════════");

  return {
    type: "bankruptcy-notice",
    title: "Bankruptcy Filing Notice - Automatic Stay",
    content: plaintext,
    markdown_content: markdown,
    requires_signature: false,
    is_official_form: false,
    generated_at: new Date().toISOString(),
    model_used: "claude",
    provider: "claude",
  };
}

/**
 * Generate attorney referral document
 */
export function generateAttorneyReferral(
  intake: CDPIntakeConfirmation
): GeneratedDocument {
  const extraction = intake.extraction;
  const markdown = `# Attorney Escalation Notice

**Date:** ${new Date().toISOString().split("T")[0]}

**Taxpayer:** ${extraction.taxpayer_name}
${extraction.taxpayer_ssn_masked ? `**SSN:** ${extraction.taxpayer_ssn_masked}` : ""}

## PROFESSIONAL REPRESENTATION REQUIRED

This notice is submitted in response to the Notice of Intent to Levy (${extraction.notice_number}) issued on ${extraction.notice_date}.

**CRITICAL SITUATION:** Your circumstances warrant immediate consultation with a qualified tax attorney or CPA. Do not delay.

## Why Professional Representation is Critical

**Total Tax Debt:** $${extraction.total_tax_debt.toLocaleString()}
**Response Deadline:** ${extraction.response_deadline} (${Math.floor((new Date(extraction.response_deadline).getTime() - new Date().getTime()) / (1000 * 60 * 60 * 24))} days remaining)

The complexity of your situation requires professional analysis:

1. **Collection Due Process Rights** - IRC § 6330 provides statutory protections that must be exercised within strict deadlines
2. **Levy Prevention Strategies** - Multiple complex options require professional evaluation
3. **IRS Negotiation** - Professional representation strengthens negotiating position
4. **Statutory Compliance** - Procedural requirements are strict and unforgiving
5. **Long-Term Implications** - Decisions made now affect future collection actions

## What to Do Now

### IMMEDIATE ACTIONS (Next 24-48 Hours):

1. **Contact a tax attorney or CPA immediately**
   - Search your state bar for tax law specialists
   - Contact National Association of Tax Professionals
   - Ask for initial consultation appointment

2. **Gather all relevant documents**
   - The IRS notice (this letter)
   - Tax returns for disputed years
   - Financial records (income, expenses)
   - Previous IRS correspondence
   - Employment records

3. **Protect your assets**
   - Do not make major financial changes
   - Avoid additional tax filings that could trigger review
   - Maintain payment records if making partial payments

4. **Do not ignore the notice**
   - Silence results in automatic levy action
   - The 30-day deadline is absolute
   - Missing deadline eliminates CDP rights

## Types of Professionals to Contact

### Tax Attorneys
- Handle legal strategy and representation
- Argue positions before Appeals
- May practice before Tax Court
- Can represent in all IRS matters

### Certified Public Accountants (CPAs) / Enrolled Agents (EAs)
- Can represent you before IRS
- Analyze financial situations
- Prepare alternative proposals
- May have settlement authority

### Bankruptcy Attorneys
- If bankruptcy is an option
- Can explain Chapter 7, 11, 13 options
- File automatic stay
- Manage IRS claims in bankruptcy

## Finding Professional Help

1. **IRS Directory:** Call 1-800-829-1040 for referrals (limited)
2. **State Bar:** Search state bar directory for tax specialists
3. **Professional Organizations:**
   - National Association of Tax Professionals (NATP)
   - American College of Tax Counsel (ACTC)
   - Your state CPA society

4. **Bankruptcy:** For bankruptcy matters, contact:
   - American Bankruptcy Institute
   - Local bankruptcy court trustee referral

## Cost Considerations

- Initial consultation: Often $200-500
- Representation: Typically $2,000-10,000+ depending on complexity
- May be deductible as business expense or legal fee
- Some professionals offer payment plans
- Investment protects assets worth thousands

## Red Flags to Avoid

**Do NOT work with:**
- Anyone promising "tax evasion" strategies
- Practitioners without proper credentials
- Anyone offering guarantees of outcome
- Advisors discouraging IRS communication

**Legitimate professionals:**
- Are transparent about fees
- Encourage compliance
- Work within tax law
- Maintain client confidentiality

## Your Collection Due Process Rights

You have the following statutory rights under IRC § 6330:

1. **Right to Hearing** - Administrative hearing before Appeals Officer
2. **Right to Representation** - Attorney or CPA may represent you
3. **Right to Present Evidence** - Submit documents and arguments
4. **Right to Dispute Liability** - Challenge the underlying tax assessment
5. **Right to Propose Alternatives** - Payment plans, currently not collectible status, OIC

## Timeline and Deadlines

- **Today:** Contact attorney/CPA for consultation
- **Within 3-5 days:** Retain professional representation
- **Within 10 days:** Attorney submits response with strategy
- **By deadline:** Submit comprehensive response with documentation
- **30-60 days after:** IRS decision on alternatives
- **If needed:** Appeal to Tax Court within statutory period

## Critical Warnings

⚠️ **THESE ARE ABSOLUTE DEADLINES:**
- Miss the response deadline → Automatic levy action
- Miss appeals deadline → Lose appeal rights
- Ignore levy notice → Wage and bank levies commence
- Continue non-compliance → Criminal prosecution possible

## Disclaimer

**This is not legal advice.** You are not represented by Notice Respond or MailMyPDF. This is educational information only. You must obtain advice from a qualified tax professional.

Notice Respond is an AI-powered educational tool, not a substitute for professional tax representation.

---

*Generated by Notice Respond | MailMyPDF*
*URGENT: Seek professional representation immediately*`;

  const plaintext = markdown
    .replace(/[#*`]/g, "")
    .replace(/---/g, "════════════════════════════════════════");

  return {
    type: "attorney-referral",
    title: "Attorney Escalation Notice",
    content: plaintext,
    markdown_content: markdown,
    requires_signature: false,
    is_official_form: false,
    generated_at: new Date().toISOString(),
    model_used: "claude",
    provider: "claude",
  };
}
