import { createFileRoute, Link } from "@tanstack/react-router";
import { useMemo, useState, type ReactNode } from "react";
import { AlertCircle, ArrowLeft, ArrowRight, Check, CheckCircle2, Download, FileText, GitBranch, LockKeyhole, ShieldCheck } from "lucide-react";
import {
  EMPTY_DEFENSE_CASE,
  EVIDENCE_ITEMS,
  STOLEN_VEHICLE_WORKFLOW,
  WORKFLOW_STEPS,
  buildDefenseIssues,
  buildDefensePacket,
  buildDependencyTree,
  packetReadiness,
  validateStep,
  type DefenseCaseInput,
  type SellerScenario,
  type StepId,
  type YesNoUnknown,
} from "@mailmypdf/legal-defense";

export const Route = createFileRoute("/_authenticated/legal-defense/workflows/$workflowId/start")({
  head: () => ({ meta: [{ title: "Build Defense Intelligence Packet | Legal Defense" }, { name: "robots", content: "noindex,nofollow" }] }),
  component: DefenseWorkflow,
});

function DefenseWorkflow() {
  const { workflowId } = Route.useParams();
  const { user } = Route.useRouteContext();
  const [input, setInput] = useState<DefenseCaseInput>(EMPTY_DEFENSE_CASE);
  const [stepIndex, setStepIndex] = useState(0);
  const [highestStep, setHighestStep] = useState(0);
  const [errors, setErrors] = useState<string[]>([]);
  const issues = useMemo(() => buildDefenseIssues(input), [input]);
  const dependencyTree = useMemo(() => buildDependencyTree(input), [input]);
  const readiness = useMemo(() => packetReadiness(input), [input]);
  const step = WORKFLOW_STEPS[stepIndex];

  if (workflowId !== STOLEN_VEHICLE_WORKFLOW.id) {
    return <main className="min-h-screen bg-slate-950 px-6 py-20 text-white"><div className="mx-auto max-w-2xl rounded-2xl border border-white/10 bg-white/[.04] p-8"><h1 className="font-serif text-4xl">Unknown defense workflow</h1><Link className="mt-6 inline-flex text-blue-300" to="/legal-defense/workflows">Return to Legal Defense →</Link></div></main>;
  }

  const set = <K extends keyof DefenseCaseInput>(key: K, value: DefenseCaseInput[K]) => setInput((current) => ({ ...current, [key]: value }));
  const toggleEvidence = (item: string) => set("evidence", input.evidence.includes(item) ? input.evidence.filter((candidate) => candidate !== item) : [...input.evidence, item]);

  function goNext() {
    const validation = validateStep(step.id, input);
    if (validation.length) { setErrors(validation); return; }
    setErrors([]);
    const next = Math.min(stepIndex + 1, WORKFLOW_STEPS.length - 1);
    setStepIndex(next);
    setHighestStep((value) => Math.max(value, next));
    window.scrollTo({ top: 0, behavior: "smooth" });
  }

  function goBack() {
    setErrors([]);
    setStepIndex((value) => Math.max(0, value - 1));
    window.scrollTo({ top: 0, behavior: "smooth" });
  }

  function downloadPacket() {
    const packet = buildDefensePacket(input);
    const blob = new Blob([packet], { type: "text/markdown;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const anchor = document.createElement("a");
    anchor.href = url;
    anchor.download = `defense-intelligence-packet-${input.caseNumber || "draft"}.md`;
    anchor.click();
    URL.revokeObjectURL(url);
  }

  return <div className="min-h-screen bg-[#071321] text-slate-100">
    <header className="border-b border-white/10 bg-[#091827]"><div className="mx-auto flex max-w-[1500px] items-center justify-between gap-4 px-4 py-4 sm:px-6"><div className="flex items-center gap-4"><Link to="/legal-defense/workflows/$workflowId" params={{ workflowId }} className="flex h-10 w-10 items-center justify-center rounded-xl border border-white/10 text-slate-400 hover:text-white"><ArrowLeft className="h-4 w-4"/></Link><div><div className="font-mono text-[9px] uppercase tracking-[.2em] text-amber-300">Legal Defense · Secure workflow</div><div className="mt-1 font-serif text-lg text-white">Stolen-Vehicle Arrest + Search Defense</div></div></div><div className="hidden items-center gap-2 text-xs text-slate-400 sm:flex"><LockKeyhole className="h-3.5 w-3.5 text-emerald-400"/>Signed in as {user.email}</div></div></header>
    <div className="mx-auto grid max-w-[1500px] lg:grid-cols-[300px_1fr]">
      <aside className="border-b border-white/10 bg-[#091827] p-4 lg:min-h-[calc(100vh-73px)] lg:border-b-0 lg:border-r lg:p-6"><div className="mb-6"><div className="flex items-center justify-between text-xs text-slate-400"><span>Packet readiness</span><span className="font-semibold text-white">{readiness.score}%</span></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-gradient-to-r from-blue-400 to-emerald-400 transition-all" style={{ width: `${readiness.score}%` }}/></div></div><nav aria-label="Workflow steps" className="grid gap-1 sm:grid-cols-3 lg:grid-cols-1">{WORKFLOW_STEPS.map((candidate,index)=>{const active=index===stepIndex;const complete=index<highestStep;const available=index<=highestStep;return <button type="button" key={candidate.id} disabled={!available} onClick={()=>{if(available){setErrors([]);setStepIndex(index)}}} className={`flex min-h-14 items-center gap-3 rounded-xl px-3 py-2.5 text-left transition ${active?"bg-blue-500/20 text-white shadow-[inset_2px_0_0_#60a5fa]":available?"text-slate-300 hover:bg-white/[.05]":"cursor-not-allowed text-slate-600"}`}><span className={`flex h-7 w-7 shrink-0 items-center justify-center rounded-full border text-[11px] ${complete?"border-emerald-400/40 bg-emerald-400/15 text-emerald-300":active?"border-blue-300/40 bg-blue-400/15 text-blue-200":"border-white/10"}`}>{complete?<Check className="h-3.5 w-3.5"/>:index+1}</span><span><span className="block text-xs font-medium">{candidate.label}</span><span className="mt-0.5 hidden text-[10px] leading-4 text-slate-500 lg:block">{candidate.description}</span></span></button>})}</nav><div className="mt-6 rounded-xl border border-amber-300/15 bg-amber-300/[.05] p-4 text-xs leading-5 text-amber-100/70"><strong className="text-amber-200">Do not contact the seller or reporting party from this workflow.</strong> Preserve existing communications and let counsel decide further contact.</div></aside>
      <main className="min-w-0 px-4 py-8 sm:px-6 lg:px-10 lg:py-12"><div className="mx-auto max-w-5xl"><div className="flex flex-wrap items-end justify-between gap-6"><div><div className="font-mono text-[10px] uppercase tracking-[.2em] text-blue-300">Step {stepIndex+1} of {WORKFLOW_STEPS.length}</div><h1 className="mt-3 font-serif text-4xl text-white sm:text-5xl">{step.label}</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-400">{step.description}</p></div>{input.custodyStatus==="in-custody"&&<div className="rounded-lg border border-red-400/30 bg-red-400/10 px-4 py-3 text-xs text-red-100">Reported in custody · counsel review is urgent</div>}</div>
        <div className="mt-8 rounded-2xl border border-white/10 bg-white/[.035] p-5 shadow-2xl sm:p-8"><StepContent step={step.id} input={input} set={set} toggleEvidence={toggleEvidence} issues={issues} dependencyTree={dependencyTree} readiness={readiness} onDownload={downloadPacket}/></div>
        {errors.length>0&&<div role="alert" className="mt-5 rounded-xl border border-red-400/30 bg-red-400/10 p-4"><div className="flex items-center gap-2 text-sm font-semibold text-red-100"><AlertCircle className="h-4 w-4"/>Complete this step</div><ul className="mt-2 list-disc space-y-1 pl-5 text-sm text-red-100/75">{errors.map(error=><li key={error}>{error}</li>)}</ul></div>}
        <div className="mt-6 flex items-center justify-between"><button type="button" onClick={goBack} disabled={stepIndex===0} className="inline-flex items-center gap-2 rounded-xl border border-white/10 px-5 py-3 text-sm text-slate-300 disabled:opacity-30"><ArrowLeft className="h-4 w-4"/>Back</button>{stepIndex<WORKFLOW_STEPS.length-1?<button type="button" onClick={goNext} className="inline-flex items-center gap-2 rounded-xl bg-blue-500 px-6 py-3 text-sm font-semibold text-white hover:bg-blue-400">Continue <ArrowRight className="h-4 w-4"/></button>:<button type="button" onClick={downloadPacket} className="inline-flex items-center gap-2 rounded-xl bg-emerald-500 px-6 py-3 text-sm font-semibold text-emerald-950 hover:bg-emerald-400"><Download className="h-4 w-4"/>Download packet</button>}</div>
      </div></main>
    </div>
  </div>;
}

type Setter = <K extends keyof DefenseCaseInput>(key: K, value: DefenseCaseInput[K]) => void;
type Issue = ReturnType<typeof buildDefenseIssues>[number];
type Node = ReturnType<typeof buildDependencyTree>[number];

function StepContent({ step, input, set, toggleEvidence, issues, dependencyTree, readiness, onDownload }: { step: StepId; input: DefenseCaseInput; set: Setter; toggleEvidence: (item:string)=>void; issues: Issue[]; dependencyTree: Node[]; readiness: ReturnType<typeof packetReadiness>; onDownload:()=>void }) {
  if(step==="case") return <Section title="Matter snapshot" note="Enter only what is known. ‘Unknown’ is better than an assumption."><Grid><Field label="Defendant name" value={input.defendantName} onChange={v=>set("defendantName",v)}/><Field label="Arrest date" type="date" value={input.arrestDate} onChange={v=>set("arrestDate",v)}/><Field label="State" value={input.state} onChange={v=>set("state",v)}/><Field label="County" value={input.county} onChange={v=>set("county",v)}/><Field label="Court" value={input.court} onChange={v=>set("court",v)}/><Field label="Case number" value={input.caseNumber} onChange={v=>set("caseNumber",v)}/><Field label="Next court date" type="date" value={input.nextCourtDate} onChange={v=>set("nextCourtDate",v)}/><Select label="Custody status" value={input.custodyStatus} options={[["unknown","Unknown"],["released","Released"],["in-custody","In custody"]]} onChange={v=>set("custodyStatus",v as DefenseCaseInput["custodyStatus"])}/><Select label="Represented by counsel?" value={input.represented} options={yesNoOptions} onChange={v=>set("represented",v as YesNoUnknown)}/><Field label="Attorney name" value={input.attorneyName} onChange={v=>set("attorneyName",v)}/></Grid><Textarea label="Charges alleged or filed" value={input.chargedOffenses} onChange={v=>set("chargedOffenses",v)} placeholder="Use the complaint, citation, booking sheet, or release papers if available."/><Notice>California is the first reviewed authority pack. Selecting another state triggers a jurisdiction warning instead of reusing California law silently.</Notice></Section>;

  if(step==="timeline") return <Section title="Reconstruct the encounter"><Grid><Field label="Stated reason for stop" value={input.stopReason} onChange={v=>set("stopReason",v)}/><Field label="Stop location" value={input.stopLocation} onChange={v=>set("stopLocation",v)}/><Field label="Stolen-vehicle hit announced" value={input.vehicleHitAnnouncedAt} onChange={v=>set("vehicleHitAnnouncedAt",v)} placeholder="Time or sequence marker"/><Field label="Bill of sale shown" value={input.billOfSaleShownAt} onChange={v=>set("billOfSaleShownAt",v)} placeholder="Time, before/after arrest, or not shown"/><Field label="Handcuffed" value={input.handcuffedAt} onChange={v=>set("handcuffedAt",v)}/><Field label="Arrested" value={input.arrestedAt} onChange={v=>set("arrestedAt",v)}/><Field label="Searched" value={input.searchedAt} onChange={v=>set("searchedAt",v)}/><Field label="Miranda warning" value={input.mirandaAt} onChange={v=>set("mirandaAt",v)} placeholder="Time, sequence, none, or unknown"/></Grid><Textarea label="Officer's stated basis" value={input.officerReasonGiven} onChange={v=>set("officerReasonGiven",v)}/><Textarea label="Statements made by defendant" value={input.statements} onChange={v=>set("statements",v)}/></Section>;

  if(step==="purchase") return <Section title="Build the vehicle provenance record"><Grid><Field label="Year, make, model" value={input.vehicleYearMakeModel} onChange={v=>set("vehicleYearMakeModel",v)}/><Field label="Vehicle plate" value={input.vehiclePlate} onChange={v=>set("vehiclePlate",v)}/><Field label="Physical / actual VIN" value={input.vehicleVin} onChange={v=>set("vehicleVin",v)}/><Field label="Bill-of-sale VIN" value={input.billOfSaleVin} onChange={v=>set("billOfSaleVin",v)}/><Field label="Purchase date" type="date" value={input.purchaseDate} onChange={v=>set("purchaseDate",v)}/><Field label="Purchase price" value={input.purchasePrice} onChange={v=>set("purchasePrice",v)}/><Field label="Seller name or listing identity" value={input.sellerName} onChange={v=>set("sellerName",v)}/><Field label="Seller contact" value={input.sellerContact} onChange={v=>set("sellerContact",v)}/><Triad label="Seller ID known?" value={input.sellerIdKnown} onChange={v=>set("sellerIdKnown",v)}/><Triad label="Keys provided?" value={input.keysProvided} onChange={v=>set("keysProvided",v)}/><Triad label="Title provided?" value={input.titleProvided} onChange={v=>set("titleProvided",v)}/><Triad label="Payment trace exists?" value={input.paymentTrace} onChange={v=>set("paymentTrace",v)}/><Triad label="DMV transfer attempted?" value={input.transferAttempted} onChange={v=>set("transferAttempted",v)}/><Triad label="Altered VIN / ignition?" value={input.alteredVinOrIgnition} onChange={v=>set("alteredVinOrIgnition",v)}/></Grid><EvidenceQuick item="Original bill of sale" checked={input.evidence.includes("Original bill of sale")} onClick={()=>toggleEvidence("Original bill of sale")}/><Notice>A bill of sale is highly important evidence of the transaction, but it does not by itself prove the seller owned the vehicle or had authority to transfer it.</Notice></Section>;

  if(step==="police-basis") return <Section title="What supported the arrest?"><Grid><Triad label="Active stolen hit known?" value={input.activeHitKnown} onChange={v=>set("activeHitKnown",v)}/><Triad label="Dispatch confirmation known?" value={input.dispatchConfirmed} onChange={v=>set("dispatchConfirmed",v)}/><Triad label="Officers reviewed bill of sale?" value={input.officersReviewedBillOfSale} onChange={v=>set("officersReviewedBillOfSale",v)}/><Triad label="Body camera known?" value={input.bodycamKnown} onChange={v=>set("bodycamKnown",v)}/><Field label="Stolen-report VIN" value={input.reportVin} onChange={v=>set("reportVin",v)}/><Field label="Stolen-report plate" value={input.reportPlate} onChange={v=>set("reportPlate",v)}/></Grid><Textarea label="What officers said or showed" value={input.officerReasonGiven} onChange={v=>set("officerReasonGiven",v)} /><IdentifierTable input={input}/></Section>;

  if(step==="search") return <Section title="Separate the search from the item merits"><Grid><Field label="Asserted search basis" value={input.searchType} onChange={v=>set("searchType",v)}/><Field label="Where object was found" value={input.itemLocation} onChange={v=>set("itemLocation",v)}/><Field label="Object description" value={input.itemDescription} onChange={v=>set("itemDescription",v)}/><Triad label="Defendant says it was theirs?" value={input.itemBelongsToDefendant} onChange={v=>set("itemBelongsToDefendant",v)}/><Triad label="Residue tested?" value={input.residueTested} onChange={v=>set("residueTested",v)}/><Triad label="Object photographed?" value={input.itemPhotographed} onChange={v=>set("itemPhotographed",v)}/><Triad label="Evidence chain known?" value={input.evidenceChainKnown} onChange={v=>set("evidenceChainKnown",v)}/></Grid><div className="mt-8"><h3 className="text-sm font-semibold text-white">Evidence dependency tree</h3><div className="mt-4 grid gap-3 sm:grid-cols-5">{dependencyTree.map((node,index)=><div className="relative rounded-xl border border-white/10 bg-black/15 p-4" key={node.id}>{index>0&&<div className="absolute -left-3 top-1/2 hidden h-px w-3 bg-amber-300/50 sm:block"/>}<div className="font-mono text-[9px] uppercase tracking-wider text-amber-300">{node.kind}</div><div className="mt-2 text-xs font-medium leading-5 text-white">{node.label}</div><div className={`mt-3 text-[10px] ${node.status==="disputed"?"text-red-300":node.status==="documented"?"text-emerald-300":"text-slate-500"}`}>{node.status}</div></div>)}</div></div></Section>;

  if(step==="evidence") return <Section title="Preservation and discovery matrix" note="Mark items already preserved or that counsel should evaluate obtaining through criminal discovery, subpoena, or another lawful channel."><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{EVIDENCE_ITEMS.map(item=><label key={item} className={`flex cursor-pointer items-center gap-3 rounded-xl border p-3 text-sm ${input.evidence.includes(item)?"border-emerald-400/35 bg-emerald-400/10 text-white":"border-white/10 text-slate-400 hover:border-white/20"}`}><input type="checkbox" className="sr-only" checked={input.evidence.includes(item)} onChange={()=>toggleEvidence(item)}/><span className={`flex h-5 w-5 shrink-0 items-center justify-center rounded border ${input.evidence.includes(item)?"border-emerald-400 bg-emerald-400 text-emerald-950":"border-white/20"}`}>{input.evidence.includes(item)&&<Check className="h-3 w-3"/>}</span>{item}</label>)}</div><Notice>Body camera, dispatch data, database returns, and evidence records may be obtained through criminal discovery rather than an ordinary public-records request. The workflow records the need; it does not send the wrong kind of request automatically.</Notice></Section>;

  if(step==="seller") return <Section title="Choose the closest ownership-chain scenario"><div className="grid gap-3">{sellerOptions.map(([value,title,text])=><label key={value} className={`flex cursor-pointer gap-4 rounded-xl border p-4 ${input.sellerScenario===value?"border-blue-400/40 bg-blue-400/10":"border-white/10 hover:border-white/20"}`}><input type="radio" name="seller-scenario" className="mt-1" checked={input.sellerScenario===value} onChange={()=>set("sellerScenario",value)}/><span><span className="block text-sm font-semibold text-white">{title}</span><span className="mt-1 block text-xs leading-5 text-slate-400">{text}</span></span></label>)}</div><Textarea label="Scenario notes and source" value={input.scenarioNotes} onChange={v=>set("scenarioNotes",v)} placeholder="Explain which documents or statements support this working scenario."/><Notice>This is a working investigation hypothesis, not a finding. Do not accuse or contact a seller or reporting party based on the selection.</Notice></Section>;

  if(step==="review") return <Section title="Counsel-review issue map"><div className="grid gap-3">{issues.map(issue=><article key={issue.id} className="rounded-xl border border-white/10 bg-black/15 p-5"><div className="flex flex-wrap items-start justify-between gap-3"><h3 className="font-serif text-xl text-white">{issue.title}</h3><Status status={issue.status}/></div><p className="mt-3 text-sm leading-6 text-slate-400">{issue.summary}</p><div className="mt-4 rounded-lg border border-blue-300/15 bg-blue-300/[.05] p-3 text-xs leading-5 text-blue-100"><strong>Counsel question:</strong> {issue.counselQuestion}</div></article>)}</div><Textarea label="Additional facts, contradictions, or questions" value={input.notes} onChange={v=>set("notes",v)}/></Section>;

  return <Section title="Attorney-ready Defense Intelligence Packet"><div className="grid gap-5 md:grid-cols-[.7fr_1.3fr]"><div className="rounded-xl border border-white/10 bg-black/15 p-6"><div className="flex items-center gap-3"><ShieldCheck className="h-6 w-6 text-emerald-300"/><div><div className="font-serif text-3xl text-white">{readiness.score}%</div><div className="text-xs text-slate-500">packet readiness</div></div></div><h3 className="mt-6 text-sm font-semibold text-white">Remaining checklist gaps</h3>{readiness.missing.length?<ul className="mt-3 space-y-2 text-xs text-slate-400">{readiness.missing.map(item=><li className="flex gap-2" key={item}><span className="text-amber-300">•</span>{item}</li>)}</ul>:<p className="mt-3 text-xs text-emerald-300">No checklist gaps detected. Source documents still require human verification.</p>}</div><div className="rounded-xl border border-emerald-400/20 bg-emerald-400/[.06] p-6"><FileText className="h-8 w-8 text-emerald-300"/><h3 className="mt-5 font-serif text-3xl text-white">Defense Intelligence Packet</h3><p className="mt-3 text-sm leading-6 text-slate-300">Includes the case theory, Stop–Arrest–Search Timeline, Vehicle Provenance record, identifier comparison, Evidence Dependency Tree, issue map, seller scenario, preservation inventory, missing-evidence list, and California authority boundaries.</p><button type="button" onClick={onDownload} className="mt-6 inline-flex items-center gap-2 rounded-xl bg-emerald-400 px-5 py-3 text-sm font-semibold text-emerald-950"><Download className="h-4 w-4"/>Download Markdown packet</button></div></div><Notice>The downloaded packet is a structured attorney-review aid. It is not a filed motion or a legal opinion, and no conclusion in it should be treated as verified until checked against source documents and discovery.</Notice></Section>;
}

const yesNoOptions:[[string,string],[string,string],[string,string]]=[["unknown","Unknown"],["yes","Yes"],["no","No"]];
const sellerOptions: Array<[SellerScenario,string,string]> = [
  ["legitimate-sale","Legitimate sale / erroneous report","The registered or authorized owner sold the vehicle, but a report remained active or was wrong."],
  ["authority-to-sell","Seller had authority despite paperwork problem","The seller may not appear on the current title but may have had authority to transfer the vehicle."],
  ["broken-title-chain","Broken title chain","One or more buyers may have failed to complete title transfers before the current sale."],
  ["fraudulent-seller","Fraudulent seller / buyer may be a victim","The seller may have transferred a vehicle without ownership or authority."],
  ["upstream-theft","Upstream theft","The vehicle may have been stolen before it reached the seller."],
  ["post-sale-report","Report after disputed transfer","A prior owner or other party may have reported the vehicle after a voluntary but disputed transfer."],
  ["unknown","Unknown","The current evidence does not support choosing a scenario yet."],
];

function Section({title,note,children}:{title:string;note?:string;children:ReactNode}){return <section><h2 className="font-serif text-2xl text-white">{title}</h2>{note&&<p className="mt-2 max-w-3xl text-sm leading-6 text-slate-400">{note}</p>}<div className="mt-6 space-y-6">{children}</div></section>}
function Grid({children}:{children:ReactNode}){return <div className="grid gap-5 sm:grid-cols-2">{children}</div>}
function Field({label,value,onChange,type="text",placeholder}:{label:string;value:string;onChange:(value:string)=>void;type?:string;placeholder?:string}){return <label className="block"><span className="text-[11px] font-semibold uppercase tracking-[.12em] text-slate-400">{label}</span><input type={type} value={value} onChange={event=>onChange(event.target.value)} placeholder={placeholder} className="mt-2 w-full rounded-xl border border-white/10 bg-black/20 px-4 py-3 text-sm text-white outline-none placeholder:text-slate-600 focus:border-blue-400/60"/></label>}
function Textarea({label,value,onChange,placeholder}:{label:string;value:string;onChange:(value:string)=>void;placeholder?:string}){return <label className="block"><span className="text-[11px] font-semibold uppercase tracking-[.12em] text-slate-400">{label}</span><textarea rows={4} value={value} onChange={event=>onChange(event.target.value)} placeholder={placeholder} className="mt-2 w-full resize-y rounded-xl border border-white/10 bg-black/20 px-4 py-3 text-sm leading-6 text-white outline-none placeholder:text-slate-600 focus:border-blue-400/60"/></label>}
function Select({label,value,options,onChange}:{label:string;value:string;options:ReadonlyArray<readonly[string,string]>;onChange:(value:string)=>void}){return <label className="block"><span className="text-[11px] font-semibold uppercase tracking-[.12em] text-slate-400">{label}</span><select value={value} onChange={event=>onChange(event.target.value)} className="mt-2 w-full rounded-xl border border-white/10 bg-[#091827] px-4 py-3 text-sm text-white outline-none focus:border-blue-400/60">{options.map(([key,text])=><option value={key} key={key}>{text}</option>)}</select></label>}
function Triad({label,value,onChange}:{label:string;value:YesNoUnknown;onChange:(value:YesNoUnknown)=>void}){return <fieldset><legend className="text-[11px] font-semibold uppercase tracking-[.12em] text-slate-400">{label}</legend><div className="mt-2 grid grid-cols-3 gap-1 rounded-xl border border-white/10 bg-black/20 p-1">{(["yes","no","unknown"] as YesNoUnknown[]).map(item=><button type="button" key={item} onClick={()=>onChange(item)} className={`rounded-lg px-2 py-2 text-xs capitalize ${value===item?"bg-blue-500 text-white":"text-slate-500 hover:text-slate-300"}`}>{item}</button>)}</div></fieldset>}
function Notice({children}:{children:ReactNode}){return <div className="flex gap-3 rounded-xl border border-amber-300/15 bg-amber-300/[.05] p-4 text-xs leading-5 text-amber-100/75"><AlertCircle className="mt-0.5 h-4 w-4 shrink-0 text-amber-300"/>{children}</div>}
function EvidenceQuick({item,checked,onClick}:{item:string;checked:boolean;onClick:()=>void}){return <button type="button" onClick={onClick} className={`flex w-full items-center gap-3 rounded-xl border p-4 text-left text-sm ${checked?"border-emerald-400/40 bg-emerald-400/10 text-white":"border-white/10 text-slate-400"}`}><span className={`flex h-6 w-6 items-center justify-center rounded-full border ${checked?"border-emerald-400 bg-emerald-400 text-emerald-950":"border-white/20"}`}>{checked&&<Check className="h-4 w-4"/>}</span>{item} is preserved</button>}
function IdentifierTable({input}:{input:DefenseCaseInput}){const rows=[["Physical vehicle",input.vehicleVin,input.vehiclePlate],["Bill of sale",input.billOfSaleVin,"—"],["Police / stolen report",input.reportVin,input.reportPlate]];return <div className="overflow-hidden rounded-xl border border-white/10"><div className="grid grid-cols-3 bg-white/[.05] px-4 py-3 text-[10px] font-semibold uppercase tracking-wider text-slate-500"><span>Source</span><span>VIN</span><span>Plate</span></div>{rows.map(row=><div key={row[0]} className="grid grid-cols-3 border-t border-white/10 px-4 py-3 text-xs"><span className="text-slate-400">{row[0]}</span><span className="font-mono text-white">{row[1]||"Not entered"}</span><span className="font-mono text-white">{row[2]||"Not entered"}</span></div>)}</div>}
function Status({status}:{status:Issue["status"]}){const style=status==="urgent"?"border-red-400/30 bg-red-400/10 text-red-300":status==="conflict"?"border-amber-300/30 bg-amber-300/10 text-amber-200":status==="supported"?"border-emerald-400/30 bg-emerald-400/10 text-emerald-300":"border-blue-300/20 bg-blue-300/[.08] text-blue-200";return <span className={`inline-flex items-center gap-1.5 rounded-full border px-2.5 py-1 font-mono text-[9px] uppercase tracking-wider ${style}`}>{status==="supported"?<CheckCircle2 className="h-3 w-3"/>:<GitBranch className="h-3 w-3"/>}{status}</span>}
