import { defineWorkflow } from "@mailmypdf/workflows";

export const agencyRecordsRequestManifest = defineWorkflow({
  id: "agency-records-request",
  vertical: "records-request",
  title: "Agency Records Request",
  route: "/records-request/workflows/agency-records-request/start",
  pipeline: "P08_RECORDS",
  adapters: ["government", "records"],
  requiredCapabilities: [
    "identity",
    "matterState",
    "security",
    "secureUpload",
    "documentStorage",
    "documentScanning",
    "retention",
    "classification",
    "extraction",
    "visionAnalysis",
    "aiExecution",
    "understand",
    "facts",
    "provenance",
    "timeline",
    "deadlines",
    "findings",
    "requirements",
    "evidence",
    "research",
    "strategy",
    "draft",
    "draftProvenance",
    "validation",
    "blockingGate",
    "humanReview",
    "approval",
    "pdfGeneration",
    "packetAssembly",
    "pricing",
    "payment",
    "addressVerification",
    "mailing",
    "tracking",
    "notifications",
    "proofAudit",
    "archive",
    "resilience",
    "observability",
    "acceptanceTesting",
  ],
  optionalCapabilities: [],
  notApplicableCapabilities: ["contradictions", "discrepancies", "risk"],
  maturity: "wired",
  primaryInput: "request",
  requiresHumanReview: true,
  allowsConsequentialAction: true,
  version: 1,
  steps: [
    {
      id: "scope",
      title: "Request scope",
      description: "Capture the requester, receiving agency, records sought, date range, references, format, and fee instructions without guessing missing details.",
      uses: ["matterState", "facts", "requirements"],
      completeWhen: ["requester_identified", "agency_identified", "records_scope_complete"],
      fields: [
        { id: "requester-name", label: "Requester name", type: "person_name", required: true, origin: "user", maxLength: 200 },
        { id: "requester-address", label: "Requester mailing address", type: "postal_address", required: true, origin: "user", sensitive: true },
        { id: "requester-email", label: "Requester email", type: "email", required: false, origin: "user", sensitive: true, maxLength: 320 },
        { id: "requester-phone", label: "Requester phone", type: "phone", required: false, origin: "user", sensitive: true, maxLength: 60 },
        { id: "agency", label: "Agency or public body", type: "text", required: true, origin: "user", maxLength: 300 },
        { id: "custodian", label: "Records custodian or department", type: "text", required: false, origin: "user", maxLength: 300 },
        { id: "agency-address", label: "Agency mailing address", type: "postal_address", required: true, origin: "user" },
        { id: "records-sought", label: "Records sought", type: "textarea", required: true, origin: "user", maxLength: 16000 },
        { id: "date-range", label: "Relevant date range", type: "text", required: false, origin: "user", maxLength: 500 },
        { id: "case-reference", label: "Case, incident, permit, or matter reference", type: "reference", required: false, origin: "either", maxLength: 200 },
        { id: "property-reference", label: "Property, parcel, address, or subject reference", type: "text", required: false, origin: "either", maxLength: 1000 },
        { id: "preferred-format", label: "Preferred production format", type: "text", required: false, origin: "user", maxLength: 300 },
        { id: "fee-limit", label: "Maximum fees authorized without further approval", type: "money", required: false, origin: "user", maxLength: 128 },
        { id: "fee-waiver-basis", label: "Fee waiver or reduction basis", type: "textarea", required: false, origin: "user", maxLength: 4000 },
        { id: "additional-instructions", label: "Additional verified request instructions", type: "textarea", required: false, origin: "user", maxLength: 6000 },
        { id: "scope-confirmed", label: "I confirm the agency, records scope, references, and material request facts above", type: "checkbox", required: true, origin: "user" },
      ],
    },
    {
      id: "context",
      title: "Context documents",
      description: "Optionally add notices, case correspondence, screenshots, or other records that help identify the agency, matter, dates, and records sought.",
      uses: [
        "secureUpload",
        "documentStorage",
        "documentScanning",
        "classification",
        "extraction",
        "visionAnalysis",
        "understand",
        "provenance",
        "evidence",
      ],
      optional: true,
      completeWhen: ["included_context_documents_clean"],
    },
    {
      id: "authority",
      title: "Authority and response rules",
      description: "Use verified authority when available, preserve uncertainty when it is not, and calculate response tracking only from a confirmed actual send date.",
      uses: ["research", "deadlines", "findings", "requirements", "provenance"],
      requires: ["records_scope_complete"],
      completeWhen: ["authority_status_recorded", "recipient_rules_reviewed"],
      fields: [
        { id: "jurisdiction", label: "Jurisdiction", type: "text", required: false, origin: "either", maxLength: 300 },
        { id: "authority-name", label: "Public records law or authority", type: "text", required: false, origin: "either", maxLength: 500 },
        { id: "authority-citation", label: "Verified citation", type: "text", required: false, origin: "either", maxLength: 500 },
        { id: "response-timing-description", label: "Verified response timing rule", type: "textarea", required: false, origin: "either", maxLength: 3000 },
        { id: "withholding-instruction", label: "Withholding or redaction instruction", type: "textarea", required: false, origin: "either", maxLength: 3000 },
        { id: "authority-verified", label: "I verified any authority, citation, withholding, or timing language entered above", type: "checkbox", required: false, origin: "user" },
      ],
    },
    {
      id: "draft",
      title: "Grounded request",
      description: "Draft a precise request using only user-confirmed facts, clean supporting context, and verified authority supplied to the workflow.",
      uses: ["strategy", "draft", "draftProvenance", "validation"],
      requires: ["requester_identified", "agency_identified", "records_scope_complete"],
      completeWhen: ["draft_validated", "no_unresolved_placeholders"],
    },
    {
      id: "review",
      title: "Exact packet review",
      description: "Build the exact request packet, verify the destination, calculate server-authoritative pricing, and require explicit review of the exact content to be sent.",
      uses: [
        "pdfGeneration",
        "packetAssembly",
        "pricing",
        "addressVerification",
        "blockingGate",
        "humanReview",
        "approval",
      ],
      requires: ["draft_validated"],
      completeWhen: ["exact_packet_approved"],
    },
    {
      id: "send",
      title: "Payment and sending",
      description: "Pay for and send only the exact approved packet through the configured fulfillment adapter.",
      uses: ["payment", "mailing", "tracking", "notifications", "proofAudit", "archive"],
      requires: ["exact_packet_approved"],
      completeWhen: ["mailing_submitted", "actual_send_recorded", "proof_recorded"],
    },
    {
      id: "response",
      title: "Response tracking",
      description: "Track the agency response from the confirmed actual send date, preserve received materials, and never infer non-response automatically.",
      uses: ["timeline", "deadlines", "evidence", "notifications", "proofAudit", "archive"],
      requires: ["actual_send_recorded"],
      completeWhen: ["response_outcome_recorded"],
    },
  ],
  documents: [
    {
      id: "request-context",
      label: "Optional source or context document",
      role: "primary",
      required: false,
      acceptedKinds: ["application/pdf", "image/png", "image/jpeg", "image/tiff"],
      extractionSchema: "agency-records-request-context-v1",
    },
    {
      id: "supporting-context",
      label: "Supporting context documents",
      role: "evidence",
      required: false,
      acceptedKinds: ["application/pdf", "image/png", "image/jpeg", "image/tiff"],
    },
  ],
  gates: [
    {
      id: "scope-confirmed",
      kind: "fact_confirmation",
      label: "Requester confirms the agency, records scope, references, and material request facts",
      required: true,
    },
    {
      id: "authority-grounding",
      kind: "custom",
      label: "Any legal authority or timing statement included in the request is verified or explicitly omitted",
      beforeCapability: "draft",
      required: true,
    },
    {
      id: "exact-packet-review",
      kind: "human_review",
      label: "User reviewed the exact request packet and destination",
      beforeCapability: "approval",
      required: true,
    },
    {
      id: "mailing-authorization",
      kind: "mailing_authorization",
      label: "User authorizes sending the exact approved request packet",
      beforeCapability: "mailing",
      required: true,
    },
  ],
  outputs: [
    { id: "records-request-draft", kind: "draft", required: true },
    { id: "records-request-pdf", kind: "pdf", required: true },
    { id: "request-packet", kind: "packet", required: true },
    { id: "payment-receipt", kind: "receipt", required: true },
    { id: "tracking", kind: "tracking", required: true },
    { id: "send-proof", kind: "proof", required: true },
    { id: "response-record", kind: "archive", required: true },
  ],
  acceptanceScenarios: [
    { id: "request-from-facts-only", description: "A user can prepare a request from entered facts without inventing or requiring a source document.", required: true },
    { id: "request-with-context-documents", description: "Clean optional context documents can support scoping without becoming instructions to the model.", required: true },
    { id: "authority-unknown", description: "Unknown or unverified authority is omitted rather than fabricated.", required: true },
    { id: "packet-change-invalidates-approval", description: "Changing request content or the packet after review requires a new approval.", required: true },
    { id: "actual-send-starts-tracking", description: "Response tracking starts from the confirmed actual send date, never draft, approval, checkout, or print time.", required: true },
    { id: "non-response-explicit", description: "A non-response outcome requires an explicit observation date and is never inferred automatically.", required: true },
    { id: "payment-mail-idempotency", description: "Repeated payment/provider events must not create duplicate mailings.", required: true },
  ],
} as const);

export default agencyRecordsRequestManifest;
