import { defineWorkflowDomainSpec } from "@mailmypdf/workflows";

export const cp2000DomainSpec = defineWorkflowDomainSpec({
  workflowId: "cp2000-response",
  version: 1,
  authorityMaxAgeDays: 90,
  extractionSchemaIds: ["irs.cp2000.v1"],
  authoritySources: [
    {
      id: "irs.cp2000-series",
      title: "Understanding your CP2000 series notice",
      publisher: "Internal Revenue Service",
      url: "https://www.irs.gov/individuals/understanding-your-cp2000-series-notice",
      sourceType: "official_agency",
      reviewedAt: "2026-09-16",
      jurisdiction: "United States",
    },
    {
      id: "irs.topic-652",
      title: "Topic no. 652, Notice of underreported income – CP2000",
      publisher: "Internal Revenue Service",
      url: "https://www.irs.gov/taxtopics/tc652",
      sourceType: "official_agency",
      reviewedAt: "2026-09-16",
      jurisdiction: "United States",
    },
  ],
  rules: [
    {
      id: "treat-as-proposal",
      label: "Treat the notice as a proposed adjustment",
      kind: "requirement",
      description: "Preserve the distinction between the CP2000 proposal and an assessed bill.",
      severity: "blocking",
      authoritySourceIds: ["irs.cp2000-series", "irs.topic-652"],
    },
    {
      id: "use-printed-response-date",
      label: "Use the controlling notice response date",
      kind: "deadline",
      description: "Extract and confirm the reply-by date printed on the user's controlling notice instead of substituting a calculated deadline.",
      severity: "blocking",
      authoritySourceIds: ["irs.cp2000-series", "irs.topic-652"],
    },
    {
      id: "follow-notice-response-instructions",
      label: "Follow the notice-specific response instructions",
      kind: "requirement",
      description: "Use the response form when the notice includes one and support disputed items with the records the user actually provides.",
      severity: "blocking",
      authoritySourceIds: ["irs.cp2000-series"],
    },
    {
      id: "use-notice-response-address",
      label: "Use the response destination printed on the notice",
      kind: "submission",
      description: "The final mailing destination must be confirmed against the response address printed on the controlling notice.",
      severity: "blocking",
      authoritySourceIds: ["irs.cp2000-series", "irs.topic-652"],
    },
    {
      id: "no-outcome-guarantee",
      label: "Do not guarantee IRS acceptance",
      kind: "drafting",
      description: "The draft must describe the user's factual response without predicting or guaranteeing the IRS outcome.",
      severity: "blocking",
      authoritySourceIds: ["irs.cp2000-series"],
    },
  ],
  evidenceRequirements: [
    {
      id: "controlling-notice",
      label: "Controlling CP2000 notice",
      description: "The complete notice being answered, including the pages that show the proposed changes, response date, and response destination.",
      required: true,
      acceptedDocumentKinds: ["notice"],
      supportsRuleIds: [
        "treat-as-proposal",
        "use-printed-response-date",
        "follow-notice-response-instructions",
        "use-notice-response-address",
      ],
    },
    {
      id: "disputed-item-support",
      label: "Records supporting disputed items",
      description: "Copies of records the user relies on to explain or dispute a proposed item.",
      required: false,
      acceptedDocumentKinds: ["evidence", "form", "receipt", "correspondence"],
      supportsRuleIds: ["follow-notice-response-instructions"],
    },
  ],
  aiTasks: [
    {
      id: "classify-cp2000",
      kind: "classify",
      promptVersion: "cp2000.classify.v1",
      purpose: "Confirm that the controlling document is a CP2000-series notice.",
      instruction: "Classify from the document itself. If it is not a CP2000-series notice, report the mismatch instead of forcing the workflow.",
      sourcePolicy: "document_only",
      requiresHumanConfirmation: true,
    },
    {
      id: "extract-cp2000",
      kind: "extract",
      promptVersion: "cp2000.extract.v1",
      purpose: "Extract the proposed changes, printed dates, identifiers, amounts, and response address.",
      instruction: "Extract only values actually supported by the notice and include page/excerpt provenance for every non-null value. Never calculate a response date.",
      sourcePolicy: "document_only",
      outputSchemaId: "irs.cp2000.v1",
      requiresHumanConfirmation: true,
    },
    {
      id: "analyze-cp2000",
      kind: "analyze",
      promptVersion: "cp2000.analyze.v1",
      purpose: "Map each proposed change to the user's response and available supporting records.",
      instruction: "Separate proposed items, confirmed user facts, disputed assertions, missing information, and supporting records. Do not invent facts or tax positions.",
      sourcePolicy: "matter_record",
      requiresHumanConfirmation: true,
    },
    {
      id: "research-cp2000",
      kind: "research",
      promptVersion: "cp2000.research.v1",
      purpose: "Ground workflow guidance in the approved IRS sources.",
      instruction: "Use the approved authority sources only for workflow guidance. Preserve the controlling notice as the source for case-specific dates and destinations.",
      sourcePolicy: "authority_grounded",
    },
    {
      id: "draft-cp2000-response",
      kind: "draft",
      promptVersion: "cp2000.draft.v1",
      purpose: "Prepare a factual response aligned to the user's selected agree, disagree, or partial-agreement path.",
      instruction: "Draft only from confirmed notice facts, confirmed user facts, and records actually included. Do not invent tax-return figures, payer records, authorities, payments, deadlines, or outcomes.",
      sourcePolicy: "matter_record",
      requiresHumanConfirmation: true,
    },
    {
      id: "validate-cp2000-response",
      kind: "validate",
      promptVersion: "cp2000.validate.v1",
      purpose: "Block unsupported claims, unconfirmed extracted facts, unresolved required items, or an unverified mailing destination.",
      instruction: "Fail closed when a material draft claim lacks support, when the controlling response date is unconfirmed, or when the response address was not confirmed against the notice.",
      sourcePolicy: "matter_record",
    },
  ],
  drafting: {
    purpose: "Prepare a reviewable factual CP2000 response from the verified matter record.",
    templateId: "official-response-letter.v1",
    tone: "professional, factual, concise",
    requiresSourceBackedClaims: true,
    prohibitedClaims: [
      "Do not call the proposed adjustment an assessed bill unless the controlling document says so.",
      "Do not calculate or invent a response deadline.",
      "Do not claim evidence is enclosed unless it is actually included in the approved packet.",
      "Do not guarantee acceptance, abatement, adjustment, or any other outcome.",
      "Do not invent statutes, tax-return figures, payer records, or payments.",
    ],
    requiredSections: [
      "notice-reference",
      "response-position",
      "itemized-explanation",
      "supporting-records",
      "requested-action",
    ],
  },
});

export default cp2000DomainSpec;
