// @generated by the supervised workflow factory build executor.
// This file is machine-owned. Do not hand-edit generated profiles.

import type { RecordsRequestWorkflowProfile } from "./profiles.js";

export const GENERATED_RECORDS_REQUEST_WORKFLOW_PROFILES = Object.freeze(
  [] as const satisfies readonly RecordsRequestWorkflowProfile[],
);
