import {
  buildCanonicalWorkflowRegistry,
  buildReviewedFactoryTemplatePlan,
  buildWorkflowMaterializationPlan,
  type FactoryJob,
  type WorkflowSeed,
} from "@mailmypdf/workflows";

export type GeneratedRecordsRequestProfile = Readonly<{
  workflowId: string;
  title: string;
  recordsSoughtPlaceholder: string;
  contextDocumentLabel: string;
  supportingContextLabel: string;
}>;

export type GeneratedNoticeResponseProfile = Readonly<{
  workflowId: string;
  title: string;
  noticeLabel: string;
  primaryDocumentId: string;
  primaryDocumentLabel: string;
  extractionSchema: string;
  sourcePurpose: string;
  responseModeLabel: string;
  responseModes: readonly Readonly<{ value: string; label: string }>[];
  evidenceKinds: readonly Readonly<{ value: string; label: string }>[];
  explanationRequiredModes: readonly string[];
  explanationLabel: string;
  explanationHint: string;
  requestedActionDefault: string;
  analysisInstructions: string;
  draftInstructions: string;
}>;

export type FactoryProfileRegistryPaths = Readonly<{
  specs: string;
  generated: string;
}>;

export type FactoryProposalFile = Readonly<{
  path: string;
  content: string;
}>;

export type FactoryProposalPlan = Readonly<{
  canonicalId: string;
  sectionId: string;
  slug: string;
  specPath: string;
  configPath: string;
  profileRegistryPath: string;
  files: readonly FactoryProposalFile[];
}>;

export const RECORDS_REQUEST_PROFILE_SPECS =
  "packages/workflows/src/domain-packs/records-request/generated-profile-specs.json";
export const RECORDS_REQUEST_PROFILES =
  "packages/workflows/src/domain-packs/records-request/generated-profiles.ts";
export const NOTICE_RESPONSE_PROFILE_SPECS =
  "packages/workflows/src/domain-packs/notice-response/generated-profile-specs.json";
export const NOTICE_RESPONSE_PROFILES =
  "packages/workflows/src/domain-packs/notice-response/generated-profiles.ts";

function canonicalRegistryContent(seeds: readonly WorkflowSeed[]): string {
  return (
    "[\n" +
    seeds.map((seed) => `  ${JSON.stringify(seed)}`).join(",\n") +
    "\n]\n"
  );
}

function inventoryContent(seeds: readonly WorkflowSeed[]): string {
  const registry = buildCanonicalWorkflowRegistry(seeds);
  return (
    JSON.stringify(
      {
        generatedFrom: "packages/workflows/src/canonical-workflows.json",
        total: registry.length,
        workflows: registry.map((workflow) => ({
          id: workflow.id,
          vertical: workflow.sectionId,
          route: workflow.publicHref,
          maturity: workflow.maturity,
          hasGoldContent: workflow.legacyGoldId !== null,
          hasApiEndpoint: workflow.execution?.kind === "platform",
          sourceVerified: workflow.authority !== null,
          testStatus: "pending",
          lastReviewed: workflow.authority?.reviewedAt ?? null,
        })),
      },
      null,
      2,
    ) + "\n"
  );
}

export function renderGeneratedRecordsRequestProfiles(
  profiles: readonly GeneratedRecordsRequestProfile[],
): string {
  return `// @generated by the supervised workflow factory build executor.
// This file is machine-owned. Do not hand-edit generated profiles.

import type { RecordsRequestWorkflowProfile } from "./profiles.js";

export const GENERATED_RECORDS_REQUEST_WORKFLOW_PROFILES = Object.freeze(
${JSON.stringify(profiles, null, 2)}
  as const satisfies readonly RecordsRequestWorkflowProfile[],
);
`;
}

export function renderGeneratedNoticeResponseProfiles(
  profiles: readonly GeneratedNoticeResponseProfile[],
): string {
  return `// @generated by the supervised workflow factory build executor.
// This file is machine-owned. Do not hand-edit generated profiles.

import type { NoticeResponseWorkflowProfile } from "./profiles.js";

export const GENERATED_NOTICE_RESPONSE_WORKFLOW_PROFILES = Object.freeze(
${JSON.stringify(profiles, null, 2)}
  as const satisfies readonly NoticeResponseWorkflowProfile[],
);
`;
}

export function renderFactoryLandingConfig(job: FactoryJob): string {
  if (!job.build) throw new Error("Factory build recipe is missing.");
  const request = job.build.request;
  const label = request.label.replaceAll('"', '\\"');
  const recordsRequest = request.startTemplate === "records-request";
  const sectionId = recordsRequest ? "records-request" : "notice-respond";
  const sectionName = recordsRequest ? "Records Request" : "Notice Respond";
  const eyebrow = recordsRequest
    ? "Records Request workflow"
    : "Notice Respond workflow";
  const description = (
    recordsRequest
      ? `Use the ${request.label} workflow to organize the requester, agency, records scope, optional context, authority review, exact packet approval, mailing, and proof record.`
      : `Use the ${request.label} workflow to work from the actual controlling notice, confirm extracted facts, choose a reviewed response mode, include supporting records, review the exact packet, mail it, and retain proof.`
  ).replaceAll('"', '\\"');

  return `import type { WorkflowLandingConfig } from "@mailmypdf/design-system"

export const workflowConfig = {
  id: "${job.build.slug}",
  sectionId: "${sectionId}",
  sectionName: "${sectionName}",
  sectionPath: "/${sectionId}",
  path: "/${sectionId}/workflows/${job.build.slug}",
  startPath: "/${sectionId}/workflows/${job.build.slug}/start",
  title: "${label}",
  seoTitle: "${label} | ${sectionName} | MailMyPDF",
  seoDescription: "${description}",
  eyebrow: "${eyebrow}",
  heroTitle: "${label}",
  heroDescription: "${description}",
  indexable: false,
  contentStatus: "scaffold",
} as const satisfies WorkflowLandingConfig

export default workflowConfig
`;
}

export function recordsRequestProfileFromJob(
  job: FactoryJob,
): GeneratedRecordsRequestProfile {
  if (!job.build) throw new Error("Factory build recipe is missing.");
  return Object.freeze({
    workflowId: job.build.slug,
    title: job.build.request.label,
    recordsSoughtPlaceholder:
      `Describe the records needed for ${job.build.request.label}, including record types, subjects, dates, departments, case or incident references, addresses, and other identifiers that will help the agency locate them.`,
    contextDocumentLabel:
      "Optional source, notice, case, or agency context document",
    supportingContextLabel: "Supporting request context",
  });
}

export function noticeResponseProfileFromJob(
  job: FactoryJob,
): GeneratedNoticeResponseProfile {
  if (!job.build) throw new Error("Factory build recipe is missing.");
  const reviewed = job.build.request.noticeProfile;
  if (!reviewed) {
    throw new Error(
      "Notice Respond supervised builds require a reviewer-authored noticeProfile.",
    );
  }
  const { domain: _domain, ...runtimeProfile } = reviewed;
  return Object.freeze({
    workflowId: job.build.slug,
    title: job.build.request.label,
    ...runtimeProfile,
  });
}

export function profileRegistryPaths(
  job: FactoryJob,
): FactoryProfileRegistryPaths {
  if (!job.build) throw new Error("Factory build recipe is missing.");
  if (job.build.request.startTemplate === "records-request") {
    return Object.freeze({
      specs: RECORDS_REQUEST_PROFILE_SPECS,
      generated: RECORDS_REQUEST_PROFILES,
    });
  }
  if (job.build.request.startTemplate === "notice-response") {
    return Object.freeze({
      specs: NOTICE_RESPONSE_PROFILE_SPECS,
      generated: NOTICE_RESPONSE_PROFILES,
    });
  }
  throw new Error(
    `Remote factory proposal planning does not support ${job.build.request.startTemplate}.`,
  );
}

function generatedProfileForJob(
  job: FactoryJob,
): GeneratedRecordsRequestProfile | GeneratedNoticeResponseProfile {
  return job.build?.request.startTemplate === "records-request"
    ? recordsRequestProfileFromJob(job)
    : noticeResponseProfileFromJob(job);
}

function renderGeneratedProfiles(
  job: FactoryJob,
  profiles: readonly (
    | GeneratedRecordsRequestProfile
    | GeneratedNoticeResponseProfile
  )[],
): string {
  return job.build?.request.startTemplate === "records-request"
    ? renderGeneratedRecordsRequestProfiles(
        profiles as readonly GeneratedRecordsRequestProfile[],
      )
    : renderGeneratedNoticeResponseProfiles(
        profiles as readonly GeneratedNoticeResponseProfile[],
      );
}

export function buildFactoryProposalPlan(input: {
  job: FactoryJob;
  canonicalSeeds: readonly WorkflowSeed[];
  profileSpecs: readonly (
    | GeneratedRecordsRequestProfile
    | GeneratedNoticeResponseProfile
  )[];
  existingConfig: string | null;
  existingSpec: string | null;
}): FactoryProposalPlan {
  const { job } = input;
  if (!job.build) throw new Error("Factory build recipe is missing.");
  const build = buildReviewedFactoryTemplatePlan(job.build.request);
  const materialization = buildWorkflowMaterializationPlan(build.spec);
  const adopting = build.request.adoptExisting === true;
  const canonicalSeeds = [...input.canonicalSeeds];
  const existingIndex = canonicalSeeds.findIndex(
    (seed) => seed.id === build.canonicalId,
  );

  if (adopting) {
    if (existingIndex < 0) {
      throw new Error(
        `Catalog workflow ${build.canonicalId} disappeared from the build base.`,
      );
    }
    const existing = canonicalSeeds[existingIndex]!;
    if (existing.execution) {
      throw new Error(
        `Catalog workflow ${build.canonicalId} became executable before adoption.`,
      );
    }
    if (existing.label !== build.request.label) {
      throw new Error(
        `Catalog workflow ${build.canonicalId} label changed before adoption.`,
      );
    }
    if (input.existingConfig === null) {
      throw new Error(
        `Catalog adoption requires reviewed public config at ${build.sectionId}/workflows/${build.slug}/config.ts.`,
      );
    }
    if (input.existingSpec !== null) {
      throw new Error(
        `Catalog workflow ${build.canonicalId} already has workflow.spec.json and requires manual reconciliation.`,
      );
    }
    canonicalSeeds[existingIndex] = materialization.canonicalSeed;
  } else {
    if (existingIndex >= 0) {
      throw new Error(
        `Canonical workflow ${build.canonicalId} already exists; use catalog adoption.`,
      );
    }
    if (input.existingConfig !== null || input.existingSpec !== null) {
      throw new Error(
        `Workflow ${build.canonicalId} already exists on the build base.`,
      );
    }
    const lastSectionIndex = canonicalSeeds.reduce(
      (last, seed, index) =>
        seed.id.startsWith(`${build.sectionId}/`) ? index : last,
      -1,
    );
    canonicalSeeds.splice(
      lastSectionIndex >= 0 ? lastSectionIndex + 1 : canonicalSeeds.length,
      0,
      materialization.canonicalSeed,
    );
  }

  const generatedProfile = generatedProfileForJob(job);
  if (
    input.profileSpecs.some(
      (profile) => profile.workflowId === generatedProfile.workflowId,
    )
  ) {
    throw new Error(
      `Generated profile ${generatedProfile.workflowId} already exists.`,
    );
  }
  const nextProfiles = [...input.profileSpecs, generatedProfile].sort(
    (left, right) => left.workflowId.localeCompare(right.workflowId),
  );

  // Validate the complete canonical set before emitting any remote write plan.
  buildCanonicalWorkflowRegistry(canonicalSeeds);

  const workflowRoot = `${build.sectionId}/workflows/${build.slug}`;
  const specPath = `${workflowRoot}/workflow.spec.json`;
  const configPath = `${workflowRoot}/config.ts`;
  const profileRegistry = profileRegistryPaths(job);
  const files: FactoryProposalFile[] = [
    ...(!adopting
      ? [{ path: configPath, content: renderFactoryLandingConfig(job) }]
      : []),
    {
      path: specPath,
      content: JSON.stringify(build.spec, null, 2) + "\n",
    },
    {
      path: profileRegistry.specs,
      content: JSON.stringify(nextProfiles, null, 2) + "\n",
    },
    {
      path: profileRegistry.generated,
      content: renderGeneratedProfiles(job, nextProfiles),
    },
    ...materialization.files,
    {
      path: "packages/workflows/src/canonical-workflows.json",
      content: canonicalRegistryContent(canonicalSeeds),
    },
    {
      path: "mailmypdf/WORKFLOW_INVENTORY.json",
      content: inventoryContent(canonicalSeeds),
    },
  ];

  return Object.freeze({
    canonicalId: build.canonicalId,
    sectionId: build.sectionId,
    slug: build.slug,
    specPath,
    configPath,
    profileRegistryPath: profileRegistry.specs,
    files: Object.freeze(
      files.map((file) => Object.freeze({ ...file })),
    ),
  });
}
