import type {
  FactoryBuildArtifact,
  FactoryBuildCheck,
  FactoryBuildRequest,
  FactoryJob,
} from "@mailmypdf/workflows";
import { findStudioProject, resolveProjectRoot } from "@/studio/domain/studio-project";
import {
  failPersistentFactoryBuild,
  loadPersistentFactoryJob,
  recordPersistentFactoryAcceptance,
  recordPersistentFactoryBuildMaterialized,
  startPersistentFactoryBuild,
} from "@/studio/factory-job.server";

type GeneratedRecordsRequestProfile = Readonly<{
  workflowId: string;
  title: string;
  recordsSoughtPlaceholder: string;
  contextDocumentLabel: string;
  supportingContextLabel: string;
}>;

const GENERATED_PROFILE_SPECS =
  "packages/workflows/src/domain-packs/records-request/generated-profile-specs.json";
const GENERATED_PROFILES =
  "packages/workflows/src/domain-packs/records-request/generated-profiles.ts";

function normalizeOutput(value: string | undefined, max = 4_000): string {
  const text = (value ?? "").trim();
  return text.length <= max ? text : text.slice(-max);
}

function renderGeneratedProfiles(
  profiles: readonly GeneratedRecordsRequestProfile[],
): string {
  return `// @generated by the supervised workflow factory build executor.
// This file is machine-owned. Do not hand-edit generated profiles.

import type { RecordsRequestWorkflowProfile } from "./profiles.js";

export const GENERATED_RECORDS_REQUEST_WORKFLOW_PROFILES = Object.freeze(
${JSON.stringify(profiles, null, 2)}
  as const satisfies readonly RecordsRequestWorkflowProfile[],
);
`;
}

function renderWorkflowSpec(request: FactoryBuildRequest): string {
  return (
    JSON.stringify(
      {
        schemaVersion: "mailmypdf.workflow-materialization/v1",
        id: `${request.sectionId}/${request.workflowId}`,
        label: request.label,
        execution: {
          kind: "platform",
          entry: "workspace-start",
          policyFamily: "records-request",
        },
        startTemplate: "records-request",
      },
      null,
      2,
    ) + "\n"
  );
}

function renderLandingConfig(request: FactoryBuildRequest): string {
  const description =
    `Use the ${request.label} workflow to organize the requester, agency, records scope, optional context, authority review, exact packet approval, mailing, and proof record.`;
  return `import type { WorkflowLandingConfig } from "@mailmypdf/design-system"

export const workflowConfig = {
  id: "${request.workflowId}",
  sectionId: "records-request",
  sectionName: "Records Request",
  sectionPath: "/records-request",
  path: "/records-request/workflows/${request.workflowId}",
  startPath: "/records-request/workflows/${request.workflowId}/start",
  title: "${request.label.replaceAll('"', '\\"')}",
  seoTitle: "${request.label.replaceAll('"', '\\"')} | Records Request | MailMyPDF",
  seoDescription: "${description.replaceAll('"', '\\"')}",
  eyebrow: "Records Request workflow",
  heroTitle: "${request.label.replaceAll('"', '\\"')}",
  heroDescription: "${description.replaceAll('"', '\\"')}",
  indexable: false,
  contentStatus: "scaffold",
} as const satisfies WorkflowLandingConfig

export default workflowConfig
`;
}

function profileFromRequest(
  request: FactoryBuildRequest,
): GeneratedRecordsRequestProfile {
  return Object.freeze({
    workflowId: request.workflowId,
    title: request.label,
    recordsSoughtPlaceholder:
      `Describe the records needed for ${request.label}, including record types, subjects, dates, departments, case or incident references, addresses, and other identifiers that will help the agency locate them.`,
    contextDocumentLabel: "Optional source, notice, case, or agency context document",
    supportingContextLabel: "Supporting request context",
  });
}

function expectedChangedPath(
  request: FactoryBuildRequest,
  path: string,
): boolean {
  const workflowRoot = `records-request/workflows/${request.workflowId}/`;
  const hostRoot =
    `mailmypdf/src/routes/records-request/workflows/${request.workflowId}/`;
  return (
    path.startsWith(workflowRoot) ||
    path.startsWith(hostRoot) ||
    path === GENERATED_PROFILE_SPECS ||
    path === GENERATED_PROFILES ||
    path === "packages/workflows/src/canonical-workflows.json" ||
    path === "mailmypdf/WORKFLOW_INVENTORY.json"
  );
}

async function runCommand(input: {
  cwd: string;
  command: string;
  args: readonly string[];
  id: string;
}): Promise<FactoryBuildCheck> {
  const { execFile } = await import("node:child_process");
  const { promisify } = await import("node:util");
  const run = promisify(execFile);
  const commandText = [input.command, ...input.args].join(" ");
  try {
    const { stdout, stderr } = await run(input.command, [...input.args], {
      cwd: input.cwd,
      maxBuffer: 30 * 1024 * 1024,
      env: process.env,
    });
    const summary = normalizeOutput([stdout, stderr].filter(Boolean).join("\n")) ||
      "Command completed successfully.";
    return Object.freeze({
      id: input.id,
      command: commandText,
      ok: true,
      summary,
    });
  } catch (cause) {
    const error = cause as Error & { stdout?: string; stderr?: string };
    const summary =
      normalizeOutput([error.stdout, error.stderr, error.message].filter(Boolean).join("\n")) ||
      "Command failed.";
    return Object.freeze({
      id: input.id,
      command: commandText,
      ok: false,
      summary,
    });
  }
}

async function git(
  cwd: string,
  args: readonly string[],
): Promise<{ stdout: string; stderr: string }> {
  const { execFile } = await import("node:child_process");
  const { promisify } = await import("node:util");
  const run = promisify(execFile);
  return run("git", [...args], {
    cwd,
    maxBuffer: 20 * 1024 * 1024,
    env: process.env,
  });
}

export async function executePersistentFactoryBuild(input: {
  jobId: string;
  actorId: string;
}): Promise<FactoryJob> {
  const current = await loadPersistentFactoryJob(input.jobId);
  if (!current) throw new Error("Factory job was not found.");
  if (
    current.stage !== "build" ||
    current.status !== "queued" ||
    !current.buildRequest
  ) {
    throw new Error("Factory job is not ready for supervised build execution.");
  }
  const request = current.buildRequest;
  if (request.family !== "records-request") {
    throw new Error(`Factory build family ${request.family} is not supported by this executor.`);
  }

  const started = await startPersistentFactoryBuild({
    jobId: current.id,
    actorId: input.actorId,
  });

  const project = findStudioProject("mailmypdf");
  if (!project) throw new Error("MailMyPDF Studio project is not configured.");

  const fs = await import("node:fs/promises");
  const fsSync = await import("node:fs");
  const path = (await import("node:path")).default;
  const os = await import("node:os");
  const rootDir = await resolveProjectRoot(project);
  const branch =
    `factory/job-${started.id.slice(0, 8)}-${request.workflowId}`;
  let worktree = "";
  let tempRoot = "";

  try {
    await git(rootDir, ["fetch", "origin", project.defaultBranch]);
    const { stdout: baseOut } = await git(rootDir, [
      "rev-parse",
      `origin/${project.defaultBranch}`,
    ]);
    const baseSha = baseOut.trim();
    if (!/^[0-9a-f]{40}$/i.test(baseSha)) {
      throw new Error("Unable to resolve the factory build base commit.");
    }

    const localBranch = await runCommand({
      cwd: rootDir,
      command: "git",
      args: ["show-ref", "--verify", "--quiet", `refs/heads/${branch}`],
      id: "branch-local-availability",
    });
    if (localBranch.ok) {
      throw new Error(`Factory build branch already exists locally: ${branch}`);
    }
    const remoteBranch = await git(rootDir, ["ls-remote", "--heads", "origin", branch]);
    if (remoteBranch.stdout.trim()) {
      throw new Error(`Factory build branch already exists on origin: ${branch}`);
    }

    tempRoot = await fs.mkdtemp(
      path.join(os.tmpdir(), `mailmypdf-factory-${started.id.slice(0, 8)}-`),
    );
    worktree = path.join(tempRoot, "worktree");
    await git(rootDir, [
      "worktree",
      "add",
      "-b",
      branch,
      worktree,
      `origin/${project.defaultBranch}`,
    ]);

    const workflowRoot = path.join(
      worktree,
      "records-request",
      "workflows",
      request.workflowId,
    );
    const configPath = path.join(workflowRoot, "config.ts");
    const specPath = path.join(workflowRoot, "workflow.spec.json");
    if (fsSync.existsSync(configPath) || fsSync.existsSync(specPath)) {
      throw new Error(
        `Workflow ${request.sectionId}/${request.workflowId} already exists on the build base.`,
      );
    }

    const canonical = JSON.parse(
      await fs.readFile(
        path.join(worktree, "packages/workflows/src/canonical-workflows.json"),
        "utf8",
      ),
    ) as Array<{ id?: string }>;
    if (canonical.some((entry) => entry.id === `${request.sectionId}/${request.workflowId}`)) {
      throw new Error(
        `Canonical workflow ${request.sectionId}/${request.workflowId} already exists.`,
      );
    }

    const profileSpecsPath = path.join(worktree, GENERATED_PROFILE_SPECS);
    const existingProfiles = JSON.parse(
      await fs.readFile(profileSpecsPath, "utf8"),
    ) as GeneratedRecordsRequestProfile[];
    if (existingProfiles.some((profile) => profile.workflowId === request.workflowId)) {
      throw new Error(`Generated profile ${request.workflowId} already exists.`);
    }
    const nextProfiles = [...existingProfiles, profileFromRequest(request)].sort(
      (left, right) => left.workflowId.localeCompare(right.workflowId),
    );

    await fs.mkdir(workflowRoot, { recursive: true });
    await fs.writeFile(configPath, renderLandingConfig(request));
    await fs.writeFile(specPath, renderWorkflowSpec(request));
    await fs.writeFile(
      profileSpecsPath,
      JSON.stringify(nextProfiles, null, 2) + "\n",
    );
    await fs.writeFile(
      path.join(worktree, GENERATED_PROFILES),
      renderGeneratedProfiles(nextProfiles),
    );

    const install = await runCommand({
      cwd: worktree,
      command: "pnpm",
      args: ["install", "--frozen-lockfile"],
      id: "install",
    });
    if (!install.ok) {
      throw new Error(`Dependency install failed: ${install.summary}`);
    }

    const specRelative =
      `records-request/workflows/${request.workflowId}/workflow.spec.json`;
    const materialize = await runCommand({
      cwd: worktree,
      command: "pnpm",
      args: [
        "--filter",
        "./mailmypdf",
        "exec",
        "tsx",
        "../scripts/materialize-workflow-spec.ts",
        "--write",
        specRelative,
      ],
      id: "materialize",
    });
    if (!materialize.ok) {
      throw new Error(`Workflow materialization failed: ${materialize.summary}`);
    }

    const { stdout: statusOut } = await git(worktree, ["status", "--porcelain"]);
    const changedFiles = statusOut
      .split("\n")
      .filter(Boolean)
      .map((line) => line.slice(3).trim().replaceAll("\\", "/"));
    if (changedFiles.length === 0) {
      throw new Error("Factory build produced no changed files.");
    }
    const unexpected = changedFiles.filter(
      (changed) => !expectedChangedPath(request, changed),
    );
    if (unexpected.length > 0) {
      throw new Error(
        `Factory build produced unexpected paths: ${unexpected.join(", ")}`,
      );
    }

    await git(worktree, ["add", "--", ...changedFiles]);
    await git(worktree, [
      "-c",
      "user.name=MailMyPDF Factory",
      "-c",
      "user.email=factory@localhost",
      "commit",
      "-m",
      `Factory proposal: ${request.sectionId}/${request.workflowId}`,
    ]);
    const { stdout: commitOut } = await git(worktree, ["rev-parse", "HEAD"]);
    const commitSha = commitOut.trim();

    const artifact: FactoryBuildArtifact = Object.freeze({
      branch,
      baseSha,
      commitSha,
      specPath: specRelative,
      profileRegistryPath: GENERATED_PROFILE_SPECS,
      configPath:
        `records-request/workflows/${request.workflowId}/config.ts`,
      changedFiles: Object.freeze(changedFiles),
      checks: Object.freeze([]),
      builtAt: new Date().toISOString(),
    });
    await recordPersistentFactoryBuildMaterialized({
      jobId: started.id,
      actorId: input.actorId,
      artifact,
    });

    const checks: FactoryBuildCheck[] = [];
    checks.push(
      await runCommand({
        cwd: worktree,
        command: "pnpm",
        args: [
          "--filter",
          "./mailmypdf",
          "exec",
          "tsx",
          "../scripts/materialize-workflow-spec.ts",
          specRelative,
        ],
        id: "materialization-drift",
      }),
    );
    checks.push(
      await runCommand({
        cwd: worktree,
        command: "pnpm",
        args: ["--filter", "@mailmypdf/workflows", "test"],
        id: "workflow-factory-chat",
      }),
    );
    checks.push(
      await runCommand({
        cwd: worktree,
        command: "pnpm",
        args: [
          "--filter",
          "./mailmypdf",
          "exec",
          "tsx",
          "../scripts/verify-factory-workflow.ts",
          `${request.sectionId}/${request.workflowId}`,
        ],
        id: "generated-workflow-certification",
      }),
    );
    checks.push(
      await runCommand({
        cwd: worktree,
        command: "pnpm",
        args: ["--filter", "@mailmypdf/records-request", "test"],
        id: "records-request-tests",
      }),
    );
    checks.push(
      await runCommand({
        cwd: worktree,
        command: "pnpm",
        args: ["--filter", "@mailmypdf/records-request", "test:acceptance"],
        id: "records-request-acceptance",
      }),
    );
    checks.push(
      await runCommand({
        cwd: worktree,
        command: "git",
        args: ["diff", "--exit-code", "HEAD", "--"],
        id: "clean-generated-tree",
      }),
    );

    return await recordPersistentFactoryAcceptance({
      jobId: started.id,
      actorId: input.actorId,
      checks,
    });
  } catch (cause) {
    const message =
      cause instanceof Error ? cause.message : "Factory build execution failed.";
    const latest = await loadPersistentFactoryJob(started.id).catch(() => null);
    if (latest?.stage === "build" && latest.status === "running") {
      await failPersistentFactoryBuild({
        jobId: started.id,
        actorId: input.actorId,
        code: "FACTORY_BUILD_FAILED",
        message,
      }).catch(() => undefined);
    } else if (latest?.stage === "acceptance" && latest.status === "running") {
      await recordPersistentFactoryAcceptance({
        jobId: started.id,
        actorId: input.actorId,
        checks: [
          {
            id: "executor",
            command: "factory-build-executor",
            ok: false,
            summary: message,
          },
        ],
      }).catch(() => undefined);
    }
    throw new Error(message);
  } finally {
    if (worktree) {
      await git(rootDir, ["worktree", "remove", "--force", worktree]).catch(
        () => undefined,
      );
    }
    if (tempRoot) {
      await fs.rm(tempRoot, { recursive: true, force: true }).catch(() => undefined);
    }
  }
}
