// @generated by MailMyPDF workflow materializer. Edit workflow.spec.json or config.ts instead.
import { createFileRoute } from "@tanstack/react-router"
import NoticeResponseWorkflow from "../../../../../../../notice-respond/shared/NoticeResponseWorkflow"
import { getNoticeResponseFactoryArtifact } from "@mailmypdf/workflows"

const resolvedFactoryArtifact = getNoticeResponseFactoryArtifact("cp2000-response")

if (!resolvedFactoryArtifact) {
  throw new Error("cp2000-response factory artifact is missing")
}
if (!resolvedFactoryArtifact.factoryReady) {
  throw new Error("cp2000-response factory artifact is not ready")
}

const factoryArtifact = resolvedFactoryArtifact

export function Cp2000ResponseStart() {
  return <NoticeResponseWorkflow config={factoryArtifact.startConfig} />
}

export const Route = createFileRoute(
  "/notice-respond/workflows/cp2000-response/start/",
)({
  component: Cp2000ResponseStart,
})

export default Cp2000ResponseStart
