import { createFileRoute, Link } from '@tanstack/react-router'
import { createElement } from 'react'
import { FileText, ShieldCheck, Search, Mail, ArrowRight } from 'lucide-react'
import { INSURANCE_WORKFLOWS } from '@/domain/insurance-workflows'
import { createTrustStrip, createVerticalHero } from '../../../../../packages/design-system/src/index'
import { PublicFooter, PublicHeader } from '../components/public-chrome'

const VerticalHero=createVerticalHero(createElement)
const TrustStrip=createTrustStrip(createElement)
export const Route=createFileRoute('/')({component:Home})
function Home(){const featured=INSURANCE_WORKFLOWS.filter((w,i,a)=>a.findIndex(x=>x.family===w.family)===i).slice(0,6);return <main><PublicHeader/>
<VerticalHero theme='insurance-claims' tone='light' eyebrow='Insurance Claims · Build the record' title='Build the claim record. Challenge the denial.' description='Choose a focused workflow for a new claim, denied claim, property loss, coverage dispute, health or disability appeal, or specialized insurance matter. Organize the evidence, review the response, and keep mailing and proof connected.' imageSrc='/hero-bg.png' imageAlt='Insurance claim documents and property-loss records' actions={<><Link to='/workflows' className='mmp-button-primary'>Find My Claim Workflow <ArrowRight size={16}/></Link><a href='/' className='mmp-button-secondary'>Mail a PDF</a></>} meta={<><span>Problem-specific claim workflows</span><span>Review before mailing</span><span>Tracking & proof options</span></>}/>
<TrustStrip items={[{icon:<FileText size={16}/>,title:'Claim-specific guidance',description:'Start from the claim or denial in front of you'},{icon:<Search size={16}/>,title:'Evidence organized',description:'Keep policy, loss, and correspondence records together'},{icon:<ShieldCheck size={16}/>,title:'Human review required',description:'Consequential responses require your review'},{icon:<Mail size={16}/>,title:'Mailing & proof options',description:'Available through MailMyPDF'}]}/>
<section className='mmp-section'><div className='mmp-section__inner'><div className='mmp-section-heading'><div><div className='mmp-directory__eyebrow'>Claim families</div><h2>Start with the insurance problem you actually have.</h2></div><p>The catalog separates new claims, denials, property damage, disputes and appeals, health and disability matters, and specialized claims so the workflow can stay specific.</p></div><div className='mmp-workflow-grid'>{featured.map(w=><article className='mmp-workflow-card' key={w.id}><div className='mmp-workflow-card__body'><div className='mmp-directory__eyebrow'>{w.family}</div><h3>{w.name}</h3><p>{w.description}</p><Link className='mmp-workflow-card__action' to='/workflows/$workflowId' params={{workflowId:w.id}}>View workflow →</Link></div></article>)}</div><div style={{marginTop:28}}><Link to='/workflows' className='mmp-button-primary'>Browse all {INSURANCE_WORKFLOWS.length} workflows →</Link></div></div></section>
<section id='how' className='mmp-section mmp-section--tight' style={{background:'var(--mmp-paper-deep)'}}><div className='mmp-section__inner'><div className='mmp-section-heading'><div><div className='mmp-directory__eyebrow'>How it works</div><h2>From claim document to reviewable response.</h2></div><p>The workflow keeps the policy or denial, facts, evidence, draft, approval, mailing, and proof stages connected.</p></div><div className='mmp-process-grid'>{[['1','Choose the workflow','Match the claim, denial, loss, or appeal to the right workflow.'],['2','Add the record','Upload the policy, notice, photos, estimates, and correspondence that matter.'],['3','Organize issues','Separate insurer statements, policy text, user facts, and evidence.'],['4','Review & approve','Check every material assertion and the exact outgoing packet.'],['5','Send & retain proof','Download it or choose MailMyPDF mailing, tracking, and proof options.']].map(([n,t,d])=><div className='mmp-process-step' key={n}><span className='mmp-process-step__number'>{n}</span><h3>{t}</h3><p>{d}</p></div>)}</div></div></section>
<section className='mmp-section'><div className='mmp-section__inner'><div className='mmp-final-cta'><div className='mmp-final-cta__inner'><div><h2>Keep the claim, evidence, response, and proof together.</h2><p>Choose the workflow matched to your insurance matter and move into the protected workspace when you're ready to prepare the response.</p></div><Link to='/workflows' className='mmp-button-primary'>Find My Workflow →</Link></div></div></div></section><PublicFooter/></main>}
