import { createFileRoute } from '@tanstack/react-router'
import { createElement } from 'react'
import { recordsWorkflows } from '../workflows'
import { createWorkflowDirectory } from '../../../../../packages/design-system/src/index'
import { PublicFooter, PublicHeader } from '../components/public-chrome'

const WorkflowDirectory=createWorkflowDirectory(createElement)
const categoryFor=(id:string)=> id.includes('police')||id.includes('criminal')||id.includes('arrest')||id.includes('background')||id.includes('court')?'Law Enforcement & Courts':id.includes('property')||id.includes('permit')||id.includes('planning')||id.includes('code-enforcement')?'Property & Development':id.includes('birth')||id.includes('marriage')||id.includes('divorce')||id.includes('death')?'Vital Records':id.includes('military')||id.includes('medical')||id.includes('employment')||id.includes('education')?'Personal Records':id.includes('follow-up')||id.includes('denial')?'Follow-up & Appeals':id.includes('communications')||id.includes('case-records')?'Communications & Cases':'General Public Records'
const categories=['General Public Records','Law Enforcement & Courts','Property & Development','Vital Records','Personal Records','Communications & Cases','Follow-up & Appeals']
export const Route=createFileRoute('/workflows')({component:Workflows,head:()=>({meta:[{title:'Public Records Request Workflows | MailMyPDF'},{name:'description',content:'Browse records-request workflows for FOIA, police and court records, property and permit records, vital records, personal records, government communications, follow-up, and denial appeals.'},{name:'robots',content:'index,follow'}]})})
function Workflows(){const items=recordsWorkflows.map(w=>({id:w.id,title:w.name,category:categoryFor(w.id),description:w.description,href:`/workflows/${w.id}`,eyebrow:w.searchIntent,meta:w.capabilities.join(' · '),keywords:[w.searchIntent,...w.request.categories]}));return <main><PublicHeader/><WorkflowDirectory productName='Records Requests' title='Find the records request workflow for the information you need.' description='Start from the records objective, agency, or record family. Browse the real catalog instead of forcing every request into one generic public-records form.' items={items} categories={categories.map(category=>({id:category,label:category}))} searchPlaceholder='Search FOIA, police report, court, property, permits, vital records, communications…' helperTitle='Not sure which records request fits?' helperDescription='Start with who likely holds the records and what information you are trying to obtain. The directory separates broad public-records requests from specialized record families and follow-up actions.' helperHref='/workflows' helperLabel='Browse All Records' steps={[
{title:'Choose the records objective',description:'Match the agency and type of record to the most focused request workflow.'},
{title:'Describe the request',description:'Organize the subject, date range, record categories, agency details, and any supporting context.'},
{title:'Review the exact request',description:'Check scope, facts, recipient, and attachments before authorizing delivery.'},
{title:'Send, track & follow up',description:'Download the request or use MailMyPDF delivery and keep the response/follow-up record connected.'},
]} finalTitle='Ask for the right records, with a record of the request.' finalDescription='Choose the workflow that matches the information you need and keep the request, agency response, follow-up, mailing, and proof together.' finalHref='/workflows' finalLabel='Choose a Records Workflow'/><PublicFooter/></main>}
