// @generated by MailMyPDF workflow materializer. Edit workflow.spec.json or config.ts instead.
import { createWorkflowSchema } from "@mailmypdf/seo"
import workflowConfig from "./config"

export const workflowSchema = createWorkflowSchema(workflowConfig)
export default workflowSchema
