import { createFileRoute } from "@tanstack/react-router";
import { requireAuthenticatedUser, getSupabaseServer } from "@/platform/supabase";
import { getWorkflow } from "@/domain/workflows";
import { validateAppealDraft } from "@/domain/draft-validator";
import { callAIText, resolveAI } from "@/platform/control-plane-ai";

export const Route = createFileRoute("/api/workflows/dental-insurance-appeal/draft")({ server: { handlers: { POST: async ({ request }) => { try {
  const user = await requireAuthenticatedUser(request); const input = await request.json() as { appealId?: string; analysis?: unknown; draftOverride?: string }; if (!input.appealId?.trim()) return Response.json({ error: "Appeal id is required." }, { status: 400 }); const supabase = await getSupabaseServer(); const { data: appeal, error } = await supabase.from("appeals").select("*").eq("id", input.appealId).single(); if (error || !appeal) return Response.json({ error: "Appeal case not found." }, { status: 404 }); if (appeal.user_id !== user.id) return Response.json({ error: "You do not own this appeal case." }, { status: 403 }); if (appeal.workflow_id !== "dental-insurance-appeal") return Response.json({ error: "Appeal workflow mismatch." }, { status: 409 });
  const workflow = getWorkflow("dental-insurance-appeal"); const draftConfig = await resolveAI("dental-insurance-appeal", "draft"); const validationConfig = await resolveAI("dental-insurance-appeal", "validation"); const analysis = input.analysis || appeal.decision; const draft = input.draftOverride?.trim() || await callAIText(draftConfig, "Write a professional dental insurance appeal for human review. Use only supplied facts and preserve uncertainty.", draftConfig.promptOverride || [`Create a response for ${workflow.title}.`, workflow.workflowPrompt, `Focus on: ${workflow.focusAreas.join(", ")}.`, "Do not invent dental findings, coverage language, legal authority, dates, deadlines, or outcomes.", `CASE ANALYSIS:\n${JSON.stringify(analysis)}`].join("\n\n")); const validation = await callAIText(validationConfig, "Return strict JSON. Flag unsupported dental or clinical claims, invented policy or legal authority, missing documentation, contradictions, deadline problems, and uncertainty.", validationConfig.promptOverride || [`Audit this ${workflow.title} draft.`, "Return JSON with valid, issues, unsupportedClaims, missingEvidence, suggestions.", `CASE ANALYSIS:\n${JSON.stringify(analysis)}`, `DRAFT:\n${draft}`].join("\n\n"), true);
  const draftValidation = validateAppealDraft(draft, appeal.decision || {}, Array.isArray(appeal.grounds) ? appeal.grounds : [], Array.isArray(appeal.evidence) ? appeal.evidence : []); const blockingFindings = draftValidation.findings.filter((f: any) => (f.severity === "block" || f.severity === "error") && !f.passed); if (blockingFindings.length) return Response.json({ error: "Draft failed validation.", draftValidation, blockingFindings }, { status: 422 }); const persisted = `${draft}\n\nSincerely,\n[Your Name]`; const currentVersion = appeal.version ?? 1; const { error: updateError } = await supabase.from("appeals").update({ draft: persisted, status: "in_progress", version: currentVersion + 1, updated_at: new Date().toISOString() }).eq("id", appeal.id).eq("user_id", user.id).eq("version", currentVersion); if (updateError) throw new Error(`Unable to persist draft: ${updateError.message}`);
  return Response.json({ ok: true, appealId: appeal.id, draft: persisted, validation, draftValidation, provider: draftConfig.provider, draftModel: draftConfig.model, validationModel: validationConfig.model });
} catch (error) { const message = error instanceof Error ? error.message : "Unable to create dental insurance appeal response."; return Response.json({ error: message }, { status: /authentication|required|token/i.test(message) ? 401 : 502 }); } } } } });
