import type {
  WorkflowExecutionBinding,
  WorkflowSeed,
} from "./canonical-workflow-registry.js";

export const WORKFLOW_MATERIALIZATION_SPEC_VERSION =
  "mailmypdf.workflow-materialization/v1" as const;

export type WorkflowStartTemplate = "notice-response" | "records-request";

export type WorkflowMaterializationSpec = Readonly<{
  schemaVersion: typeof WORKFLOW_MATERIALIZATION_SPEC_VERSION;
  id: string;
  label: string;
  execution?: WorkflowExecutionBinding;
  authority?: WorkflowSeed["authority"];
  legacyGoldId?: string;
  startTemplate?: WorkflowStartTemplate;
}>;

export type MaterializedWorkflowFile = Readonly<{
  path: string;
  content: string;
}>;

export type WorkflowMaterializationPlan = Readonly<{
  spec: WorkflowMaterializationSpec;
  sectionId: string;
  slug: string;
  canonicalSeed: WorkflowSeed;
  files: readonly MaterializedWorkflowFile[];
}>;

const WORKFLOW_ID =
  /^[a-z0-9]+(?:-[a-z0-9]+)*\/[a-z0-9]+(?:-[a-z0-9]+)*$/;

const GENERATED =
  "// @generated by MailMyPDF workflow materializer. Edit workflow.spec.json or config.ts instead.\n";

function assertMaterializationSpec(
  spec: WorkflowMaterializationSpec,
): void {
  if (spec.schemaVersion !== WORKFLOW_MATERIALIZATION_SPEC_VERSION) {
    throw new Error(
      `Unsupported workflow materialization schema: ${spec.schemaVersion}`,
    );
  }
  if (!WORKFLOW_ID.test(spec.id)) {
    throw new Error(`Invalid workflow materialization id: ${spec.id}`);
  }
  if (!spec.label.trim()) {
    throw new Error(`Workflow materialization ${spec.id} requires a label.`);
  }

  const [sectionId] = spec.id.split("/");
  if (spec.execution && !spec.startTemplate) {
    throw new Error(
      `Executable workflow ${spec.id} requires a startTemplate.`,
    );
  }
  if (!spec.execution && spec.startTemplate) {
    throw new Error(
      `Non-executable workflow ${spec.id} cannot declare a startTemplate.`,
    );
  }

  if (spec.startTemplate === "notice-response") {
    if (sectionId !== "notice-respond") {
      throw new Error(
        `notice-response startTemplate requires notice-respond, got ${sectionId}.`,
      );
    }
    if (
      spec.execution?.kind !== "platform" ||
      spec.execution.policyFamily !== "notice-response"
    ) {
      throw new Error(
        `notice-response startTemplate requires the notice-response platform policy.`,
      );
    }
  }
  if (spec.startTemplate === "records-request") {
    if (sectionId !== "records-request") {
      throw new Error(
        `records-request startTemplate requires records-request, got ${sectionId}.`,
      );
    }
    if (
      spec.execution?.kind !== "platform" ||
      spec.execution.policyFamily !== "records-request"
    ) {
      throw new Error(
        `records-request startTemplate requires the records-request platform policy.`,
      );
    }
  }
}

function pascal(value: string): string {
  return value
    .split("-")
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
}

function renderTopLevelLanding(sectionId: string, slug: string): string {
  return `${GENERATED}import { createFileRoute } from "@tanstack/react-router"
import { WorkflowLandingPage } from "@mailmypdf/design-system"
import workflowConfig from "./config"
import workflowSeo from "./seo"
import workflowSchema from "./schema"

export const Route = createFileRoute("/${sectionId}/workflows/${slug}/")({
  head: () => ({
    ...workflowSeo,
    scripts: workflowSchema.map((schema) => ({
      type: "application/ld+json",
      children: JSON.stringify(schema),
    })),
  }),
  component: () => <WorkflowLandingPage config={workflowConfig} />,
})
`;
}

function renderSeo(): string {
  return `${GENERATED}import { createWorkflowHead } from "@mailmypdf/seo"
import workflowConfig from "./config"

export const workflowSeo = createWorkflowHead(workflowConfig)
export default workflowSeo
`;
}

function renderSchema(): string {
  return `${GENERATED}import { createWorkflowSchema } from "@mailmypdf/seo"
import workflowConfig from "./config"

export const workflowSchema = createWorkflowSchema(workflowConfig)
export default workflowSchema
`;
}

function renderHostLanding(sectionId: string, slug: string): string {
  return `${GENERATED}import { createFileRoute } from "@tanstack/react-router"
import { WorkflowLandingPage } from "@mailmypdf/design-system"
import workflowConfig from "../../../../../../${sectionId}/workflows/${slug}/config"
import workflowSeo from "../../../../../../${sectionId}/workflows/${slug}/seo"
import workflowSchema from "../../../../../../${sectionId}/workflows/${slug}/schema"

export const Route = createFileRoute("/${sectionId}/workflows/${slug}/")({
  head: () => ({
    ...workflowSeo,
    scripts: workflowSchema.map((schema) => ({
      type: "application/ld+json",
      children: JSON.stringify(schema),
    })),
  }),
  component: () => <WorkflowLandingPage config={workflowConfig} />,
})
`;
}

function renderNoticeResponseStart(input: {
  sectionId: string;
  slug: string;
  sharedImport: string;
}): string {
  const component = `${pascal(input.slug)}Start`;
  return `${GENERATED}import { createFileRoute } from "@tanstack/react-router"
import NoticeResponseWorkflow from "${input.sharedImport}"
import { getNoticeResponseFactoryArtifact } from "@mailmypdf/workflows"

const resolvedFactoryArtifact = getNoticeResponseFactoryArtifact("${input.slug}")

if (!resolvedFactoryArtifact) {
  throw new Error("${input.slug} factory artifact is missing")
}
if (!resolvedFactoryArtifact.factoryReady) {
  throw new Error("${input.slug} factory artifact is not ready")
}

const factoryArtifact = resolvedFactoryArtifact

export function ${component}() {
  return <NoticeResponseWorkflow config={factoryArtifact.startConfig} />
}

export const Route = createFileRoute(
  "/${input.sectionId}/workflows/${input.slug}/start/",
)({
  component: ${component},
})

export default ${component}
`;
}

function renderRecordsRequestStart(input: {
  sectionId: string;
  slug: string;
  sharedImport: string;
}): string {
  const component = `${pascal(input.slug)}Start`;
  return `${GENERATED}import { createFileRoute } from "@tanstack/react-router"
import RecordsRequestWorkflow from "${input.sharedImport}"
import { getRecordsRequestFactoryArtifact } from "@mailmypdf/workflows"

const resolvedFactoryArtifact = getRecordsRequestFactoryArtifact("${input.slug}")

if (!resolvedFactoryArtifact) {
  throw new Error("${input.slug} factory artifact is missing")
}
if (!resolvedFactoryArtifact.factoryReady) {
  throw new Error("${input.slug} factory artifact is not ready")
}

const factoryArtifact = resolvedFactoryArtifact

export function ${component}() {
  return <RecordsRequestWorkflow config={factoryArtifact.startConfig} />
}

export const Route = createFileRoute(
  "/${input.sectionId}/workflows/${input.slug}/start/",
)({
  component: ${component},
})

export default ${component}
`;
}

function renderStart(
  spec: WorkflowMaterializationSpec,
  sectionId: string,
  slug: string,
  surface: "top-level" | "host",
): string {
  switch (spec.startTemplate) {
    case "notice-response":
      return renderNoticeResponseStart({
        sectionId,
        slug,
        sharedImport:
          surface === "top-level"
            ? "../../../shared/NoticeResponseWorkflow"
            : "../../../../../../../notice-respond/shared/NoticeResponseWorkflow",
      });
    case "records-request":
      return renderRecordsRequestStart({
        sectionId,
        slug,
        sharedImport:
          surface === "top-level"
            ? "../../../shared/RecordsRequestWorkflow"
            : "../../../../../../../records-request/shared/RecordsRequestWorkflow",
      });
    default:
      throw new Error(
        `No start-route materializer for ${String(spec.startTemplate)}.`,
      );
  }
}

export function canonicalSeedFromMaterializationSpec(
  spec: WorkflowMaterializationSpec,
): WorkflowSeed {
  assertMaterializationSpec(spec);
  return Object.freeze({
    id: spec.id,
    label: spec.label,
    ...(spec.execution ? { execution: Object.freeze({ ...spec.execution }) } : {}),
    ...(spec.authority ? { authority: Object.freeze({ ...spec.authority }) } : {}),
    ...(spec.legacyGoldId ? { legacyGoldId: spec.legacyGoldId } : {}),
  });
}

/**
 * Produce deterministic filesystem and canonical-registry outputs from one
 * reviewed workflow spec. Substantive public copy remains in config.ts and is
 * intentionally not generated here.
 */
export function buildWorkflowMaterializationPlan(
  spec: WorkflowMaterializationSpec,
): WorkflowMaterializationPlan {
  assertMaterializationSpec(spec);
  const [sectionId, slug] = spec.id.split("/") as [string, string];
  const workflowRoot = `${sectionId}/workflows/${slug}`;
  const hostRoot = `mailmypdf/src/routes/${sectionId}/workflows/${slug}`;

  const files: MaterializedWorkflowFile[] = [
    {
      path: `${workflowRoot}/index.tsx`,
      content: renderTopLevelLanding(sectionId, slug),
    },
    { path: `${workflowRoot}/seo.ts`, content: renderSeo() },
    { path: `${workflowRoot}/schema.ts`, content: renderSchema() },
    {
      path: `${hostRoot}/index.tsx`,
      content: renderHostLanding(sectionId, slug),
    },
  ];

  if (spec.execution) {
    files.push(
      {
        path: `${workflowRoot}/start/index.tsx`,
        content: renderStart(spec, sectionId, slug, "top-level"),
      },
      {
        path: `${hostRoot}/start/index.tsx`,
        content: renderStart(spec, sectionId, slug, "host"),
      },
    );
  }

  return Object.freeze({
    spec,
    sectionId,
    slug,
    canonicalSeed: canonicalSeedFromMaterializationSpec(spec),
    files: Object.freeze(files),
  });
}

export function isMaterializerOwnedFile(content: string): boolean {
  return content.startsWith(GENERATED);
}
