// @generated by MailMyPDF workflow materializer. Edit workflow.spec.json or config.ts instead.
import { createFileRoute } from "@tanstack/react-router"
import { WorkflowLandingPage } from "@mailmypdf/design-system"
import workflowConfig from "../../../../../../records-request/workflows/public-records-request/config"
import workflowSeo from "../../../../../../records-request/workflows/public-records-request/seo"
import workflowSchema from "../../../../../../records-request/workflows/public-records-request/schema"

export const Route = createFileRoute("/records-request/workflows/public-records-request/")({
  head: () => ({
    ...workflowSeo,
    scripts: workflowSchema.map((schema) => ({
      type: "application/ld+json",
      children: JSON.stringify(schema),
    })),
  }),
  component: () => <WorkflowLandingPage config={workflowConfig} />,
})
