import { defineWorkflow } from "@mailmypdf/workflows";

export const immigrationFilingCoverLetterManifest = defineWorkflow({
  id: "immigration-filing-cover-letter",
  vertical: "immigration-mail",
  title: "Immigration Filing Cover Letter",
  route: "/immigration-mail/workflows/immigration-filing-cover-letter/start",
  pipeline: "P02_OFFICIAL_RESPONSE",
  adapters: ["government", "immigration"],
  requiredCapabilities: [
    "identity", "matterState", "security", "secureUpload", "documentStorage",
    "documentScanning", "retention", "classification", "extraction", "visionAnalysis",
    "aiExecution", "understand", "facts", "provenance", "findings", "requirements",
    "evidence", "draft", "draftProvenance", "validation", "blockingGate", "humanReview",
    "approval", "pdfGeneration", "packetAssembly", "pricing", "payment", "addressVerification",
    "mailing", "tracking", "notifications", "proofAudit", "archive", "resilience",
    "observability", "acceptanceTesting",
  ],
  optionalCapabilities: ["deadlines", "research", "risk"],
  notApplicableCapabilities: ["strategy"],
  maturity: "executable",
  primaryInput: "document",
  requiresHumanReview: true,
  allowsConsequentialAction: true,
  version: 1,
  steps: [
    {
      id: "filing",
      title: "Primary filing document",
      description: "Securely upload the application, petition, form, or USCIS document the cover letter will accompany.",
      uses: ["secureUpload", "documentStorage", "documentScanning", "classification", "extraction", "visionAnalysis", "understand", "provenance"],
      completeWhen: ["primary_document_clean", "primary_document_understood"],
    },
    {
      id: "analysis",
      title: "Filing details",
      description: "Extract candidate filing type, identifiers, dates, and mailing-destination clues for user review.",
      uses: ["findings", "requirements", "facts", "provenance"],
      requires: ["primary_document_clean"],
      completeWhen: ["filing_details_extracted"],
    },
    {
      id: "facts",
      title: "Confirm filing details",
      description: "Store user-confirmed filing details separately from extracted document facts.",
      uses: ["matterState", "facts"],
      requires: ["filing_details_extracted"],
      completeWhen: ["filing_details_confirmed"],
    },
    {
      id: "documents",
      title: "Packet documents",
      description: "Upload, scan, categorize, and explicitly select documents for the filing packet.",
      uses: ["secureUpload", "documentStorage", "documentScanning", "evidence", "provenance"],
      completeWhen: ["packet_documents_reviewed"],
    },
    {
      id: "draft",
      title: "Filing cover letter",
      description: "Generate a concise cover letter constrained to user-confirmed filing details and selected packet documents.",
      uses: ["draft", "draftProvenance", "validation"],
      requires: ["filing_details_confirmed"],
      completeWhen: ["draft_validated", "no_unresolved_placeholders"],
    },
    {
      id: "review",
      title: "Packet review",
      description: "Build the exact mail-ready packet, calculate server-authoritative pricing, and require explicit review.",
      uses: ["pdfGeneration", "packetAssembly", "pricing", "addressVerification", "blockingGate", "humanReview", "approval"],
      requires: ["draft_validated"],
      completeWhen: ["exact_packet_approved"],
    },
    {
      id: "mail",
      title: "Payment, mailing, tracking, and proof",
      description: "Pay for and submit only the exact approved packet, then retain tracking and proof.",
      uses: ["payment", "mailing", "tracking", "notifications", "proofAudit", "archive"],
      requires: ["exact_packet_approved"],
      completeWhen: ["mailing_submitted", "proof_recorded"],
    },
  ],
  documents: [
    {
      id: "primary-filing-document",
      label: "Primary filing document",
      role: "primary",
      required: true,
      acceptedKinds: ["application/pdf", "image/png", "image/jpeg", "image/tiff"],
      extractionSchema: "immigration-filing-document-v1",
    },
    {
      id: "packet-documents",
      label: "Supporting packet documents",
      role: "evidence",
      required: false,
      acceptedKinds: ["application/pdf", "image/png", "image/jpeg", "image/tiff"],
    },
  ],
  gates: [
    { id: "primary-document-ready", kind: "document_ready", label: "Primary filing document is clean and usable", required: true },
    { id: "facts-confirmed", kind: "fact_confirmation", label: "User confirms material filing details", required: true },
    { id: "exact-packet-review", kind: "human_review", label: "User reviewed the exact filing packet and destination", beforeCapability: "approval", required: true },
    { id: "mailing-authorization", kind: "mailing_authorization", label: "User authorizes mailing of the approved packet", beforeCapability: "mailing", required: true },
  ],
  outputs: [
    { id: "cover-letter", kind: "draft", required: true },
    { id: "cover-letter-pdf", kind: "pdf", required: true },
    { id: "mail-packet", kind: "packet", required: true },
    { id: "payment-receipt", kind: "receipt", required: true },
    { id: "tracking", kind: "tracking", required: true },
    { id: "mailing-proof", kind: "proof", required: true },
    { id: "matter-archive", kind: "archive", required: true },
  ],
  acceptanceScenarios: [
    { id: "standard-filing-cover-letter", description: "Primary filing document, confirmed details, supporting documents, cover letter, exact packet, payment, mailing, and proof.", required: true },
    { id: "quarantined-document", description: "Unscanned primary or supporting document blocks downstream use.", required: true },
    { id: "packet-tamper", description: "A packet changed after approval must fail closed.", required: true },
    { id: "payment-mail-idempotency", description: "Repeated payment/provider events must not create duplicate mail.", required: true },
  ],
} as const);

export default immigrationFilingCoverLetterManifest;
