// @generated by the supervised workflow factory build executor.
// This file is machine-owned. Do not hand-edit generated profiles.

import type { SsaReconsiderationWorkflowProfile } from "./ssa-reconsideration-profiles.js";

export const GENERATED_SSA_RECONSIDERATION_WORKFLOW_PROFILES = Object.freeze(
  [] as const satisfies readonly SsaReconsiderationWorkflowProfile[],
);
