import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import test from "node:test";

const repoRoot = path.resolve(import.meta.dirname, "../..");

function read(relative: string) {
  return fs.readFileSync(path.join(repoRoot, relative), "utf8");
}

test("SSDI and SSI start routes are materializer-owned mounts of one shared SSA shell", () => {
  const ssdi = read("appeal-mail/workflows/appeal-ssdi-denial/start/index.tsx");
  const ssi = read("appeal-mail/workflows/appeal-ssi-denial/start/index.tsx");
  const shell = read("appeal-mail/workflows/ssa-reconsideration/start/index.tsx");

  assert.match(ssdi, /@generated by MailMyPDF workflow materializer/);
  assert.match(ssi, /@generated by MailMyPDF workflow materializer/);
  assert.match(ssdi, /getSsaReconsiderationFactoryArtifact\("appeal-ssdi-denial"\)/);
  assert.match(ssi, /getSsaReconsiderationFactoryArtifact\("appeal-ssi-denial"\)/);
  assert.match(ssdi, /SsaReconsiderationStartShell/);
  assert.match(ssi, /SsaReconsiderationStartShell/);

  assert.match(shell, /getSsaReconsiderationFactoryArtifact\(workflowId\)/);
  assert.match(shell, /const \{ startConfig \} = artifact/);
  assert.match(shell, /title=\{startConfig\.title\}/);
  assert.match(shell, /subtitle=\{startConfig\.subtitle\}/);
  assert.match(shell, /href: startConfig\.backHref/);
});

test("shared SSA shell preserves SSDI work facts and SSI eligibility facts", () => {
  const shell = read("appeal-mail/workflows/ssa-reconsideration/start/index.tsx");
  const workflow = read("appeal-mail/workflows/ssa-reconsideration/start/workflow.ts");

  assert.match(shell, /program === "SSDI"/);
  assert.match(shell, /Work changes/);
  assert.match(shell, /facts\.workChanges/);

  assert.match(shell, /program === "SSI" && decisionBasis === "nonmedical"/);
  assert.match(shell, /facts\.incomeFacts/);
  assert.match(shell, /facts\.resourceFacts/);
  assert.match(shell, /facts\.livingArrangementFacts/);
  assert.match(shell, /facts\.eligibilityFacts/);

  assert.match(workflow, /work_history/);
  assert.match(workflow, /income_resources/);
  assert.match(workflow, /living_arrangement/);
  assert.match(workflow, /identity_eligibility/);
  assert.match(workflow, /medical-reconsideration/);
  assert.match(workflow, /nonmedical-reconsideration/);
});

test("both SSA workflows use the canonical shared browser runtime surface", () => {
  const ssdiRuntime = read("appeal-mail/workflows/appeal-ssdi-denial/start/runtime-client.ts");
  const ssiRuntime = read("appeal-mail/workflows/appeal-ssi-denial/start/runtime-client.ts");

  assert.equal(ssdiRuntime, ssiRuntime);
  assert.match(ssdiRuntime, /from "@mailmypdf\/workflows"/);
  assert.doesNotMatch(ssdiRuntime, /createHttpWorkflowMatterClient/);
});
