/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as WorkflowsRouteImport } from './routes/workflows'
import { Route as WorkflowsWorkflowIdRouteImport } from './routes/workflows/$workflowId'
import { Route as WorkflowsWorkflowIdStartRouteImport } from './routes/workflows/$workflowId/start'
import { Route as ApiWorkflowsWorkflowIdAnalyzeRouteImport } from './routes/api/workflows/$workflowId/analyze'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsRoute = WorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsWorkflowIdRoute = WorkflowsWorkflowIdRouteImport.update({
  id: '/$workflowId',
  path: '/$workflowId',
  getParentRoute: () => WorkflowsRoute,
} as any)
const WorkflowsWorkflowIdStartRoute =
  WorkflowsWorkflowIdStartRouteImport.update({
    id: '/start',
    path: '/start',
    getParentRoute: () => WorkflowsWorkflowIdRoute,
  } as any)
const ApiWorkflowsWorkflowIdAnalyzeRoute =
  ApiWorkflowsWorkflowIdAnalyzeRouteImport.update({
    id: '/api/workflows/$workflowId/analyze',
    path: '/api/workflows/$workflowId/analyze',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/workflows': typeof WorkflowsRouteWithChildren
  '/workflows/$workflowId': typeof WorkflowsWorkflowIdRouteWithChildren
  '/workflows/$workflowId/start': typeof WorkflowsWorkflowIdStartRoute
  '/api/workflows/$workflowId/analyze': typeof ApiWorkflowsWorkflowIdAnalyzeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/workflows': typeof WorkflowsRouteWithChildren
  '/workflows/$workflowId': typeof WorkflowsWorkflowIdRouteWithChildren
  '/workflows/$workflowId/start': typeof WorkflowsWorkflowIdStartRoute
  '/api/workflows/$workflowId/analyze': typeof ApiWorkflowsWorkflowIdAnalyzeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/workflows': typeof WorkflowsRouteWithChildren
  '/workflows/$workflowId': typeof WorkflowsWorkflowIdRouteWithChildren
  '/workflows/$workflowId/start': typeof WorkflowsWorkflowIdStartRoute
  '/api/workflows/$workflowId/analyze': typeof ApiWorkflowsWorkflowIdAnalyzeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/workflows'
    | '/workflows/$workflowId'
    | '/workflows/$workflowId/start'
    | '/api/workflows/$workflowId/analyze'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/workflows'
    | '/workflows/$workflowId'
    | '/workflows/$workflowId/start'
    | '/api/workflows/$workflowId/analyze'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/workflows'
    | '/workflows/$workflowId'
    | '/workflows/$workflowId/start'
    | '/api/workflows/$workflowId/analyze'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  WorkflowsRoute: typeof WorkflowsRouteWithChildren
  ApiWorkflowsWorkflowIdAnalyzeRoute: typeof ApiWorkflowsWorkflowIdAnalyzeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows': {
      id: '/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/$workflowId': {
      id: '/workflows/$workflowId'
      path: '/$workflowId'
      fullPath: '/workflows/$workflowId'
      preLoaderRoute: typeof WorkflowsWorkflowIdRouteImport
      parentRoute: typeof WorkflowsRoute
    }
    '/workflows/$workflowId/start': {
      id: '/workflows/$workflowId/start'
      path: '/start'
      fullPath: '/workflows/$workflowId/start'
      preLoaderRoute: typeof WorkflowsWorkflowIdStartRouteImport
      parentRoute: typeof WorkflowsWorkflowIdRoute
    }
    '/api/workflows/$workflowId/analyze': {
      id: '/api/workflows/$workflowId/analyze'
      path: '/api/workflows/$workflowId/analyze'
      fullPath: '/api/workflows/$workflowId/analyze'
      preLoaderRoute: typeof ApiWorkflowsWorkflowIdAnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface WorkflowsWorkflowIdRouteChildren {
  WorkflowsWorkflowIdStartRoute: typeof WorkflowsWorkflowIdStartRoute
}

const WorkflowsWorkflowIdRouteChildren: WorkflowsWorkflowIdRouteChildren = {
  WorkflowsWorkflowIdStartRoute: WorkflowsWorkflowIdStartRoute,
}

const WorkflowsWorkflowIdRouteWithChildren =
  WorkflowsWorkflowIdRoute._addFileChildren(WorkflowsWorkflowIdRouteChildren)

interface WorkflowsRouteChildren {
  WorkflowsWorkflowIdRoute: typeof WorkflowsWorkflowIdRouteWithChildren
}

const WorkflowsRouteChildren: WorkflowsRouteChildren = {
  WorkflowsWorkflowIdRoute: WorkflowsWorkflowIdRouteWithChildren,
}

const WorkflowsRouteWithChildren = WorkflowsRoute._addFileChildren(
  WorkflowsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  WorkflowsRoute: WorkflowsRouteWithChildren,
  ApiWorkflowsWorkflowIdAnalyzeRoute: ApiWorkflowsWorkflowIdAnalyzeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
