// @generated by MailMyPDF workflow materializer. Edit workflow.spec.json or config.ts instead.
import { createFileRoute } from "@tanstack/react-router"
import SsaReconsiderationStartShell from "../../ssa-reconsideration/start"
import { getSsaReconsiderationFactoryArtifact } from "@mailmypdf/workflows"

const resolvedFactoryArtifact = getSsaReconsiderationFactoryArtifact("appeal-ssdi-denial")

if (!resolvedFactoryArtifact) {
  throw new Error("appeal-ssdi-denial factory artifact is missing")
}
if (!resolvedFactoryArtifact.factoryReady) {
  throw new Error("appeal-ssdi-denial factory artifact is not ready")
}

const factoryArtifact = resolvedFactoryArtifact

export function AppealSsdiDenialStart() {
  return <SsaReconsiderationStartShell workflowId={factoryArtifact.workflowId} />
}

export const Route = createFileRoute(
  "/appeal-mail/workflows/appeal-ssdi-denial/start/",
)({
  component: AppealSsdiDenialStart,
})

export default AppealSsdiDenialStart
