// @generated by MailMyPDF workflow materializer. Edit workflow.spec.json or config.ts instead.
import { createWorkflowHead } from "@mailmypdf/seo"
import workflowConfig from "./config"

export const workflowSeo = createWorkflowHead(workflowConfig)
export default workflowSeo
