import { createFileRoute, Link } from "@tanstack/react-router";
import { AlertTriangle, ArrowRight, Car, FileCheck2, GitBranch, Scale, ShieldCheck } from "lucide-react";
import { SiteFooter, SiteHeader } from "@/components/site-chrome";
import { STOLEN_VEHICLE_WORKFLOW, WORKFLOW_STEPS } from "@mailmypdf/legal-defense";

export const Route = createFileRoute("/legal-defense/workflows/$workflowId")({
  head: ({ params }) => ({
    meta: [
      { title: params.workflowId === STOLEN_VEHICLE_WORKFLOW.id ? `${STOLEN_VEHICLE_WORKFLOW.title} | MailMyPDF` : "Legal Defense Workflow | MailMyPDF" },
      { name: "description", content: "Reconstruct the stop, arrest, search, vehicle purchase record, and derivative evidence into an attorney-ready defense intelligence packet." },
      { name: "robots", content: "noindex,nofollow" },
    ],
  }),
  component: WorkflowDetail,
});

function WorkflowDetail() {
  const { workflowId } = Route.useParams();
  if (workflowId !== STOLEN_VEHICLE_WORKFLOW.id) {
    return <><SiteHeader /><main className="mx-auto max-w-3xl px-6 py-20"><h1 className="font-serif text-5xl">Workflow not found</h1><p className="mt-4 text-muted-foreground">This Legal Defense workflow is not yet registered.</p><Link className="mt-8 inline-flex text-cobalt" to="/legal-defense/workflows">Return to workflows →</Link></main><SiteFooter /></>;
  }
  return <div className="min-h-screen bg-paper text-foreground"><SiteHeader /><main>
    <section className="border-b border-rule bg-ink text-white"><div className="mx-auto max-w-6xl px-4 py-16 sm:px-6 sm:py-24"><div className="font-mono text-[10px] uppercase tracking-[.2em] text-brass">California v1 · Criminal defense preparation</div><div className="mt-5 grid gap-10 lg:grid-cols-[1.25fr_.75fr]"><div><h1 className="max-w-4xl font-serif text-5xl leading-[1.02] sm:text-6xl">{STOLEN_VEHICLE_WORKFLOW.title}</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-white/70">Treat the case as one traceable chain: stop, alleged stolen-vehicle basis, arrest, search, and the object found afterward. Preserve the purchase record and build a packet an attorney can review quickly.</p><div className="mt-8 flex flex-wrap gap-3"><a href={STOLEN_VEHICLE_WORKFLOW.executionRoute} className="inline-flex items-center gap-2 rounded-md bg-white px-5 py-3 text-sm font-semibold text-ink">Start secure workflow <ArrowRight className="h-4 w-4" /></a><Link to="/legal-defense/workflows" className="inline-flex items-center rounded-md border border-white/30 px-5 py-3 text-sm font-semibold text-white">All defense workflows</Link></div></div><div className="rounded-2xl border border-white/15 bg-white/[.05] p-6"><div className="flex items-center gap-3"><ShieldCheck className="h-6 w-6 text-brass"/><h2 className="font-serif text-2xl">What this does</h2></div><ul className="mt-5 space-y-3 text-sm leading-6 text-white/70"><li>Builds a source-aware event timeline</li><li>Compares the physical VIN, bill-of-sale VIN, report VIN, and plates</li><li>Maps alleged evidence to the event that produced it</li><li>Separates the vehicle theory from the paraphernalia merits</li><li>Generates an attorney-ready review packet</li></ul></div></div></div></section>
    <section className="border-b border-rule"><div className="mx-auto grid max-w-6xl gap-4 px-4 py-10 sm:grid-cols-2 sm:px-6 lg:grid-cols-4">{[[Car,"Vehicle provenance","Bill of sale, payment, seller, VIN, keys, and transfer attempts"],[GitBranch,"Evidence dependency","See what evidence sits downstream of the arrest and search"],[FileCheck2,"Discovery matrix","Track police records, video, dispatch, database returns, and evidence logs"],[Scale,"Counsel review","Issue spotting without pretending the software decides the motion"]].map(([Icon,title,text])=><div className="rounded-xl border border-rule bg-card p-5" key={title as string}><Icon className="h-5 w-5 text-cobalt"/><h2 className="mt-4 font-serif text-xl">{title as string}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{text as string}</p></div>)}</div></section>
    <section className="border-b border-rule bg-paper-deep/20"><div className="mx-auto max-w-6xl px-4 py-14 sm:px-6"><div className="max-w-3xl"><div className="font-mono text-[10px] uppercase tracking-[.18em] text-cobalt">Nine controlled steps</div><h2 className="mt-3 font-serif text-4xl sm:text-5xl">From scattered facts to a coherent defense file.</h2></div><div className="mt-10 grid gap-px overflow-hidden rounded-xl border border-rule bg-rule md:grid-cols-3">{WORKFLOW_STEPS.map((step,index)=><div className="bg-card p-6" key={step.id}><div className="font-serif text-3xl text-cobalt">0{index+1}</div><h3 className="mt-3 text-sm font-semibold">{step.label}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{step.description}</p></div>)}</div></div></section>
    <section className="border-b border-amber-900/20 bg-amber-50"><div className="mx-auto flex max-w-6xl gap-4 px-4 py-8 sm:px-6"><AlertTriangle className="mt-1 h-6 w-6 shrink-0 text-amber-800"/><div><h2 className="font-semibold text-amber-950">This is defense preparation—not legal representation.</h2><p className="mt-2 max-w-4xl text-sm leading-6 text-amber-950/75">The workflow does not contact witnesses, law enforcement, a seller, or a reporting party; does not file a suppression motion; and does not promise that evidence will be excluded. If the person is in custody or has a hearing approaching, contact licensed criminal-defense counsel immediately.</p></div></div></section>
    <section className="bg-cobalt text-white"><div className="mx-auto flex max-w-6xl flex-col gap-6 px-4 py-14 sm:px-6 md:flex-row md:items-center md:justify-between"><div><h2 className="font-serif text-4xl">Start with the bill of sale and arrest sequence.</h2><p className="mt-3 max-w-3xl text-white/70">The original bill of sale, the source stolen-vehicle return, and what officers knew before arrest are the first three priorities.</p></div><a href={STOLEN_VEHICLE_WORKFLOW.executionRoute} className="inline-flex shrink-0 items-center gap-2 rounded-full bg-white px-6 py-3 text-sm font-semibold text-cobalt">Start workflow <ArrowRight className="h-4 w-4"/></a></div></section>
  </main><SiteFooter /></div>;
}
