/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as WorkflowsRouteImport } from './routes/workflows'
import { Route as ApiApproveMailingRouteImport } from './routes/api/approve-mailing'
import { Route as ApiCheckoutRouteImport } from './routes/api/checkout'
import { Route as WorkflowsSlugRouteImport } from './routes/workflows/$slug'
import { Route as ApiMailFinalizeRouteImport } from './routes/api/mail/finalize'
import { Route as ApiWebhooksStripeRouteImport } from './routes/api/webhooks/stripe'
import { Route as WorkflowsSlugBuilderRouteImport } from './routes/workflows/$slug/builder'
import { Route as ApiWorkflowsSlugBuildRouteImport } from './routes/api/workflows/$slug/build'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsRoute = WorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiApproveMailingRoute = ApiApproveMailingRouteImport.update({
  id: '/api/approve-mailing',
  path: '/api/approve-mailing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckoutRoute = ApiCheckoutRouteImport.update({
  id: '/api/checkout',
  path: '/api/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsSlugRoute = WorkflowsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => WorkflowsRoute,
} as any)
const ApiMailFinalizeRoute = ApiMailFinalizeRouteImport.update({
  id: '/api/mail/finalize',
  path: '/api/mail/finalize',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksStripeRoute = ApiWebhooksStripeRouteImport.update({
  id: '/api/webhooks/stripe',
  path: '/api/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsSlugBuilderRoute = WorkflowsSlugBuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => WorkflowsSlugRoute,
} as any)
const ApiWorkflowsSlugBuildRoute = ApiWorkflowsSlugBuildRouteImport.update({
  id: '/api/workflows/$slug/build',
  path: '/api/workflows/$slug/build',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/workflows': typeof WorkflowsRouteWithChildren
  '/api/approve-mailing': typeof ApiApproveMailingRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/workflows/$slug': typeof WorkflowsSlugRouteWithChildren
  '/api/mail/finalize': typeof ApiMailFinalizeRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/workflows/$slug/builder': typeof WorkflowsSlugBuilderRoute
  '/api/workflows/$slug/build': typeof ApiWorkflowsSlugBuildRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/workflows': typeof WorkflowsRouteWithChildren
  '/api/approve-mailing': typeof ApiApproveMailingRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/workflows/$slug': typeof WorkflowsSlugRouteWithChildren
  '/api/mail/finalize': typeof ApiMailFinalizeRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/workflows/$slug/builder': typeof WorkflowsSlugBuilderRoute
  '/api/workflows/$slug/build': typeof ApiWorkflowsSlugBuildRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/workflows': typeof WorkflowsRouteWithChildren
  '/api/approve-mailing': typeof ApiApproveMailingRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/workflows/$slug': typeof WorkflowsSlugRouteWithChildren
  '/api/mail/finalize': typeof ApiMailFinalizeRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeRoute
  '/workflows/$slug/builder': typeof WorkflowsSlugBuilderRoute
  '/api/workflows/$slug/build': typeof ApiWorkflowsSlugBuildRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/workflows'
    | '/api/approve-mailing'
    | '/api/checkout'
    | '/workflows/$slug'
    | '/api/mail/finalize'
    | '/api/webhooks/stripe'
    | '/workflows/$slug/builder'
    | '/api/workflows/$slug/build'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/workflows'
    | '/api/approve-mailing'
    | '/api/checkout'
    | '/workflows/$slug'
    | '/api/mail/finalize'
    | '/api/webhooks/stripe'
    | '/workflows/$slug/builder'
    | '/api/workflows/$slug/build'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/workflows'
    | '/api/approve-mailing'
    | '/api/checkout'
    | '/workflows/$slug'
    | '/api/mail/finalize'
    | '/api/webhooks/stripe'
    | '/workflows/$slug/builder'
    | '/api/workflows/$slug/build'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  WorkflowsRoute: typeof WorkflowsRouteWithChildren
  ApiApproveMailingRoute: typeof ApiApproveMailingRoute
  ApiCheckoutRoute: typeof ApiCheckoutRoute
  ApiMailFinalizeRoute: typeof ApiMailFinalizeRoute
  ApiWebhooksStripeRoute: typeof ApiWebhooksStripeRoute
  ApiWorkflowsSlugBuildRoute: typeof ApiWorkflowsSlugBuildRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows': {
      id: '/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/approve-mailing': {
      id: '/api/approve-mailing'
      path: '/api/approve-mailing'
      fullPath: '/api/approve-mailing'
      preLoaderRoute: typeof ApiApproveMailingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checkout': {
      id: '/api/checkout'
      path: '/api/checkout'
      fullPath: '/api/checkout'
      preLoaderRoute: typeof ApiCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/$slug': {
      id: '/workflows/$slug'
      path: '/$slug'
      fullPath: '/workflows/$slug'
      preLoaderRoute: typeof WorkflowsSlugRouteImport
      parentRoute: typeof WorkflowsRoute
    }
    '/api/mail/finalize': {
      id: '/api/mail/finalize'
      path: '/api/mail/finalize'
      fullPath: '/api/mail/finalize'
      preLoaderRoute: typeof ApiMailFinalizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/stripe': {
      id: '/api/webhooks/stripe'
      path: '/api/webhooks/stripe'
      fullPath: '/api/webhooks/stripe'
      preLoaderRoute: typeof ApiWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/$slug/builder': {
      id: '/workflows/$slug/builder'
      path: '/builder'
      fullPath: '/workflows/$slug/builder'
      preLoaderRoute: typeof WorkflowsSlugBuilderRouteImport
      parentRoute: typeof WorkflowsSlugRoute
    }
    '/api/workflows/$slug/build': {
      id: '/api/workflows/$slug/build'
      path: '/api/workflows/$slug/build'
      fullPath: '/api/workflows/$slug/build'
      preLoaderRoute: typeof ApiWorkflowsSlugBuildRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface WorkflowsSlugRouteChildren {
  WorkflowsSlugBuilderRoute: typeof WorkflowsSlugBuilderRoute
}

const WorkflowsSlugRouteChildren: WorkflowsSlugRouteChildren = {
  WorkflowsSlugBuilderRoute: WorkflowsSlugBuilderRoute,
}

const WorkflowsSlugRouteWithChildren = WorkflowsSlugRoute._addFileChildren(
  WorkflowsSlugRouteChildren,
)

interface WorkflowsRouteChildren {
  WorkflowsSlugRoute: typeof WorkflowsSlugRouteWithChildren
}

const WorkflowsRouteChildren: WorkflowsRouteChildren = {
  WorkflowsSlugRoute: WorkflowsSlugRouteWithChildren,
}

const WorkflowsRouteWithChildren = WorkflowsRoute._addFileChildren(
  WorkflowsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  WorkflowsRoute: WorkflowsRouteWithChildren,
  ApiApproveMailingRoute: ApiApproveMailingRoute,
  ApiCheckoutRoute: ApiCheckoutRoute,
  ApiMailFinalizeRoute: ApiMailFinalizeRoute,
  ApiWebhooksStripeRoute: ApiWebhooksStripeRoute,
  ApiWorkflowsSlugBuildRoute: ApiWorkflowsSlugBuildRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
