import type { ValidatedRequest } from '../request-service'
import { createRecordsWorkflow, type RecordsWorkflow } from '../workflow-factory'
import type { RecordsDomainCapability } from './domain-pack'
import { analyzeGenericProduction, type GenericProductionRecord } from './generic-records-analysis'
import { assessGenericRecordContradiction, classifyGenericRecord, extractGenericRecordFacts, recommendGenericRecordFollowUp } from './generic-records-ai'
import { getConfiguredRecordsLlmProviders } from '../ai/records-llm-providers'

export const AGENCY_RECORDS_CATEGORIES = [
  'agency-index-metadata-and-request-status',
  'governance-authority-organization-and-decision-records',
  'program-operational-case-and-administrative-records',
  'policy-guidance-directives-procedures-and-manuals',
  'contracts-procurement-grants-expenditures-and-vendor-records',
  'emails-correspondence-texts-and-communications',
  'meetings-calendars-agendas-minutes-and-presentations',
  'inspections-audits-compliance-performance-and-evaluation-records',
  'complaint-investigation-inquiry-referral-and-case-status-records',
  'datasets-reports-statistics-and-machine-readable-records',
  'public-role-assignment-organizational-and-responsibility-records',
  'referenced-cross-indexed-and-attachment-records',
  'fee-transfer-withholding-redaction-no-records-and-closure-status',
] as const

export const AGENCY_RECORDS_CAPABILITIES: readonly RecordsDomainCapability[] = ['classification','extraction','deadline','contradiction','findings','evidence','research','risk','strategy','draft','draftProvenance','validation','review','approval','mailing','tracking','proofAudit']

export const AGENCY_RECORDS_INTAKE = [
  { id:'agency', label:'Agency / department', required:true, helpText:'Specific government agency, department, board, authority, district, office, court office, or other public body.' },
  { id:'jurisdiction', label:'Jurisdiction', required:true, helpText:'Federal, state, county, city, district, court, or other jurisdiction.' },
  { id:'department', label:'Division / bureau / office / component', helpText:'Specific division, bureau, component, program, office, or records unit when known.' },
  { id:'recordsDescription', label:'Records sought', required:true, helpText:'Describe identifiable existing agency records rather than asking the agency to create an answer or new analysis.' },
  { id:'subjectMatter', label:'Subject / objective', required:true, helpText:'Plain-English description of the matter and what the agency records should document.' },
  { id:'dateStart', label:'Record period start', required:true, helpText:'Beginning of the requested record period.' },
  { id:'dateEnd', label:'Record period end', required:true, helpText:'End of the requested record period.' },
  { id:'identifiers', label:'Identifiers', helpText:'Case, incident, permit, parcel, project, contract, invoice, grant, program, employee role, address, meeting, or other search-ready identifiers.' },
  { id:'custodians', label:'Likely custodians / responsible roles', helpText:'People, offices, roles, departments, contractors, or systems likely to maintain responsive records.' },
  { id:'searchTerms', label:'Search terms', helpText:'Distinctive names, phrases, project terms, addresses, program names, or other useful search terms.' },
  { id:'preferredFormat', label:'Preferred format', helpText:'Native electronic files, PDF, CSV, spreadsheet, email export, audio/video, or another available format.' },
  { id:'systemsOrPrograms', label:'Known programs / systems / repositories', helpText:'Known program, database, case system, records repository, portal, or file location when lawfully known. Do not provide credentials or security-sensitive details.' },
  { id:'exclusions', label:'Scope exclusions / narrowing', helpText:'Optional exclusions that reduce noise without changing the objective.' },
] as const

function text(input:Record<string,unknown>,key:string):string|undefined{const raw=input[key];if(typeof raw!=='string')return undefined;const value=raw.trim();return value||undefined}
function selectedCategories(input:Record<string,unknown>):string[]{const raw=input.categories;if(!Array.isArray(raw))return [...AGENCY_RECORDS_CATEGORIES];const known=new Set(AGENCY_RECORDS_CATEGORIES);const selected=raw.filter((entry):entry is string=>typeof entry==='string'&&known.has(entry as typeof AGENCY_RECORDS_CATEGORIES[number]));return selected.length?selected:[...AGENCY_RECORDS_CATEGORIES]}
function scope(input:Record<string,unknown>):string{const start=text(input,'dateStart'),end=text(input,'dateEnd');const parts=[text(input,'identifiers')&&`Identifiers: ${text(input,'identifiers')}.`,text(input,'custodians')&&`Likely custodians/responsible roles: ${text(input,'custodians')}.`,text(input,'searchTerms')&&`Search terms: ${text(input,'searchTerms')}.`,text(input,'preferredFormat')&&`Preferred format: ${text(input,'preferredFormat')}.`,text(input,'systemsOrPrograms')&&`Known programs/systems/repositories supplied by requester: ${text(input,'systemsOrPrograms')}.`,text(input,'exclusions')&&`Scope exclusions/narrowing: ${text(input,'exclusions')}.`].filter(Boolean);return `${start&&end?` Cover ${start} through ${end}.`:''}${parts.length?` ${parts.join(' ')}`:''}`}
function describe(category:string,input:Record<string,unknown>):string{
  const s=scope(input);const objective=text(input,'subjectMatter')?` Objective: ${text(input,'subjectMatter')}.`:'';const supplied=text(input,'recordsDescription')?` Records description supplied by requester: ${text(input,'recordsDescription')}.`:''
  const descriptions:Record<string,string>={
    'agency-index-metadata-and-request-status':`Existing agency indexes, inventories, logs, metadata, file lists, database exports, tracking records, routing/referral records, or equivalent records identifying responsive record sets, custodians, dates, attachments, systems, production, or request status. Ask for existing records only and do not demand security-sensitive system details.${s}`,
    'governance-authority-organization-and-decision-records':`Existing charters, delegations, organizational records, authority/delegation documents, memoranda, approvals, findings, recommendations, staff analyses, decision records, and implementation records tied to the identified matter.${s}`,
    'program-operational-case-and-administrative-records':`Existing program, operational, administrative, intake, case-management, service, workflow, project, transaction, or other agency records tied to the matter and maintained in the ordinary course of agency activity.${s}`,
    'policy-guidance-directives-procedures-and-manuals':`Existing policies, procedures, directives, manuals, guidance, bulletins, training materials, standards, forms/instructions, and relevant versions applicable during the requested period.${s}`,
    'contracts-procurement-grants-expenditures-and-vendor-records':`Existing contracts, amendments, solicitations, procurement files, grants, purchase orders, invoices, expenditure/payment records, vendor records, deliverables, and related financial documentation tied to the matter, subject to lawful access limits.${s}`,
    'emails-correspondence-texts-and-communications':`Existing emails, attachments, letters, correspondence, text/message records, platform messages, and other communications within scope. Use supplied custodians and search terms where known and preserve attachments as a separate completeness check.${s}`,
    'meetings-calendars-agendas-minutes-and-presentations':`Existing calendars, invitations, agendas, minutes, notes where maintained and lawfully accessible, presentations, handouts, attendance records, recordings, and meeting follow-up records tied to the matter.${s}`,
    'inspections-audits-compliance-performance-and-evaluation-records':`Existing inspection, audit, compliance, monitoring, performance, evaluation, quality-review, corrective-action, and related supporting records within scope.${s}`,
    'complaint-investigation-inquiry-referral-and-case-status-records':`Lawfully accessible complaint, investigation, inquiry, referral, intake, case, status, disposition, and related records. Do not assume confidential source, victim, witness, juvenile, privileged, law-enforcement-sensitive, whistleblower, or other protected material is publicly disclosable.${s}`,
    'datasets-reports-statistics-and-machine-readable-records':`Existing datasets, database exports, reports, statistics, dashboards, spreadsheets, analyses, and machine-readable data where maintained and lawfully available. Prefer requested native/machine-readable format when available.${s}`,
    'public-role-assignment-organizational-and-responsibility-records':`Lawfully accessible organizational charts, public employee roles, titles, assignments, office responsibilities, delegation records, and other public-facing employment or organizational information pertinent to the matter. Do not treat private personnel, medical, financial, disciplinary, or authentication data as automatically public.${s}`,
    'referenced-cross-indexed-and-attachment-records':`Existing attachments, enclosures, exhibits, linked files, referenced documents, cross-indexed records, related identifiers, subordinate/related files, and records expressly identified within responsive material but not otherwise produced.${s}`,
    'fee-transfer-withholding-redaction-no-records-and-closure-status':`Existing acknowledgment, search/status, fee, clarification, transfer/referral, no-records, withholding, redaction, exemption, partial-production, closure, and other response records. Preserve the agency's actual stated basis and route rather than inferring a deadline, exemption, disclosure entitlement, violation, or appeal right.${s}`,
  }
  return `${descriptions[category]??`Existing agency records concerning ${category}.${s}`}${supplied}${objective}`
}
function validateAgencyRecords(request:ValidatedRequest):readonly {field:string;message:string}[]{const issues:{field:string;message:string}[]=[];const corpus=request.items.map(item=>item.description.toLowerCase()).join(' ');if(!request.agency?.trim())issues.push({field:'agency',message:'Identify the specific agency or public body.'});if(!request.jurisdiction?.trim())issues.push({field:'jurisdiction',message:'Identify the relevant jurisdiction.'});if(!corpus.includes('records description supplied by requester:'))issues.push({field:'recordsDescription',message:'Describe the identifiable existing agency records sought.'});if(!corpus.includes('objective:'))issues.push({field:'subjectMatter',message:'Describe the subject and records objective.'});if(!corpus.includes('cover '))issues.push({field:'dateRange',message:'Provide the requested record period.'});return issues}
export function buildAgencyRecordsRequest(input:Record<string,unknown>){const agency=text(input,'agency')??'';const subject=text(input,'subjectMatter');const start=text(input,'dateStart'),end=text(input,'dateEnd');const categories=selectedCategories(input);return {title:`Agency Records Request — ${subject??agency??'Agency Records'}`,agency,jurisdiction:text(input,'jurisdiction'),purpose:text(input,'purpose')??'Request identifiable existing records from a specific agency with office, custodian, identifier, search, format, and production-review controls.',scope:JSON.stringify({workflow:'agency-records-request',department:text(input,'department'),recordsDescription:text(input,'recordsDescription'),subjectMatter:subject,dateStart:start,dateEnd:end,identifiers:text(input,'identifiers'),custodians:text(input,'custodians'),searchTerms:text(input,'searchTerms'),preferredFormat:text(input,'preferredFormat'),systemsOrPrograms:text(input,'systemsOrPrograms'),exclusions:text(input,'exclusions')}),items:categories.map(category=>({category,description:describe(category,input),dateStart:start,dateEnd:end,custodian:text(input,'department')??text(input,'custodians'),format:text(input,'preferredFormat'),systemHint:category==='emails-correspondence-texts-and-communications'?'email / messaging / correspondence systems':category==='datasets-reports-statistics-and-machine-readable-records'?'reporting database / program system / spreadsheet or native data system':category==='agency-index-metadata-and-request-status'?'records index / document management / case / request tracking system':undefined}))}}

export const AGENCY_RECORDS_FINDINGS=['MISSING_REQUESTED_CATEGORY','REFERENCED_RECORD_NOT_PRODUCED','IDENTIFIER_MISMATCH','DATE_GAP','DUPLICATE_RECORD','MISSING_ATTACHMENT','UNEXPLAINED_WITHHOLDING','REDACTION_REVIEW','PARTIAL_PRODUCTION','UNRESPONSIVE_ITEM'] as const

export const productionAgencyRecordsRequestWorkflow:RecordsWorkflow=createRecordsWorkflow({
  id:'agency-records-request',name:'Agency Records Request',description:'Build a targeted request to a specific government agency with office/component mapping, custodians, identifiers, date ranges, formats, programs/systems, narrowing, and production-review controls.',searchIntent:'agency records request',seo:{title:'Agency Records Request — Target a Specific Government Agency',description:'Build a targeted agency records request with the right office, records categories, dates, custodians, identifiers, search terms, formats, and production-review controls.',canonicalPath:'/workflows/agency-records-request'},intakeVersion:'2.0.0',intake:AGENCY_RECORDS_INTAKE,capabilities:AGENCY_RECORDS_CAPABILITIES,request:{categories:AGENCY_RECORDS_CATEGORIES,build:buildAgencyRecordsRequest},validate:validateAgencyRecords,
  policies:[{jurisdiction:'all',version:'2.0.0',rules:{requestExistingIdentifiableAgencyRecordsRatherThanAgencyCreatedAnswersOrNewAnalysis:true,preserveAgencyOfficeComponentJurisdictionAndCustodianScopeAsExplicitResearchInputs:true,doNotInventRecordExistenceCustodiansProgramsSystemsSearchTermsAgencyFactsOrRequestStatus:true,doNotAssertJurisdictionSpecificDeadlinesExemptionsFeesWaiversAppealRightsDisclosureRightsOrViolationsWithoutVerifiedAuthority:true,doNotTreatProtectedPersonnelMedicalFinancialJuvenileVictimWitnessWhistleblowerSecurityOrAuthenticationDataAsPublic:true,doNotRequestPasswordsSecurityAnswersOneTimeCodesAuthenticationTokensPaymentCredentialsOrSecuritySensitiveSystemDetails:true,preserveRequesterScopeIdentifiersCustodiansSearchTermsFormatsSystemsAndExclusions:true,requireHumanReviewWhenConsequentialDeadlineLegalConclusionSensitiveAccessOrAgencyRoutingIsUnclear:true}}],
  responseAnalysis:{findingTypes:AGENCY_RECORDS_FINDINGS,async analyze(input:unknown){if(!input||typeof input!=='object')throw new Error('AGENCY_RECORDS_PRODUCTION_ANALYSIS_INPUT_INVALID');const source=input as {requestedItems?:readonly {category:string;description:string}[];records?:readonly GenericProductionRecord[]};const records=source.records??[];const requested=(source.requestedItems??[]).map(item=>({id:item.category,label:item.category,keywords:item.description.split(/\W+/).filter(word=>word.length>=4).slice(0,20)}));const deterministic=analyzeGenericProduction(requested,records,'agency record');const providers=getConfiguredRecordsLlmProviders();if(providers.length<2)return deterministic;const policy={minimumProviders:2,agreementThreshold:0.67,maxProviders:3} as const;const requestedCategories=requested.map(item=>item.id);const analyzed=await Promise.all(records.slice(0,20).map(async record=>({id:record.id,classification:await classifyGenericRecord(providers,record,'agency-records-request',requestedCategories,policy),facts:await extractGenericRecordFacts(providers,record,'agency-records-request',policy)})));const contradictions:Array<{leftId:string;rightId:string;result:Awaited<ReturnType<typeof assessGenericRecordContradiction>>}>=[];for(let i=0;i<Math.min(records.length,10);i+=1)for(let j=i+1;j<Math.min(records.length,10);j+=1)contradictions.push({leftId:records[i].id,rightId:records[j].id,result:await assessGenericRecordContradiction(providers,records[i],records[j],'agency-records-request',policy)});const strategy=await recommendGenericRecordFollowUp(providers,'agency-records-request',{deterministic,requestedItems:source.requestedItems??[],records:records.slice(0,20).map(record=>({id:record.id,filename:record.filename,category:record.category,text:record.text??''})),extracted:analyzed.map(item=>({id:item.id,classification:item.classification.value,facts:item.facts.value})),contradictions:contradictions.filter(item=>item.result.value.contradictory).map(item=>({leftId:item.leftId,rightId:item.rightId,analysis:item.result.value}))},policy);return {...deterministic,aiStrategy:strategy.value,aiProvenance:{providers:strategy.providers,confidence:strategy.confidence,disagreements:strategy.disagreements,warnings:strategy.warnings},aiRecordAnalysis:analyzed.map(item=>({id:item.id,classification:item.classification.value,facts:item.facts.value,classificationProvenance:item.classification.providers,factProvenance:item.facts.providers})),aiContradictions:contradictions.filter(item=>item.result.value.contradictory).map(item=>({leftId:item.leftId,rightId:item.rightId,analysis:item.result.value,providers:item.result.providers}))}}},
})
