import type { ValidatedRequest } from '../request-service'
import { createRecordsWorkflow, type RecordsWorkflow } from '../workflow-factory'
import type { RecordsDomainCapability } from './domain-pack'
import { analyzeGenericProduction, type GenericProductionRecord } from './generic-records-analysis'
import { assessGenericRecordContradiction, classifyGenericRecord, extractGenericRecordFacts, recommendGenericRecordFollowUp } from './generic-records-ai'
import { getConfiguredRecordsLlmProviders } from '../ai/records-llm-providers'

export const CASE_RECORDS_PRODUCTION_CATEGORIES = [
  'case-index-file-metadata-and-status',
  'initiating-complaints-referrals-intake-and-source-records',
  'allegations-violations-citations-notices-orders-and-actions',
  'investigation-inspection-interview-and-field-records',
  'evidence-exhibits-photographs-video-audio-and-media',
  'emails-correspondence-texts-and-case-communications',
  'staff-notes-analysis-recommendations-and-decision-records',
  'permits-property-licenses-contracts-and-related-records',
  'hearings-conferences-meetings-calendars-and-scheduling',
  'service-mailing-delivery-and-notice-proof-records',
  'cross-agency-department-referral-and-coordination-records',
  'referenced-cross-indexed-attachment-and-linked-records',
  'fee-withholding-redaction-no-records-and-case-request-status',
] as const

export const CASE_RECORDS_PRODUCTION_CAPABILITIES: readonly RecordsDomainCapability[] = ['classification','extraction','deadline','contradiction','findings','evidence','research','risk','strategy','draft','draftProvenance','validation','review','approval','mailing','tracking','proofAudit']

export const CASE_RECORDS_PRODUCTION_INTAKE = [
  { id:'agency', label:'Agency / department', required:true, helpText:'Agency or public body that maintains or handled the case.' },
  { id:'jurisdiction', label:'Jurisdiction', required:true, helpText:'Federal, state, county, city, district, court, or other jurisdiction.' },
  { id:'caseNumber', label:'Case / file / reference number', helpText:'Known case, file, incident, complaint, permit, citation, enforcement, appeal, or reference number.' },
  { id:'relatedIdentifiers', label:'Related identifiers', helpText:'Related case numbers, permit numbers, parcel/APN, incident numbers, project IDs, docket numbers, complaint IDs, or other identifiers.' },
  { id:'personName', label:'Person / entity involved', helpText:'Person, business, organization, owner, applicant, respondent, complainant name where lawfully appropriate, or other entity connected to the matter.' },
  { id:'address', label:'Property / location', helpText:'Property address, parcel, facility, incident location, or other location connected to the case.' },
  { id:'subjectMatter', label:'Case / matter description', required:true, helpText:'Describe the matter and what the requested case records should document. Do not state disputed allegations as established facts.' },
  { id:'dateStart', label:'Case period start', required:true, helpText:'Beginning of the relevant case period.' },
  { id:'dateEnd', label:'Case period end', required:true, helpText:'End of the relevant case period.' },
  { id:'departments', label:'Other departments / agencies involved', helpText:'Cross-referenced offices, departments, agencies, boards, contractors, consultants, or outside public bodies known to be involved.' },
  { id:'custodians', label:'Likely custodians / case roles', helpText:'Investigators, inspectors, analysts, hearing officers, program staff, records staff, supervisors, attorneys where nonprivileged records may exist, or other likely custodians.' },
  { id:'searchTerms', label:'Search terms', helpText:'Distinctive names, addresses, case numbers, project terms, allegations, permit numbers, or phrases useful for locating records.' },
  { id:'preferredFormat', label:'Preferred format', helpText:'Native electronic files, PDF, CSV, email export, photographs, audio/video, or another available format.' },
  { id:'knownCaseStatus', label:'Known case status', helpText:'Optional requester-supplied status such as open, closed, pending, referred, appealed, or unknown. This is not treated as verified unless supported by records.' },
  { id:'exclusions', label:'Scope exclusions / narrowing', helpText:'Optional exclusions that reduce noise without changing the case-record objective.' },
] as const

function text(input:Record<string,unknown>,key:string):string|undefined{const raw=input[key];if(typeof raw!=='string')return undefined;const value=raw.trim();return value||undefined}
function selectedCategories(input:Record<string,unknown>):string[]{const raw=input.categories;if(!Array.isArray(raw))return [...CASE_RECORDS_PRODUCTION_CATEGORIES];const known=new Set(CASE_RECORDS_PRODUCTION_CATEGORIES);const selected=raw.filter((entry):entry is string=>typeof entry==='string'&&known.has(entry as typeof CASE_RECORDS_PRODUCTION_CATEGORIES[number]));return selected.length?selected:[...CASE_RECORDS_PRODUCTION_CATEGORIES]}
function scope(input:Record<string,unknown>):string{const start=text(input,'dateStart'),end=text(input,'dateEnd');const parts=[text(input,'caseNumber')&&`Primary case/file/reference number: ${text(input,'caseNumber')}.`,text(input,'relatedIdentifiers')&&`Related identifiers: ${text(input,'relatedIdentifiers')}.`,text(input,'personName')&&`Person/entity identifier supplied by requester: ${text(input,'personName')}.`,text(input,'address')&&`Property/location identifier: ${text(input,'address')}.`,text(input,'departments')&&`Other departments/agencies: ${text(input,'departments')}.`,text(input,'custodians')&&`Likely custodians/case roles: ${text(input,'custodians')}.`,text(input,'searchTerms')&&`Search terms: ${text(input,'searchTerms')}.`,text(input,'preferredFormat')&&`Preferred format: ${text(input,'preferredFormat')}.`,text(input,'knownCaseStatus')&&`Requester-supplied case status: ${text(input,'knownCaseStatus')} (unverified unless supported by records).`,text(input,'exclusions')&&`Scope exclusions/narrowing: ${text(input,'exclusions')}.`].filter(Boolean);return `${start&&end?` Cover ${start} through ${end}.`:''}${parts.length?` ${parts.join(' ')}`:''}`}
function describe(category:string,input:Record<string,unknown>):string{
  const s=scope(input);const objective=text(input,'subjectMatter')?` Matter description supplied by requester: ${text(input,'subjectMatter')}. Treat allegations, complaints, violations, responsibility, findings, and outcomes according to the status shown by the records; do not convert disputed or unadjudicated allegations into established facts.`:''
  const descriptions:Record<string,string>={
    'case-index-file-metadata-and-status':`Existing master case file, case index, file inventory, metadata, case-management entries, status/history records, assignment records, routing records, related identifiers, and records sufficient to identify the maintained case record set. Ask for existing records only and do not demand security-sensitive system details.${s}`,
    'initiating-complaints-referrals-intake-and-source-records':`Existing complaints, referrals, intake records, applications, tips, source documents, opening memoranda, initiating correspondence, and records showing how the matter was opened or referred. Do not assume complainant/source identity or protected source information is publicly disclosable.${s}`,
    'allegations-violations-citations-notices-orders-and-actions':`Existing allegations, asserted violations, citations, notices, orders, directives, warnings, corrective-action records, enforcement actions, amendments, withdrawals, dismissals, and disposition records. Preserve whether each item is alleged, noticed, found, admitted, adjudicated, withdrawn, dismissed, corrected, or otherwise resolved according to the record evidence.${s}`,
    'investigation-inspection-interview-and-field-records':`Lawfully accessible investigation, inspection, interview, site-visit, field-note, observation, measurement, test, checklist, report, warrant/access, and related records. Do not assume privileged, confidential-source, victim/witness, juvenile, law-enforcement-sensitive, medical, or security-sensitive material is publicly disclosable.${s}`,
    'evidence-exhibits-photographs-video-audio-and-media':`Existing evidence logs, exhibits, photographs, video, audio, recordings, diagrams, maps, samples, media files, chain/index records, and supporting materials associated with the case where lawfully accessible.${s}`,
    'emails-correspondence-texts-and-case-communications':`Existing emails, attachments, letters, notices, correspondence, text/message records, platform messages, communications with involved parties, internal case communications where lawfully accessible, and communications with outside agencies or contractors within scope.${s}`,
    'staff-notes-analysis-recommendations-and-decision-records':`Lawfully accessible staff notes, analyses, recommendations, review records, supervisor comments, decision memoranda, approvals, findings, disposition reasoning, and other decision-development records. Do not assume privileged attorney-client, attorney-work-product, deliberative, or other protected material is disclosable.${s}`,
    'permits-property-licenses-contracts-and-related-records':`Existing permits, applications, licenses, certificates, parcel/property records, plans, contracts, approvals, conditions, inspection records, project files, and other records referenced by or linked to the case.${s}`,
    'hearings-conferences-meetings-calendars-and-scheduling':`Existing hearing notices, agendas, minutes, recordings, exhibits, conference records, meeting notes where maintained and lawfully accessible, calendars, invitations, continuances, scheduling records, and appearance/attendance records related to the case.${s}`,
    'service-mailing-delivery-and-notice-proof-records':`Existing mailing, service, delivery, posting, receipt, returned-mail, tracking, certified-mail, proof-of-service, notice-distribution, electronic-delivery, and other records showing how case documents were transmitted or served.${s}`,
    'cross-agency-department-referral-and-coordination-records':`Existing referrals, transfers, requests for assistance, joint-action records, cross-department communications, agency coordination, consultant/contractor communications, and records linking the matter to another agency, department, case, project, permit, or proceeding.${s}`,
    'referenced-cross-indexed-attachment-and-linked-records':`Existing attachments, enclosures, exhibits, linked files, referenced documents, cross-indexed records, related cases, subordinate files, incorporated records, and documents expressly identified within responsive material but not otherwise produced.${s}`,
    'fee-withholding-redaction-no-records-and-case-request-status':`Existing acknowledgment, search/status, fee, clarification, transfer/referral, no-records, withholding, redaction, exemption, partial-production, closure, appeal/review-instruction where actually stated, and other response records. Preserve the agency's actual stated basis rather than inventing a deadline, exemption, disclosure entitlement, violation, or review right.${s}`,
  }
  return `${descriptions[category]??`Existing case records concerning ${category}.${s}`}${objective}`
}
function validateCaseRecordsProduction(request:ValidatedRequest):readonly {field:string;message:string}[]{const issues:{field:string;message:string}[]=[];const corpus=request.items.map(item=>item.description.toLowerCase()).join(' ');if(!request.agency?.trim())issues.push({field:'agency',message:'Identify the agency or public body maintaining the case.'});if(!request.jurisdiction?.trim())issues.push({field:'jurisdiction',message:'Identify the relevant jurisdiction.'});if(!corpus.includes('matter description supplied by requester:'))issues.push({field:'subjectMatter',message:'Describe the case or matter and records objective.'});if(!corpus.includes('cover '))issues.push({field:'dateRange',message:'Provide the relevant case period.'});const hasIdentifier=['primary case/file/reference number:','related identifiers:','person/entity identifier supplied by requester:','property/location identifier:'].some(marker=>corpus.includes(marker));if(!hasIdentifier)issues.push({field:'identifiers',message:'Provide at least one case/file number, related identifier, person/entity, or property/location identifier.'});return issues}
export function buildCaseRecordsProductionRequest(input:Record<string,unknown>){const agency=text(input,'agency')??'';const subject=text(input,'subjectMatter');const caseNumber=text(input,'caseNumber');const start=text(input,'dateStart'),end=text(input,'dateEnd');const categories=selectedCategories(input);return {title:`Case Records — ${caseNumber??text(input,'personName')??text(input,'address')??subject??'Case'}`,agency,jurisdiction:text(input,'jurisdiction'),purpose:text(input,'purpose')??'Obtain a coherent evidence-preserving case record set using case identifiers, parties, locations, departments, custodians, dates, and cross-referenced records.',scope:JSON.stringify({workflow:'case-records',caseNumber,relatedIdentifiers:text(input,'relatedIdentifiers'),personName:text(input,'personName'),address:text(input,'address'),subjectMatter:subject,dateStart:start,dateEnd:end,departments:text(input,'departments'),custodians:text(input,'custodians'),searchTerms:text(input,'searchTerms'),preferredFormat:text(input,'preferredFormat'),knownCaseStatus:text(input,'knownCaseStatus'),exclusions:text(input,'exclusions')}),items:categories.map(category=>({category,description:describe(category,input),dateStart:start,dateEnd:end,custodian:text(input,'custodians'),format:text(input,'preferredFormat'),systemHint:category==='case-index-file-metadata-and-status'?'case management / records index / document management system':category==='emails-correspondence-texts-and-case-communications'?'email / messaging / correspondence systems':undefined}))}}

export const CASE_RECORDS_PRODUCTION_FINDINGS=['MISSING_REQUESTED_CATEGORY','REFERENCED_RECORD_NOT_PRODUCED','IDENTIFIER_MISMATCH','DATE_GAP','DUPLICATE_RECORD','MISSING_ATTACHMENT','UNEXPLAINED_WITHHOLDING','REDACTION_REVIEW','PARTIAL_PRODUCTION','UNRESPONSIVE_ITEM'] as const

export const productionCaseRecordsWorkflow:RecordsWorkflow=createRecordsWorkflow({
  id:'case-records',name:'Case Records Request',description:'Build a case-centered records request that links case numbers, parties, locations, complaints, allegations, investigations, evidence, communications, hearings, service proof, departments, and referenced records into one evidence-preserving scope.',searchIntent:'records about a specific case',seo:{title:'Case Records Request — Build a Complete Government Case File Search',description:'Build a case-centered records request using case numbers, people, properties, departments, complaints, notices, investigations, evidence, communications, hearings, service records, and referenced documents.',canonicalPath:'/workflows/case-records'},intakeVersion:'2.0.0',intake:CASE_RECORDS_PRODUCTION_INTAKE,capabilities:CASE_RECORDS_PRODUCTION_CAPABILITIES,request:{categories:CASE_RECORDS_PRODUCTION_CATEGORIES,build:buildCaseRecordsProductionRequest},validate:validateCaseRecordsProduction,
  policies:[{jurisdiction:'all',version:'2.0.0',rules:{preserveAllegationFindingDispositionAndCaseStatusDistinctions:true,doNotConvertComplaintsAllegationsViolationsResponsibilityOrOutcomesIntoEstablishedFactsWithoutRecordEvidence:true,doNotInventRecordExistenceCaseStatusCustodiansSystemsCaseNumbersAgencyFactsOrSearchResults:true,doNotAssertJurisdictionSpecificDeadlinesExemptionsAppealRightsDisclosureRightsViolationsOrServiceValidityWithoutVerifiedAuthority:true,doNotTreatProtectedSourceComplainantVictimWitnessJuvenileMedicalFinancialPrivilegedDeliberativePersonnelSecurityOrAuthenticationDataAsAutomaticallyPublic:true,doNotRequestPasswordsSecurityAnswersOneTimeCodesAuthenticationTokensPaymentCredentialsOrSecuritySensitiveSystemDetails:true,preserveIdentifiersPartiesLocationsDepartmentsCustodiansSearchTermsFormatsCaseStatusAndExclusionsAsRequesterSuppliedUnlessVerified:true,requireHumanReviewWhenConsequentialDeadlineLegalConclusionServiceQuestionCaseStatusSensitiveAccessOrPrivilegeIssueIsUnclear:true}}],
  responseAnalysis:{findingTypes:CASE_RECORDS_PRODUCTION_FINDINGS,async analyze(input:unknown){if(!input||typeof input!=='object')throw new Error('CASE_RECORDS_V2_ANALYSIS_INPUT_INVALID');const source=input as {requestedItems?:readonly {category:string;description:string}[];records?:readonly GenericProductionRecord[]};const records=source.records??[];const requested=(source.requestedItems??[]).map(item=>({id:item.category,label:item.category,keywords:item.description.split(/\W+/).filter(word=>word.length>=4).slice(0,20)}));const deterministic=analyzeGenericProduction(requested,records,'case record');const providers=getConfiguredRecordsLlmProviders();if(providers.length<2)return deterministic;const policy={minimumProviders:2,agreementThreshold:0.67,maxProviders:3} as const;const requestedCategories=requested.map(item=>item.id);const analyzed=await Promise.all(records.slice(0,20).map(async record=>({id:record.id,classification:await classifyGenericRecord(providers,record,'case-records',requestedCategories,policy),facts:await extractGenericRecordFacts(providers,record,'case-records',policy)})));const contradictions:Array<{leftId:string;rightId:string;result:Awaited<ReturnType<typeof assessGenericRecordContradiction>>}>=[];for(let i=0;i<Math.min(records.length,10);i+=1)for(let j=i+1;j<Math.min(records.length,10);j+=1)contradictions.push({leftId:records[i].id,rightId:records[j].id,result:await assessGenericRecordContradiction(providers,records[i],records[j],'case-records',policy)});const strategy=await recommendGenericRecordFollowUp(providers,'case-records',{deterministic,requestedItems:source.requestedItems??[],records:records.slice(0,20).map(record=>({id:record.id,filename:record.filename,category:record.category,text:record.text??''})),extracted:analyzed.map(item=>({id:item.id,classification:item.classification.value,facts:item.facts.value})),contradictions:contradictions.filter(item=>item.result.value.contradictory).map(item=>({leftId:item.leftId,rightId:item.rightId,analysis:item.result.value}))},policy);return {...deterministic,aiStrategy:strategy.value,aiProvenance:{providers:strategy.providers,confidence:strategy.confidence,disagreements:strategy.disagreements,warnings:strategy.warnings},aiRecordAnalysis:analyzed.map(item=>({id:item.id,classification:item.classification.value,facts:item.facts.value,classificationProvenance:item.classification.providers,factProvenance:item.facts.providers})),aiContradictions:contradictions.filter(item=>item.result.value.contradictory).map(item=>({leftId:item.leftId,rightId:item.rightId,analysis:item.result.value,providers:item.result.providers}))}}},
})
