import type { ValidatedRequest } from '../request-service'
import { createRecordsWorkflow, type RecordsWorkflow } from '../workflow-factory'
import type { RecordsDomainCapability } from './domain-pack'
import { analyzeGenericProduction, type GenericProductionRecord } from './generic-records-analysis'
import { assessGenericRecordContradiction, classifyGenericRecord, extractGenericRecordFacts, recommendGenericRecordFollowUp } from './generic-records-ai'
import { getConfiguredRecordsLlmProviders } from '../ai/records-llm-providers'

export const DEATH_RECORD_CATEGORIES = [
  'certificate-copy-type-and-availability',
  'registration-index-and-search-result-records',
  'public-confidential-restricted-and-medical-detail-access-status',
  'eligibility-relationship-and-authorization-requirements',
  'application-order-and-submission-requirements',
  'identity-verification-notarization-and-supporting-document-requirements',
  'registration-cause-of-death-and-medical-detail-status',
  'amendment-correction-supplement-and-status-records',
  'fees-processing-delivery-and-order-status-records',
  'agency-custodian-referral-and-jurisdiction-records',
  'denial-restriction-no-record-found-and-review-status',
] as const

export const DEATH_RECORD_CAPABILITIES: readonly RecordsDomainCapability[] = ['classification','extraction','deadline','contradiction','findings','evidence','research','risk','strategy','draft','draftProvenance','validation','review','approval','mailing','tracking','proofAudit']

export const DEATH_RECORD_INTAKE = [
  { id:'agency', label:'Vital records office / custodian', required:true, helpText:'State, county, city, territorial, archive, or other office believed to hold or issue the record.' },
  { id:'jurisdiction', label:'Jurisdiction', required:true, helpText:'State, county, territory, or other jurisdiction where the death was registered.' },
  { id:'recordName', label:'Name on the death record', required:true, helpText:'Name as it appears, or likely appears, on the record.' },
  { id:'deathYear', label:'Death year', required:true, helpText:'Year of death or registration.' },
  { id:'deathPlace', label:'Place of death', helpText:'City, county, facility, or other location when known.' },
  { id:'certificateNumber', label:'Certificate / registration number', helpText:'Certificate, registration, file, state-file, or other record number when known.' },
  { id:'requesterCapacity', label:'Requester capacity', required:true, helpText:'For example: immediate family member, legal representative, authorized agent, genealogical requester, or member of the public where lawful.' },
  { id:'relationship', label:'Relationship / authority', helpText:'Relationship or legal authority supporting access if the requested copy or medical-detail field is restricted.' },
  { id:'copyType', label:'Desired copy / record type', helpText:'Certified, informational, genealogical, verification, redacted, medical-detail, or other jurisdiction-specific product where offered.' },
  { id:'existingOrderNumber', label:'Existing order / application number', helpText:'Order, application, tracking, or correspondence number if following up.' },
  { id:'dateStart', label:'Request / search period start', required:true, helpText:'Beginning of the relevant search, order, or status period.' },
  { id:'dateEnd', label:'Request / search period end', required:true, helpText:'End of the relevant search, order, or status period.' },
  { id:'subjectMatter', label:'Objective', required:true, helpText:'Plain-English description of the certificate, verification, correction, access-status, or order-status objective.' },
] as const

function text(input:Record<string,unknown>,key:string):string|undefined{const raw=input[key];if(typeof raw!=='string')return undefined;const v=raw.trim();return v||undefined}
function selectedCategories(input:Record<string,unknown>):string[]{const raw=input.categories;if(!Array.isArray(raw))return [...DEATH_RECORD_CATEGORIES];const known=new Set(DEATH_RECORD_CATEGORIES);const selected=raw.filter((e):e is string=>typeof e==='string'&&known.has(e as typeof DEATH_RECORD_CATEGORIES[number]));return selected.length?selected:[...DEATH_RECORD_CATEGORIES]}
function scopeText(input:Record<string,unknown>):string{const ids=[text(input,'recordName')&&`record name ${text(input,'recordName')}`,text(input,'deathYear')&&`death year ${text(input,'deathYear')}`,text(input,'deathPlace')&&`death place ${text(input,'deathPlace')}`,text(input,'certificateNumber')&&`certificate/registration number ${text(input,'certificateNumber')}`,text(input,'existingOrderNumber')&&`order/application number ${text(input,'existingOrderNumber')}`].filter(Boolean);const start=text(input,'dateStart'),end=text(input,'dateEnd');return `${ids.length?` Identify the matter using: ${ids.join('; ')}.`:''}${start&&end?` Cover request/search activity from ${start} through ${end}.`:''}`}
function accessText(input:Record<string,unknown>):string{return `${text(input,'requesterCapacity')?` Requester capacity: ${text(input,'requesterCapacity')}.`:''}${text(input,'relationship')?` Relationship/authority: ${text(input,'relationship')}.`:''}${text(input,'copyType')?` Desired copy/record type: ${text(input,'copyType')}.`:''}`}
function describe(category:string,input:Record<string,unknown>):string{
  const scope=scopeText(input),access=accessText(input),objective=text(input,'subjectMatter')?` Objective: ${text(input,'subjectMatter')}.`:''
  const descriptions:Record<string,string>={
    'certificate-copy-type-and-availability':`Records or written information sufficient to identify which death-certificate, certified, informational, redacted, genealogical, verification, or other jurisdiction-specific products are available for this record and requester. Do not assume every certificate field or copy type is public.${scope}${access}`,
    'registration-index-and-search-result-records':`Lawfully accessible death-registration indexes, search results, verification records, and no-record-found information sufficient to identify whether the office located the record and which identifiers may lawfully be disclosed.${scope}${access}`,
    'public-confidential-restricted-and-medical-detail-access-status':`Written information sufficient to determine which death-record fields or products are public, restricted, confidential, redacted, family-only, requester-specific, or subject to separate access rules for cause-of-death or medical information. Request lawful status and conditions, not circumvention.${scope}${access}`,
    'eligibility-relationship-and-authorization-requirements':`Current written requester-eligibility, kinship/relationship, legal-representative, authorization, court-order, agency-purpose, or other access requirements for the requested death-record product or restricted fields.${scope}${access}`,
    'application-order-and-submission-requirements':`Current application/order forms, required fields, signatures, submission instructions, accepted channels, and records sufficient to identify how a lawful death-record request must be submitted.${scope}${access}`,
    'identity-verification-notarization-and-supporting-document-requirements':`Current written requirements for identity verification, notarization, sworn statements, relationship proof, authorization, representative authority, court orders, or supporting documents. Request the requirements and status only; do not request authentication secrets or another person's protected identity documents.${scope}${access}`,
    'registration-cause-of-death-and-medical-detail-status':`Lawfully accessible records or written status sufficient to identify whether the death was registered and whether cause-of-death, manner, medical-certifier, medical-detail, or related fields are available to this requester. Do not request protected medical details unless the requester is legally entitled to receive them.${scope}${access}`,
    'amendment-correction-supplement-and-status-records':`Lawfully accessible amendment, correction, supplementation, delayed-registration, or change-status records and procedures sufficient to identify whether the official death record changed and the current status of a correction matter.${scope}${access}`,
    'fees-processing-delivery-and-order-status-records':`Current fee schedule, processing guidance, delivery/certification options, expedite options if offered, and lawfully accessible order/application status. Do not request payment-card, bank-account, or authentication credentials.${scope}${access}`,
    'agency-custodian-referral-and-jurisdiction-records':`Records or written information sufficient to identify the correct issuing office, registrar, medical examiner/coroner records custodian, archive, state office, or referral destination when the current office does not hold or issue the requested product. Do not conflate vital records with separate coroner/medical-examiner investigative records.${scope}${access}`,
    'denial-restriction-no-record-found-and-review-status':`Written denial, restriction, no-record-found, incomplete-application, insufficient-eligibility, restricted-medical-detail, or other nonproduction status; the stated reason; available cure/review procedure; and any segregable status information the requester may lawfully receive.${scope}${access}`,
  }
  return `${descriptions[category]??`Records concerning ${category}.${scope}${access}`}${objective}`
}
function validateDeathRecords(request:ValidatedRequest):readonly {field:string;message:string}[]{const issues:{field:string;message:string}[]=[];const corpus=request.items.map(i=>i.description.toLowerCase()).join(' ');if(!corpus.includes('record name '))issues.push({field:'recordName',message:'Provide the name on the death record.'});if(!corpus.includes('death year '))issues.push({field:'deathYear',message:'Provide the death year.'});if(!corpus.includes('requester capacity:'))issues.push({field:'requesterCapacity',message:'State the requester capacity so access can be evaluated.'});if(!corpus.includes('cover request/search activity'))issues.push({field:'dateRange',message:'Provide the relevant request or search period.'});if(!corpus.includes('objective:'))issues.push({field:'subjectMatter',message:'Describe the death-record objective.'});return issues}
export function buildDeathRecordsRequest(input:Record<string,unknown>){const name=text(input,'recordName'),year=text(input,'deathYear'),start=text(input,'dateStart'),end=text(input,'dateEnd'),categories=selectedCategories(input);return {title:`Death Records — ${name??'Record'}${year?` (${year})`:''}`,agency:text(input,'agency')??'',jurisdiction:text(input,'jurisdiction'),purpose:text(input,'purpose')??'Determine lawful access and obtain, verify, correct, or track the appropriate death-record product or status for the identified record.',scope:JSON.stringify({workflow:'death-records',recordName:name,deathYear:year,deathPlace:text(input,'deathPlace'),certificateNumber:text(input,'certificateNumber'),requesterCapacity:text(input,'requesterCapacity'),relationship:text(input,'relationship'),copyType:text(input,'copyType'),existingOrderNumber:text(input,'existingOrderNumber'),dateStart:start,dateEnd:end,jurisdiction:text(input,'jurisdiction'),subjectMatter:text(input,'subjectMatter')}),items:categories.map(category=>({category,description:describe(category,input),dateStart:start,dateEnd:end,custodian:text(input,'agency'),systemHint:category==='registration-index-and-search-result-records'||category==='registration-cause-of-death-and-medical-detail-status'?'vital-registration / index system':category==='fees-processing-delivery-and-order-status-records'||category==='application-order-and-submission-requirements'?'vital-records order / application system':undefined}))}}
export const DEATH_RECORD_FINDINGS=['MISSING_REQUESTED_CATEGORY','REFERENCED_RECORD_NOT_PRODUCED','IDENTIFIER_MISMATCH','DATE_GAP','DUPLICATE_RECORD','MISSING_ATTACHMENT','UNEXPLAINED_WITHHOLDING','REDACTION_REVIEW','PARTIAL_PRODUCTION','UNRESPONSIVE_ITEM'] as const
export const productionDeathRecordsWorkflow:RecordsWorkflow=createRecordsWorkflow({
  id:'death-records',name:'Death Records Request',description:'Build a lawful death-record request covering certificate availability, registration/search status, public/restricted access, cause-of-death and medical-detail access status, eligibility, applications, corrections, fees/order status, referrals, and restrictions.',searchIntent:'death records request',seo:{title:'Death Records Request — Certificates, Access, Cause-of-Death Status & Orders',description:'Build a lawful death-record request for certificate availability, access rules, registration and cause-of-death status, eligibility, corrections, fees, and order status.',canonicalPath:'/workflows/death-records'},intakeVersion:'2.0.0',intake:DEATH_RECORD_INTAKE,capabilities:DEATH_RECORD_CAPABILITIES,request:{categories:DEATH_RECORD_CATEGORIES,build:buildDeathRecordsRequest},validate:validateDeathRecords,
  policies:[{jurisdiction:'all',version:'2.0.0',rules:{determineJurisdictionSpecificEligibilityAndFieldLevelAccessBeforeRequestingRestrictedContent:true,doNotAssumeDeathCertificatesCauseOfDeathOrMedicalDetailsArePublic:true,doNotImpersonateOrBypassRelationshipAuthorizationIdentityNotarizationCourtOrderOrOtherAccessRequirements:true,doNotRequestProtectedMedicalDetailsWithoutLawfulAccess:true,doNotRequestAuthenticationSecretsOrAnotherPersonsProtectedIdentityDocuments:true,requestOnlyLawfullyAccessibleProductsStatusAndSegregableInformation:true,distinguishVitalRecordsFromCoronerMedicalExaminerInvestigativeRecords:true,preserveCertificateOrderAndRegistrationIdentifiers:true,requireHumanReviewBeforeSubmissionWhenMedicalDetailEligibilityOrAuthorizationIsUnclear:true}}],
  responseAnalysis:{findingTypes:DEATH_RECORD_FINDINGS,async analyze(input:unknown){if(!input||typeof input!=='object')throw new Error('DEATH_PRODUCTION_ANALYSIS_INPUT_INVALID');const source=input as {requestedItems?:readonly {category:string;description:string}[];records?:readonly GenericProductionRecord[]};const records=source.records??[];const requested=(source.requestedItems??[]).map(item=>({id:item.category,label:item.category,keywords:item.description.split(/\W+/).filter(w=>w.length>=4).slice(0,20)}));const deterministic=analyzeGenericProduction(requested,records,'death-record request record');const providers=getConfiguredRecordsLlmProviders();if(providers.length<2)return deterministic;const policy={minimumProviders:2,agreementThreshold:0.67,maxProviders:3} as const;const requestedCategories=requested.map(i=>i.id);const analyzed=await Promise.all(records.slice(0,20).map(async record=>({id:record.id,classification:await classifyGenericRecord(providers,record,'death-records',requestedCategories,policy),facts:await extractGenericRecordFacts(providers,record,'death-records',policy)})));const contradictions:Array<{leftId:string;rightId:string;result:Awaited<ReturnType<typeof assessGenericRecordContradiction>>}>=[];for(let i=0;i<Math.min(records.length,10);i+=1)for(let j=i+1;j<Math.min(records.length,10);j+=1)contradictions.push({leftId:records[i].id,rightId:records[j].id,result:await assessGenericRecordContradiction(providers,records[i],records[j],'death-records',policy)});const strategy=await recommendGenericRecordFollowUp(providers,'death-records',{deterministic,requestedItems:source.requestedItems??[],records:records.slice(0,20).map(r=>({id:r.id,filename:r.filename,category:r.category,text:r.text??''})),extracted:analyzed.map(i=>({id:i.id,classification:i.classification.value,facts:i.facts.value})),contradictions:contradictions.filter(i=>i.result.value.contradictory).map(i=>({leftId:i.leftId,rightId:i.rightId,analysis:i.result.value}))},policy);return {...deterministic,aiStrategy:strategy.value,aiProvenance:{providers:strategy.providers,confidence:strategy.confidence,disagreements:strategy.disagreements,warnings:strategy.warnings},aiRecordAnalysis:analyzed.map(i=>({id:i.id,classification:i.classification.value,facts:i.facts.value,classificationProvenance:i.classification.providers,factProvenance:i.facts.providers})),aiContradictions:contradictions.filter(i=>i.result.value.contradictory).map(i=>({leftId:i.leftId,rightId:i.rightId,analysis:i.result.value,providers:i.result.providers}))}}},
})
