import type { ValidatedRequest } from '../request-service'
import { createRecordsWorkflow, type RecordsWorkflow } from '../workflow-factory'
import type { RecordsDomainCapability } from './domain-pack'
import { analyzeGenericProduction, type GenericProductionRecord } from './generic-records-analysis'
import { assessGenericRecordContradiction, classifyGenericRecord, extractGenericRecordFacts, recommendGenericRecordFollowUp } from './generic-records-ai'
import { getConfiguredRecordsLlmProviders } from '../ai/records-llm-providers'

export const DIVORCE_RECORD_CATEGORIES = [
  'decree-judgment-certificate-and-copy-availability',
  'case-index-docket-and-disposition-status',
  'public-sealed-confidential-and-restricted-access-status',
  'eligibility-party-representative-and-authorization-requirements',
  'copy-order-application-and-submission-requirements',
  'identity-verification-notarization-and-supporting-document-requirements',
  'judgment-entry-dissolution-and-finality-status',
  'amendment-correction-vacatur-and-status-records',
  'fees-processing-delivery-and-order-status-records',
  'court-vital-records-custodian-referral-and-jurisdiction-records',
  'denial-restriction-no-record-found-and-review-status',
] as const

export const DIVORCE_RECORD_CAPABILITIES: readonly RecordsDomainCapability[] = ['classification','extraction','deadline','contradiction','findings','evidence','research','risk','strategy','draft','draftProvenance','validation','review','approval','mailing','tracking','proofAudit']

export const DIVORCE_RECORD_INTAKE = [
  { id:'agency', label:'Court / vital records office', required:true, helpText:'Court clerk, state vital records office, county office, archive, or other lawful custodian.' },
  { id:'jurisdiction', label:'Jurisdiction', required:true, helpText:'Court, county, state, territory, or other jurisdiction where the dissolution was filed or registered.' },
  { id:'party1Name', label:'First party name', required:true, helpText:'Name of one party as it appears, or likely appears, on the record.' },
  { id:'party2Name', label:'Second party name', helpText:'Name of the other party when known.' },
  { id:'caseNumber', label:'Case / docket number', helpText:'Divorce, dissolution, family-court, or docket number when known.' },
  { id:'divorceYear', label:'Divorce / judgment year', required:true, helpText:'Year of judgment, decree, dissolution, or registration.' },
  { id:'requesterCapacity', label:'Requester capacity', required:true, helpText:'For example: party to the case, authorized representative, attorney/agent with authority, genealogical requester, or member of the public where lawful.' },
  { id:'relationship', label:'Relationship / authority', helpText:'Relationship or legal authority supporting access if the requested record is restricted.' },
  { id:'copyType', label:'Desired record / copy type', helpText:'Decree, judgment, certified copy, verification, certificate, docket, informational copy, or other jurisdiction-specific product.' },
  { id:'existingOrderNumber', label:'Existing order / request number', helpText:'Copy order, application, tracking, or correspondence number if following up.' },
  { id:'dateStart', label:'Request / search period start', required:true, helpText:'Beginning of the relevant search, order, or case-status period.' },
  { id:'dateEnd', label:'Request / search period end', required:true, helpText:'End of the relevant search, order, or case-status period.' },
  { id:'subjectMatter', label:'Objective', required:true, helpText:'Plain-English description of the decree, judgment, verification, case status, correction, or copy objective.' },
] as const

function text(input:Record<string,unknown>,key:string):string|undefined{const raw=input[key];if(typeof raw!=='string')return undefined;const v=raw.trim();return v||undefined}
function selectedCategories(input:Record<string,unknown>):string[]{const raw=input.categories;if(!Array.isArray(raw))return [...DIVORCE_RECORD_CATEGORIES];const known=new Set(DIVORCE_RECORD_CATEGORIES);const selected=raw.filter((e):e is string=>typeof e==='string'&&known.has(e as typeof DIVORCE_RECORD_CATEGORIES[number]));return selected.length?selected:[...DIVORCE_RECORD_CATEGORIES]}
function scopeText(input:Record<string,unknown>):string{const ids=[text(input,'party1Name')&&`first party ${text(input,'party1Name')}`,text(input,'party2Name')&&`second party ${text(input,'party2Name')}`,text(input,'caseNumber')&&`case/docket number ${text(input,'caseNumber')}`,text(input,'divorceYear')&&`divorce/judgment year ${text(input,'divorceYear')}`,text(input,'existingOrderNumber')&&`order/request number ${text(input,'existingOrderNumber')}`].filter(Boolean);const start=text(input,'dateStart'),end=text(input,'dateEnd');return `${ids.length?` Identify the matter using: ${ids.join('; ')}.`:''}${start&&end?` Cover request/search activity from ${start} through ${end}.`:''}`}
function accessText(input:Record<string,unknown>):string{return `${text(input,'requesterCapacity')?` Requester capacity: ${text(input,'requesterCapacity')}.`:''}${text(input,'relationship')?` Relationship/authority: ${text(input,'relationship')}.`:''}${text(input,'copyType')?` Desired record/copy type: ${text(input,'copyType')}.`:''}`}
function describe(category:string,input:Record<string,unknown>):string{
  const scope=scopeText(input),access=accessText(input),objective=text(input,'subjectMatter')?` Objective: ${text(input,'subjectMatter')}.`:''
  const descriptions:Record<string,string>={
    'decree-judgment-certificate-and-copy-availability':`Records or written information sufficient to identify which divorce decree, dissolution judgment, certificate, verification, certified copy, informational copy, or other jurisdiction-specific products are available for this case and requester. Do not assume the full family-court file is public.${scope}${access}`,
    'case-index-docket-and-disposition-status':`Lawfully accessible case index, docket, register of actions, disposition, filing-date, judgment-date, and case-status information sufficient to identify the proceeding and locate the requested final record.${scope}${access}`,
    'public-sealed-confidential-and-restricted-access-status':`Written information sufficient to determine whether the requested decree, docket, filing, exhibit, or family-case material is public, sealed, confidential, redacted, restricted, or available only to specified parties in this jurisdiction. Request lawful status and access conditions, not circumvention.${scope}${access}`,
    'eligibility-party-representative-and-authorization-requirements':`Current written eligibility, party-status, representative, authorization, court-order, or other requester requirements for the desired divorce-record product or restricted family-court material.${scope}${access}`,
    'copy-order-application-and-submission-requirements':`Current copy-order/application forms, required fields, signatures, submission instructions, accepted channels, clerk procedures, and records sufficient to identify how a lawful request for the selected divorce-record product must be submitted.${scope}${access}`,
    'identity-verification-notarization-and-supporting-document-requirements':`Current written requirements for identity verification, notarization, authorization, representative authority, court orders, or supporting documents. Request the requirements and status only; do not request authentication secrets or another person's protected identity documents.${scope}${access}`,
    'judgment-entry-dissolution-and-finality-status':`Lawfully accessible records sufficient to identify judgment/decree entry, dissolution status, effective/finality date if maintained, disposition, and whether the requested final order or certificate has been entered or registered. Do not infer marital status beyond the official record produced.${scope}${access}`,
    'amendment-correction-vacatur-and-status-records':`Lawfully accessible amendment, correction, nunc-pro-tunc, vacatur/set-aside, replacement-copy, or record-correction status and procedures sufficient to identify whether the final record changed and the current official status.${scope}${access}`,
    'fees-processing-delivery-and-order-status-records':`Current fee schedule, processing guidance, delivery/certification options, expedite options if offered, and lawfully accessible order/application status. Do not request payment-card, bank-account, or authentication credentials.${scope}${access}`,
    'court-vital-records-custodian-referral-and-jurisdiction-records':`Records or written information sufficient to identify whether the court, state vital-records office, county clerk/recorder, archive, or other custodian issues the requested product and where a request should be directed if the current office is not the correct custodian.${scope}${access}`,
    'denial-restriction-no-record-found-and-review-status':`Written denial, restriction, sealed/confidential status, no-record-found result, incomplete-request status, insufficient eligibility, or other nonproduction response; the stated reason; available cure/review procedure; and any segregable status information the requester may lawfully receive.${scope}${access}`,
  }
  return `${descriptions[category]??`Records concerning ${category}.${scope}${access}`}${objective}`
}
function validateDivorceRecords(request:ValidatedRequest):readonly {field:string;message:string}[]{const issues:{field:string;message:string}[]=[];const corpus=request.items.map(i=>i.description.toLowerCase()).join(' ');if(!corpus.includes('first party '))issues.push({field:'party1Name',message:'Provide at least one party name.'});if(!corpus.includes('divorce/judgment year '))issues.push({field:'divorceYear',message:'Provide the divorce or judgment year.'});if(!corpus.includes('requester capacity:'))issues.push({field:'requesterCapacity',message:'State the requester capacity so access can be evaluated.'});if(!corpus.includes('cover request/search activity'))issues.push({field:'dateRange',message:'Provide the relevant request or search period.'});if(!corpus.includes('objective:'))issues.push({field:'subjectMatter',message:'Describe the divorce-record objective.'});return issues}
export function buildDivorceRecordsRequest(input:Record<string,unknown>){const p1=text(input,'party1Name'),p2=text(input,'party2Name'),caseNumber=text(input,'caseNumber'),year=text(input,'divorceYear'),start=text(input,'dateStart'),end=text(input,'dateEnd'),categories=selectedCategories(input);return {title:`Divorce Records — ${caseNumber??(p1&&p2?`${p1} & ${p2}`:p1??'Record')}${year?` (${year})`:''}`,agency:text(input,'agency')??'',jurisdiction:text(input,'jurisdiction'),purpose:text(input,'purpose')??'Determine lawful access and obtain, verify, correct, or track the appropriate divorce decree, judgment, certificate, docket/status, or copy for the identified proceeding.',scope:JSON.stringify({workflow:'divorce-records',party1Name:p1,party2Name:p2,caseNumber,divorceYear:year,requesterCapacity:text(input,'requesterCapacity'),relationship:text(input,'relationship'),copyType:text(input,'copyType'),existingOrderNumber:text(input,'existingOrderNumber'),dateStart:start,dateEnd:end,jurisdiction:text(input,'jurisdiction'),subjectMatter:text(input,'subjectMatter')}),items:categories.map(category=>({category,description:describe(category,input),dateStart:start,dateEnd:end,custodian:text(input,'agency'),systemHint:category==='case-index-docket-and-disposition-status'||category==='judgment-entry-dissolution-and-finality-status'?'court case-management / docket system':category==='fees-processing-delivery-and-order-status-records'||category==='copy-order-application-and-submission-requirements'?'court/vital-records copy order system':undefined}))}}
export const DIVORCE_RECORD_FINDINGS=['MISSING_REQUESTED_CATEGORY','REFERENCED_RECORD_NOT_PRODUCED','IDENTIFIER_MISMATCH','DATE_GAP','DUPLICATE_RECORD','MISSING_ATTACHMENT','UNEXPLAINED_WITHHOLDING','REDACTION_REVIEW','PARTIAL_PRODUCTION','UNRESPONSIVE_ITEM'] as const
export const productionDivorceRecordsWorkflow:RecordsWorkflow=createRecordsWorkflow({
  id:'divorce-records',name:'Divorce Records Request',description:'Build a lawful divorce-record request for decrees/judgments, case index and disposition status, access restrictions, eligibility, copy ordering, finality status, corrections, fees, referrals, and review status.',searchIntent:'divorce records request',seo:{title:'Divorce Records Request — Decrees, Judgments, Access & Copy Status',description:'Build a lawful divorce-record request for decrees, judgments, docket/disposition status, access rules, copy requirements, corrections, fees, and order status.',canonicalPath:'/workflows/divorce-records'},intakeVersion:'2.0.0',intake:DIVORCE_RECORD_INTAKE,capabilities:DIVORCE_RECORD_CAPABILITIES,request:{categories:DIVORCE_RECORD_CATEGORIES,build:buildDivorceRecordsRequest},validate:validateDivorceRecords,
  policies:[{jurisdiction:'all',version:'2.0.0',rules:{determinePublicSealedConfidentialOrRestrictedStatusBeforeRequestingSensitiveFamilyCaseContent:true,doNotAssumeDivorceCaseFilesOrSupportingFamilyRecordsArePublic:true,doNotImpersonateOrBypassPartyAuthorizationIdentityCourtOrderOrOtherAccessRequirements:true,doNotRequestProtectedMinorMedicalFinancialOrAuthenticationDataWithoutLawfulAccess:true,requestOnlyLawfullyAccessibleProductsStatusAndSegregableInformation:true,routeBroadFiledCaseMaterialResearchToCourtRecordsWorkflow:true,preserveCaseOrderAndJudgmentIdentifiers:true,requireHumanReviewBeforeSubmissionWhenSealingConfidentialityEligibilityOrAuthorizationIsUnclear:true}}],
  responseAnalysis:{findingTypes:DIVORCE_RECORD_FINDINGS,async analyze(input:unknown){if(!input||typeof input!=='object')throw new Error('DIVORCE_PRODUCTION_ANALYSIS_INPUT_INVALID');const source=input as {requestedItems?:readonly {category:string;description:string}[];records?:readonly GenericProductionRecord[]};const records=source.records??[];const requested=(source.requestedItems??[]).map(item=>({id:item.category,label:item.category,keywords:item.description.split(/\W+/).filter(w=>w.length>=4).slice(0,20)}));const deterministic=analyzeGenericProduction(requested,records,'divorce-record request record');const providers=getConfiguredRecordsLlmProviders();if(providers.length<2)return deterministic;const policy={minimumProviders:2,agreementThreshold:0.67,maxProviders:3} as const;const requestedCategories=requested.map(i=>i.id);const analyzed=await Promise.all(records.slice(0,20).map(async record=>({id:record.id,classification:await classifyGenericRecord(providers,record,'divorce-records',requestedCategories,policy),facts:await extractGenericRecordFacts(providers,record,'divorce-records',policy)})));const contradictions:Array<{leftId:string;rightId:string;result:Awaited<ReturnType<typeof assessGenericRecordContradiction>>}>=[];for(let i=0;i<Math.min(records.length,10);i+=1)for(let j=i+1;j<Math.min(records.length,10);j+=1)contradictions.push({leftId:records[i].id,rightId:records[j].id,result:await assessGenericRecordContradiction(providers,records[i],records[j],'divorce-records',policy)});const strategy=await recommendGenericRecordFollowUp(providers,'divorce-records',{deterministic,requestedItems:source.requestedItems??[],records:records.slice(0,20).map(r=>({id:r.id,filename:r.filename,category:r.category,text:r.text??''})),extracted:analyzed.map(i=>({id:i.id,classification:i.classification.value,facts:i.facts.value})),contradictions:contradictions.filter(i=>i.result.value.contradictory).map(i=>({leftId:i.leftId,rightId:i.rightId,analysis:i.result.value}))},policy);return {...deterministic,aiStrategy:strategy.value,aiProvenance:{providers:strategy.providers,confidence:strategy.confidence,disagreements:strategy.disagreements,warnings:strategy.warnings},aiRecordAnalysis:analyzed.map(i=>({id:i.id,classification:i.classification.value,facts:i.facts.value,classificationProvenance:i.classification.providers,factProvenance:i.facts.providers})),aiContradictions:contradictions.filter(i=>i.result.value.contradictory).map(i=>({leftId:i.leftId,rightId:i.rightId,analysis:i.result.value,providers:i.result.providers}))}}},
})
