import type { ValidatedRequest } from '../request-service'
import { createRecordsWorkflow, type RecordsWorkflow } from '../workflow-factory'
import type { RecordsDomainCapability } from './domain-pack'
import { analyzeGenericProduction, type GenericProductionRecord } from './generic-records-analysis'
import { assessGenericRecordContradiction, classifyGenericRecord, extractGenericRecordFacts, recommendGenericRecordFollowUp } from './generic-records-ai'
import { getConfiguredRecordsLlmProviders } from '../ai/records-llm-providers'

export const EDUCATION_RECORD_CATEGORIES = [
  'record-index-directory-and-access-status',
  'transcripts-grades-credits-and-academic-history',
  'enrollment-registration-program-and-completion-history',
  'attendance-schedule-and-course-participation-records',
  'discipline-conduct-and-resolution-records',
  'assessment-testing-and-progress-records',
  'special-education-accommodation-and-support-plan-records',
  'student-services-advising-and-program-records',
  'consent-disclosure-and-record-access-history',
  'amendment-correction-challenge-and-request-status',
  'format-fees-delivery-and-order-status',
  'withholding-unavailable-record-and-review-status',
] as const

export const EDUCATION_RECORD_CAPABILITIES: readonly RecordsDomainCapability[] = ['classification','extraction','deadline','contradiction','findings','evidence','research','risk','strategy','draft','draftProvenance','validation','review','approval','mailing','tracking','proofAudit']

export const EDUCATION_RECORD_INTAKE = [
  { id:'agency', label:'School / district / institution / records custodian', required:true, helpText:'School, district, college, university, registrar, records office, or other lawful custodian.' },
  { id:'studentName', label:'Student name', required:true, helpText:'Name associated with the requested education record.' },
  { id:'requesterCapacity', label:'Requester capacity', required:true, helpText:'For example: eligible student, parent/guardian with applicable rights, or authorized representative.' },
  { id:'authorizationBasis', label:'Authorization / authority', helpText:'Consent, guardianship, power of attorney, institutional authorization, or other lawful basis when required.' },
  { id:'studentId', label:'Student / applicant / record identifier', helpText:'Student ID, application ID, alumni ID, or other non-secret record identifier when known.' },
  { id:'schoolProgram', label:'School / campus / program', helpText:'School, campus, grade level, department, degree program, or academic program.' },
  { id:'dateStart', label:'Record period start', required:true, helpText:'Beginning of the enrollment or records period.' },
  { id:'dateEnd', label:'Record period end', required:true, helpText:'End of the enrollment or records period.' },
  { id:'preferredFormat', label:'Preferred format', helpText:'Electronic PDF, official transcript delivery, machine-readable export, or other format where available.' },
  { id:'subjectMatter', label:'Records objective', required:true, helpText:'Plain-English description of the education records or access/status issue.' },
] as const

function text(input:Record<string,unknown>,key:string):string|undefined{const raw=input[key];if(typeof raw!=='string')return undefined;const v=raw.trim();return v||undefined}
function selectedCategories(input:Record<string,unknown>):string[]{const raw=input.categories;if(!Array.isArray(raw))return [...EDUCATION_RECORD_CATEGORIES];const known=new Set(EDUCATION_RECORD_CATEGORIES);const selected=raw.filter((e):e is string=>typeof e==='string'&&known.has(e as typeof EDUCATION_RECORD_CATEGORIES[number]));return selected.length?selected:[...EDUCATION_RECORD_CATEGORIES]}
function scopeText(input:Record<string,unknown>):string{const ids=[text(input,'studentName')&&`student ${text(input,'studentName')}`,text(input,'studentId')&&`record identifier ${text(input,'studentId')}`,text(input,'schoolProgram')&&`school/program ${text(input,'schoolProgram')}`].filter(Boolean);const start=text(input,'dateStart'),end=text(input,'dateEnd');return `${ids.length?` Identify the records using: ${ids.join('; ')}.`:''}${start&&end?` Cover ${start} through ${end}.`:''}`}
function accessText(input:Record<string,unknown>):string{return `${text(input,'requesterCapacity')?` Requester capacity: ${text(input,'requesterCapacity')}.`:''}${text(input,'authorizationBasis')?` Authorization/authority: ${text(input,'authorizationBasis')}.`:''}`}
function describe(category:string,input:Record<string,unknown>):string{
  const scope=scopeText(input),access=accessText(input),objective=text(input,'subjectMatter')?` Objective: ${text(input,'subjectMatter')}.`:''
  const descriptions:Record<string,string>={
    'record-index-directory-and-access-status':`A lawfully accessible record index, education-record directory, transcript/order index, or equivalent listing sufficient to identify the record categories and systems maintained for the requested period, together with current access or eligibility status. Request only information the requester is lawfully entitled to receive.${scope}${access}`,
    'transcripts-grades-credits-and-academic-history':`Lawfully accessible official or unofficial transcripts, grades, credits, academic standing, degree or certificate history, transfer-credit records, and related academic-history records for the requested period.${scope}${access}`,
    'enrollment-registration-program-and-completion-history':`Lawfully accessible enrollment, registration, admission status, program/major history, withdrawal, completion, graduation, and credential-status records for the requested period.${scope}${access}`,
    'attendance-schedule-and-course-participation-records':`Lawfully accessible attendance, schedule, course registration, section, participation, and completion records for the requested period.${scope}${access}`,
    'discipline-conduct-and-resolution-records':`Lawfully accessible discipline, conduct, allegation/charge notice, hearing or review, sanction, resolution, and appeal-status records. Do not assume third-party student information or restricted investigative material is available.${scope}${access}`,
    'assessment-testing-and-progress-records':`Lawfully accessible assessments, standardized or institutional test results, progress reports, evaluations, academic-progress records, and records sufficient to identify referenced results.${scope}${access}`,
    'special-education-accommodation-and-support-plan-records':`Lawfully accessible special-education, accommodation, accessibility, support-plan, evaluation, service, meeting, and implementation records when the requester has the required access rights. Do not request another student's records or bypass heightened confidentiality rules.${scope}${access}`,
    'student-services-advising-and-program-records':`Lawfully accessible advising, counseling-program, student-services, program-participation, internship/practicum, placement, and related records, excluding separately protected health or counseling content unless the requester is lawfully entitled to it.${scope}${access}`,
    'consent-disclosure-and-record-access-history':`Lawfully accessible consent, authorization, disclosure, record-access, directory-information election, and request-history records relevant to the identified student and requester, where maintained and available under applicable rules.${scope}${access}`,
    'amendment-correction-challenge-and-request-status':`Lawfully accessible amendment, correction, challenge, hearing/request, response, statement, and status records concerning disputed or incomplete education records.${scope}${access}`,
    'format-fees-delivery-and-order-status':`Current instructions, available formats, transcript/order delivery options, fee notices, processing/status communications, and records sufficient to track the identified request. Never request portal passwords, security answers, one-time codes, or authentication secrets.${scope}${access}`,
    'withholding-unavailable-record-and-review-status':`Written denial, withholding, unavailable-record, insufficient-authorization, non-retained-record, or other nonproduction status; the stated reason; any available cure/review path; and segregable information the requester may lawfully receive.${scope}${access}`,
  }
  return `${descriptions[category]??`Education records concerning ${category}.${scope}${access}`}${objective}`
}
function validateEducationRecords(request:ValidatedRequest):readonly {field:string;message:string}[]{const issues:{field:string;message:string}[]=[];const corpus=request.items.map(i=>i.description.toLowerCase()).join(' ');if(!corpus.includes('student '))issues.push({field:'studentName',message:'Provide the student name.'});if(!corpus.includes('requester capacity:'))issues.push({field:'requesterCapacity',message:'State the requester capacity and access basis.'});if(!corpus.includes('cover '))issues.push({field:'dateRange',message:'Provide the requested education-record period.'});if(!corpus.includes('objective:'))issues.push({field:'subjectMatter',message:'Describe the education-records objective.'});return issues}
export function buildEducationRecordsRequest(input:Record<string,unknown>){const student=text(input,'studentName'),start=text(input,'dateStart'),end=text(input,'dateEnd'),categories=selectedCategories(input);return {title:`Education Records — ${student??'Student'}`,agency:text(input,'agency')??'',jurisdiction:text(input,'jurisdiction'),purpose:text(input,'purpose')??'Obtain and reconcile the lawfully accessible education record set, access status, and unresolved production gaps for the identified student and period.',scope:JSON.stringify({workflow:'education-records',studentName:student,requesterCapacity:text(input,'requesterCapacity'),authorizationBasis:text(input,'authorizationBasis'),studentId:text(input,'studentId'),schoolProgram:text(input,'schoolProgram'),preferredFormat:text(input,'preferredFormat'),dateStart:start,dateEnd:end,subjectMatter:text(input,'subjectMatter')}),items:categories.map(category=>({category,description:describe(category,input),dateStart:start,dateEnd:end,custodian:text(input,'schoolProgram'),systemHint:category==='transcripts-grades-credits-and-academic-history'?'student information system / registrar / transcript system':category==='special-education-accommodation-and-support-plan-records'?'authorized special-education / accessibility records system':category==='discipline-conduct-and-resolution-records'?'student conduct / discipline system':undefined,format:category==='record-index-directory-and-access-status'?'native export, CSV, JSON, spreadsheet, or other machine-readable index where maintained and lawfully available':undefined}))}}

export const EDUCATION_RECORD_FINDINGS=['MISSING_REQUESTED_CATEGORY','REFERENCED_RECORD_NOT_PRODUCED','IDENTIFIER_MISMATCH','DATE_GAP','DUPLICATE_RECORD','MISSING_ATTACHMENT','UNEXPLAINED_WITHHOLDING','REDACTION_REVIEW','PARTIAL_PRODUCTION','UNRESPONSIVE_ITEM'] as const

export const productionEducationRecordsWorkflow:RecordsWorkflow=createRecordsWorkflow({
  id:'education-records',name:'Education Records Request',description:'Build an authorization-aware request for transcripts, enrollment, attendance, discipline, assessments, support-plan records, access history, corrections, and request status.',searchIntent:'education records request',seo:{title:'Education Records Request — Transcripts, Enrollment, Discipline & Student Records',description:'Build an authorization-aware education-records request for transcripts, enrollment, attendance, discipline, assessments, support records, corrections, formats, fees, and access status.',canonicalPath:'/workflows/education-records'},intakeVersion:'2.0.0',intake:EDUCATION_RECORD_INTAKE,capabilities:EDUCATION_RECORD_CAPABILITIES,request:{categories:EDUCATION_RECORD_CATEGORIES,build:buildEducationRecordsRequest},validate:validateEducationRecords,
  policies:[{jurisdiction:'all',version:'2.0.0',rules:{verifyEligibleStudentParentGuardianOrAuthorizedRepresentativeAccessBeforeProtectedRecords:true,doNotImpersonateStudentParentGuardianOrInstitution:true,doNotBypassConsentAuthorizationIdentityOrEducationPrivacyRestrictions:true,doNotRequestPasswordsSecurityAnswersOneTimeCodesOrAuthenticationSecrets:true,doNotRequestAnotherStudentsProtectedRecords:true,requestOnlyRecordsWithinLawfulRequesterAuthorityAndScope:true,requireHumanReviewWhenRequesterRightsOrSensitiveRecordAccessIsUnclear:true,preserveStudentCourseProgramRequestAndOrderIdentifiers:true}}],
  responseAnalysis:{findingTypes:EDUCATION_RECORD_FINDINGS,async analyze(input:unknown){if(!input||typeof input!=='object')throw new Error('EDUCATION_PRODUCTION_ANALYSIS_INPUT_INVALID');const source=input as {requestedItems?:readonly {category:string;description:string}[];records?:readonly GenericProductionRecord[]};const records=source.records??[];const requested=(source.requestedItems??[]).map(item=>({id:item.category,label:item.category,keywords:item.description.split(/\W+/).filter(w=>w.length>=4).slice(0,20)}));const deterministic=analyzeGenericProduction(requested,records,'education record');const providers=getConfiguredRecordsLlmProviders();if(providers.length<2)return deterministic;const policy={minimumProviders:2,agreementThreshold:0.67,maxProviders:3} as const;const requestedCategories=requested.map(i=>i.id);const analyzed=await Promise.all(records.slice(0,20).map(async record=>({id:record.id,classification:await classifyGenericRecord(providers,record,'education-records',requestedCategories,policy),facts:await extractGenericRecordFacts(providers,record,'education-records',policy)})));const contradictions:Array<{leftId:string;rightId:string;result:Awaited<ReturnType<typeof assessGenericRecordContradiction>>}>=[];for(let i=0;i<Math.min(records.length,10);i+=1)for(let j=i+1;j<Math.min(records.length,10);j+=1)contradictions.push({leftId:records[i].id,rightId:records[j].id,result:await assessGenericRecordContradiction(providers,records[i],records[j],'education-records',policy)});const strategy=await recommendGenericRecordFollowUp(providers,'education-records',{deterministic,requestedItems:source.requestedItems??[],records:records.slice(0,20).map(r=>({id:r.id,filename:r.filename,category:r.category,text:r.text??''})),extracted:analyzed.map(i=>({id:i.id,classification:i.classification.value,facts:i.facts.value})),contradictions:contradictions.filter(i=>i.result.value.contradictory).map(i=>({leftId:i.leftId,rightId:i.rightId,analysis:i.result.value}))},policy);return {...deterministic,aiStrategy:strategy.value,aiProvenance:{providers:strategy.providers,confidence:strategy.confidence,disagreements:strategy.disagreements,warnings:strategy.warnings},aiRecordAnalysis:analyzed.map(i=>({id:i.id,classification:i.classification.value,facts:i.facts.value,classificationProvenance:i.classification.providers,factProvenance:i.facts.providers})),aiContradictions:contradictions.filter(i=>i.result.value.contradictory).map(i=>({leftId:i.leftId,rightId:i.rightId,analysis:i.result.value,providers:i.result.providers}))}}},
})
