import type { ValidatedRequest } from '../request-service'
import { createRecordsWorkflow, type RecordsWorkflow } from '../workflow-factory'
import type { RecordsDomainCapability } from './domain-pack'
import { analyzeGenericProduction, type GenericProductionRecord } from './generic-records-analysis'
import { assessGenericRecordContradiction, classifyGenericRecord, extractGenericRecordFacts, recommendGenericRecordFollowUp } from './generic-records-ai'
import { getConfiguredRecordsLlmProviders } from '../ai/records-llm-providers'

export const EMPLOYMENT_RECORD_CATEGORIES = [
  'personnel-file-index-and-access-status',
  'application-hiring-onboarding-and-employment-history',
  'job-title-position-duty-and-classification-records',
  'compensation-payroll-earnings-and-deduction-records',
  'time-attendance-leave-and-schedule-records',
  'performance-evaluation-goal-and-review-records',
  'discipline-investigation-grievance-and-resolution-records',
  'training-certification-license-and-qualification-records',
  'benefit-election-and-employment-status-records',
  'separation-resignation-termination-and-offboarding-records',
  'employee-access-correction-and-request-history',
  'format-fees-delivery-and-request-status',
  'withholding-unavailable-record-and-review-status',
] as const

export const EMPLOYMENT_RECORD_CAPABILITIES: readonly RecordsDomainCapability[] = ['classification','extraction','deadline','contradiction','findings','evidence','research','risk','strategy','draft','draftProvenance','validation','review','approval','mailing','tracking','proofAudit']

export const EMPLOYMENT_RECORD_INTAKE = [
  { id:'agency', label:'Employer / agency / records custodian', required:true, helpText:'Employer, public agency, HR office, payroll office, personnel office, or other lawful custodian.' },
  { id:'employeeName', label:'Employee name', required:true, helpText:'Name associated with the requested employment record.' },
  { id:'requesterCapacity', label:'Requester capacity', required:true, helpText:'For example: employee/former employee or representative with valid authorization.' },
  { id:'authorizationBasis', label:'Authorization / authority', helpText:'Written authorization, representation authority, or other lawful basis when the requester is not the employee.' },
  { id:'employeeId', label:'Employee / personnel identifier', helpText:'Employee ID, personnel number, payroll number, or other non-secret identifier when known.' },
  { id:'positionOrUnit', label:'Position / department / bargaining unit', helpText:'Job title, department, division, location, classification, or bargaining unit.' },
  { id:'dateStart', label:'Record period start', required:true, helpText:'Beginning of the employment or records period.' },
  { id:'dateEnd', label:'Record period end', required:true, helpText:'End of the employment or records period.' },
  { id:'preferredFormat', label:'Preferred format', helpText:'Electronic PDF, payroll export, spreadsheet, or other format where available.' },
  { id:'subjectMatter', label:'Records objective', required:true, helpText:'Plain-English description of the employment records or access/status issue.' },
] as const

function text(input:Record<string,unknown>,key:string):string|undefined{const raw=input[key];if(typeof raw!=='string')return undefined;const v=raw.trim();return v||undefined}
function selectedCategories(input:Record<string,unknown>):string[]{const raw=input.categories;if(!Array.isArray(raw))return [...EMPLOYMENT_RECORD_CATEGORIES];const known=new Set(EMPLOYMENT_RECORD_CATEGORIES);const selected=raw.filter((e):e is string=>typeof e==='string'&&known.has(e as typeof EMPLOYMENT_RECORD_CATEGORIES[number]));return selected.length?selected:[...EMPLOYMENT_RECORD_CATEGORIES]}
function scopeText(input:Record<string,unknown>):string{const ids=[text(input,'employeeName')&&`employee ${text(input,'employeeName')}`,text(input,'employeeId')&&`personnel identifier ${text(input,'employeeId')}`,text(input,'positionOrUnit')&&`position/unit ${text(input,'positionOrUnit')}`].filter(Boolean);const start=text(input,'dateStart'),end=text(input,'dateEnd');return `${ids.length?` Identify the records using: ${ids.join('; ')}.`:''}${start&&end?` Cover ${start} through ${end}.`:''}`}
function accessText(input:Record<string,unknown>):string{return `${text(input,'requesterCapacity')?` Requester capacity: ${text(input,'requesterCapacity')}.`:''}${text(input,'authorizationBasis')?` Authorization/authority: ${text(input,'authorizationBasis')}.`:''}`}
function describe(category:string,input:Record<string,unknown>):string{
  const scope=scopeText(input),access=accessText(input),objective=text(input,'subjectMatter')?` Objective: ${text(input,'subjectMatter')}.`:''
  const descriptions:Record<string,string>={
    'personnel-file-index-and-access-status':`A lawfully accessible personnel-file index, document list, HR-record directory, payroll-record index, or equivalent listing sufficient to identify the employment record categories maintained for the requested period, together with current requester access status. Request only records the requester is legally entitled to receive.${scope}${access}`,
    'application-hiring-onboarding-and-employment-history':`Lawfully accessible application, offer, appointment, onboarding, employment-verification, service-date, assignment-history, and employment-status records for the identified employee.${scope}${access}`,
    'job-title-position-duty-and-classification-records':`Lawfully accessible job title, position description, classification, duty, assignment, promotion, transfer, reclassification, supervisor/organizational assignment, and related status records.${scope}${access}`,
    'compensation-payroll-earnings-and-deduction-records':`Lawfully accessible compensation, payroll, wage/salary, earning, deduction, adjustment, and pay-history records. Do not request bank-account, payment-card, tax-authentication, or payroll-login credentials.${scope}${access}`,
    'time-attendance-leave-and-schedule-records':`Lawfully accessible time, attendance, schedule, overtime, accrual, and leave-status records. Request only the leave information the requester is entitled to access and do not assume medical details supporting leave are available under the same access path.${scope}${access}`,
    'performance-evaluation-goal-and-review-records':`Lawfully accessible performance evaluations, goals, ratings, review notes, acknowledgments, performance plans, commendations, and related review records.${scope}${access}`,
    'discipline-investigation-grievance-and-resolution-records':`Lawfully accessible discipline, notice, allegation, investigation-status, grievance, hearing, response, corrective-action, resolution, and appeal records. Do not assume witness, third-party employee, privileged, or restricted investigative material is available.${scope}${access}`,
    'training-certification-license-and-qualification-records':`Lawfully accessible training, certification, qualification, license-status, continuing-education, required-course, and competency records tied to the identified employee or position.${scope}${access}`,
    'benefit-election-and-employment-status-records':`Lawfully accessible benefit-election/status and employment-eligibility records where the requester has access rights. Do not request protected health information, beneficiary financial data, passwords, or another person's protected benefit information.${scope}${access}`,
    'separation-resignation-termination-and-offboarding-records':`Lawfully accessible resignation, separation, termination, layoff, retirement, exit, final-pay, property-return, and offboarding records, including stated status and effective dates where maintained.${scope}${access}`,
    'employee-access-correction-and-request-history':`Lawfully accessible employee record-access requests, correction/amendment requests, responses, acknowledgments, request logs, and status records relevant to the identified employment record set.${scope}${access}`,
    'format-fees-delivery-and-request-status':`Current request instructions, available formats, delivery options, fee notices where applicable, processing/status communications, and records sufficient to track the identified request. Never request passwords, security answers, one-time codes, or authentication tokens.${scope}${access}`,
    'withholding-unavailable-record-and-review-status':`Written denial, withholding, unavailable-record, insufficient-authorization, non-retained-record, or other nonproduction status; the stated reason; any available cure/review path; and segregable information the requester may lawfully receive.${scope}${access}`,
  }
  return `${descriptions[category]??`Employment records concerning ${category}.${scope}${access}`}${objective}`
}
function validateEmploymentRecords(request:ValidatedRequest):readonly {field:string;message:string}[]{const issues:{field:string;message:string}[]=[];const corpus=request.items.map(i=>i.description.toLowerCase()).join(' ');if(!corpus.includes('employee '))issues.push({field:'employeeName',message:'Provide the employee name.'});if(!corpus.includes('requester capacity:'))issues.push({field:'requesterCapacity',message:'State the employee or representative requester capacity.'});if(!corpus.includes('cover '))issues.push({field:'dateRange',message:'Provide the requested employment-record period.'});if(!corpus.includes('objective:'))issues.push({field:'subjectMatter',message:'Describe the employment-records objective.'});return issues}
export function buildEmploymentRecordsRequest(input:Record<string,unknown>){const employee=text(input,'employeeName'),start=text(input,'dateStart'),end=text(input,'dateEnd'),categories=selectedCategories(input);return {title:`Employment Records — ${employee??'Employee'}`,agency:text(input,'agency')??'',jurisdiction:text(input,'jurisdiction'),purpose:text(input,'purpose')??'Obtain and reconcile the lawfully accessible employment record set, related indexes, request status, and unresolved production gaps for the identified employee and period.',scope:JSON.stringify({workflow:'employment-records',employeeName:employee,requesterCapacity:text(input,'requesterCapacity'),authorizationBasis:text(input,'authorizationBasis'),employeeId:text(input,'employeeId'),positionOrUnit:text(input,'positionOrUnit'),preferredFormat:text(input,'preferredFormat'),dateStart:start,dateEnd:end,subjectMatter:text(input,'subjectMatter')}),items:categories.map(category=>({category,description:describe(category,input),dateStart:start,dateEnd:end,custodian:text(input,'positionOrUnit'),systemHint:category==='personnel-file-index-and-access-status'?'HRIS / personnel document index':category==='compensation-payroll-earnings-and-deduction-records'?'payroll / timekeeping system':category==='discipline-investigation-grievance-and-resolution-records'?'HR / labor relations / employee relations system':undefined,format:category==='personnel-file-index-and-access-status'?'native export, CSV, JSON, spreadsheet, or other machine-readable index where maintained and lawfully available':undefined}))}}

export const EMPLOYMENT_RECORD_FINDINGS=['MISSING_REQUESTED_CATEGORY','REFERENCED_RECORD_NOT_PRODUCED','IDENTIFIER_MISMATCH','DATE_GAP','DUPLICATE_RECORD','MISSING_ATTACHMENT','UNEXPLAINED_WITHHOLDING','REDACTION_REVIEW','PARTIAL_PRODUCTION','UNRESPONSIVE_ITEM'] as const

export const productionEmploymentRecordsWorkflow:RecordsWorkflow=createRecordsWorkflow({
  id:'employment-records',name:'Employment Records Request',description:'Build an authorization-aware request for personnel, payroll, time, performance, discipline, training, separation, and employment-record access status.',searchIntent:'employment records request',seo:{title:'Employment Records Request — Personnel Files, Payroll, Reviews & Discipline',description:'Build an authorization-aware employment-records request for personnel files, payroll, attendance, reviews, discipline, training, separation, corrections, and request status.',canonicalPath:'/workflows/employment-records'},intakeVersion:'2.0.0',intake:EMPLOYMENT_RECORD_INTAKE,capabilities:EMPLOYMENT_RECORD_CAPABILITIES,request:{categories:EMPLOYMENT_RECORD_CATEGORIES,build:buildEmploymentRecordsRequest},validate:validateEmploymentRecords,
  policies:[{jurisdiction:'all',version:'2.0.0',rules:{verifyEmployeeOrAuthorizedRepresentativeAccessBeforeProtectedPersonnelRecords:true,doNotImpersonateEmployeeRepresentativeOrEmployer:true,doNotBypassConsentAuthorizationIdentityOrPersonnelPrivacyRestrictions:true,doNotRequestPasswordsSecurityAnswersOneTimeCodesAuthenticationTokensOrFinancialCredentials:true,doNotRequestAnotherEmployeesProtectedPersonnelRecords:true,requestOnlyRecordsWithinLawfulRequesterAuthorityAndScope:true,requireHumanReviewWhenRequesterRightsOrSensitivePersonnelAccessIsUnclear:true,preserveEmployeePositionPayrollRequestAndCaseIdentifiers:true}}],
  responseAnalysis:{findingTypes:EMPLOYMENT_RECORD_FINDINGS,async analyze(input:unknown){if(!input||typeof input!=='object')throw new Error('EMPLOYMENT_PRODUCTION_ANALYSIS_INPUT_INVALID');const source=input as {requestedItems?:readonly {category:string;description:string}[];records?:readonly GenericProductionRecord[]};const records=source.records??[];const requested=(source.requestedItems??[]).map(item=>({id:item.category,label:item.category,keywords:item.description.split(/\W+/).filter(w=>w.length>=4).slice(0,20)}));const deterministic=analyzeGenericProduction(requested,records,'employment record');const providers=getConfiguredRecordsLlmProviders();if(providers.length<2)return deterministic;const policy={minimumProviders:2,agreementThreshold:0.67,maxProviders:3} as const;const requestedCategories=requested.map(i=>i.id);const analyzed=await Promise.all(records.slice(0,20).map(async record=>({id:record.id,classification:await classifyGenericRecord(providers,record,'employment-records',requestedCategories,policy),facts:await extractGenericRecordFacts(providers,record,'employment-records',policy)})));const contradictions:Array<{leftId:string;rightId:string;result:Awaited<ReturnType<typeof assessGenericRecordContradiction>>}>=[];for(let i=0;i<Math.min(records.length,10);i+=1)for(let j=i+1;j<Math.min(records.length,10);j+=1)contradictions.push({leftId:records[i].id,rightId:records[j].id,result:await assessGenericRecordContradiction(providers,records[i],records[j],'employment-records',policy)});const strategy=await recommendGenericRecordFollowUp(providers,'employment-records',{deterministic,requestedItems:source.requestedItems??[],records:records.slice(0,20).map(r=>({id:r.id,filename:r.filename,category:r.category,text:r.text??''})),extracted:analyzed.map(i=>({id:i.id,classification:i.classification.value,facts:i.facts.value})),contradictions:contradictions.filter(i=>i.result.value.contradictory).map(i=>({leftId:i.leftId,rightId:i.rightId,analysis:i.result.value}))},policy);return {...deterministic,aiStrategy:strategy.value,aiProvenance:{providers:strategy.providers,confidence:strategy.confidence,disagreements:strategy.disagreements,warnings:strategy.warnings},aiRecordAnalysis:analyzed.map(i=>({id:i.id,classification:i.classification.value,facts:i.facts.value,classificationProvenance:i.classification.providers,factProvenance:i.facts.providers})),aiContradictions:contradictions.filter(i=>i.result.value.contradictory).map(i=>({leftId:i.leftId,rightId:i.rightId,analysis:i.result.value,providers:i.result.providers}))}}},
})
