import type { ValidatedRequest } from '../request-service'
import { createRecordsWorkflow, type RecordsWorkflow } from '../workflow-factory'
import type { RecordsDomainCapability } from './domain-pack'
import { analyzeGenericProduction, type GenericProductionRecord } from './generic-records-analysis'
import { assessGenericRecordContradiction, classifyGenericRecord, extractGenericRecordFacts, recommendGenericRecordFollowUp } from './generic-records-ai'
import { getConfiguredRecordsLlmProviders } from '../ai/records-llm-providers'

export const GOVERNMENT_DOCUMENTS_CATEGORIES = [
  'document-index-catalog-metadata-and-access-status',
  'official-orders-decisions-notices-and-issued-documents',
  'reports-studies-assessments-and-evaluations',
  'publications-bulletins-fact-sheets-and-guides',
  'memoranda-directives-circulars-and-policy-documents',
  'forms-instructions-manuals-and-procedural-documents',
  'plans-specifications-presentations-and-supporting-documents',
  'data-datasets-tables-spreadsheets-and-appendices',
  'versions-drafts-revisions-superseded-and-effective-documents',
  'attachments-enclosures-exhibits-and-referenced-documents',
  'certified-official-copy-format-and-delivery-status',
  'fee-withholding-redaction-no-records-and-request-status',
] as const

export const GOVERNMENT_DOCUMENTS_CAPABILITIES: readonly RecordsDomainCapability[] = ['classification','extraction','deadline','contradiction','findings','evidence','research','risk','strategy','draft','draftProvenance','validation','review','approval','mailing','tracking','proofAudit']

export const GOVERNMENT_DOCUMENTS_INTAKE = [
  { id:'agency', label:'Government agency / issuing body', required:true, helpText:'Agency, department, board, authority, court office, district, or other public body likely to maintain or issue the documents.' },
  { id:'jurisdiction', label:'Jurisdiction', required:true, helpText:'Federal, state, county, city, district, court, or other jurisdiction.' },
  { id:'department', label:'Issuing / maintaining office', helpText:'Division, bureau, component, program, clerk, publications office, records unit, or other office when known.' },
  { id:'recordsDescription', label:'Documents sought', required:true, helpText:'Describe identifiable existing documents and supporting materials rather than asking the agency to create a new explanation.' },
  { id:'subjectMatter', label:'Subject / objective', required:true, helpText:'Plain-English description of the matter and what the documents should establish.' },
  { id:'documentType', label:'Document type', helpText:'Report, order, notice, publication, study, memo, directive, manual, plan, form, dataset, specification, presentation, or another type.' },
  { id:'documentTitleOrNumber', label:'Known title / document number', helpText:'Exact or partial title, report/order/publication number, identifier, or series when known.' },
  { id:'authorOrOffice', label:'Author / issuing office', helpText:'Known author, signatory, office, board, committee, or issuing unit.' },
  { id:'dateStart', label:'Document period start', required:true, helpText:'Beginning of the requested document period.' },
  { id:'dateEnd', label:'Document period end', required:true, helpText:'End of the requested document period.' },
  { id:'versionOrEdition', label:'Version / edition / revision', helpText:'Known version, edition, revision, effective date, superseded version, draft/final designation, or other version marker.' },
  { id:'identifiers', label:'Related identifiers', helpText:'Project, case, contract, grant, permit, meeting, program, address, docket, or other identifiers that help locate the documents.' },
  { id:'searchTerms', label:'Search terms', helpText:'Distinctive title words, names, phrases, topics, or identifiers useful for locating documents.' },
  { id:'preferredFormat', label:'Preferred format', helpText:'Native electronic file, PDF, CSV, spreadsheet, image, audio/video, paper copy, or another available format.' },
  { id:'certifiedCopyNeeded', label:'Official / certified copy preference', helpText:'State whether an official or certified copy is desired. This does not establish that certification is available or required.' },
  { id:'exclusions', label:'Scope exclusions / narrowing', helpText:'Optional exclusions that reduce noise without changing the document objective.' },
] as const

function text(input:Record<string,unknown>,key:string):string|undefined{const raw=input[key];if(typeof raw!=='string')return undefined;const value=raw.trim();return value||undefined}
function selectedCategories(input:Record<string,unknown>):string[]{const raw=input.categories;if(!Array.isArray(raw))return [...GOVERNMENT_DOCUMENTS_CATEGORIES];const known=new Set(GOVERNMENT_DOCUMENTS_CATEGORIES);const selected=raw.filter((entry):entry is string=>typeof entry==='string'&&known.has(entry as typeof GOVERNMENT_DOCUMENTS_CATEGORIES[number]));return selected.length?selected:[...GOVERNMENT_DOCUMENTS_CATEGORIES]}
function scope(input:Record<string,unknown>):string{const start=text(input,'dateStart'),end=text(input,'dateEnd');const parts=[text(input,'documentType')&&`Document type: ${text(input,'documentType')}.`,text(input,'documentTitleOrNumber')&&`Known title/number: ${text(input,'documentTitleOrNumber')}.`,text(input,'authorOrOffice')&&`Known author/issuing office: ${text(input,'authorOrOffice')}.`,text(input,'versionOrEdition')&&`Version/edition/revision supplied by requester: ${text(input,'versionOrEdition')}.`,text(input,'identifiers')&&`Related identifiers: ${text(input,'identifiers')}.`,text(input,'searchTerms')&&`Search terms: ${text(input,'searchTerms')}.`,text(input,'preferredFormat')&&`Preferred format: ${text(input,'preferredFormat')}.`,text(input,'certifiedCopyNeeded')&&`Official/certified-copy preference: ${text(input,'certifiedCopyNeeded')}.`,text(input,'exclusions')&&`Scope exclusions/narrowing: ${text(input,'exclusions')}.`].filter(Boolean);return `${start&&end?` Cover ${start} through ${end}.`:''}${parts.length?` ${parts.join(' ')}`:''}`}
function describe(category:string,input:Record<string,unknown>):string{
  const s=scope(input);const objective=text(input,'subjectMatter')?` Objective: ${text(input,'subjectMatter')}.`:'';const supplied=text(input,'recordsDescription')?` Documents description supplied by requester: ${text(input,'recordsDescription')}.`:''
  const descriptions:Record<string,string>={
    'document-index-catalog-metadata-and-access-status':`Existing document catalogs, indexes, inventories, registers, publication lists, metadata, file lists, routing records, document-control records, or equivalent records identifying titles, numbers, authors/offices, dates, versions, attachments, storage locations, publication/access status, or request status. Ask for existing records only; do not demand security-sensitive repository details.${s}`,
    'official-orders-decisions-notices-and-issued-documents':`Existing officially issued orders, decisions, determinations, findings, notices, resolutions, proclamations, certificates, approvals, licenses, permits, or comparable government documents tied to the identified matter.${s}`,
    'reports-studies-assessments-and-evaluations':`Existing reports, studies, assessments, evaluations, reviews, audits, analyses, findings, technical reports, and supporting appendices within scope.${s}`,
    'publications-bulletins-fact-sheets-and-guides':`Existing publications, bulletins, fact sheets, newsletters where relevant, advisories, guides, handbooks, public information materials, and identified editions within scope.${s}`,
    'memoranda-directives-circulars-and-policy-documents':`Existing memoranda, directives, circulars, policy documents, guidance, standards, administrative issuances, and relevant versions within scope.${s}`,
    'forms-instructions-manuals-and-procedural-documents':`Existing forms, instructions, manuals, procedures, checklists, templates, job aids, filing guidance, and identified versions in effect or maintained during the requested period.${s}`,
    'plans-specifications-presentations-and-supporting-documents':`Existing plans, specifications, drawings where lawfully accessible, presentations, slide decks, schedules, supporting documents, exhibits, technical materials, and related deliverables tied to the matter.${s}`,
    'data-datasets-tables-spreadsheets-and-appendices':`Existing datasets, tables, spreadsheets, appendices, schedules, charts, machine-readable exports, and structured data underlying or accompanying requested documents where maintained and lawfully available.${s}`,
    'versions-drafts-revisions-superseded-and-effective-documents':`Existing versions, editions, revisions, change histories, superseded documents, draft documents where lawfully accessible, final/issued versions, effective-date records, and document-control history. Do not label a document draft, final, superseded, effective, approved, or official unless the record evidence establishes that status.${s}`,
    'attachments-enclosures-exhibits-and-referenced-documents':`Existing attachments, enclosures, exhibits, appendices, linked files, referenced documents, incorporated materials, cross-indexed documents, and related records expressly identified in a responsive document but not otherwise produced.${s}`,
    'certified-official-copy-format-and-delivery-status':`Existing records or agency information establishing whether an official, authenticated, file-stamped, exemplified, certified, or other special copy is available; applicable copy format; and delivery/production status. Preserve the requester's preference but do not claim certification, authenticity, official-copy status, or availability unless established by the agency or source record.${s}`,
    'fee-withholding-redaction-no-records-and-request-status':`Existing acknowledgment, search/status, fee, clarification, transfer/referral, no-records, withholding, redaction, exemption, partial-production, closure, and other response records. Preserve the agency's actual stated basis rather than inventing deadlines, exemptions, disclosure rights, violations, or review rights.${s}`,
  }
  return `${descriptions[category]??`Existing government documents concerning ${category}.${s}`}${supplied}${objective}`
}
function validateGovernmentDocuments(request:ValidatedRequest):readonly {field:string;message:string}[]{const issues:{field:string;message:string}[]=[];const corpus=request.items.map(item=>item.description.toLowerCase()).join(' ');if(!request.agency?.trim())issues.push({field:'agency',message:'Identify the agency or public body likely to maintain or issue the documents.'});if(!request.jurisdiction?.trim())issues.push({field:'jurisdiction',message:'Identify the relevant jurisdiction.'});if(!corpus.includes('documents description supplied by requester:'))issues.push({field:'recordsDescription',message:'Describe the identifiable existing documents sought.'});if(!corpus.includes('objective:'))issues.push({field:'subjectMatter',message:'Describe the document objective.'});if(!corpus.includes('cover '))issues.push({field:'dateRange',message:'Provide the requested document period.'});return issues}
export function buildGovernmentDocumentsRequest(input:Record<string,unknown>){const agency=text(input,'agency')??'';const subject=text(input,'subjectMatter');const start=text(input,'dateStart'),end=text(input,'dateEnd');const categories=selectedCategories(input);return {title:`Government Documents Request — ${subject??text(input,'documentTitleOrNumber')??agency??'Documents'}`,agency,jurisdiction:text(input,'jurisdiction'),purpose:text(input,'purpose')??'Request identifiable existing government documents, versions, attachments, structured data, and copy-status evidence with precise search and production controls.',scope:JSON.stringify({workflow:'government-documents-request',department:text(input,'department'),recordsDescription:text(input,'recordsDescription'),subjectMatter:subject,documentType:text(input,'documentType'),documentTitleOrNumber:text(input,'documentTitleOrNumber'),authorOrOffice:text(input,'authorOrOffice'),dateStart:start,dateEnd:end,versionOrEdition:text(input,'versionOrEdition'),identifiers:text(input,'identifiers'),searchTerms:text(input,'searchTerms'),preferredFormat:text(input,'preferredFormat'),certifiedCopyNeeded:text(input,'certifiedCopyNeeded'),exclusions:text(input,'exclusions')}),items:categories.map(category=>({category,description:describe(category,input),dateStart:start,dateEnd:end,custodian:text(input,'department')??text(input,'authorOrOffice'),format:text(input,'preferredFormat'),systemHint:category==='document-index-catalog-metadata-and-access-status'?'document catalog / records index / publication or document-control system':category==='data-datasets-tables-spreadsheets-and-appendices'?'native spreadsheet / data / reporting system':undefined}))}}

export const GOVERNMENT_DOCUMENTS_FINDINGS=['MISSING_REQUESTED_CATEGORY','REFERENCED_RECORD_NOT_PRODUCED','IDENTIFIER_MISMATCH','DATE_GAP','DUPLICATE_RECORD','MISSING_ATTACHMENT','UNEXPLAINED_WITHHOLDING','REDACTION_REVIEW','PARTIAL_PRODUCTION','UNRESPONSIVE_ITEM'] as const

export const productionGovernmentDocumentsRequestWorkflow:RecordsWorkflow=createRecordsWorkflow({
  id:'government-documents-request',name:'Government Documents Request',description:'Build a document-centric government request using titles, numbers, versions, issuing offices, date ranges, attachments, formats, structured data, and official/certified-copy preferences with production-review controls.',searchIntent:'government documents request',seo:{title:'Government Documents Request — Reports, Orders, Publications & Official Copies',description:'Build a precise request for government reports, orders, publications, manuals, datasets, versions, attachments, and official-copy status with search-ready document details.',canonicalPath:'/workflows/government-documents-request'},intakeVersion:'2.0.0',intake:GOVERNMENT_DOCUMENTS_INTAKE,capabilities:GOVERNMENT_DOCUMENTS_CAPABILITIES,request:{categories:GOVERNMENT_DOCUMENTS_CATEGORIES,build:buildGovernmentDocumentsRequest},validate:validateGovernmentDocuments,
  policies:[{jurisdiction:'all',version:'2.0.0',rules:{requestExistingIdentifiableDocumentsVersionsAttachmentsAndDataRatherThanAgencyCreatedExplanations:true,preserveTitleNumberAuthorOfficeVersionJurisdictionAndFormatAsExplicitSearchInputs:true,doNotInventDocumentExistenceTitleNumberAuthorCustodianVersionEditionEffectiveDatePublicationStatusOrOfficialStatus:true,doNotLabelDraftFinalApprovedSupersededEffectiveCertifiedAuthenticatedOrOfficialWithoutRecordEvidence:true,doNotAssertJurisdictionSpecificDeadlinesExemptionsFeesAppealRightsDisclosureRightsCertificationRequirementsOrViolationsWithoutVerifiedAuthority:true,doNotTreatDraftInternalPrivilegedSecuritySensitivePersonnelMedicalFinancialVictimWitnessOrAuthenticationMaterialAsAutomaticallyPublic:true,doNotRequestPasswordsSecurityAnswersOneTimeCodesAuthenticationTokensPaymentCredentialsOrSecuritySensitiveRepositoryDetails:true,preserveRequesterDocumentScopeIdentifiersSearchTermsFormatsVersionPreferencesCertificationPreferencesAndExclusions:true,requireHumanReviewWhenConsequentialLegalConclusionVersionStatusCertificationStatusOrSensitiveAccessIsUnclear:true}}],
  responseAnalysis:{findingTypes:GOVERNMENT_DOCUMENTS_FINDINGS,async analyze(input:unknown){if(!input||typeof input!=='object')throw new Error('GOVERNMENT_DOCUMENTS_PRODUCTION_ANALYSIS_INPUT_INVALID');const source=input as {requestedItems?:readonly {category:string;description:string}[];records?:readonly GenericProductionRecord[]};const records=source.records??[];const requested=(source.requestedItems??[]).map(item=>({id:item.category,label:item.category,keywords:item.description.split(/\W+/).filter(word=>word.length>=4).slice(0,20)}));const deterministic=analyzeGenericProduction(requested,records,'government document');const providers=getConfiguredRecordsLlmProviders();if(providers.length<2)return deterministic;const policy={minimumProviders:2,agreementThreshold:0.67,maxProviders:3} as const;const requestedCategories=requested.map(item=>item.id);const analyzed=await Promise.all(records.slice(0,20).map(async record=>({id:record.id,classification:await classifyGenericRecord(providers,record,'government-documents-request',requestedCategories,policy),facts:await extractGenericRecordFacts(providers,record,'government-documents-request',policy)})));const contradictions:Array<{leftId:string;rightId:string;result:Awaited<ReturnType<typeof assessGenericRecordContradiction>>}>=[];for(let i=0;i<Math.min(records.length,10);i+=1)for(let j=i+1;j<Math.min(records.length,10);j+=1)contradictions.push({leftId:records[i].id,rightId:records[j].id,result:await assessGenericRecordContradiction(providers,records[i],records[j],'government-documents-request',policy)});const strategy=await recommendGenericRecordFollowUp(providers,'government-documents-request',{deterministic,requestedItems:source.requestedItems??[],records:records.slice(0,20).map(record=>({id:record.id,filename:record.filename,category:record.category,text:record.text??''})),extracted:analyzed.map(item=>({id:item.id,classification:item.classification.value,facts:item.facts.value})),contradictions:contradictions.filter(item=>item.result.value.contradictory).map(item=>({leftId:item.leftId,rightId:item.rightId,analysis:item.result.value}))},policy);return {...deterministic,aiStrategy:strategy.value,aiProvenance:{providers:strategy.providers,confidence:strategy.confidence,disagreements:strategy.disagreements,warnings:strategy.warnings},aiRecordAnalysis:analyzed.map(item=>({id:item.id,classification:item.classification.value,facts:item.facts.value,classificationProvenance:item.classification.providers,factProvenance:item.facts.providers})),aiContradictions:contradictions.filter(item=>item.result.value.contradictory).map(item=>({leftId:item.leftId,rightId:item.rightId,analysis:item.result.value,providers:item.result.providers}))}}},
})
