import type { ValidatedRequest } from '../request-service'
import { createRecordsWorkflow, type RecordsWorkflow } from '../workflow-factory'
import type { RecordsDomainCapability } from './domain-pack'
import { analyzeGenericProduction, type GenericProductionRecord } from './generic-records-analysis'
import { assessGenericRecordContradiction, classifyGenericRecord, extractGenericRecordFacts, recommendGenericRecordFollowUp } from './generic-records-ai'
import { getConfiguredRecordsLlmProviders } from '../ai/records-llm-providers'

export const MEDICAL_RECORD_CATEGORIES = [
  'designated-record-set-and-chart-index',
  'clinical-notes-history-and-treatment-records',
  'laboratory-pathology-and-test-results',
  'imaging-reports-and-native-image-availability',
  'medication-allergy-and-administration-records',
  'procedure-operative-and-anesthesia-records',
  'referral-consult-and-care-coordination-records',
  'billing-claims-and-itemized-account-records',
  'authorizations-consents-and-disclosure-accounting-status',
  'amendment-correction-restriction-and-request-status',
  'record-format-fees-delivery-and-request-status',
  'withholding-unavailable-record-and-review-status',
] as const

export const MEDICAL_RECORD_CAPABILITIES: readonly RecordsDomainCapability[] = ['classification','extraction','deadline','contradiction','findings','evidence','research','risk','strategy','draft','draftProvenance','validation','review','approval','mailing','tracking','proofAudit']

export const MEDICAL_RECORD_INTAKE = [
  { id:'agency', label:'Provider / facility / records custodian', required:true, helpText:'Hospital, clinic, physician practice, health system, insurer, laboratory, imaging center, or other lawful custodian.' },
  { id:'patientName', label:'Patient name', required:true, helpText:'Name associated with the requested record set.' },
  { id:'requesterCapacity', label:'Requester capacity', required:true, helpText:'For example: patient, personal representative, parent/guardian where legally authorized, or agent with valid authorization.' },
  { id:'authorizationBasis', label:'Authorization / authority', helpText:'Authorization, representative authority, guardianship, or other lawful basis when the requester is not the patient.' },
  { id:'facilityOrDepartment', label:'Facility / department / clinician', helpText:'Hospital, clinic, department, treating clinician, laboratory, imaging center, or service line.' },
  { id:'accountOrRecordNumber', label:'Record / account / encounter number', helpText:'Medical-record, account, encounter, visit, claim, accession, or other identifier when known.' },
  { id:'dateStart', label:'Record period start', required:true, helpText:'Beginning of the treatment or records period.' },
  { id:'dateEnd', label:'Record period end', required:true, helpText:'End of the treatment or records period.' },
  { id:'preferredFormat', label:'Preferred format', helpText:'Electronic PDF, portal delivery, native imaging, machine-readable export, or other format where available.' },
  { id:'subjectMatter', label:'Records objective', required:true, helpText:'Plain-English description of the care episode, records needed, or request-status objective.' },
] as const

function text(input:Record<string,unknown>,key:string):string|undefined{const raw=input[key];if(typeof raw!=='string')return undefined;const v=raw.trim();return v||undefined}
function selectedCategories(input:Record<string,unknown>):string[]{const raw=input.categories;if(!Array.isArray(raw))return [...MEDICAL_RECORD_CATEGORIES];const known=new Set(MEDICAL_RECORD_CATEGORIES);const selected=raw.filter((e):e is string=>typeof e==='string'&&known.has(e as typeof MEDICAL_RECORD_CATEGORIES[number]));return selected.length?selected:[...MEDICAL_RECORD_CATEGORIES]}
function scopeText(input:Record<string,unknown>):string{const ids=[text(input,'patientName')&&`patient ${text(input,'patientName')}`,text(input,'facilityOrDepartment')&&`facility/department/clinician ${text(input,'facilityOrDepartment')}`,text(input,'accountOrRecordNumber')&&`record/account/encounter identifier ${text(input,'accountOrRecordNumber')}`].filter(Boolean);const start=text(input,'dateStart'),end=text(input,'dateEnd');return `${ids.length?` Identify the records using: ${ids.join('; ')}.`:''}${start&&end?` Cover ${start} through ${end}.`:''}`}
function accessText(input:Record<string,unknown>):string{return `${text(input,'requesterCapacity')?` Requester capacity: ${text(input,'requesterCapacity')}.`:''}${text(input,'authorizationBasis')?` Authorization/authority: ${text(input,'authorizationBasis')}.`:''}`}
function describe(category:string,input:Record<string,unknown>):string{
  const scope=scopeText(input),access=accessText(input),objective=text(input,'subjectMatter')?` Objective: ${text(input,'subjectMatter')}.`:''
  const descriptions:Record<string,string>={
    'designated-record-set-and-chart-index':`The lawfully accessible designated record set or equivalent chart/document index, including record categories, encounter indexes, document lists, source systems, and records sufficient to identify what is maintained for the requested period. Request only records this requester is legally entitled to access.${scope}${access}`,
    'clinical-notes-history-and-treatment-records':`Lawfully accessible history and physical records, progress notes, encounter notes, discharge summaries, treatment plans, nursing notes, therapy notes where accessible, and other clinical documentation for the requested period. Do not assume specially protected or separately restricted records are available under the same access path.${scope}${access}`,
    'laboratory-pathology-and-test-results':`Lawfully accessible laboratory, pathology, diagnostic-test, microbiology, genetic-test, and related result records, including result metadata and referenced attachments where part of the accessible record set.${scope}${access}`,
    'imaging-reports-and-native-image-availability':`Lawfully accessible radiology/imaging reports, study indexes, accession information, and records sufficient to identify whether native imaging files can be provided in an available electronic format. Do not request system credentials or internal access tokens.${scope}${access}`,
    'medication-allergy-and-administration-records':`Lawfully accessible medication lists, medication-administration records, prescription/order history, allergy/adverse-reaction records, reconciliation records, and relevant medication-change history for the requested period.${scope}${access}`,
    'procedure-operative-and-anesthesia-records':`Lawfully accessible procedure notes, operative reports, anesthesia records, procedure logs, implant/device records, and associated documentation for procedures within the requested period.${scope}${access}`,
    'referral-consult-and-care-coordination-records':`Lawfully accessible referrals, consult notes, care-coordination records, transfer summaries, outside-record indexes, and records sufficient to identify referenced but separately maintained clinical material.${scope}${access}`,
    'billing-claims-and-itemized-account-records':`Lawfully accessible itemized bills, statements, claim records, coding summaries, payment/adjustment history, and account records tied to the requested care. Do not request payment-card, bank-account, login, or authentication credentials.${scope}${access}`,
    'authorizations-consents-and-disclosure-accounting-status':`Lawfully accessible authorization, consent, release, disclosure-request, and accounting-of-disclosure status or records where applicable to the requester and scope. Do not use this workflow to bypass consent or authorization requirements.${scope}${access}`,
    'amendment-correction-restriction-and-request-status':`Lawfully accessible amendment/correction requests, patient statements, restriction requests, status records, responses, and records sufficient to identify unresolved correction or access issues.${scope}${access}`,
    'record-format-fees-delivery-and-request-status':`Current record-request instructions, available electronic formats, delivery options, fee notices, processing/status communications, request logs, and records sufficient to track the identified request. Prefer secure electronic delivery where offered; never request portal credentials.${scope}${access}`,
    'withholding-unavailable-record-and-review-status':`Written denial, withholding, unavailable-record, non-retained-record, incomplete-request, insufficient-authorization, or other nonproduction status; the stated reason; available cure/review path; and any segregable information the requester may lawfully receive.${scope}${access}`,
  }
  return `${descriptions[category]??`Records concerning ${category}.${scope}${access}`}${objective}`
}
function validateMedicalRecords(request:ValidatedRequest):readonly {field:string;message:string}[]{const issues:{field:string;message:string}[]=[];const corpus=request.items.map(i=>i.description.toLowerCase()).join(' ');if(!corpus.includes('patient '))issues.push({field:'patientName',message:'Provide the patient name.'});if(!corpus.includes('requester capacity:'))issues.push({field:'requesterCapacity',message:'State whether the requester is the patient or has lawful representative/authorization authority.'});if(!corpus.includes('cover '))issues.push({field:'dateRange',message:'Provide the requested record period.'});if(!corpus.includes('objective:'))issues.push({field:'subjectMatter',message:'Describe the medical-records objective.'});return issues}
export function buildMedicalRecordsRequest(input:Record<string,unknown>){const patient=text(input,'patientName'),start=text(input,'dateStart'),end=text(input,'dateEnd'),categories=selectedCategories(input);return {title:`Medical Records — ${patient??'Patient'}`,agency:text(input,'agency')??'',jurisdiction:text(input,'jurisdiction'),purpose:text(input,'purpose')??'Obtain and reconcile the lawfully accessible medical record set, related indexes, request status, and unresolved production gaps for the identified patient and period.',scope:JSON.stringify({workflow:'medical-records',patientName:patient,requesterCapacity:text(input,'requesterCapacity'),authorizationBasis:text(input,'authorizationBasis'),facilityOrDepartment:text(input,'facilityOrDepartment'),accountOrRecordNumber:text(input,'accountOrRecordNumber'),preferredFormat:text(input,'preferredFormat'),dateStart:start,dateEnd:end,subjectMatter:text(input,'subjectMatter')}),items:categories.map(category=>({category,description:describe(category,input),dateStart:start,dateEnd:end,custodian:text(input,'facilityOrDepartment'),systemHint:category==='designated-record-set-and-chart-index'?'EHR / health-information-management document index':category==='billing-claims-and-itemized-account-records'?'billing / claims system':category==='imaging-reports-and-native-image-availability'?'PACS / imaging archive':undefined,format:category==='designated-record-set-and-chart-index'?'native export, CSV, JSON, spreadsheet, or other machine-readable index where maintained and lawfully available':category==='imaging-reports-and-native-image-availability'?(text(input,'preferredFormat')??'native imaging files or highest-quality available electronic format'):undefined}))}}
export const MEDICAL_RECORD_FINDINGS=['MISSING_REQUESTED_CATEGORY','REFERENCED_RECORD_NOT_PRODUCED','IDENTIFIER_MISMATCH','DATE_GAP','DUPLICATE_RECORD','MISSING_ATTACHMENT','UNEXPLAINED_WITHHOLDING','REDACTION_REVIEW','PARTIAL_PRODUCTION','UNRESPONSIVE_ITEM'] as const
export const productionMedicalRecordsWorkflow:RecordsWorkflow=createRecordsWorkflow({
  id:'medical-records',name:'Medical Records Request',description:'Build an authorization-aware request for clinical records, tests, imaging, medications, procedures, referrals, billing, request-status, and unresolved access or production issues.',searchIntent:'medical records request',seo:{title:'Medical Records Request — Charts, Tests, Imaging, Billing & Request Status',description:'Build an authorization-aware medical-records request for charts, test results, imaging, medications, procedures, billing, corrections, formats, fees, and request status.',canonicalPath:'/workflows/medical-records'},intakeVersion:'2.0.0',intake:MEDICAL_RECORD_INTAKE,capabilities:MEDICAL_RECORD_CAPABILITIES,request:{categories:MEDICAL_RECORD_CATEGORIES,build:buildMedicalRecordsRequest},validate:validateMedicalRecords,
  policies:[{jurisdiction:'all',version:'2.0.0',rules:{verifyPatientOrLawfulRepresentativeAuthorizationBeforeRequestingProtectedRecords:true,doNotImpersonatePatientRepresentativeOrProvider:true,doNotBypassConsentAuthorizationIdentityOrSpeciallyProtectedRecordRestrictions:true,doNotRequestPasswordsPortalCredentialsAuthenticationTokensOrPaymentCredentials:true,requestOnlyRecordsWithinLawfulRequesterAuthorityAndScope:true,requireHumanReviewWhenRepresentativeAuthorityOrSensitiveRecordAccessIsUnclear:true,preserveEncounterAccessionClaimAndRequestIdentifiers:true,preferSecureElectronicDeliveryAndStructuredIndexesWhereAvailable:true}}],
  responseAnalysis:{findingTypes:MEDICAL_RECORD_FINDINGS,async analyze(input:unknown){if(!input||typeof input!=='object')throw new Error('MEDICAL_PRODUCTION_ANALYSIS_INPUT_INVALID');const source=input as {requestedItems?:readonly {category:string;description:string}[];records?:readonly GenericProductionRecord[]};const records=source.records??[];const requested=(source.requestedItems??[]).map(item=>({id:item.category,label:item.category,keywords:item.description.split(/\W+/).filter(w=>w.length>=4).slice(0,20)}));const deterministic=analyzeGenericProduction(requested,records,'medical record');const providers=getConfiguredRecordsLlmProviders();if(providers.length<2)return deterministic;const policy={minimumProviders:2,agreementThreshold:0.67,maxProviders:3} as const;const requestedCategories=requested.map(i=>i.id);const analyzed=await Promise.all(records.slice(0,20).map(async record=>({id:record.id,classification:await classifyGenericRecord(providers,record,'medical-records',requestedCategories,policy),facts:await extractGenericRecordFacts(providers,record,'medical-records',policy)})));const contradictions:Array<{leftId:string;rightId:string;result:Awaited<ReturnType<typeof assessGenericRecordContradiction>>}>=[];for(let i=0;i<Math.min(records.length,10);i+=1)for(let j=i+1;j<Math.min(records.length,10);j+=1)contradictions.push({leftId:records[i].id,rightId:records[j].id,result:await assessGenericRecordContradiction(providers,records[i],records[j],'medical-records',policy)});const strategy=await recommendGenericRecordFollowUp(providers,'medical-records',{deterministic,requestedItems:source.requestedItems??[],records:records.slice(0,20).map(r=>({id:r.id,filename:r.filename,category:r.category,text:r.text??''})),extracted:analyzed.map(i=>({id:i.id,classification:i.classification.value,facts:i.facts.value})),contradictions:contradictions.filter(i=>i.result.value.contradictory).map(i=>({leftId:i.leftId,rightId:i.rightId,analysis:i.result.value}))},policy);return {...deterministic,aiStrategy:strategy.value,aiProvenance:{providers:strategy.providers,confidence:strategy.confidence,disagreements:strategy.disagreements,warnings:strategy.warnings},aiRecordAnalysis:analyzed.map(i=>({id:i.id,classification:i.classification.value,facts:i.facts.value,classificationProvenance:i.classification.providers,factProvenance:i.facts.providers})),aiContradictions:contradictions.filter(i=>i.result.value.contradictory).map(i=>({leftId:i.leftId,rightId:i.rightId,analysis:i.result.value,providers:i.result.providers}))}}},
})
