import type { ValidatedRequest } from '../request-service'
import { createRecordsWorkflow, type RecordsWorkflow } from '../workflow-factory'
import type { RecordsDomainCapability } from './domain-pack'
import { analyzeGenericProduction, type GenericProductionRecord } from './generic-records-analysis'
import { assessGenericRecordContradiction, classifyGenericRecord, extractGenericRecordFacts, recommendGenericRecordFollowUp } from './generic-records-ai'
import { getConfiguredRecordsLlmProviders } from '../ai/records-llm-providers'

export const MILITARY_RECORD_CATEGORIES = [
  'service-record-index-and-access-status',
  'separation-discharge-and-dd214-equivalent-records',
  'service-history-assignments-duty-and-unit-records',
  'personnel-actions-evaluations-promotion-and-rank-records',
  'awards-decorations-commendations-and-citations',
  'training-qualification-certification-and-school-records',
  'orders-travel-deployment-and-assignment-records',
  'pay-entitlement-and-service-finance-record-status',
  'service-treatment-medical-and-dental-record-access-status',
  'disciplinary-adverse-action-and-review-status',
  'correspondence-request-tracking-and-custodian-referral',
  'correction-amendment-and-board-review-status',
  'withholding-unavailable-record-and-review-status',
] as const

export const MILITARY_RECORD_CAPABILITIES: readonly RecordsDomainCapability[] = ['classification','extraction','deadline','contradiction','findings','evidence','research','risk','strategy','draft','draftProvenance','validation','review','approval','mailing','tracking','proofAudit']

export const MILITARY_RECORD_INTAKE = [
  { id:'agency', label:'Military branch / records custodian', required:true, helpText:'Branch, records center, archives office, personnel command, VA-linked custodian, or other office maintaining the records.' },
  { id:'serviceMemberName', label:'Service member / veteran name', required:true, helpText:'Name associated with the requested military record.' },
  { id:'requesterCapacity', label:'Requester capacity', required:true, helpText:'For example: service member/veteran, authorized representative, next-of-kin where eligible, or other lawful requester.' },
  { id:'authorizationBasis', label:'Authorization / eligibility basis', helpText:'Written authorization, next-of-kin relationship/eligibility, representative authority, or other lawful access basis when required.' },
  { id:'serviceNumber', label:'Service / record identifier', helpText:'Service number or other non-secret military record identifier when known. Avoid unnecessary sensitive identifiers.' },
  { id:'branch', label:'Branch / component', helpText:'Service branch, reserve component, National Guard component, or other component.' },
  { id:'unitOrAssignment', label:'Unit / assignment / installation', helpText:'Known unit, command, installation, ship, squadron, battalion, duty station, or assignment.' },
  { id:'dateStart', label:'Service / record period start', required:true, helpText:'Beginning of the requested service or records period.' },
  { id:'dateEnd', label:'Service / record period end', required:true, helpText:'End of the requested service or records period.' },
  { id:'subjectMatter', label:'Records objective', required:true, helpText:'Plain-English description of the military records, correction issue, or request-status objective.' },
] as const

function text(input:Record<string,unknown>,key:string):string|undefined{const raw=input[key];if(typeof raw!=='string')return undefined;const v=raw.trim();return v||undefined}
function selectedCategories(input:Record<string,unknown>):string[]{const raw=input.categories;if(!Array.isArray(raw))return [...MILITARY_RECORD_CATEGORIES];const known=new Set(MILITARY_RECORD_CATEGORIES);const selected=raw.filter((e):e is string=>typeof e==='string'&&known.has(e as typeof MILITARY_RECORD_CATEGORIES[number]));return selected.length?selected:[...MILITARY_RECORD_CATEGORIES]}
function scopeText(input:Record<string,unknown>):string{const ids=[text(input,'serviceMemberName')&&`service member/veteran ${text(input,'serviceMemberName')}`,text(input,'serviceNumber')&&`record identifier ${text(input,'serviceNumber')}`,text(input,'branch')&&`branch/component ${text(input,'branch')}`,text(input,'unitOrAssignment')&&`unit/assignment ${text(input,'unitOrAssignment')}`].filter(Boolean);const start=text(input,'dateStart'),end=text(input,'dateEnd');return `${ids.length?` Identify the records using: ${ids.join('; ')}.`:''}${start&&end?` Cover ${start} through ${end}.`:''}`}
function accessText(input:Record<string,unknown>):string{return `${text(input,'requesterCapacity')?` Requester capacity: ${text(input,'requesterCapacity')}.`:''}${text(input,'authorizationBasis')?` Authorization/eligibility basis: ${text(input,'authorizationBasis')}.`:''}`}
function describe(category:string,input:Record<string,unknown>):string{
  const scope=scopeText(input),access=accessText(input),objective=text(input,'subjectMatter')?` Objective: ${text(input,'subjectMatter')}.`:''
  const descriptions:Record<string,string>={
    'service-record-index-and-access-status':`A lawfully accessible service-record index, personnel-file inventory, document list, accession/reference index, or equivalent listing sufficient to identify the military record categories maintained for the requested period, together with requester access/eligibility status.${scope}${access}`,
    'separation-discharge-and-dd214-equivalent-records':`Lawfully accessible separation, discharge, release-from-duty, DD-214 or equivalent documents, correction copies, separation orders, and records sufficient to identify the authoritative discharge/separation record and its current status.${scope}${access}`,
    'service-history-assignments-duty-and-unit-records':`Lawfully accessible service-history, duty-status, assignment, station, unit, billet, occupational specialty, deployment-history, and related personnel-history records.${scope}${access}`,
    'personnel-actions-evaluations-promotion-and-rank-records':`Lawfully accessible personnel actions, evaluation/performance reports, rank, promotion, reduction, appointment, reenlistment, extension, transfer, and related status records where available to this requester.${scope}${access}`,
    'awards-decorations-commendations-and-citations':`Lawfully accessible award, decoration, medal, commendation, citation, recommendation-status, and entitlement records tied to the identified service member.${scope}${access}`,
    'training-qualification-certification-and-school-records':`Lawfully accessible military education, school, training, qualification, certification, weapons/technical qualification status, and completion records, excluding restricted operational/security detail where applicable.${scope}${access}`,
    'orders-travel-deployment-and-assignment-records':`Lawfully accessible orders, assignment, transfer, mobilization/demobilization, deployment, temporary-duty, travel-status, and related records. Do not request current sensitive operational locations or restricted mission/security information.${scope}${access}`,
    'pay-entitlement-and-service-finance-record-status':`Lawfully accessible service-pay, entitlement, allowance, leave-and-earnings, retirement-credit, or finance-record status relevant to the requester. Do not request banking credentials, payment-card information, tax-authentication secrets, or another person's protected financial information.${scope}${access}`,
    'service-treatment-medical-and-dental-record-access-status':`Lawfully accessible service-treatment, medical, dental, or health-record access/status information where this requester has the required authority. Do not assume protected medical content is available under the same rules as ordinary personnel records.${scope}${access}`,
    'disciplinary-adverse-action-and-review-status':`Lawfully accessible adverse-action, nonjudicial-punishment status, administrative action, reprimand, discharge-review, correction-review, or related disposition records. Do not assume restricted investigative, victim, witness, classified, or third-party material is releasable.${scope}${access}`,
    'correspondence-request-tracking-and-custodian-referral':`Lawfully accessible request correspondence, tracking/status, transfer/referral, custodian identification, search-status, fee/status notices, and records sufficient to identify which office maintains separately held responsive material.${scope}${access}`,
    'correction-amendment-and-board-review-status':`Lawfully accessible correction/amendment requests, board or administrative-review status, decisions, advisory records where releasable, applicant statements, and records sufficient to identify unresolved correction issues.${scope}${access}`,
    'withholding-unavailable-record-and-review-status':`Written denial, withholding, unavailable/destroyed/non-retained record, insufficient-authorization, classified/restricted status, or other nonproduction response; the stated reason; available cure/review route; and segregable information the requester may lawfully receive.${scope}${access}`,
  }
  return `${descriptions[category]??`Military records concerning ${category}.${scope}${access}`}${objective}`
}
function validateMilitaryRecords(request:ValidatedRequest):readonly {field:string;message:string}[]{const issues:{field:string;message:string}[]=[];const corpus=request.items.map(i=>i.description.toLowerCase()).join(' ');if(!corpus.includes('service member/veteran '))issues.push({field:'serviceMemberName',message:'Provide the service member or veteran name.'});if(!corpus.includes('requester capacity:'))issues.push({field:'requesterCapacity',message:'State the requester capacity and eligibility basis.'});if(!corpus.includes('cover '))issues.push({field:'dateRange',message:'Provide the requested military-record period.'});if(!corpus.includes('objective:'))issues.push({field:'subjectMatter',message:'Describe the military-records objective.'});return issues}
export function buildMilitaryRecordsRequest(input:Record<string,unknown>){const subject=text(input,'serviceMemberName'),start=text(input,'dateStart'),end=text(input,'dateEnd'),categories=selectedCategories(input);return {title:`Military Records — ${subject??'Service Member'}`,agency:text(input,'agency')??'',jurisdiction:'Federal',purpose:text(input,'purpose')??'Obtain and reconcile the lawfully accessible military service record set, related indexes, request status, and unresolved production gaps for the identified service member and period.',scope:JSON.stringify({workflow:'military-records',serviceMemberName:subject,requesterCapacity:text(input,'requesterCapacity'),authorizationBasis:text(input,'authorizationBasis'),serviceNumber:text(input,'serviceNumber'),branch:text(input,'branch'),unitOrAssignment:text(input,'unitOrAssignment'),dateStart:start,dateEnd:end,subjectMatter:text(input,'subjectMatter')}),items:categories.map(category=>({category,description:describe(category,input),dateStart:start,dateEnd:end,custodian:text(input,'branch'),systemHint:category==='service-record-index-and-access-status'?'official military personnel file / records index':category==='service-treatment-medical-and-dental-record-access-status'?'authorized service-treatment / medical record system':category==='pay-entitlement-and-service-finance-record-status'?'military pay / finance record system':undefined,format:category==='service-record-index-and-access-status'?'native export, index, spreadsheet, or other machine-readable listing where maintained and lawfully available':undefined}))}}

export const MILITARY_RECORD_FINDINGS=['MISSING_REQUESTED_CATEGORY','REFERENCED_RECORD_NOT_PRODUCED','IDENTIFIER_MISMATCH','DATE_GAP','DUPLICATE_RECORD','MISSING_ATTACHMENT','UNEXPLAINED_WITHHOLDING','REDACTION_REVIEW','PARTIAL_PRODUCTION','UNRESPONSIVE_ITEM'] as const

export const productionMilitaryRecordsWorkflow:RecordsWorkflow=createRecordsWorkflow({
  id:'military-records',name:'Military Records Request',description:'Build an eligibility-aware request for service history, discharge, personnel actions, awards, training, orders, finance status, treatment-record access, corrections, and request status.',searchIntent:'military records request',seo:{title:'Military Records Request — DD-214, Service, Personnel & Correction Records',description:'Build an eligibility-aware military-records request for DD-214/separation records, service history, personnel actions, awards, training, orders, treatment-record access, corrections, and request status.',canonicalPath:'/workflows/military-records'},intakeVersion:'2.0.0',intake:MILITARY_RECORD_INTAKE,capabilities:MILITARY_RECORD_CAPABILITIES,request:{categories:MILITARY_RECORD_CATEGORIES,build:buildMilitaryRecordsRequest},validate:validateMilitaryRecords,
  policies:[{jurisdiction:'federal',version:'2.0.0',rules:{verifyServiceMemberVeteranRepresentativeOrOtherRequesterEligibilityBeforeProtectedRecords:true,doNotImpersonateServiceMemberVeteranRepresentativeOrGovernmentOffice:true,doNotBypassConsentAuthorizationIdentityNextOfKinOrOtherAccessRestrictions:true,doNotRequestPasswordsSecurityAnswersOneTimeCodesAuthenticationTokensOrFinancialCredentials:true,doNotRequestClassifiedRestrictedOperationalOrThirdPartyProtectedMaterialAsIfPublic:true,requestOnlyRecordsWithinLawfulRequesterAuthorityAndScope:true,requireHumanReviewWhenRequesterEligibilityDeceasedSubjectStatusOrSensitiveRecordAccessIsUnclear:true,preserveServiceUnitOrderRequestAndRecordIdentifiers:true}}],
  responseAnalysis:{findingTypes:MILITARY_RECORD_FINDINGS,async analyze(input:unknown){if(!input||typeof input!=='object')throw new Error('MILITARY_PRODUCTION_ANALYSIS_INPUT_INVALID');const source=input as {requestedItems?:readonly {category:string;description:string}[];records?:readonly GenericProductionRecord[]};const records=source.records??[];const requested=(source.requestedItems??[]).map(item=>({id:item.category,label:item.category,keywords:item.description.split(/\W+/).filter(w=>w.length>=4).slice(0,20)}));const deterministic=analyzeGenericProduction(requested,records,'military record');const providers=getConfiguredRecordsLlmProviders();if(providers.length<2)return deterministic;const policy={minimumProviders:2,agreementThreshold:0.67,maxProviders:3} as const;const requestedCategories=requested.map(i=>i.id);const analyzed=await Promise.all(records.slice(0,20).map(async record=>({id:record.id,classification:await classifyGenericRecord(providers,record,'military-records',requestedCategories,policy),facts:await extractGenericRecordFacts(providers,record,'military-records',policy)})));const contradictions:Array<{leftId:string;rightId:string;result:Awaited<ReturnType<typeof assessGenericRecordContradiction>>}>=[];for(let i=0;i<Math.min(records.length,10);i+=1)for(let j=i+1;j<Math.min(records.length,10);j+=1)contradictions.push({leftId:records[i].id,rightId:records[j].id,result:await assessGenericRecordContradiction(providers,records[i],records[j],'military-records',policy)});const strategy=await recommendGenericRecordFollowUp(providers,'military-records',{deterministic,requestedItems:source.requestedItems??[],records:records.slice(0,20).map(r=>({id:r.id,filename:r.filename,category:r.category,text:r.text??''})),extracted:analyzed.map(i=>({id:i.id,classification:i.classification.value,facts:i.facts.value})),contradictions:contradictions.filter(i=>i.result.value.contradictory).map(i=>({leftId:i.leftId,rightId:i.rightId,analysis:i.result.value}))},policy);return {...deterministic,aiStrategy:strategy.value,aiProvenance:{providers:strategy.providers,confidence:strategy.confidence,disagreements:strategy.disagreements,warnings:strategy.warnings},aiRecordAnalysis:analyzed.map(i=>({id:i.id,classification:i.classification.value,facts:i.facts.value,classificationProvenance:i.classification.providers,factProvenance:i.facts.providers})),aiContradictions:contradictions.filter(i=>i.result.value.contradictory).map(i=>({leftId:i.leftId,rightId:i.rightId,analysis:i.result.value,providers:i.result.providers}))}}},
})
