import type { ValidatedRequest } from '../request-service'
import { createRecordsWorkflow, type RecordsWorkflow } from '../workflow-factory'
import type { RecordsDomainCapability } from './domain-pack'
import { analyzeGenericProduction, type GenericProductionRecord } from './generic-records-analysis'
import { assessGenericRecordContradiction, classifyGenericRecord, extractGenericRecordFacts, recommendGenericRecordFollowUp } from './generic-records-ai'
import { getConfiguredRecordsLlmProviders } from '../ai/records-llm-providers'

export const PUBLIC_INFORMATION_CATEGORIES = [
  'information-index-metadata-and-request-status',
  'agency-program-decision-and-administrative-records',
  'reports-studies-statistics-dashboards-and-data',
  'policy-guidance-directives-procedures-and-manuals',
  'emails-correspondence-texts-and-communications',
  'meetings-calendars-agendas-minutes-and-presentations',
  'contracts-procurement-grants-expenditures-and-vendor-records',
  'inspections-audits-compliance-and-performance-records',
  'complaint-investigation-inquiry-and-case-status-records',
  'public-role-assignment-and-organizational-records',
  'referenced-cross-indexed-and-attachment-records',
  'fee-transfer-withholding-redaction-no-records-and-closure-status',
] as const

export const PUBLIC_INFORMATION_CAPABILITIES: readonly RecordsDomainCapability[] = ['classification','extraction','deadline','contradiction','findings','evidence','research','risk','strategy','draft','draftProvenance','validation','review','approval','mailing','tracking','proofAudit']

export const PUBLIC_INFORMATION_INTAKE = [
  { id:'agency', label:'Government agency / public body', required:true, helpText:'Agency, board, office, authority, district, department, court office, or other public body likely to maintain the information or underlying records.' },
  { id:'jurisdiction', label:'Jurisdiction', required:true, helpText:'Federal, state, county, city, district, court, or other jurisdiction whose disclosure rules and procedures may apply.' },
  { id:'department', label:'Specific office / division / custodian', helpText:'Office, division, program, records custodian, or employee role when known.' },
  { id:'informationDescription', label:'Information / records sought', required:true, helpText:'Describe identifiable existing records, data, reports, communications, or documents. Avoid asking the agency to create an answer or new analysis.' },
  { id:'subjectMatter', label:'Subject / objective', required:true, helpText:'Plain-English description of the topic and what the requested information should document.' },
  { id:'dateStart', label:'Record period start', required:true, helpText:'Beginning of the requested record period.' },
  { id:'dateEnd', label:'Record period end', required:true, helpText:'End of the requested record period.' },
  { id:'identifiers', label:'Identifiers', helpText:'Names, case/project numbers, addresses, contracts, programs, meetings, report titles, data fields, or other search-ready identifiers.' },
  { id:'custodians', label:'Likely custodians', helpText:'People, offices, roles, departments, contractors, or systems likely to maintain responsive information.' },
  { id:'searchTerms', label:'Search terms', helpText:'Distinctive names, phrases, topics, project terms, addresses, or other terms useful for communications or data searches.' },
  { id:'preferredFormat', label:'Preferred format', helpText:'Native electronic files, PDF, CSV, spreadsheet, email export, audio/video, or another available format.' },
  { id:'dataFields', label:'Data fields / columns requested', helpText:'For structured data, identify desired existing fields or columns when known.' },
  { id:'exclusions', label:'Scope exclusions / narrowing', helpText:'Optional exclusions that reduce noise without changing the objective.' },
] as const

function text(input:Record<string,unknown>,key:string):string|undefined{const raw=input[key];if(typeof raw!=='string')return undefined;const value=raw.trim();return value||undefined}
function selectedCategories(input:Record<string,unknown>):string[]{const raw=input.categories;if(!Array.isArray(raw))return [...PUBLIC_INFORMATION_CATEGORIES];const known=new Set(PUBLIC_INFORMATION_CATEGORIES);const selected=raw.filter((entry):entry is string=>typeof entry==='string'&&known.has(entry as typeof PUBLIC_INFORMATION_CATEGORIES[number]));return selected.length?selected:[...PUBLIC_INFORMATION_CATEGORIES]}
function scope(input:Record<string,unknown>):string{const start=text(input,'dateStart'),end=text(input,'dateEnd');const parts=[text(input,'identifiers')&&`Identifiers: ${text(input,'identifiers')}.`,text(input,'custodians')&&`Likely custodians: ${text(input,'custodians')}.`,text(input,'searchTerms')&&`Search terms: ${text(input,'searchTerms')}.`,text(input,'preferredFormat')&&`Preferred format: ${text(input,'preferredFormat')}.`,text(input,'dataFields')&&`Requested existing data fields/columns: ${text(input,'dataFields')}.`,text(input,'exclusions')&&`Scope exclusions/narrowing: ${text(input,'exclusions')}.`].filter(Boolean);return `${start&&end?` Cover ${start} through ${end}.`:''}${parts.length?` ${parts.join(' ')}`:''}`}
function describe(category:string,input:Record<string,unknown>):string{
  const s=scope(input);const objective=text(input,'subjectMatter')?` Objective: ${text(input,'subjectMatter')}.`:'';const supplied=text(input,'informationDescription')?` Information/records description supplied by requester: ${text(input,'informationDescription')}.`:''
  const descriptions:Record<string,string>={
    'information-index-metadata-and-request-status':`Existing indexes, inventories, logs, catalogs, metadata, file lists, database dictionaries where maintained, tracking records, or equivalent records that identify responsive information, record sets, custodians, dates, attachments, referrals, production, or request status. Do not require a new explanatory record.${s}`,
    'agency-program-decision-and-administrative-records':`Existing agency, program, administrative, decision, approval, recommendation, staff-analysis, operational, and implementation records tied to the identified topic.${s}`,
    'reports-studies-statistics-dashboards-and-data':`Existing reports, studies, analyses, statistical products, dashboards, spreadsheets, datasets, database exports, and underlying machine-readable data where maintained and lawfully available. Prefer requested native/machine-readable format and existing fields when available.${s}`,
    'policy-guidance-directives-procedures-and-manuals':`Existing policies, procedures, directives, manuals, guidance, bulletins, training materials, standards, and relevant versions applicable during the requested period.${s}`,
    'emails-correspondence-texts-and-communications':`Existing emails, attachments, letters, correspondence, text/message records, platform messages, and other communications within scope. Use supplied custodians/search terms when known and preserve attachments as a separate completeness check.${s}`,
    'meetings-calendars-agendas-minutes-and-presentations':`Existing calendars, invitations, agendas, minutes, notes where maintained and lawfully accessible, presentations, handouts, attendance records, recordings, and meeting follow-up records tied to the topic.${s}`,
    'contracts-procurement-grants-expenditures-and-vendor-records':`Existing contracts, amendments, procurement records, grants, purchase orders, invoices, expenditure/payment records, vendor records, and related financial documentation tied to the topic, subject to lawful access limits.${s}`,
    'inspections-audits-compliance-and-performance-records':`Existing inspection, audit, compliance, monitoring, evaluation, performance, corrective-action, and supporting records within scope.${s}`,
    'complaint-investigation-inquiry-and-case-status-records':`Lawfully accessible complaint, investigation, inquiry, intake, referral, case, status, disposition, and related records. Do not assume confidential source, victim, witness, juvenile, privileged, law-enforcement-sensitive, or other protected information is publicly disclosable.${s}`,
    'public-role-assignment-and-organizational-records':`Lawfully accessible organizational charts, public employee roles, titles, assignments, responsibility records, office directories, and other public-facing employment or organizational information pertinent to the topic. Do not treat private personnel, medical, financial, disciplinary, or authentication data as automatically public.${s}`,
    'referenced-cross-indexed-and-attachment-records':`Existing attachments, enclosures, exhibits, linked files, referenced documents, cross-indexed records, related identifiers, and records expressly identified within responsive material but not otherwise produced.${s}`,
    'fee-transfer-withholding-redaction-no-records-and-closure-status':`Existing acknowledgment, search/status, fee, clarification, transfer/referral, no-records, withholding, redaction, exemption, partial-production, closure, and other response records. Preserve the agency's actual stated basis rather than inferring a deadline, exemption, disclosure entitlement, violation, or appeal right.${s}`,
  }
  return `${descriptions[category]??`Existing public information concerning ${category}.${s}`}${supplied}${objective}`
}
function validatePublicInformation(request:ValidatedRequest):readonly {field:string;message:string}[]{const issues:{field:string;message:string}[]=[];const corpus=request.items.map(item=>item.description.toLowerCase()).join(' ');if(!request.agency?.trim())issues.push({field:'agency',message:'Identify the public body likely to maintain the information or records.'});if(!request.jurisdiction?.trim())issues.push({field:'jurisdiction',message:'Identify the relevant jurisdiction.'});if(!corpus.includes('information/records description supplied by requester:'))issues.push({field:'informationDescription',message:'Describe identifiable existing information, data, or records sought.'});if(!corpus.includes('objective:'))issues.push({field:'subjectMatter',message:'Describe the subject and information objective.'});if(!corpus.includes('cover '))issues.push({field:'dateRange',message:'Provide the requested record period.'});return issues}
export function buildPublicInformationRequest(input:Record<string,unknown>){const agency=text(input,'agency')??'';const subject=text(input,'subjectMatter');const start=text(input,'dateStart'),end=text(input,'dateEnd');const categories=selectedCategories(input);return {title:`Public Information Request — ${subject??agency??'Government Information'}`,agency,jurisdiction:text(input,'jurisdiction'),purpose:text(input,'purpose')??'Request identifiable existing public information and underlying records with search-ready scope, data/format controls, and production-review safeguards.',scope:JSON.stringify({workflow:'public-information-request',department:text(input,'department'),informationDescription:text(input,'informationDescription'),subjectMatter:subject,dateStart:start,dateEnd:end,identifiers:text(input,'identifiers'),custodians:text(input,'custodians'),searchTerms:text(input,'searchTerms'),preferredFormat:text(input,'preferredFormat'),dataFields:text(input,'dataFields'),exclusions:text(input,'exclusions')}),items:categories.map(category=>({category,description:describe(category,input),dateStart:start,dateEnd:end,custodian:text(input,'department')??text(input,'custodians'),format:text(input,'preferredFormat'),systemHint:category==='emails-correspondence-texts-and-communications'?'email / messaging / correspondence systems':category==='reports-studies-statistics-dashboards-and-data'?'reporting database / dashboard / spreadsheet / data warehouse or native data system':category==='information-index-metadata-and-request-status'?'records catalog / index / document management / request tracking system':undefined}))}}

export const PUBLIC_INFORMATION_FINDINGS=['MISSING_REQUESTED_CATEGORY','REFERENCED_RECORD_NOT_PRODUCED','IDENTIFIER_MISMATCH','DATE_GAP','DUPLICATE_RECORD','MISSING_ATTACHMENT','UNEXPLAINED_WITHHOLDING','REDACTION_REVIEW','PARTIAL_PRODUCTION','UNRESPONSIVE_ITEM'] as const

export const productionPublicInformationRequestWorkflow:RecordsWorkflow=createRecordsWorkflow({
  id:'public-information-request',name:'Public Information Request',description:'Build a search-ready request for identifiable existing government information, records, reports, data, communications, and supporting materials with jurisdiction, custodians, formats, data fields, and production-review controls.',searchIntent:'public information request',seo:{title:'Public Information Request — Government Records, Reports & Data',description:'Build a precise public information request for existing government records, reports, data, communications, policies, contracts, and supporting materials with search-ready scope and production-review controls.',canonicalPath:'/workflows/public-information-request'},intakeVersion:'2.0.0',intake:PUBLIC_INFORMATION_INTAKE,capabilities:PUBLIC_INFORMATION_CAPABILITIES,request:{categories:PUBLIC_INFORMATION_CATEGORIES,build:buildPublicInformationRequest},validate:validatePublicInformation,
  policies:[{jurisdiction:'all',version:'2.0.0',rules:{requestExistingIdentifiableInformationAndRecordsRatherThanAgencyCreatedAnswersOrNewAnalysis:true,preserveJurisdictionAsAnExplicitAuthorityAndProcedureResearchInput:true,doNotInventRecordOrDataExistenceCustodiansSystemsFieldsSearchTermsAgencyFactsOrRequestStatus:true,doNotAssertJurisdictionSpecificDeadlinesExemptionsFeesWaiversAppealRightsDisclosureRightsOrViolationsWithoutVerifiedAuthority:true,doNotTreatProtectedPersonnelMedicalFinancialJuvenileVictimWitnessSecurityOrAuthenticationDataAsPublic:true,doNotRequestPasswordsSecurityAnswersOneTimeCodesAuthenticationTokensPaymentCredentialsOrSecuritySensitiveSystemDetails:true,preserveRequesterScopeIdentifiersCustodiansSearchTermsFormatsDataFieldsAndExclusions:true,requireHumanReviewWhenConsequentialDeadlineLegalConclusionDataInterpretationOrSensitiveAccessIsUnclear:true}}],
  responseAnalysis:{findingTypes:PUBLIC_INFORMATION_FINDINGS,async analyze(input:unknown){if(!input||typeof input!=='object')throw new Error('PUBLIC_INFORMATION_PRODUCTION_ANALYSIS_INPUT_INVALID');const source=input as {requestedItems?:readonly {category:string;description:string}[];records?:readonly GenericProductionRecord[]};const records=source.records??[];const requested=(source.requestedItems??[]).map(item=>({id:item.category,label:item.category,keywords:item.description.split(/\W+/).filter(word=>word.length>=4).slice(0,20)}));const deterministic=analyzeGenericProduction(requested,records,'public information record');const providers=getConfiguredRecordsLlmProviders();if(providers.length<2)return deterministic;const policy={minimumProviders:2,agreementThreshold:0.67,maxProviders:3} as const;const requestedCategories=requested.map(item=>item.id);const analyzed=await Promise.all(records.slice(0,20).map(async record=>({id:record.id,classification:await classifyGenericRecord(providers,record,'public-information-request',requestedCategories,policy),facts:await extractGenericRecordFacts(providers,record,'public-information-request',policy)})));const contradictions:Array<{leftId:string;rightId:string;result:Awaited<ReturnType<typeof assessGenericRecordContradiction>>}>=[];for(let i=0;i<Math.min(records.length,10);i+=1)for(let j=i+1;j<Math.min(records.length,10);j+=1)contradictions.push({leftId:records[i].id,rightId:records[j].id,result:await assessGenericRecordContradiction(providers,records[i],records[j],'public-information-request',policy)});const strategy=await recommendGenericRecordFollowUp(providers,'public-information-request',{deterministic,requestedItems:source.requestedItems??[],records:records.slice(0,20).map(record=>({id:record.id,filename:record.filename,category:record.category,text:record.text??''})),extracted:analyzed.map(item=>({id:item.id,classification:item.classification.value,facts:item.facts.value})),contradictions:contradictions.filter(item=>item.result.value.contradictory).map(item=>({leftId:item.leftId,rightId:item.rightId,analysis:item.result.value}))},policy);return {...deterministic,aiStrategy:strategy.value,aiProvenance:{providers:strategy.providers,confidence:strategy.confidence,disagreements:strategy.disagreements,warnings:strategy.warnings},aiRecordAnalysis:analyzed.map(item=>({id:item.id,classification:item.classification.value,facts:item.facts.value,classificationProvenance:item.classification.providers,factProvenance:item.facts.providers})),aiContradictions:contradictions.filter(item=>item.result.value.contradictory).map(item=>({leftId:item.leftId,rightId:item.rightId,analysis:item.result.value,providers:item.result.providers}))}}},
})
