import type { ValidatedRequest } from '../request-service'
import { createRecordsWorkflow, type RecordsWorkflow } from '../workflow-factory'
import type { RecordsDomainCapability } from './domain-pack'
import { analyzeGenericProduction, type GenericProductionRecord } from './generic-records-analysis'
import { assessGenericRecordContradiction, classifyGenericRecord, extractGenericRecordFacts, recommendGenericRecordFollowUp } from './generic-records-ai'
import { getConfiguredRecordsLlmProviders } from '../ai/records-llm-providers'

export const RECORDS_FOLLOW_UP_CATEGORIES = [
  'original-request-and-scope-reference',
  'acknowledgment-and-status-history',
  'production-inventory-and-missing-categories',
  'referenced-but-unproduced-records',
  'search-custodian-and-system-status',
  'rolling-production-and-estimated-completion',
  'fee-estimate-and-payment-status',
  'clarification-narrowing-and-scope-status',
  'redaction-withholding-and-segregability-status',
  'deadline-and-response-timeline',
  'correspondence-and-contact-history',
  'closure-no-records-and-review-status',
] as const

export const RECORDS_FOLLOW_UP_CAPABILITIES: readonly RecordsDomainCapability[] = ['classification','extraction','deadline','contradiction','findings','evidence','research','risk','strategy','draft','draftProvenance','validation','review','approval','mailing','tracking','proofAudit']

export const RECORDS_FOLLOW_UP_INTAKE = [
  { id:'agency', label:'Agency / records custodian', required:true, helpText:'Agency or office handling the original request.' },
  { id:'jurisdiction', label:'Jurisdiction', helpText:'Federal, state, county, city, district, court, or other jurisdiction when known.' },
  { id:'originalRequestDate', label:'Original request date', required:true, helpText:'Date the original request was sent or submitted.' },
  { id:'originalRequestNumber', label:'Original request / tracking number', helpText:'Reference, portal, case, ticket, or tracking number when known.' },
  { id:'originalScopeSummary', label:'Original request scope', required:true, helpText:'Paste or summarize the record categories and scope from the original request without expanding it.' },
  { id:'responseStatus', label:'Current response status', required:true, helpText:'For example: no response, acknowledgment, partial production, rolling production, fee notice, clarification request, estimated completion date, or closed.' },
  { id:'lastAgencyContactDate', label:'Last agency contact date', helpText:'Date of the most recent agency communication.' },
  { id:'promisedOrEstimatedDate', label:'Promised / estimated completion date', helpText:'Use only a date actually stated by the agency.' },
  { id:'producedCategories', label:'Categories already produced', helpText:'Record categories already received, if any.' },
  { id:'missingCategories', label:'Missing / incomplete categories', helpText:'Original categories not yet produced or apparently incomplete.' },
  { id:'withholdingOrRedactionSummary', label:'Withholding / redaction summary', helpText:'Exact or close summary of withholding, exemption, redaction, or nonproduction language if supplied.' },
  { id:'feeIssue', label:'Fee / cost issue', helpText:'Fee estimate, deposit, payment status, waiver request, or cost question if relevant.' },
  { id:'subjectMatter', label:'Follow-up objective', required:true, helpText:'What needs to be clarified, completed, confirmed, or preserved in this follow-up.' },
] as const

function text(input:Record<string,unknown>,key:string):string|undefined{const raw=input[key];if(typeof raw!=='string')return undefined;const value=raw.trim();return value||undefined}
function selectedCategories(input:Record<string,unknown>):string[]{const raw=input.categories;if(!Array.isArray(raw))return [...RECORDS_FOLLOW_UP_CATEGORIES];const known=new Set(RECORDS_FOLLOW_UP_CATEGORIES);const selected=raw.filter((entry):entry is string=>typeof entry==='string'&&known.has(entry as typeof RECORDS_FOLLOW_UP_CATEGORIES[number]));return selected.length?selected:[...RECORDS_FOLLOW_UP_CATEGORIES]}
function context(input:Record<string,unknown>):string{const parts=[`Original request date: ${text(input,'originalRequestDate')??'unknown'}.`,text(input,'originalRequestNumber')&&`Original request/reference number: ${text(input,'originalRequestNumber')}.`,text(input,'responseStatus')&&`Current response status: ${text(input,'responseStatus')}.`,text(input,'lastAgencyContactDate')&&`Last agency contact date: ${text(input,'lastAgencyContactDate')}.`,text(input,'promisedOrEstimatedDate')&&`Agency-stated promised/estimated date: ${text(input,'promisedOrEstimatedDate')}.`].filter(Boolean);return ` ${parts.join(' ')}`}
function describe(category:string,input:Record<string,unknown>):string{
  const original=text(input,'originalScopeSummary')??'the preserved original request scope';const produced=text(input,'producedCategories');const missing=text(input,'missingCategories');const withholding=text(input,'withholdingOrRedactionSummary');const fee=text(input,'feeIssue');const objective=text(input,'subjectMatter')?` Follow-up objective: ${text(input,'subjectMatter')}.`:'';const ctx=context(input)
  const descriptions:Record<string,string>={
    'original-request-and-scope-reference':`Preserve and reference the original request exactly enough to identify its scope without silently broadening it. Original scope: ${original}.${ctx}`,
    'acknowledgment-and-status-history':`Request or confirm the current processing status, acknowledgment history, assigned tracking/reference information, and any agency-stated processing stage or next action.${ctx}`,
    'production-inventory-and-missing-categories':`Compare the production received so far against the preserved original scope. Produced categories: ${produced??'not specified'}. Missing or incomplete categories: ${missing??'not specified'}. Ask the agency to identify the status of each unresolved original category without asserting that an unverified record exists.${ctx}`,
    'referenced-but-unproduced-records':`Identify records, attachments, enclosures, logs, media, indexes, or other items that the agency production or correspondence expressly references but did not include, and ask for their production status or the stated reason they were not produced.${ctx}`,
    'search-custodian-and-system-status':`Ask for available status information about the offices, custodians, record systems, archives, or referrals involved in processing the original request when useful to understand an incomplete or no-records response. Do not demand security-sensitive system details or credentials.${ctx}`,
    'rolling-production-and-estimated-completion':`Confirm whether production is complete or rolling, what portions remain outstanding, and any completion date or sequence actually stated by the agency. Do not invent a promised date or characterize an estimate as guaranteed.${ctx}`,
    'fee-estimate-and-payment-status':`Clarify any fee estimate, deposit, payment, waiver, copying, delivery, or cost status relevant to the original request. Fee issue supplied by requester: ${fee??'none specified'}. Do not provide or request payment credentials.${ctx}`,
    'clarification-narrowing-and-scope-status':`Preserve any agency request for clarification or narrowing, the requester's response, and the resulting scope status. Distinguish an agreed narrowing from an agency interpretation or unresolved scope question; do not silently alter the original request.${ctx}`,
    'redaction-withholding-and-segregability-status':`Preserve and ask for clarification of any stated withholding, redaction, exemption, confidentiality, or partial-disclosure status and whether segregable/non-exempt portions were addressed. Supplied summary: ${withholding??'none specified'}. Do not invent legal authority or assert that a withholding is unlawful without verified controlling authority.${ctx}`,
    'deadline-and-response-timeline':`Create a factual timeline from the original submission, agency acknowledgments, productions, fee/clarification notices, and other communications. Ask the agency to confirm any deadline, extension, estimated date, or next response date it actually stated. Do not calculate or assert a legal deadline unless controlling authority and trigger facts are supplied and verified.${ctx}`,
    'correspondence-and-contact-history':`Preserve and reference relevant correspondence, portal messages, letters, emails, call notes, and contact dates so the follow-up reflects the documented history rather than assumptions.${ctx}`,
    'closure-no-records-and-review-status':`If the agency closed the request, reported no responsive records, transferred it, or otherwise ended processing, ask for the documented closure/status basis, any available referral or review path, and any segregable status/index information that can lawfully be provided.${ctx}`,
  }
  return `${descriptions[category]??`Follow-up status for ${category}.${ctx}`}${objective}`
}
function validateRecordsFollowUp(request:ValidatedRequest):readonly {field:string;message:string}[]{const issues:{field:string;message:string}[]=[];const corpus=request.items.map(item=>item.description.toLowerCase()).join(' ');if(!corpus.includes('original request date:'))issues.push({field:'originalRequestDate',message:'Provide the original request date.'});if(!corpus.includes('original scope:'))issues.push({field:'originalScopeSummary',message:'Preserve the original request scope.'});if(!corpus.includes('current response status:'))issues.push({field:'responseStatus',message:'State the current response status.'});if(!corpus.includes('follow-up objective:'))issues.push({field:'subjectMatter',message:'Describe the follow-up objective.'});return issues}
export function buildRecordsFollowUpRequest(input:Record<string,unknown>){const categories=selectedCategories(input);const subject=text(input,'subjectMatter');return {title:`Records Follow-Up — ${subject??'Status and Production Review'}`,agency:text(input,'agency')??'',jurisdiction:text(input,'jurisdiction'),purpose:text(input,'purpose')??'Follow up on the documented status, completeness, timeline, and unresolved items from the preserved original records request without silently expanding its scope.',scope:JSON.stringify({workflow:'records-follow-up',originalRequestDate:text(input,'originalRequestDate'),originalRequestNumber:text(input,'originalRequestNumber'),originalScopeSummary:text(input,'originalScopeSummary'),responseStatus:text(input,'responseStatus'),lastAgencyContactDate:text(input,'lastAgencyContactDate'),promisedOrEstimatedDate:text(input,'promisedOrEstimatedDate'),producedCategories:text(input,'producedCategories'),missingCategories:text(input,'missingCategories'),withholdingOrRedactionSummary:text(input,'withholdingOrRedactionSummary'),feeIssue:text(input,'feeIssue'),subjectMatter:subject}),items:categories.map(category=>({category,description:describe(category,input)}))}}

export const RECORDS_FOLLOW_UP_FINDINGS=['MISSING_REQUESTED_CATEGORY','REFERENCED_RECORD_NOT_PRODUCED','IDENTIFIER_MISMATCH','DATE_GAP','DUPLICATE_RECORD','MISSING_ATTACHMENT','UNEXPLAINED_WITHHOLDING','REDACTION_REVIEW','PARTIAL_PRODUCTION','UNRESPONSIVE_ITEM'] as const

export const productionRecordsFollowUpWorkflow:RecordsWorkflow=createRecordsWorkflow({
  id:'records-follow-up',name:'Records Follow-Up Request',description:'Build an evidence-based follow-up for an unanswered, delayed, partial, rolling, fee-pending, clarified, or closed records request while preserving the original scope and response history.',searchIntent:'records follow up request',seo:{title:'Records Follow-Up Request — Status, Missing Records & Partial Production',description:'Build a targeted records-request follow-up that preserves the original scope, documents the response timeline, identifies missing categories and referenced-but-unproduced records, and clarifies fees, withholding, or completion status.',canonicalPath:'/workflows/records-follow-up'},intakeVersion:'2.0.0',intake:RECORDS_FOLLOW_UP_INTAKE,capabilities:RECORDS_FOLLOW_UP_CAPABILITIES,request:{categories:RECORDS_FOLLOW_UP_CATEGORIES,build:buildRecordsFollowUpRequest},validate:validateRecordsFollowUp,
  policies:[{jurisdiction:'all',version:'2.0.0',rules:{preserveOriginalRequestScopeAndDoNotSilentlyBroadenIt:true,doNotInventRecordExistenceAgencyPromisesReceiptDatesOrDeadlines:true,doNotAssertLegalViolationOrControllingDeadlineWithoutVerifiedAuthorityAndTriggerFacts:true,distinguishAgencyStatementsFromRequesterAssertionsAndSystemInferences:true,doNotRequestCredentialsPaymentSecretsOrSecuritySensitiveSystemDetails:true,requireHumanReviewWhenConsequentialDeadlineWaiverOrLegalConclusionIsUnclear:true,preserveOriginalRequestTrackingProductionAndCorrespondenceIdentifiers:true}}],
  responseAnalysis:{findingTypes:RECORDS_FOLLOW_UP_FINDINGS,async analyze(input:unknown){if(!input||typeof input!=='object')throw new Error('FOLLOWUP_PRODUCTION_ANALYSIS_INPUT_INVALID');const source=input as {requestedItems?:readonly {category:string;description:string}[];records?:readonly GenericProductionRecord[]};const records=source.records??[];const requested=(source.requestedItems??[]).map(item=>({id:item.category,label:item.category,keywords:item.description.split(/\W+/).filter(word=>word.length>=4).slice(0,20)}));const deterministic=analyzeGenericProduction(requested,records,'records follow-up');const providers=getConfiguredRecordsLlmProviders();if(providers.length<2)return deterministic;const policy={minimumProviders:2,agreementThreshold:0.67,maxProviders:3} as const;const requestedCategories=requested.map(item=>item.id);const analyzed=await Promise.all(records.slice(0,20).map(async record=>({id:record.id,classification:await classifyGenericRecord(providers,record,'records-follow-up',requestedCategories,policy),facts:await extractGenericRecordFacts(providers,record,'records-follow-up',policy)})));const contradictions:Array<{leftId:string;rightId:string;result:Awaited<ReturnType<typeof assessGenericRecordContradiction>>}>=[];for(let i=0;i<Math.min(records.length,10);i+=1)for(let j=i+1;j<Math.min(records.length,10);j+=1)contradictions.push({leftId:records[i].id,rightId:records[j].id,result:await assessGenericRecordContradiction(providers,records[i],records[j],'records-follow-up',policy)});const strategy=await recommendGenericRecordFollowUp(providers,'records-follow-up',{deterministic,requestedItems:source.requestedItems??[],records:records.slice(0,20).map(record=>({id:record.id,filename:record.filename,category:record.category,text:record.text??''})),extracted:analyzed.map(item=>({id:item.id,classification:item.classification.value,facts:item.facts.value})),contradictions:contradictions.filter(item=>item.result.value.contradictory).map(item=>({leftId:item.leftId,rightId:item.rightId,analysis:item.result.value}))},policy);return {...deterministic,aiStrategy:strategy.value,aiProvenance:{providers:strategy.providers,confidence:strategy.confidence,disagreements:strategy.disagreements,warnings:strategy.warnings},aiRecordAnalysis:analyzed.map(item=>({id:item.id,classification:item.classification.value,facts:item.facts.value,classificationProvenance:item.classification.providers,factProvenance:item.facts.providers})),aiContradictions:contradictions.filter(item=>item.result.value.contradictory).map(item=>({leftId:item.leftId,rightId:item.rightId,analysis:item.result.value,providers:item.result.providers}))}}},
})
