import type { ValidatedRequest } from '../request-service'
import { createRecordsWorkflow, type RecordsWorkflow } from '../workflow-factory'
import type { RecordsDomainCapability } from './domain-pack'
import { analyzeGenericProduction, type GenericProductionRecord } from './generic-records-analysis'
import { assessGenericRecordContradiction, classifyGenericRecord, extractGenericRecordFacts, recommendGenericRecordFollowUp } from './generic-records-ai'
import { getConfiguredRecordsLlmProviders } from '../ai/records-llm-providers'

export const RECORDS_DENIAL_APPEAL_CATEGORIES = [
  'original-request-and-scope-record',
  'denial-letter-and-stated-basis',
  'denied-category-and-partial-production-inventory',
  'exemption-withholding-and-redaction-language',
  'segregability-and-partial-disclosure-status',
  'search-adequacy-record-existence-and-custodian-status',
  'factual-identifier-and-scope-correction',
  'fee-format-burden-and-processing-basis',
  'administrative-review-route-and-instructions',
  'appeal-deadline-and-response-timeline',
  'prior-correspondence-and-evidence-preservation',
  'requested-review-remedy-and-status',
] as const

export const RECORDS_DENIAL_APPEAL_CAPABILITIES: readonly RecordsDomainCapability[] = ['classification','extraction','deadline','contradiction','findings','evidence','research','risk','strategy','draft','draftProvenance','validation','review','approval','mailing','tracking','proofAudit']

export const RECORDS_DENIAL_APPEAL_INTAKE = [
  { id:'agency', label:'Agency / records custodian', required:true, helpText:'Agency or office that issued the denial, withholding decision, closure, or other adverse response.' },
  { id:'jurisdiction', label:'Jurisdiction', required:true, helpText:'Federal, state, county, city, district, court, or other jurisdiction governing the request.' },
  { id:'originalRequestDate', label:'Original request date', required:true, helpText:'Date the original request was submitted.' },
  { id:'originalRequestNumber', label:'Original request / tracking number', helpText:'Portal, ticket, case, reference, or tracking number when known.' },
  { id:'originalScopeSummary', label:'Original request scope', required:true, helpText:'Paste or accurately summarize the original requested categories and scope.' },
  { id:'denialDate', label:'Denial / adverse response date', required:true, helpText:'Date shown on the denial, closure, withholding, no-records, or other adverse response.' },
  { id:'denialReceivedDate', label:'Date received', helpText:'Use the actual receipt date only when known; do not estimate.' },
  { id:'denialBasisExact', label:'Stated denial / withholding basis', required:true, helpText:'Paste or closely preserve the agency’s actual exemption, rule, reason, or explanation.' },
  { id:'deniedCategories', label:'Denied / withheld categories', required:true, helpText:'Identify which original categories were denied, withheld, closed, or left unresolved.' },
  { id:'partialProductionSummary', label:'Partial production / released portions', helpText:'Describe records or segregable portions that were produced, if any.' },
  { id:'appealInstructions', label:'Review / appeal instructions', helpText:'Paste the agency’s actual administrative review, appeal, reconsideration, or cure instructions.' },
  { id:'statedAppealDeadline', label:'Agency-stated appeal deadline', helpText:'Enter only the deadline actually stated by the agency or verified controlling authority.' },
  { id:'authorityNotes', label:'Verified authority / policy notes', helpText:'Optional controlling statute, regulation, rule, policy, order, or official guidance that has been verified and is relevant to review.' },
  { id:'desiredOutcome', label:'Requested outcome', required:true, helpText:'For example: reconsider denial, release segregable portions, clarify basis, conduct supplemental search, correct identifier/scope error, or provide review decision.' },
  { id:'subjectMatter', label:'Review objective / factual issue', required:true, helpText:'Plain-English description of the documented issue to be reviewed. Do not invent law or facts.' },
] as const

function text(input:Record<string,unknown>,key:string):string|undefined{const raw=input[key];if(typeof raw!=='string')return undefined;const value=raw.trim();return value||undefined}
function selectedCategories(input:Record<string,unknown>):string[]{const raw=input.categories;if(!Array.isArray(raw))return [...RECORDS_DENIAL_APPEAL_CATEGORIES];const known=new Set(RECORDS_DENIAL_APPEAL_CATEGORIES);const selected=raw.filter((entry):entry is string=>typeof entry==='string'&&known.has(entry as typeof RECORDS_DENIAL_APPEAL_CATEGORIES[number]));return selected.length?selected:[...RECORDS_DENIAL_APPEAL_CATEGORIES]}
function context(input:Record<string,unknown>):string{const parts=[`Original request date: ${text(input,'originalRequestDate')??'unknown'}.`,`Denial/adverse response date: ${text(input,'denialDate')??'unknown'}.`,text(input,'denialReceivedDate')&&`Actual received date supplied by requester: ${text(input,'denialReceivedDate')}.`,text(input,'originalRequestNumber')&&`Request/reference number: ${text(input,'originalRequestNumber')}.`,text(input,'statedAppealDeadline')&&`Agency-stated or independently verified review deadline: ${text(input,'statedAppealDeadline')}.`].filter(Boolean);return ` ${parts.join(' ')}`}
function describe(category:string,input:Record<string,unknown>):string{
  const scope=text(input,'originalScopeSummary')??'the preserved original request scope';const basis=text(input,'denialBasisExact')??'not supplied';const denied=text(input,'deniedCategories')??'not supplied';const partial=text(input,'partialProductionSummary');const instructions=text(input,'appealInstructions');const authority=text(input,'authorityNotes');const outcome=text(input,'desiredOutcome')??'review of the documented adverse response';const objective=text(input,'subjectMatter')?` Review objective/factual issue: ${text(input,'subjectMatter')}.`:'';const ctx=context(input)
  const descriptions:Record<string,string>={
    'original-request-and-scope-record':`Preserve the original request, its exact material scope, identifiers, categories, and any agreed narrowing or clarification. Do not rewrite the original scope to make the review stronger. Original scope: ${scope}.${ctx}`,
    'denial-letter-and-stated-basis':`Preserve the denial or other adverse response and the agency’s stated reasoning accurately. Stated basis: ${basis}. Distinguish quoted/stated agency reasoning from requester assertions and AI analysis.${ctx}`,
    'denied-category-and-partial-production-inventory':`Map each denied, withheld, closed, or unresolved category back to the original request and identify any portions actually produced. Denied/unresolved categories: ${denied}. Partial production: ${partial??'none specified'}.${ctx}`,
    'exemption-withholding-and-redaction-language':`Identify the exact exemption, confidentiality, privilege, withholding, redaction, burden, no-records, or other language actually stated by the agency. Analyze its application only against verified facts and verified controlling authority supplied to the workflow; do not invent a legal rule.${ctx}`,
    'segregability-and-partial-disclosure-status':`Determine whether the adverse response addresses partial disclosure, segregable/non-exempt portions, redacted copies, indexes, metadata, or other portions potentially separable from withheld material. Ask for clarification or review where the documented response leaves that status unresolved; do not assume disclosure is legally required without verified authority.${ctx}`,
    'search-adequacy-record-existence-and-custodian-status':`Where the response is based on no records, inability to locate records, transfer/referral, or incomplete search information, identify documented custodians, systems, identifiers, referenced records, and search gaps that can support a factual request for clarification or supplemental search. Do not assert that an unverified record exists.${ctx}`,
    'factual-identifier-and-scope-correction':`Identify objective mistakes or mismatches in names, dates, addresses, case/incident/permit numbers, scope interpretation, categories, or other search identifiers that are supported by the record. Request correction or reconsideration based on documented facts rather than invented legal conclusions.${ctx}`,
    'fee-format-burden-and-processing-basis':`Preserve and review any fee, format, burden, overbreadth, duplication, processing, delivery, or technical basis stated in the adverse response, including any cure or narrowing instructions. Do not supply payment credentials or silently agree to a materially changed scope.${ctx}`,
    'administrative-review-route-and-instructions':`Preserve the agency’s actual appeal, administrative review, reconsideration, ombuds, supervisor, cure, or other review instructions. Supplied instructions: ${instructions??'none supplied'}. Do not invent an appeal route or filing requirement.${ctx}`,
    'appeal-deadline-and-response-timeline':`Build a factual timeline from the original request, acknowledgments, productions, adverse response, receipt date if actually known, and review instructions. Preserve any agency-stated or independently verified deadline as supplied, but do not calculate or assert a controlling deadline unless the legal rule and triggering facts are verified.${ctx}`,
    'prior-correspondence-and-evidence-preservation':`Preserve the original request, denial, production inventory, correspondence, portal messages, tracking records, attachments, and other evidence needed to show what was requested, what the agency said, and what remains disputed.${ctx}`,
    'requested-review-remedy-and-status':`Prepare a precise request for the documented review outcome without promising success or making unsupported legal claims. Requested outcome: ${outcome}. Any substantive legal proposition should be tied to verified authority supplied in the matter.${authority?` Verified authority/policy notes supplied: ${authority}.`:''}${ctx}`,
  }
  return `${descriptions[category]??`Review material concerning ${category}.${ctx}`}${objective}`
}
function validateRecordsDenialAppeal(request:ValidatedRequest):readonly {field:string;message:string}[]{const issues:{field:string;message:string}[]=[];const corpus=request.items.map(item=>item.description.toLowerCase()).join(' ');if(!corpus.includes('original scope:'))issues.push({field:'originalScopeSummary',message:'Preserve the original request scope.'});if(!corpus.includes('denial/adverse response date:'))issues.push({field:'denialDate',message:'Provide the denial or adverse-response date.'});if(!corpus.includes('stated basis:'))issues.push({field:'denialBasisExact',message:'Provide the agency’s stated denial or withholding basis.'});if(!corpus.includes('denied/unresolved categories:'))issues.push({field:'deniedCategories',message:'Identify denied or unresolved original categories.'});if(!corpus.includes('requested outcome:'))issues.push({field:'desiredOutcome',message:'State the requested review outcome.'});if(!corpus.includes('review objective/factual issue:'))issues.push({field:'subjectMatter',message:'Describe the documented issue for review.'});return issues}
export function buildRecordsDenialAppealRequest(input:Record<string,unknown>){const categories=selectedCategories(input);const outcome=text(input,'desiredOutcome');return {title:`Records Denial Review — ${outcome??'Adverse Response'}`,agency:text(input,'agency')??'',jurisdiction:text(input,'jurisdiction'),purpose:text(input,'purpose')??'Prepare an evidence-based administrative review or appeal package addressing the documented records denial or other adverse response using preserved facts, exact agency reasoning, and verified authority only.',scope:JSON.stringify({workflow:'records-denial-appeal',originalRequestDate:text(input,'originalRequestDate'),originalRequestNumber:text(input,'originalRequestNumber'),originalScopeSummary:text(input,'originalScopeSummary'),denialDate:text(input,'denialDate'),denialReceivedDate:text(input,'denialReceivedDate'),denialBasisExact:text(input,'denialBasisExact'),deniedCategories:text(input,'deniedCategories'),partialProductionSummary:text(input,'partialProductionSummary'),appealInstructions:text(input,'appealInstructions'),statedAppealDeadline:text(input,'statedAppealDeadline'),authorityNotes:text(input,'authorityNotes'),desiredOutcome:outcome,subjectMatter:text(input,'subjectMatter')}),items:categories.map(category=>({category,description:describe(category,input)}))}}

export const RECORDS_DENIAL_APPEAL_FINDINGS=['MISSING_REQUESTED_CATEGORY','REFERENCED_RECORD_NOT_PRODUCED','IDENTIFIER_MISMATCH','DATE_GAP','DUPLICATE_RECORD','MISSING_ATTACHMENT','UNEXPLAINED_WITHHOLDING','REDACTION_REVIEW','PARTIAL_PRODUCTION','UNRESPONSIVE_ITEM'] as const

export const productionRecordsDenialAppealWorkflow:RecordsWorkflow=createRecordsWorkflow({
  id:'records-denial-appeal',name:'Records Denial / Appeal Request',description:'Prepare an evidence-based review of a records denial, withholding, no-records response, closure, fee/burden decision, or other adverse response using exact agency reasoning and verified authority.',searchIntent:'records denial appeal',seo:{title:'Records Denial Appeal — Review Withholding, Exemptions & Adverse Responses',description:'Prepare a records-denial review or appeal by preserving the original request, exact denial basis, denied categories, partial production, appeal instructions, timeline, factual issues, segregability, search gaps, and verified authority.',canonicalPath:'/workflows/records-denial-appeal'},intakeVersion:'2.0.0',intake:RECORDS_DENIAL_APPEAL_INTAKE,capabilities:RECORDS_DENIAL_APPEAL_CAPABILITIES,request:{categories:RECORDS_DENIAL_APPEAL_CATEGORIES,build:buildRecordsDenialAppealRequest},validate:validateRecordsDenialAppeal,
  policies:[{jurisdiction:'all',version:'2.0.0',rules:{preserveOriginalRequestDenialAndAgencyReasoningWithoutMaterialRewrite:true,distinguishAgencyStatementsRequesterAssertionsVerifiedAuthorityAndAIInferences:true,doNotInventExemptionsAppealRightsFilingRoutesDeadlinesViolationsOrCaseLaw:true,doNotAssertControllingLawUnlessAuthoritativeSourceAndApplicabilityAreVerified:true,doNotInventRecordExistenceSearchFailuresOrSegregabilityConclusions:true,requireHumanReviewBeforeConsequentialAppealSubmissionOrWhenDeadlineAuthorityOrLegalConclusionIsUnclear:true,preserveRequestDenialProductionCorrespondenceAndReviewIdentifiers:true}}],
  responseAnalysis:{findingTypes:RECORDS_DENIAL_APPEAL_FINDINGS,async analyze(input:unknown){if(!input||typeof input!=='object')throw new Error('DENIAL_APPEAL_ANALYSIS_INPUT_INVALID');const source=input as {requestedItems?:readonly {category:string;description:string}[];records?:readonly GenericProductionRecord[]};const records=source.records??[];const requested=(source.requestedItems??[]).map(item=>({id:item.category,label:item.category,keywords:item.description.split(/\W+/).filter(word=>word.length>=4).slice(0,20)}));const deterministic=analyzeGenericProduction(requested,records,'records denial review');const providers=getConfiguredRecordsLlmProviders();if(providers.length<2)return deterministic;const policy={minimumProviders:2,agreementThreshold:0.67,maxProviders:3} as const;const requestedCategories=requested.map(item=>item.id);const analyzed=await Promise.all(records.slice(0,20).map(async record=>({id:record.id,classification:await classifyGenericRecord(providers,record,'records-denial-appeal',requestedCategories,policy),facts:await extractGenericRecordFacts(providers,record,'records-denial-appeal',policy)})));const contradictions:Array<{leftId:string;rightId:string;result:Awaited<ReturnType<typeof assessGenericRecordContradiction>>}>=[];for(let i=0;i<Math.min(records.length,10);i+=1)for(let j=i+1;j<Math.min(records.length,10);j+=1)contradictions.push({leftId:records[i].id,rightId:records[j].id,result:await assessGenericRecordContradiction(providers,records[i],records[j],'records-denial-appeal',policy)});const strategy=await recommendGenericRecordFollowUp(providers,'records-denial-appeal',{deterministic,requestedItems:source.requestedItems??[],records:records.slice(0,20).map(record=>({id:record.id,filename:record.filename,category:record.category,text:record.text??''})),extracted:analyzed.map(item=>({id:item.id,classification:item.classification.value,facts:item.facts.value})),contradictions:contradictions.filter(item=>item.result.value.contradictory).map(item=>({leftId:item.leftId,rightId:item.rightId,analysis:item.result.value}))},policy);return {...deterministic,aiStrategy:strategy.value,aiProvenance:{providers:strategy.providers,confidence:strategy.confidence,disagreements:strategy.disagreements,warnings:strategy.warnings},aiRecordAnalysis:analyzed.map(item=>({id:item.id,classification:item.classification.value,facts:item.facts.value,classificationProvenance:item.classification.providers,factProvenance:item.facts.providers})),aiContradictions:contradictions.filter(item=>item.result.value.contradictory).map(item=>({leftId:item.leftId,rightId:item.rightId,analysis:item.result.value,providers:item.result.providers}))}}},
})
