// @generated by MailMyPDF workflow materializer. Edit workflow.spec.json or config.ts instead.
import { createFileRoute } from "@tanstack/react-router"
import RecordsRequestWorkflow from "../../../../../../../records-request/shared/RecordsRequestWorkflow"
import { getRecordsRequestFactoryArtifact } from "@mailmypdf/workflows"

const resolvedFactoryArtifact = getRecordsRequestFactoryArtifact("public-records-request")

if (!resolvedFactoryArtifact) {
  throw new Error("public-records-request factory artifact is missing")
}
if (!resolvedFactoryArtifact.factoryReady) {
  throw new Error("public-records-request factory artifact is not ready")
}

const factoryArtifact = resolvedFactoryArtifact

export function PublicRecordsRequestStart() {
  return <RecordsRequestWorkflow config={factoryArtifact.startConfig} />
}

export const Route = createFileRoute(
  "/records-request/workflows/public-records-request/start/",
)({
  component: PublicRecordsRequestStart,
})

export default PublicRecordsRequestStart
