// @generated by MailMyPDF workflow materializer. Edit workflow.spec.json or config.ts instead.
import { createFileRoute } from "@tanstack/react-router"
import { WorkflowLandingPage } from "@mailmypdf/design-system"
import workflowConfig from "../../../../../../appeal-mail/workflows/appeal-ssdi-denial/config"
import workflowSeo from "../../../../../../appeal-mail/workflows/appeal-ssdi-denial/seo"
import workflowSchema from "../../../../../../appeal-mail/workflows/appeal-ssdi-denial/schema"

export const Route = createFileRoute("/appeal-mail/workflows/appeal-ssdi-denial/")({
  head: () => ({
    ...workflowSeo,
    scripts: workflowSchema.map((schema) => ({
      type: "application/ld+json",
      children: JSON.stringify(schema),
    })),
  }),
  component: () => <WorkflowLandingPage config={workflowConfig} />,
})
