import { createFileRoute, Link } from '@tanstack/react-router'
import { Eye, FileText, Mail, Search, ArrowRight } from 'lucide-react'
import { createElement } from 'react'
import { recordsWorkflows } from '../workflows'
import { createTrustStrip, createVerticalHero } from '../../../../../packages/design-system/src/index'
import { PublicFooter, PublicHeader } from '../components/public-chrome'

const VerticalHero=createVerticalHero(createElement)
const TrustStrip=createTrustStrip(createElement)
const categoryFor=(id:string)=> id.includes('police')||id.includes('criminal')||id.includes('arrest')||id.includes('court')?'Law Enforcement & Courts':id.includes('property')||id.includes('permit')||id.includes('planning')||id.includes('code-enforcement')?'Property & Development':id.includes('birth')||id.includes('marriage')||id.includes('divorce')||id.includes('death')?'Vital Records':id.includes('military')||id.includes('medical')||id.includes('employment')||id.includes('education')?'Personal Records':id.includes('follow-up')||id.includes('denial')?'Follow-up & Appeals':'General Public Records'
export const Route=createFileRoute('/')({component:Home,head:()=>({meta:[{title:'Records Requests — Public Records, FOIA & Government Records | MailMyPDF'},{name:'description',content:'Prepare focused public-records, FOIA, police, court, property, permit, vital-records, government communications, follow-up, and denial-appeal requests.'},{name:'robots',content:'index,follow'}]})})
function Home(){const featured=recordsWorkflows.slice(0,8);return <main><PublicHeader/>
<VerticalHero theme='records-request' tone='dark' eyebrow='Records Requests · Access. Information. Accountability.' title="Get the records you're looking for." description='Choose a focused public-records workflow, describe the information and agency, review the exact request, and keep the request, delivery, response, follow-up, and proof record connected.' imageSrc='/ecosystem-hero-sprite.jpg' imageAlt='Organized public-records files and government documents' imageBackgroundSize='200% 300%' imageBackgroundPosition='0% 100%' actions={<><Link className='mmp-button-primary' to='/workflows'>Find a Records Workflow <ArrowRight size={16}/></Link><a className='mmp-button-secondary' href='/'>Mail a PDF</a></>} meta={<><span>Federal, state & local records</span><span>Review before sending</span><span>Mailing & proof options</span></>}/>
<TrustStrip items={[{icon:<FileText size={16}/>,title:'Focused request types',description:'Start from the records objective'},{icon:<Search size={16}/>,title:'Agency-aware intake',description:'Organize holder, scope, and record categories'},{icon:<Eye size={16}/>,title:'Review before delivery',description:'Check the exact request first'},{icon:<Mail size={16}/>,title:'Tracking & proof options',description:'Keep the delivery record together'}]}/>
<section className='mmp-section'><div className='mmp-section__inner'><div className='mmp-section-heading'><div><div style={{fontSize:11,fontWeight:800,letterSpacing:'.16em',textTransform:'uppercase',color:'var(--mmp-accent)'}}>Popular records workflows</div><h2>Start with the kind of record you need.</h2></div><p>The strongest request is specific about the records objective without pretending every agency, jurisdiction, or record family works the same way.</p></div><div className='mmp-workflow-grid'>{featured.map(w=><article className='mmp-workflow-card' key={w.id}><div className='mmp-workflow-card__body'><div style={{fontSize:10,fontWeight:800,letterSpacing:'.12em',textTransform:'uppercase',color:'var(--mmp-accent)'}}>{categoryFor(w.id)}</div><h3>{w.name}</h3><p>{w.description}</p><Link className='mmp-workflow-card__action' to='/workflows/$slug' params={{slug:w.id}}>View workflow →</Link></div></article>)}</div><div style={{marginTop:28}}><Link to='/workflows' className='mmp-button-primary'>Browse all {recordsWorkflows.length} workflows →</Link></div></div></section>
<section className='mmp-section mmp-section--tight' style={{background:'var(--mmp-paper-deep)'}}><div className='mmp-section__inner'><div className='mmp-section-heading'><div><div style={{fontSize:11,fontWeight:800,letterSpacing:'.16em',textTransform:'uppercase',color:'var(--mmp-accent)'}}>Not sure where to start?</div><h2>Start with who holds the records.</h2></div><p>Identify the agency or institution likely to hold the information, then choose the closest records family. The directory separates general requests from police, court, property, vital, personal, communications, and follow-up workflows.</p></div><Link className='mmp-button-primary' to='/workflows'>Find My Request Type →</Link></div></section>
<section id='how' className='mmp-section'><div className='mmp-section__inner'><div className='mmp-section-heading'><div><div style={{fontSize:11,fontWeight:800,letterSpacing:'.16em',textTransform:'uppercase',color:'var(--mmp-accent)'}}>How it works</div><h2>From records objective to documented request.</h2></div><p>Keep the requested records, agency, scope, outgoing request, response, follow-up, and delivery evidence in one connected matter.</p></div><div className='mmp-process-grid'>{[['1','Choose the workflow','Match the agency and record family to the most focused request.'],['2','Define the scope','Add subject, date range, categories, agency details, and supporting context.'],['3','Prepare the request','Build the request around the information actually needed.'],['4','Review & approve','Check scope, facts, recipient, and attachments before delivery.'],['5','Send & follow up','Download it or use mailing and proof options, then keep the response record connected.']].map(([n,t,d])=><div className='mmp-process-step' key={n}><span className='mmp-process-step__number'>{n}</span><h3>{t}</h3><p>{d}</p></div>)}</div></div></section>
<section className='mmp-section'><div className='mmp-section__inner'><div className='mmp-final-cta'><div className='mmp-final-cta__inner'><div><h2>Make the request specific. Keep proof of what you sent.</h2><p>Find the workflow that matches the records you need and move into the request process with the scope and delivery record intact.</p></div><Link className='mmp-button-primary' to='/workflows'>Find a Records Workflow →</Link></div></div></div></section><PublicFooter/></main>}
