import { createContext, useContext, useEffect, useState, type ReactNode } from 'react'
import type { Session } from '@supabase/supabase-js'
import { supabase } from './supabase'
export type AccountUser={id:string;email:string;fullName?:string}
type AuthValue={user:AccountUser|null;session:Session|null;accessToken:string|null;loading:boolean;isConfigured:boolean;signIn:(e:string,p:string)=>Promise<{error:string|null}>;signUp:(e:string,p:string)=>Promise<{error:string|null;needsConfirmation?:boolean}>;resetPassword:(e:string)=>Promise<{error:string|null}>;signOut:()=>Promise<{error:string|null}>}
const AuthContext=createContext<AuthValue|null>(null)
const map=(u:{id:string;email?:string;user_metadata?:Record<string,string>})=>({id:u.id,email:u.email??'',fullName:u.user_metadata?.full_name})
export function AuthProvider({children}:{children:ReactNode}){const [user,setUser]=useState<AccountUser|null>(null);const [session,setSession]=useState<Session|null>(null);const [accessToken,setAccessToken]=useState<string|null>(null);const [loading,setLoading]=useState(true);const isConfigured=Boolean(import.meta.env.VITE_SUPABASE_URL&&import.meta.env.VITE_SUPABASE_ANON_KEY);useEffect(()=>{let alive=true;supabase.auth.getSession().then(({data})=>{if(!alive)return;setSession(data.session);setUser(data.session?.user?map(data.session.user):null);setAccessToken(data.session?.access_token??null);setLoading(false)}).catch(()=>alive&&setLoading(false));const {data}=supabase.auth.onAuthStateChange((_e,s)=>{setSession(s);setUser(s?.user?map(s.user):null);setAccessToken(s?.access_token??null);setLoading(false)});return()=>{alive=false;data.subscription.unsubscribe()}},[]);const signIn=async(e:string,p:string)=>({error:(await supabase.auth.signInWithPassword({email:e,password:p})).error?.message??null});const signUp=async(e:string,p:string)=>{const r=await supabase.auth.signUp({email:e,password:p,options:{emailRedirectTo:`${window.location.origin}/dashboard`}});return{error:r.error?.message??null,needsConfirmation:!r.data.session}};const resetPassword=async(e:string)=>({error:(await supabase.auth.resetPasswordForEmail(e,{redirectTo:`${window.location.origin}/auth`})).error?.message??null});const signOut=async()=>({error:(await supabase.auth.signOut()).error?.message??null});return <AuthContext.Provider value={{user,session,accessToken,loading,isConfigured,signIn,signUp,resetPassword,signOut}}>{children}</AuthContext.Provider>}
export const useAuth=()=>{const v=useContext(AuthContext);if(!v)throw new Error('useAuth must be used within AuthProvider');return v}
