// This file is automatically generated. Do not edit it directly.
// Patched: gracefully degrades when Supabase is not configured.
// Patched: falls back to /api/auth/config for runtime secrets on Cloudflare Pages.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function isNewSupabaseApiKey(value: string): boolean { return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_'); }
function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined);
    if (init?.headers) new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) { /* Storage compatibility */ }
    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}
interface RuntimeConfig { configured: boolean; url: string | null; anonKey: string | null; }
let _runtimeConfigPromise: Promise<RuntimeConfig> | null = null;
async function fetchRuntimeConfig(): Promise<RuntimeConfig> {
  if (_runtimeConfigPromise) return _runtimeConfigPromise;
  _runtimeConfigPromise = (async () => { try { const res = await fetch('/api/auth/config'); if (!res.ok) return { configured: false, url: null, anonKey: null }; return await res.json() as RuntimeConfig; } catch { return { configured: false, url: null, anonKey: null }; } })();
  return _runtimeConfigPromise;
}
function createSupabaseClient(url: string, key: string) {
  return createClient<Database>(url, key, { global: { fetch: createSupabaseFetch(key) }, auth: { storage: typeof window !== 'undefined' ? localStorage : undefined, persistSession: true, autoRefreshToken: true } });
}
const envUrl = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
const envKey = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY || import.meta.env.VITE_SUPABASE_ANON_KEY || process.env.SUPABASE_ANON_KEY;
let _supabase: ReturnType<typeof createSupabaseClient> | null | undefined;
_supabase = envUrl && envKey ? createSupabaseClient(envUrl, envKey) : null;
let _initPromise: Promise<void> | null = null;
export function ensureSupabase(): Promise<void> {
  if (_supabase) return Promise.resolve();
  if (_initPromise) return _initPromise;
  _initPromise = (async () => { const config = await fetchRuntimeConfig(); if (config.configured && config.url && config.anonKey) _supabase = createSupabaseClient(config.url, config.anonKey); })();
  return _initPromise;
}
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, { get(_, prop, receiver) { if (!_supabase) { if (typeof window !== 'undefined') void ensureSupabase(); return undefined; } return Reflect.get(_supabase, prop, receiver); } });
